### ISSUE TITLE
Add scheduled publishing webhook

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#10067]
### What I'm trying to achieve
Trigger a webhook when a product/sale gets published given a scheduled date.

**Comment by CossackDex** [comment]
@timuric It seems like a helpful tool. I will ask team to put it on our roadmap.

**Comment by timuric** [comment]
@CossackDex thanks! Send my regards to the team!

**Comment by CossackDex** [comment]
I will @timuric! I will

**Comment by timuric** [comment]
Internal task: [7520](https://app.clickup.com/t/2549495/SALEOR-7520)
