### ISSUE TITLE
Non localizable date format used in invoice plugin

### ISSUE THREAD

**Issue by gleniat** [saleor/saleor#10068]
### What I'm trying to achieve
Get a creation date on invoices based on locale settings.

### Steps to reproduce the problem

1. set locale, date and datetime format globally in python/django - add something like this to `saleor/settings.py`:
```
USE_L10N = False
TIME_FORMAT = 'G:i'
DATE_FORMAT = 'd. m. Y'
DATETIME_FORMAT = 'd. m. Y - G:i'
```
2. generate invoice from dashboard (open any order and click Generate)

### What I expected to happen
I expect Saleor invoice templating engine to use locale settings set in Django.

Template snippet:
`<span class="header-item">{{ creation_date }}</span>`
I'd like to get `01. 01. 2022`. I get `01 Jun 2022` instead, no matter what settings I set in `settings.py`.

### Possible cause
The date format in Invoicing plugin is currently hard-coded:
```
"creation_date": creation_date.strftime("%d %b %Y"),
```
See [`saleor/saleor/plugins/invoicing/utils.py:101`](https://github.com/saleor/saleor/blob/2a5e6795271fcec84228f86267f3127c9925a888/saleor/plugins/invoicing/utils.py#L101)

**System information**

Saleor version:
- [*] dev (current main)
- [*] 3.0

**Comment by timuric** [comment]
@gleniat it is not high priority atm, but please feel free to open a PR

**Comment by aniav** [comment]
Hey @gleniat we're moving towards apps in favour of plugins and we'll definitely not address any existing feature requests. At this point we will only fix critical bugs in plugins. I'll close this issue but feel free to issue a PR with a fix for the localisation and we'll make sure to review 🙌
