### ISSUE TITLE
Not able to Compose Supergraph because of Subscriptions

### ISSUE THREAD

**Issue by inf3cti0n95** [saleor/saleor#10170]
I'm not able to use Apllo Federation to extend Saleor because Federation is not supporting Subscription yet.

https://www.apollographql.com/docs/federation/#how-it-works:~:text=Apollo%20Federation%20does%20not%20currently%20support%20GraphQL%20subscription%20operations.

**Comment by patrys** [comment]
We'll look into it. Saleor itself does not support subscriptions using WebSockets so I think it's mostly a matter of hiding that part of the schema from the federation protocol.

**Comment by inf3cti0n95** [comment]
@patrys when can we expect a patch for this in the main release?

**Comment by inf3cti0n95** [comment]
@patrys I'll cehck and confirm if it's working.
