### ISSUE TITLE
Order number not available in ORDER_CONFIRMED event

### ISSUE THREAD

**Issue by ianninirojas** [saleor/saleor#10229]
### What I'm trying to achieve
Get all order detail included order number field in ORDER_CONFIRMED event

### Steps to reproduce the problem

1. Confirm an order
2. The webhook is activated with ORDER_CONFIRMED event
3. Get order information (without order number) 

### What I expected to happen
Get order number in ORDER_CONFIRMED event

### Screenshots and logs
```
{
  "type": "Order",
  "id": "T3JkZXI6Y2RmY2UzMjQtNWEwOC00YjY4LWFjNDQtYjkwYTRiOGY3Njlk",
  "channel": {
    "type": "Channel",
    "id": "Q2hhbm5lbDoz",
    "slug": "default-channel",
    "currency_code": "EUR"
  },
  "shipping_address": null,
  "billing_address": "billing_address",
  "discounts": null,
  "token": "cdfce324-5a08-4b68-ac44-b90a4b8f769d",
  "user_email": "email",
  "created": "2018-01-01T00:00:00+00:00",
  "original": "T3JkZXI6Tm9uZQ==",
  "lines": ["ProductLine"],
  "fulfillments": [],
  "collection_point": null,
  "payments": ["Payment"],
  "shipping_method": null,
  "meta": {
    "issued_at": "2022-07-25T12:11:38.934685+00:00",
    "version": "3.5.0",
    "issuing_principal": { "id": "VXNlcjo5ODM", "type": "user" }
  },
  "private_metadata": {},
  "metadata": {},
  "status": "unfulfilled",
  "language_code": "en",
  "origin": "checkout",
  "shipping_method_name": null,
  "collection_point_name": null,
  "shipping_price_net_amount": "0.00",
  "shipping_price_gross_amount": "0.00",
  "shipping_tax_rate": "0.0000",
  "total_net_amount": "23.00",
  "undiscounted_total_net_amount": "23.00",
  "total_gross_amount": "23.00",
  "undiscounted_total_gross_amount": "23.00",
  "weight": "2.0kg"
}
```

**System information**

Saleor version:
- [ ] dev (current main)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

**Comment by patrys** [comment]
Thanks for flagging this, we'll make sure the number is available. In the meantime, I encourage you to look at [GraphQL subscription queries for webhooks](https://docs.saleor.io/docs/3.x/developer/extending/apps/subscription-webhook-payloads) that allow you to decide what information becomes part of your webhooks payload.
