### ISSUE TITLE
Set MEDIA_ROOT environment does not change location for media files

### ISSUE THREAD

**Issue by tiendq** [saleor/saleor#10238]
### What I'm trying to achieve

Change default location for media files.

### Steps to reproduce the problem

1. `export MEDIA_ROOT=/var/www/saleor/media/`
2. run saleor

### What I expected to happen

Uploaded product images will be stored in `/var/www/saleor/media/`

### What actual happened

Uploaded product images were still stored in `/home/tiendq/saleor/media/` (project folder/default location)

Saleor version:
- [x] 3.0

Operating system:
- [x] Linux

**Comment by patrys** [comment]
Setting `MEDIA_ROOT` through an environment variable is not currently supported. We strongly encourage you to use some form of cloud storage (AWS S3, GCP Cloud Buckets, Azure Blob Storage) as a shared storage mechanism to be able to scale your cluster horizontally by adding more worker nodes.

If you absolutely need to use a local directory outside of development, please submit a pull request that allows `MEDIA_ROOT` to be overridden.

**Comment by peelar** [comment]
@tiendq As I see that you acknowledged @patrys response, and I see no further questions, I am closing this issue.
