### ISSUE TITLE
productBulkDelete mutation fails with more than 20 products

### ISSUE THREAD

**Issue by simon-online** [saleor/saleor#10237]
When you attempt to delete more than 20 products with the productBulkDelete mutation it fails with the following error message.

code: "GRAPHQL_ERROR"
field: "ids"
message: "Could not resolve to a node with the global id list of '[\"{'0': 'UHJvZHVjdDoxODU2', '1': 'UHJvZHVjdDoxODU1', '2': 'UHJvZHVjdDoxODU0', ...}\"]'."

### Steps to reproduce the problem
In the Saleor dashboard go to the Products screen, adjust the page size to be more than 20, bulk select more than 20 products and click the bulk delete button.

Expected all the selected products to be deleted but instead got the error mentioned above.

**System information**
Saleor version:
core v3.5.0
dashboard v3.5.0

**Comment by simon-online** [comment]
Ah yes, it looks like it's an issue with how the dashboard is sending the IDs.

For a small number of selected products to delete which is successful variables looks like this:
```
{
  variables: {
    ids: ["UHJvZHVjdDoxMTI=", "UHJvZHVjdDoxMTE="]
  }
}
```

But when a request for a larger number (eg. 40) of selected products to delete is made it fails and it looks like this:
```
{
  variables: {
    ids: [{0: "UHJvZHVjdDo3Mg==", 1: "UHJvZHVjdDo3NA==", 2: "UHJvZHVjdDoxMjI=", 3: "UHJvZHVjdDo3OQ==",…}]
  }
}
```

I guess this issue should be added to saleor-dashboard instead.

**Comment by peelar** [comment]
@simon-online If you don't mind, I will open a new issue in @saleor/dashboard and reference this one.
