### ISSUE TITLE
FATAL:  sorry, too many clients already

### ISSUE THREAD

**Issue by tiendq** [saleor/saleor#10319]
### What I'm trying to achieve
Don't see this error.

### Steps to reproduce the problem
1. Start saleor with `python manage.py runserver 0:8000`
2. Use dashboard for awhile (about 15 minutes or so) e.g. creating new products, update existing data

Occasionally dashboard stopped working and checking browser's network log reveals GraphQL query errors as "FATAL:  sorry, too many clients already". I did googles and it likely a known issue with many Django apps, unfortunately there is no reliable fix/workaround.

I looked at `pg_stat_activity` and saw several dead connections (from Saleor) 3-4 days ago while I have only used this saleor instance less than an hour a day.

Whenever I saw this error saleor stopped working (500 error) and I needed to restart it.

### What I expected to happen
No error.

### Screenshots and logs
- [ ] dev (current main)
- [x] 3.5.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by patrys** [comment]
@tiendq Please keep in mind that `runserver` is not a production solution, it's meant for local debugging and is quite limited. You can try restarting it to see if fixes your problem.

**Comment by tiendq** [comment]
> @tiendq Please keep in mind that `runserver` is not a production solution, it's meant for local debugging and is quite limited. You can try restarting it to see if fixes your problem.

I had to restart saleor every time I saw this error, I guess it will happen after I use saleor for awhile (and open many connections). But why too many connections? And I think even in development mode it shouldn't happen.

**Comment by patrys** [comment]
I have never seen this happen. Did you modify any part of the stack? Custom PostgreSQL configuration?

**Comment by manojLondhe** [comment]
We noticed when using https://github.com/saleor/saleor-platform setup on a dev server

**Comment by patrys** [comment]
@saleor/devtools folks, could you try to reproduce?

**Comment by tiendq** [comment]
Do you use anything like this `db_from_env = dj_database_url.config(conn_max_age=500)`? Some guys (not all) could fixed the issue by dropping `conn_max_age`, more detail [here](https://github.com/django/channels/issues/871#issuecomment-371592113).

**Comment by lkostrowski** [comment]
@manojLondhe can you provide on what commits are your `saleor-platform` submodules?

![Zrzut ekranu 2022-08-5 o 08 52 06](https://user-images.githubusercontent.com/9268745/183019027-fe18aca3-dd25-4e2c-ab73-2bd94d7f62c6.png)

**Comment by patrys** [comment]
I believe this problem should be fixed in the current main branch. We got rid of connection reuse as it's no longer supported by Django 4 in ASGI mode.
