### ISSUE TITLE
Attribute with numeric type returns only one data set

### ISSUE THREAD

**Issue by g-londhe** [saleor/saleor#10315]
### What I'm trying to achieve
I'm trying to search a product by attribute with numeric type

### Steps to reproduce the problem

1. QUERY
`query ProductList(
  $after: String
  $before: String
  $first: Int
  $last: Int
  $sortBy: ProductOrder
  $filter: ProductFilterInput
) {
  products(
  after: $after,
  before: $before,
  first: $first,
  last: $last,
  sortBy: $sortBy,
  filter: $filter) {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
      __typename
    }
    totalCount
    edges {
      node {
        id
        name
        slug
        created
        updatedAt
        category{
          name
        }
        channelListings {
          channel {
            id
            slug
          }
          id
          isPublished
          publishedAt
          isAvailableForPurchase
        }
        metadata{
          key
          value
        }
        variants {
          id
          name
          sku
          pricing {
            onSale
            __typename
          }
          __typename
        }
        attributes {
          attribute {
            id
            slug
            name
            __typename
          }
          values {
            name
            __typename
          }
        }
        __typename
      }
    }
  }
}`
2. VARIABLES 
`{
  "first": 100,
  "after": "",
  "before": "",
  "filter": {
    "attributes": [{
      "slug": "attribute-slug-here",
      "valuesRange": {
          "gte": 12345,
          "lte": 12345
      }
    }]
  }
}`

### What I expected to happen
Get details of products having attributes value provided in the variables

### Screenshots and logs

Not available
**System information**

Saleor version:
- [ ] dev (current main)
- [x] 3.5.3
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by peelar** [comment]
Hello @g-londhe 👋 

We are looking into it along with the other filter-related issues. Your reports are much appreciated and a great help 🙇.

**Comment by IKarbowiak** [comment]
Hi @g-londhe,

Could you describe what is your problem, I've just checked filtering by the numeric attributes by providing the same value in `gte` and `lte` and it works properly. I received the product that I was looking for.

**Comment by IKarbowiak** [comment]
Thank you for the explanation. I already reproduced the problem, and I'll be working on this soon. 🙂
