### ISSUE TITLE
Add support for .env

### ISSUE THREAD

**Issue by tiendq** [saleor/saleor#10478]
### What I'm trying to achieve
Configure with `.env` file to make it easier to deploy Saleor with system services e.g. systemd and uWSGI.

### Describe a proposed solution
Support environment variables in a `.env` file.

### Other solutions I've tried and won't work
Set environment variables with systemd service configuration file but it's hard and inconvenient to do.

**Comment by patrys** [comment]
@tiendq Is there a reason you don't want to use containers for deployment? Saleor was built with horizontal scalability in mind which is hard to achieve without a platform like Kubernetes.

For `systemd`, you can use the `EnvironmentFile` directive to load an env file.

**Comment by tiendq** [comment]
> @tiendq Is there a reason you don't want to use containers for deployment? Saleor was built with horizontal scalability in mind which is hard to achieve without a platform like Kubernetes.
> 
> For `systemd`, you can use the `EnvironmentFile` directive to load an env file.

When I have a dedicated Ubuntu instance for saleor (which we could reset and try everything again without affecting any other apps) I'd like to not use docker (just an extra layer for nothing). Another reason is `saleor-platform` currently has everything while most people just need a `saleor core` docker container, storefront and dashboard are SPAs and easily built locally.

I tried to use systemd's service conf file like below example, it worked well, but when I run saleor with WSGI it stopped working (saleor didn't see environment variables). I don't know `EnvironmentFile`, I'll try it, thanks.

```
[Service]
Environment="MEDIA_ROOT=/var/www/saleor/media/"
Environment="RSA_PRIVATE_KEY=RSA_PRIVATE_KEY"
Environment="SECRET_KEY=SECRET_KEY"
...
```
