### ISSUE TITLE
Bug: out of stock 

### ISSUE THREAD

**Issue by Javokhir-1999** [saleor/saleor#10511]
### What are you trying to achieve?

I am just adding the new product in the dashboard (showed the achievable stock, made it public and active )
But every time when I add a new product they are counted as "out of stock".

Can anyone help me, how to configure it?
Thanks in advance.
![screenshot](https://user-images.githubusercontent.com/63791100/187210378-910d9fbc-01c0-4cd3-8f11-e9c5f2c358c7.jpg)

### Steps to reproduce the problem

1. add product

### What did you expect to happen?

added product

### Environment

any

**Comment by karolkielecki** [comment]
Hi @Javokhir-1999, Could you please tell me your Saleor version and share screenshots of your previously added products?

**Comment by CossackDex** [comment]
Hi @Javokhir-1999,

my guess is that you didn’t allocate stock https://docs.saleor.io/docs/3.x/dashboard/catalog/products#stock-management

**Comment by Javokhir-1999** [comment]
Hi, sorry for being so late,
Saleor version is: 3x.

Thanks, for the help and Yes I have read all docs you have)  
I have solved this problem, by adding the shipping, 
it seems strange, why shipping has relation to the product  "out of stock"
