### ISSUE TITLE
add the production date to ProductVariants

### ISSUE THREAD

**Issue by manhtd98** [saleor/saleor#10534]
I have a product with different production and expiration dates. Why not add the production date to ProductVariants. It help us to manage our product better

**Comment by CossackDex** [comment]
Hi @manhtd98,

thank you for reporting an issue, 

Is there something that prevents you from using attributes? https://docs.saleor.io/docs/3.x/developer/attributes

**Comment by manhtd98** [comment]
i have 1 product but many production date
So attributes not a perfect solution i think

**Comment by aniav** [comment]
Attributes is the way to go in this case. You can specify a text attribute and use a different balie for this. Alternetively you can use metafora for ProductVariant 🫡
