### ISSUE TITLE
Address metadata

### ISSUE THREAD

**Issue by guyguy333** [saleor/saleor#10638]
### What I'm trying to achieve

It's useful to store address category, address type, or any other custom field with address. Currently, there is no way to do that. It has already been discussed here for another use case: https://github.com/saleor/saleor/issues/6705

### Describe a proposed solution

Add private and public metadata field to Address model.
A (great) PR has already been pushed with the feature : https://github.com/saleor/saleor/pull/6785 and currently need a rebase (see https://github.com/saleor/saleor/pull/6785#issuecomment-1243012807)

### Other solutions I've tried and won't work

None that I know.

### Other

It would be great if Saleor team could state on this issue so PR can be rebased, cleaned and merged.

**Comment by maarcingebala** [comment]
Addresses do support metadata now 🎉
