### ISSUE TITLE
Include Voucher in Checkout instead of voucherCode

### ISSUE THREAD

**Issue by akhial** [saleor/saleor#10693]
### What I'm trying to achieve
I would like to be able to retrieve applied voucher information in the `checkout` query instead of having to make a second query to
```graphql
vouchers(filter: { search: "VOUCHER" }, channel: "slug", first: 1)
```

### Describe a proposed solution
Include `voucher: Voucher` in `Checkout` instead of `voucherCode: String`
https://docs.saleor.io/docs/3.x/developer/api-reference/objects/checkout
https://docs.saleor.io/docs/3.x/developer/api-reference/objects/voucher

### Screenshots or mockups
Proposed object:
```graphql
type Checkout implements Node & ObjectWithMetadata {
  """ ... """
  voucher: Voucher
  """ ... """
}
```

**Comment by akhial** [comment]
Am interested in submitting a PR for this if team decides it's a good fit for the Saleor GraphQL API.

**Comment by zedzior** [comment]
https://github.com/saleor/saleor/pull/14512
