### ISSUE TITLE
Extend JWT tokens with issuer and audience fields

### ISSUE THREAD

**Issue by mmiszy** [saleor/saleor#10799]
### What are you trying to achieve?

JWT tokens are missing some fields:

- `iss` - issuer of this token, this would be the environment's domain
- `aud` - audience for this token, who is it for (app, frontend, ...), to be refined/discussed what it should contain

Originally created in: https://app.clickup.com/t/2549495/SALEOR-7262

Rel: https://github.com/saleor/react-storefront/issues/283

### Steps to reproduce the problem

1. Obtain a token
2. See that fields are missing

### What did you expect to happen?

For `iss` and `aud` to exist.

### Environment

.

**Comment by patrys** [comment]
My take:
* `iss` should contain a fully qualified URL of the GraphQL endpoint (`https://my.domain.com/graphql/`)
* `aud` for apps should contain an app identifier, as defined by the manifest file

**Comment by korycins** [comment]
# RFC

## `iss`

The JWT tokens will recieve `iss` in url format pointing to `graphql` scheme.  Like `https://<saleor-domain>/graphql/`

## `aud`

### JWT tokens
The JWT tokens for app's iframe should have included `aud` based on the app's url. We want to use app's url to be sure that `aud` will be different for dev, stage or production instances.

This points us to discussion, which app url should be used. The proposition is to use `tokenTargetUrl` from manifest, as this field is mandatory during the app installation. 
- Each newly installed App will have include `aud` based on `tokenTargetUrl`.
- We don't store `tokenTargetUrl` in database yet, so only JWT tokens for newly installed apps will get `aud` field.
- If in the future we will want to support apps that doesn't need to have app's bearer token (like maiking `tokenTargetUrl` optional in the manifest) this will cause that such tokens will not have `aud` included.

### `tokenCreate`
`tokenCreate` mutation will recieve new optional input `audience` , that will include `aud` in the format `custom:<recieved-input>`
Like: `tokenCreate(email: "admin@example", password: "123", audience:"dashboard")`
the JWT tokens will have `{... "aud": "custom:dashboard"}`

**Comment by patrys** [comment]
I think `appUrl` is a better fit as I'd like to make `tokenTargetUrl` optional and turn it into a regular webhook later.

**Comment by patrys** [comment]
It's important to remember that we don't _need_ to include the audience claim if the app author does not care about it. Didn't we want to deprecate `configurationUrl` in favor of requiring the `appUrl`? We need to display something when you visit the app.

**Comment by korycins** [comment]
You're right. We already deprecate the `configurationUrl`.  Okay, so `appUrl` is fine for me.

**Comment by korycins** [comment]
> The JWT tokens for app's iframe should have included aud based on the app's url. We want to use app's url to be sure that aud will be different for dev, stage or production instances.
> This points us to discussion, which app url should be used. The proposition is to use tokenTargetUrl from manifest, as this field is mandatory during the app installation.
> Each newly installed App will have include aud based on tokenTargetUrl.
We don't store tokenTargetUrl in database yet, so only JWT tokens for newly installed apps will get aud field.
If in the future we will want to support apps that doesn't need to have app's bearer token (like maiking tokenTargetUrl optional in the manifest) this will cause that such tokens will not have aud included.

We can't by default add `aud` to the tokens that already didn't have this. According to the RFC https://www.rfc-editor.org/rfc/rfc7519#section-4.1.3, if `aud` is in the token, the validation should be called. This means, that all existing apps that decode/validate jwt token on its side can receive the exception that `audience` is incorrect. 
We will add a new optional field to manifest `audience`. If provided, the JWT token will contain `aud` field.

**Comment by yasirub** [comment]
Hi, I'm using nextjs saleor app boilerplate app to create a saleor app. I managed to setup every thing but app token verification fails inside the app. I found out that this was caused by the missing 'iss' field in the app token. So How do I add Iss to the apptoken?
