### ISSUE TITLE
When talking to Saleor Apps, always include the fully qualified API URL

### ISSUE THREAD

**Issue by patrys** [saleor/saleor#10819]
Only the domain name is currently included in all webhook events, including the initial installation handshake.

Not knowing the full URL requires Apps to make a lot of assumptions (like using the HTTPS protocol or the API living under `/graphql/`) which may not be true in complex setups or—more importantly—during local development.

**Comment by korycins** [comment]
So we would like to have a new request header like:
`SALEOR_GRAPHQL` / `SALEOR_GRAPHQL_URL`?

**Comment by patrys** [comment]
HTTP headers ignore case and don't use underscores. `saleor-api-url`? Or just `saleor-url`?

**Comment by lkostrowski** [comment]
@przlada will take this
