### ISSUE TITLE
Add external keys to objects

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#10820]
### Problem
1. Saleor integrations are often, if not usually done on an existing infrastructure - that infrastructure relies on Business IDentifiers (BIDs) - which are understood across the whole platform. Introducing Saleor which can only operate on (mutate data in particular) on its own IDs (Saleor IDs). This requires additional, external mappings or API round trips for one to be able to plug Saleor to an existing platform. ERP systems are often the root of most issues of this kind. The ERP system can emit a domain event that a product was sold in a brick and mortar store, stocks for that product now need to be updated across the platform - event like that usually contains the BID of the product, the BID of the warehouse and the new stock value, the BIDs now need to be translated to Saleor IDs for Saleor to consume.
2. Another thing is batch updates where there is a lot of data to process, stock synchronization coming from a ERP system is one example. To reduce traffic other systems want to send updates in batches (one current example is a batch of 120k stock updates split to 50, 50 and 20k). Not only one needs to translate the BIDs for each, there’s also a need to update all these one-by-one.

### Functional requirements
1. There should be a way to operate (mutate) the following entities by BIDs:
a. Orders
b. Products
c. Product Variants (here SKU sometimes acts as a Product BID but it’s not a given)
d. Attributes
e. Attribute Values
f. Warehouses (only for the purpose of Stock update)
g. Customers
2. There should be a way to update the following entities in bulks (or batches): a. Stocks
b. Attributes and their Values (although it’s not MVP)

### Non-functional requirements
1. The solution should define the canonical naming for the BID fields.
2. API Call costs rules should be defined and well documented.
3. The solution should not impact the responsiveness of Saleor.
4. Batch updates might be done in an asynchronous matter, in that case, a promise should be returned which would allow checking if a batch process was completed.
5. Proposed API changes need to be backward compatible.

### Solution
The solution to the first problem would be to agree on the naming convention, here are some ideas:
• Bid - Business Identifier - an ID for an entity that is understood across the whole organization, it uniquely defines an Entity regardless of the queried system - this Foreign Key / Batch update in Saleor 2 is nice and descriptive but might be too constricting as it sounds like it has a hidden purpose to it.
• ExternalId or ForeignID - I don’t like the latter one as it steps on a “foreign” key relation naming in a database. ExternalId seems to fit the purpose but in turn, feels too loose to rely on.

The decision around this should be made by someone with a broad understanding of Saleor and where Saleor is heading.
The BID should be unique in the scope of the whole database.

Another thing is the API changes which I’ll try to describe in the API changes section below.

The last part is the database which will need to accommodate a new field on the entities in question. That field would need to be indexed on its own so it’s possible to query with it.

```mermaid
sequenceDiagram
  ERP->>Saleor: update Product BID: 123, set Attribute: Color to Value: Red
  Saleor->>Saleor: Fetch with the BID and update
  Saleor->>ERP: OK
```

Next the batching solution proposal. One idea would be to accept a batch job, return a promise and handle the batch tasks queries - this has the potential to handle more changes in one call but will result in a complex promise system.

```mermaid
sequenceDiagram
  ERP->>Saleor: 50k of products stock update
  activate Saleor
  Saleor->>Saleor Worker: delay the update
  Saleor Worker->>Saleor: Job ID
  Saleor->>ERP: Promise with Job ID
  deactivate Saleor
  ERP->>Saleor: Query job state
  activate Saleor
  Saleor->>ERP: Job state: IN PROGRES
  deactivate Saleor
  Saleor Worker->>Saleor: Job ID DONE
  ERP->>Saleor: Query job state
  activate Saleor
  Saleor->>ERP: Job state: DONE
  deactivate Saleor
```

The other is to make the changes hot, those would need to be “paged” (I assume) and will have the potential to block a thread for a long time (updates in particular).

```mermaid
sequenceDiagram
  loop Until done
    ERP->>Saleor: 100 products stock update
    activate Saleor
    Saleor->>Saleor: Make changes
    Saleor->>ERP: Respond with the result
    deactivate Saleor
end
```

In both cases, either on the “hot” or “delayed” response a Job or Result type should be returned. That type would carry the outcome of the individual change outcome, the ID, BID, and potential errors.

### Existing components
Saleor Core will require database and API changes.
Saleor Dashboard will require changes to accommodate the new BID fields.

### Security
The addition of BIDs has the potential to expose the entities through additional keys to be guessed. It might be a good idea to prohibit the ability to query with those only to the principals with a BID_QUERY permission (which would be a new one). As of now I see no reason to query by those in any other way than though an app.
Batching carries another problem - should an authorization check be done for each updated entity (do I have the right to all of the orders I’m about to update?) or just in the scope of the entity type (I have the right to update orders in general). As of now batch changes are not something others than apps should be allowed to do but introducing this might tempt a mistake in the future.

**Comment by mociepka** [comment]
@timuric, one issue that we have right now is worth outlining:

When you do a bulk update, other updates can also be done (someone bought the product when the update was running). So bulk updates and single updates need to be queued somehow to get, for instance, real stock value or product description at the end.

Ideas we were internally considering:

1. Use the FIFO queue for all stock updates,
2. Require an update date in the input. Then FIFO is not needed, and the last updated item can be used (if you have all data).
