### ISSUE TITLE
Fix: updating attribute values with similar values

### ISSUE THREAD

**Issue by jakubkuc** [saleor/saleor#10829]
Updating attribute value with similar value e.g: "424l" to "42.4l" does not update the value. 

to reproduce use query:
```
mutation {
  productVariantUpdate(
    id: "UHJvZHVjdFZhcmlhbnQ6MjAz"
    input: { attributes: { id: "QXR0cmlidXRlOjE1", values: ["24l"] } }
  ) {
    errors {
      code
      field
    }
    productVariant {
     id
      attributes {
        attribute {
          id
          name
        }
        values {
          id
          name
          slug
          value
        }
      }
    }
  }

```
Then change `24l` to `2.4l` or `24L` - this should create new value with those names and new unique slug. But at the moment it returns the old object without updating anything. 

This reproduces in Saleor 3.1+

**Comment by maarcingebala** [comment]
@jakubkuc Please provide more steps to reproduce, at least Saleor version and example mutation/query that causes the issue.
