### ISSUE TITLE
Unable to filter customers with 0 orders

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#10832]
### **Steps to reproduce the problem:**
```graphql
query Customers{
  customers(filter: {numberOfOrders: {lte: 0, gte: 0}},  first: 10){
    edges{
      node{
        id
        email
        orders{
          totalCount
        }
      }
    }
    totalCount
  }
}
```

### **Current result:**
Backend returns all customers instead of those with 0 orders

### **Expected result:**
Return all customers with 0 orders

### **Environment:**
master.staging core v3.8.0-a

### **Additional info/links:**
https://master.staging.saleor.cloud/dashboard/customers/?asc=true&sort=name&numberOfOrdersFrom=0&numberOfOrdersTo=0

**Comment by AswinkumarRA** [comment]
I would like to work on this bug, can you please assign this to me

**Comment by AswinkumarRA** [comment]
@IKarbowiak I have raised the PR for this issue, please review it, Thanks.
