### ISSUE TITLE
Add workflow to require changelog in PRs

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#10846]
Add a Github workflow that would check in CI whether the changelog file was updated for a pull request. We should be able to disable this check by adding a dedicated label to the PR (e.g. `no-changelog`). Only run the workflow on the `main` branch.

**Comment by techrajdeep** [comment]
Hey @maarcingebala , I am looking for an issue for my first contribution . Can you explain a bit more.

**Comment by maarcingebala** [comment]
@techrajdeep We have a bunch of workflows defined here: https://github.com/saleor/saleor/tree/main/.github/workflows, they run with Github Actions. We also have the [changelog file](https://github.com/saleor/saleor/blob/main/CHANGELOG.md) where we describe changes made to Saleor. We want to add a new workflow that would be run for each new pull request and check if the changelog was provided. It's enough for now just to check if there were any changes made to the CHANGELOG.md file. We need to be able to disable the changelog check in CI for pull request that are marked with special label, e.g. `no-changelog`.

**Comment by maarcingebala** [comment]
Fixed in https://github.com/saleor/saleor/pull/11198
