### ISSUE TITLE
Bug: exclude quantityReserved from products (stockAvailability: IN_STOCK)

### ISSUE THREAD

**Issue by 0xWhiteleaf** [saleor/saleor#10877]
### What are you trying to achieve?

Hello guys,

We're currently using the reservation feature in our project and we need to know which product is "virtually" out of stock (I mean products that can't be reserved anymore because of **quantity - quantityAllocated - quantityReserved = 0**).
Actually the GraphQL API is only computing **quantity - quantityAllocated** when the filter stockAvailability: IN_STOCK is present, so even product that are fully reserved are appearing in the request results.

Is it possible _(the way you want)_ to add an additional argument to take quantityReserved into account.

Bellow the query that're using:
```
query GetProductsByCollection {
  products(
    filter: {
      collections: "Q29sbGVjdGlvbjox"
      stockAvailability: IN_STOCK
    }
    first: 100) {
    edges {
      node {
        id
        name
        variants {
          id
          name
          stocks {
            quantity
            quantityAllocated
            quantityReserved
          }
        }
      }
    }
  }
}
```

Thanks a lot for your help

### Steps to reproduce the problem

1. Open the GraphQL playground
2. Paste this query:
```
query GetProductsByCollection {
  products(
    filter: {
      collections: "Q29sbGVjdGlvbjox"
      stockAvailability: IN_STOCK
    }
    first: 100) {
    edges {
      node {
        id
        name
        variants {
          id
          name
          stocks {
            quantity
            quantityAllocated
            quantityReserved
          }
        }
      }
    }
  }
}
```

### What did you expect to happen?

Product that are fully reserved (**quantity - quantityAllocated - quantityReserved = 0**) need somehow to be excluded from the result.

### Logs

> stockAvailability: IN_STOCK

```
{
  "data": {
    "products": {
      "edges": [
        {
          "node": {
            "id": "UHJvZHVjdDo3",
            "name": "Product #1",
            "variants": [
              {
                "id": "UHJvZHVjdFZhcmlhbnQ6OA==",
                "name": "PRD1",
                "stocks": [
                  {
                    "quantity": 2,
                    "quantityAllocated": 1,
                    "quantityReserved": 1
                  }
                ]
              }
            ]
          }
        }
      ]
    }
  }
}
```

### Environment

Saleor version: 3.7.11
OS and version: macOS Monterey 12.5

**Comment by 0xWhiteleaf** [comment]
@peelar Is it a bug or it's the targeted behaviour (so a feature) ?

**Comment by timuric** [comment]
@0xWhiteleaf thanks for reporting, this is indeed a bug. We have added this to our backlog
