### ISSUE TITLE
Optimize pre_save_values in AttributeAssignmentMixin

### ISSUE THREAD

**Issue by jakubkuc** [saleor/saleor#10872]
In `AttributeAssignmentMixin` class the `pre_save_values` method should be optimized to not send so many db queries. Keep in mind cases when multiple values with the same slug (e.g. `red`, `Red`, `r.e.d`) are passed and they all need a unique slug to be generated.

**Comment by aniav** [comment]
The function doesn't exist in the codebase anymore, so I'm assuming this has been fixed.
