### ISSUE TITLE
[RFC] Assigning values of an attribute by using indentifier

### ISSUE THREAD

**Issue by andrzejewsky** [saleor/saleor#10915]
### What I'm trying to achieve
Currently, the API returns attribute values along with its id and slug, while during assigning value for the product we can use the only values or slug, which can work improperly in some cases

### Describe a proposed solution
For `dropdown` and `multiselect` attribute types let's pass `AttributeValueSelectableTypeInput` input, which contain `ID` and `value`. If `ID` is passed, it means we want to assign existing attribute value. If `value` is passed, that means we want to resolve it how it is done now (if doesn't exist, it will be created)

Additionally, `dropdowns`, `multiselects` and `numeric` input types are handled by the same field - `values`. Suggest to clean it a little bit: within `AttributeValueInput` let's keep dedicated field for each attribute's input type. 

graphql
```graphql
input AttributeValueSelectableTypeInput {
   id: ID
   value: String
}

input AttributeValueInput {
  id: ID
 
  # --- change
  values: [String!] @deprecated
  dropdown: AttributeValueSelectableTypeInput
  multiselect: [AttributeValueSelectableTypeInput]
  numeric: String
  # --- change

  file: String
  contentType: String
  references: [ID!]
  richText: JSONString
  plainText: String
  boolean: Boolean
  date: Date
  dateTime: DateTime
}
```

**Comment by zedzior** [comment]
https://saleorcommerce.slack.com/archives/C039MGJDWU8/p1666105752429509
