### ISSUE TITLE
Add filters to category.products

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#10917]
### Discussed in https://github.com/saleor/saleor/discussions/10902

<div type='discussions-op-text'>

<sup>Originally posted by **tiendq** October 11, 2022</sup>
You could sort and filter with `collection.products` [here](https://docs.saleor.io/docs/3.x/developer/api-reference/objects/collection), but you cannot do the same thing with `category.products` [here](https://docs.saleor.io/docs/3.x/developer/api-reference/objects/category).

Generally a category and a collection are same and so why is their `products` query not same? I think sort and filter are basic and should be supported in all listing queries. It result in I needs two queries to retrieve a category and its products instead of just one query with a collection.

</div>

**Comment by ogunheper** [comment]
Hi @timuric ,

Can you please engage the team to look into PR #10997 , which adds this feature.

We really need this in 3.7 and the PR is waiting nearly for 3 weeks by now :)

Best regards and thank you,
Ogün
