### ISSUE TITLE
Support restricting shipping rate by checkout subtotal instead of order value

### ISSUE THREAD

**Issue by akhial** [saleor/saleor#10928]
### What I'm trying to achieve
We're trying to create a free shipping rate for carts with products worth over $30. Currently if the customer applies a voucher in checkout process, when the voucher reduces order value under $30 we can no longer apply the free shipping rate.

For example a customer with $34 cart applies a $5 discount voucher, cart still has $34 value of products (`checkout.subTotal`) but order value is now $29 (`checkout.totalPrice`).

This makes `checkoutDeliveryMethodUpdate` raise `DELIVERY_METHOD_NOT_APPLICABLE` when trying to add free shipping rate to checkout.

Currently a customer may be getting a better deal by not applying a voucher than by applying it. This makes for a bad customer experience, because customer expectations were let down.

For example consider $15 shipping fees, with free shipping over $75.
Customer adds $75 of goods to cart. Expects free shipping.
Customer attempts to apply $5 coupon voucher.
Total is now $75 - $5 discount + $15 shipping fee = $85

Result: Applying voucher gave customer a worse deal.

### Describe a proposed solution
Support restricting shipping rates by checkout subtotal. This would allow customers to apply vouchers guilt-free.

### Screenshots or mockups

![mockup](https://user-images.githubusercontent.com/20596622/196030176-7bdd2536-8b50-4736-8d93-5292b8c81dee.jpeg)

**Comment by patrys** [comment]
Which version of Saleor are you running? I'm asking because you will likely start to see vouchers included in the `subTotal` soon as we're forced to include them due to how taxes work in some countries, requiring all discounts to be distributed among line items.

**Comment by akhial** [comment]
Hi @patrys 

I'm running Saleor 3.7.24.

In that case will it be possible to retrieve the `subTotal` without vouchers applied from a different field? We would like to avoid moving business logic rules out of Saleor if possible :sweat_smile:

**Comment by patrys** [comment]
Yes, we provide undiscounted variants of most if not all fields.

**Comment by akhial** [comment]
Good to hear, thanks!
