### ISSUE TITLE
Bug: Product search (GQL/Dashboard) does not work until a product is saved/updated after updating from 2.x to 3.x

### ISSUE THREAD

**Issue by byronrode** [saleor/saleor#10938]
### What are you trying to achieve?

Search for a product by name via GraphQL (playground, in-app) or in the dashboard search.

### Steps to reproduce the problem

1. Open the playground (or the product catalog), and add a search filter to the products query, searching for a product that already exists in the catalog.

### What did you expect to happen?

Expected search results for the product search for all products that have the search query.

### Logs

Manually looking through our catalog, for a specific product, there are 5 results.

<img width="1293" alt="Screenshot 2022-10-17 at 08 58 30" src="https://user-images.githubusercontent.com/382018/196111184-3b0b9f5c-761b-4f04-a538-23ba9b7889e0.png">

Searching for the term "Cappy" returns 2 results in search. The results that are returned are the ones that have been saved/edited since the upgrade.

<img width="1324" alt="Screenshot 2022-10-17 at 08 57 55" src="https://user-images.githubusercontent.com/382018/196111366-84255dc1-472a-45cf-93de-c64f85d056c9.png">

On further inspection, it appears that the `search_vector` column is null until saving/updating a product. Here is a raw query from the table with the 2 products that were updated showing the vectors as not null.

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/382018/196111627-2ea2f538-e362-4381-980a-436dfa5b7e23.png">
 
Here is the same query post save, as well as the results:

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/382018/196111884-2537dc94-0d98-4b93-a442-b3ecd4f8fc45.png">

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/382018/196111990-dfcf5985-28b1-40e4-85eb-26d5045fdb0b.png">

### Environment

Saleor version: 3.7.24
OS and version: Google Container OS (GCP) Staging Environment

**Comment by byronrode** [comment]
After some digging, I found the `./manage.py update_search_indexes` command, which seems to have assisted, but cannot find this in the documentation or any of the upgrade guides.

**Comment by maarcingebala** [comment]
Hey, there are Celery tasks that should be run in the background that update search vectors whenever there is a change in a product. The task is `update-products-search-vectors` and it runs in Celery Beat. Sorry for missing docs around this; we will fix that.
