### ISSUE TITLE
[Fix] This is tests with stable tag, to be fixed on last 2 versions

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor#10942]
expected 'NOT_CHARGED' to equal 'FULLY_CHARGED'

[cypress/e2e/configuration/plugins/adyen.jsat line165](https://github.com/saleor/saleor-dashboard/blob/9d9949162325a9b409435bcf4653a52ed2873119/cypress/e2e/configuration/plugins/adyen.js#L165)

`  163 |         })164 |         .then(order => {> 165 |           expect(order.paymentStatus).to.eq("FULLY_CHARGED");|                                          ^166 |         });167 |     },168 |   );`

**Comment by aniav** [comment]
Is this still valid? Should we close it?

**Comment by szczecha** [comment]
Fixed by updating plugin config before test https://github.com/saleor/saleor-dashboard/pull/2545/files
