### ISSUE TITLE
Bug: No notification email sent for new customer added in v2.11

### ISSUE THREAD

**Issue by CopperMS** [saleor/saleor#10990]
### What are you trying to achieve?

I'm running Saleor v2.11, and as recently as last year, when I added a new Customer into Saleor and confirmed it was accepted in the dashboard view, an email would be sent to the customer asking to complete registration / set a password then they could log in. I've just tried adding 2 new Customers (with my own 'dummy' GMail accounts), and neither received any notification. Also, if I simply tried going to the login prompts on the site's home page after logging out of the admin dashboard, then using 'Forgot Password', nothing happens.

What might be the root cause for this issue?

### Steps to reproduce the problem

1. Log into the admin dashboard
2. Go to 'Customers' screen & select the 'Create Customer' button
3. fill out all required fields for new Customer
4. Save 
5. Go back to Customers screen & verify the new customer is listed
6. Check email inbox for new customer to see if any notification from my website or Saleor appears for completing registration

### What did you expect to happen?

See above - no notice/access to the new customer

### Environment

Saleor version: 2.11
OS and version: Windows 8

**Comment by karolkielecki** [comment]
Hi @CopperMS, Saleor 2.11 and also 3.0 are no longer supported. I encourage you to update Saleor to the latest version, 3.7+. If you have any questions or issues with the latest versions, feel free to open an issue or [discussion](https://github.com/saleor/saleor/discussions).
