### ISSUE TITLE
Handle new iat validation after updating pyjwt to 2.6.0 version

### ISSUE THREAD

**Issue by szdrasiak** [saleor/saleor#11047]
After updating pyjwt version to `2.6.0` many of saleor tests fail with `ImmatureSignatureError - The token is not yet valid (iat)` because validation for `iat` has changed in this version.

https://github.com/jpadilla/pyjwt/issues/814

**Comment by maarcingebala** [comment]
Steps to reproduce:
1. Install PyJWT==2.6.0
```shell
$ pip install pyjwt==2.6.0
```
3. Run tests:
```shell
$ pytest 
```
