### ISSUE TITLE
Bug: Unknown command 'update_all_products_minimal_variant_prices'

### ISSUE THREAD

**Issue by tiendq** [saleor/saleor#11045]
### What are you trying to achieve?

Updating minimal variant prices [here](https://docs.saleor.io/docs/3.x/developer/running-saleor/background-tasks#updating-minimal-variant-prices).

### Steps to reproduce the problem

Run `python manage.py update_all_products_minimal_variant_prices`

### What did you expect to happen?

No error, instead I got this `Unknown command: 'update_all_products_minimal_variant_prices'. Did you mean update_all_products_discounted_prices?`.

### Environment

Saleor version: 3.8.0-a, main branch.
OS and version: Linux

**Comment by peelar** [comment]
Hello @tiendq 👋 

I updated the documentation [here](https://github.com/saleor/saleor-docs/pull/585). Thanks for pointing it out 🙇.
