### ISSUE TITLE
Financial management

### ISSUE THREAD

**Issue by manhtd98** [saleor/saleor#11137]
We have money management, payment but don't have place to Financial management. 
It's place when i can add credit card with the account, can plus money, minus money when needed

**Comment by peelar** [comment]
Hello @manhtd98 👋 

Please follow [the bug report issue template ](https://github.com/saleor/saleor/issues/new?assignees=&labels=bug,triage&template=bug_report.yaml&title=Bug:+). Without the details, we can't really help you.

**Comment by manhtd98** [comment]
Hi, i created new here: https://github.com/saleor/saleor/issues/11144
