### ISSUE TITLE
Use two-character prefix on ulid as primary key for all tables

### ISSUE THREAD

**Issue by gsoec** [saleor/saleor#11158]
### What I'm trying to achieve
We need to call `graphene.Node.from_global_id` or `graphene.Node.to_global_id` every time we resolve a id from entity which adds  overhead to the codebase.

### Describe a proposed solution
pulid - A Prefixed Universally Unique Lexicographically Sortable Identifier [ulid](https://github.com/ulid/spec)
With two-character prefixed ulid, a CheckoutLine's ID looks like `CL`+`01BX5ZZKBKACTAV9WEVGEMMVRZ `
The `pulid` can be used to fetch entity directly from database, and easily convert to a graphene global id
since we have a map that points a database table to a two-character prefix.

[ent](https://github.com/ent/ent) uses pulid as its graphql example [todopulid](https://github.com/ent/contrib/tree/master/entgql/internal/todopulid)

**Comment by peelar** [comment]
Hello @gsoec 👋 

We don't plan to introduce it now, as it would be a breaking change. However, given that we've already discussed this in the past, we may come back to it after some time.

Thanks for your suggestion.
