### ISSUE TITLE
Bug: Percentage discount with specific products and min quantity of products set does not work.

### ISSUE THREAD

**Issue by CossackDex** [saleor/saleor#11230]
### What are you trying to achieve?

I want to be able to properly applied discounts for products from collection

### Steps to reproduce the problem

1. Go to dashboard → Vouchers and create new voucher
2. Select percentage value with specific products
3. Select collection with product
4. select 2 different products
5. minimum quantity of items: 2
6. set  usage limit: 1000
7. Go to checkout add products from the collection to which the discount should be applied
8. Add the discount
9. The discount got applied but its 0. Also, when u place an order from the checkout, the discount isn't even in the order (don't know if that part is expected).

### What did you expect to happen?

I want the discount to be properly applied 

### Environment

Saleor version: dashboard v3.7.11 core v3.7.33
OS and version: …

**Comment by aniav** [comment]
This has been resolved in the newest version of Saleor.
