### ISSUE TITLE
Validate App Manifest to ensure permissions match declared webhook events

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#11261]
### What I'm trying to achieve

When I install app and it doesn't have permission for event I request, event will be never delivered

### Describe a proposed solution

During app installation via manifest, check if every event declared in manifest matches requested permissions, otherwise fail installation with proper message

### Other solutions I've tried and won't work
…

**Comment by aniav** [comment]
@lkostrowski is this still am issue? Maybe we can close this?

**Comment by lkostrowski** [comment]
https://linear.app/saleor/issue/IFREQ-29
