### ISSUE TITLE
Bug: Creating an upload an image in dashboard, thumbnail url is http://localhost:8000

### ISSUE THREAD

**Issue by skymoore** [saleor/saleor#11267]
### What are you trying to achieve?

I have saleor [deployed with kubernetes](https://github.com/skymoore/saleor-platform-k8s-kustomize).  When I create a product and upload an image for that product in the dashboard, then go back to the products listing, the dashboard makes a request to http://localhost:8000/thumbnail/someImage, because that's what the api responds with for the thumbnail url, even though the `MEDIA_URL` is configured, and the `API_URI` is configured.  Not sure what I'm missing in [my configuration](https://github.com/skymoore/saleor-platform-k8s-kustomize/tree/main/environments/slr.rwx.dev/config) and image build.

If I call the thumbnail endpoint myself with curl, it will generate the thumbnail and then display it, but for some reason when the image is uploaded the thumbnail url for the product is populated with localhost:8000.

Core and Dashboard version 3.8.4.

The queries below were performed against my test instance at : https://api.slr.rwx.dev/graphql/.  I would be happy to supply a token to this test instance if anyone would like for debugging.

```bash
root@saleor-84c754f9c6-fqvq7:/app# env |grep localhost
# nooutput
```

### Steps to reproduce the problem
1. create a product
   **mutation**
```
mutation {
  productCreate(input: {name: "TEST PRODUCT", category: "Q2F0ZWdvcnk6MQ==", productType: "UHJvZHVjdFR5cGU6MQ=="}) {
    product {
      id
      name
      thumbnail{url}
    }
  }
}
```
2. create product media
**mutation**
```
mutation {
  productMediaCreate(input: {alt:"",mediaUrl:"http://ecx.images-amazon.com/images/I/415W2YHAJ4L._AA160_.jpg",product:"UHJvZHVjdDo4"}){__typename}
}
```
3. get products
**query**
```
{
  products(first:1){
    edges{
      node{
        id , slug, channel, name,
        variants{
          name, id
        },
        media{
          id, url
        },
        thumbnail{
            url
        }
      }
    }
  }
}
```
**results**
```
{
  "data": {
    "products": {
      "edges": [
        {
          "node": {
            "id": "UHJvZHVjdDo4",
            "slug": "test-product",
            "channel": null,
            "name": "TEST PRODUCT",
            "variants": [],
            "media": [
              {
                "id": "UHJvZHVjdE1lZGlhOjY=",
                "url": "https://cdn.slr.rwx.dev/media/products/415W2YHAJ4L._AA160__563c1bdb.jpg"
              }
            ],
            "thumbnail": {
              "url": "http://localhost:8000/thumbnail/UHJvZHVjdE1lZGlhOjY=/256/"
            }
          }
        }
      ]
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 5,
      "maximumAvailable": 50000
    }
  }
}
```

### What did you expect to happen?

thumbnail url should start with baseurl of api.

### Environment

Saleor version: 3.8.4
OS and version: Docker images built as shown in [my readme](https://github.com/skymoore/saleor-platform-k8s-kustomize/blob/main/README.md)

**Comment by ashishkpaul** [comment]
Mingt be There is a bug in dashboard to update store settings https://docs.saleor.io/docs/3.x/dashboard/configuration/site#general-information
May be help u https://docs.saleor.io/docs/3.x/developer/api-reference/objects/shop-settings-update
If it helps u Please also post store settings update mutation here :)

**Comment by skymoore** [comment]
@ashishkpaul That fixed it, but it's a little tricky.   The mutation only works once per container start... no idea why, subsequent calls will update the site name, but not the site domain.  
mutation:
```
mutation {
  shopDomainUpdate(input: {domain: "api.slr.rwx.dev", name: "saleor"}){__typename}
}
```
query to verify:
```
{
  shop{domain{__typename, url}, name}
}
```
response:
```
{
  "data": {
    "shop": {
      "domain": {
        "__typename": "Domain",
        "url": "http://api.slr.rwx.dev/"
      },
      "name": "saleor"
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 0,
      "maximumAvailable": 50000
    }
  }
}
```
and thumbnail urls are fixed... sort of... only issue is I don't know how to set the protocol to https.  If you put the protocol in the domain field of the mutation it cuts off at the first `/` and the domain ends up being `https://` either way, I have ssl redirect set up so it's good enough for me for now... definitely think this should be able to be set in the dashboard.

**Comment by magul** [comment]
@skymoore that looks like something related to #11117.

**Comment by ashishkpaul** [comment]
> @ashishkpaul That fixed it, but it's a little tricky. The mutation only works once per container start... no idea why, subsequent calls will update the site name, but not the site domain. mutation:
> 
> ```
> mutation {
>   shopDomainUpdate(input: {domain: "api.slr.rwx.dev", name: "saleor"}){__typename}
> }
> ```
> 
> query to verify:
> 
> ```
> {
>   shop{domain{__typename, url}, name}
> }
> ```
> 
> response:
> 
> ```
> {
>   "data": {
>     "shop": {
>       "domain": {
>         "__typename": "Domain",
>         "url": "http://api.slr.rwx.dev/"
>       },
>       "name": "saleor"
>     }
>   },
>   "extensions": {
>     "cost": {
>       "requestedQueryCost": 0,
>       "maximumAvailable": 50000
>     }
>   }
> }
> ```
> 
> and thumbnail urls are fixed... sort of... only issue is I don't know how to set the protocol to https. If you put the protocol in the domain field of the mutation it cuts off at the first `/` and the domain ends up being `https://` either way, I have ssl redirect set up so it's good enough for me for now... definitely think this should be able to be set in the dashboard.

u can try environment variable like ```export ENABLE_SSL=True```

**Comment by skymoore** [comment]
Curl command to update the site domain:
```bash
export TOKEN="someReallyLongTokenGoesHere"
# set the name and domain in the mutation
curl 'https://api.slr.rwx.dev/graphql/' \
    -X POST \
	-H 'Content-Type: application/json' \
	-H "authorization-bearer: $TOKEN" \
    --data-raw '{"operationName":"ShopDomainUpdate","variables":{"input":{"name":"saleor","domain":"api.slr.rwx.dev"}},"query":"mutation ShopDomainUpdate($input:SiteDomainInput!){shopDomainUpdate(input:$input){__typename}}"}'
```

**Comment by skymoore** [comment]
> u can try environment variable like export ENABLE_SSL=True
> query to verify: https://docs.saleor.io/docs/3.x/developer/api-reference/objects/domain
@ashishkpaul That worked.  Thank you!

**Comment by skymoore** [comment]
> @skymoore that looks like something related to #11117.

@magul 
I agree.  I think the issue really is that in 3.8.4, there is no place to set this in the dashboard, so a new user like myself, doesn't even know this setting exists.  It seems to me like it should be an environment variable.

**Comment by akhial** [comment]
For me the domain update mutation doesn't update the URL...
``` graphql
mutation {
  shopDomainUpdate(
    input: { domain: "www.example.com", name: "Saleor" }
  ) {
    shop {
      domain {
        host
        url
        sslEnabled
      }
      name
    }
  }
}

```

Result: 
``` json
{
  "data": {
    "shopDomainUpdate": {
      "shop": {
        "domain": {
          "host": "www.example.com",
          "url": "http://localhost:8000/",
          "sslEnabled": false
        },
        "name": "Saleor"
      }
    }
  }
}
```

**Comment by skymoore** [comment]
> For me the domain update mutation doesn't update the URL...
> 
> ```graphql
> mutation {
>   shopDomainUpdate(
>     input: { domain: "www.example.com", name: "Saleor" }
>   ) {
>     shop {
>       domain {
>         host
>         url
>         sslEnabled
>       }
>       name
>     }
>   }
> }
> ```
> 
> Result:
> 
> ```json
> {
>   "data": {
>     "shopDomainUpdate": {
>       "shop": {
>         "domain": {
>           "host": "www.example.com",
>           "url": "http://localhost:8000/",
>           "sslEnabled": false
>         },
>         "name": "Saleor"
>       }
>     }
>   }
> }
> ```

For me it only works once per container start.  Try restarting the container.

**Comment by akhial** [comment]
Seems like the URL is only updated after restarting the service. Thanks @skymoore and @ashishkpaul!

**Comment by akhial** [comment]
I think it would be nice if the shop domain was configurable via an environment variable.

**Comment by gempain** [comment]
There seems to be an open issue about this in https://github.com/saleor/saleor-dashboard/issues/2641

**Comment by simon-online** [comment]
Is this caused by a breaking change after upgrading to a newer version of Saleor?

Why are there no details about this in the CHANGELOG.md files or documentation?

**Comment by tiendq** [comment]
> For me the domain update mutation doesn't update the URL...
> 
> ```graphql
> mutation {
>   shopDomainUpdate(
>     input: { domain: "www.example.com", name: "Saleor" }
>   ) {
>     shop {
>       domain {
>         host
>         url
>         sslEnabled
>       }
>       name
>     }
>   }
> }
> ```
> 
> Result:
> 
> ```json
> {
>   "data": {
>     "shopDomainUpdate": {
>       "shop": {
>         "domain": {
>           "host": "www.example.com",
>           "url": "http://localhost:8000/",
>           "sslEnabled": false
>         },
>         "name": "Saleor"
>       }
>     }
>   }
> }
> ```

I'm facing the same issue with 3.12.9, don't know why this road blocker doesn't happen with their cloud.

And my `url` field is not updated too :(

**Comment by tiendq** [comment]
@skymoore 

I see product thumbnail image is `http://localhost:8000/thumbnail/UHJvZHVjdE1lZGlhOjM=/4096/` in `saleor dashboard` edit product page. In production deployment which app will handle this thumbnail url? It looks like a dynamic generated content since I didn't see the thumbnail image file under `media/products/thumbnails` folder.

Thanks,

**Comment by skymoore** [comment]
@tiendq Glad you got it sorted, yeah I don't know anything about cloud, I only learned about this because I was developing [this k8s deployment for saleor](https://github.com/skymoore/saleor-platform-k8s-kustomize)

**Comment by tiendq** [comment]
> @tiendq Glad you got it sorted, yeah I don't know anything about cloud, I only learned about this because I was developing [this k8s deployment for saleor](https://github.com/skymoore/saleor-platform-k8s-kustomize)

Thanks, actually there were a few changes to configuration but it has been not documented well. I believe they should improve the understanding of "domain" in this context.

**Comment by akhial** [comment]
Update on http to https redirect when running behind Nginx.

If you need ENABLE_SSL to be off and have the instance be accessible by http (to install apps for example), you can add:
```
error_page 497 =308 https://$host:$server_port$request_uri;
```
To your Nginx config.

This will catch the "http request sent to https port" error in Nginx and bounce the client to the proper protocol.
It returns a 308 permanent redirect to preserve the POST method.
