### ISSUE TITLE
Add `schemaVersion` field to `Shop` type

### ISSUE THREAD

**Issue by zedzior** [saleor/saleor#11274]
### What I'm trying to achieve
I want to add public information about Saleor's api version to `Shop` type.

### Describe a proposed solution
```graphql
type Shop {
   ...
   schemaVersion: String!
}
```

`schemaVersion` will be displayed without any permissions and will be truncated to minor version only. 

### Other solutions I've tried and won't work
…

**Comment by patrys** [comment]
I think it needs to be `String!` as it's guaranteed not to return `null`.
