### ISSUE TITLE
Make email case insensitive 

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#11277]
### What are you trying to achieve?

Make emails case insensitive to prevent login issues.

### Steps to reproduce the problem

Create account Test@test.com
Login with test@test.com

### What did you expect to happen?

It should be possible to login under the same account using test@test.com and Test@test.com. Essentially any provided email should be read in lower case. With exception if the system has two accounts under test@test.com and Test@test.com then login should happen to the corresponding account provided. 

### Environment

Saleor version: 3.9

**Comment by korycins** [comment]
@timuric  Should we also take into account the case where we have email provided with upper case? Like [test@test.com](mailto:test@test.com), [Test@test.com](mailto:Test@test.com) and TEST@TEST.COM?
