### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by likecodingloveproblems** [saleor/saleor#11458]
### What are you trying to achieve?

I try to see Checkout app about content in demo dashboard app.

### Steps to reproduce the problem

Get https://demo.saleor.io/dashboard/apps/QXBwOjMx/

### What did you expect to happen?

see information

### Environment

Saleor version: …
OS and version: …

**Comment by lkostrowski** [comment]
Thanks for the report, fixed in https://github.com/saleor/saleor-dashboard/pull/2803
