### ISSUE TITLE
Bug: Unable to add digital product to draft order without assigning a new warehouse with stock.

### ISSUE THREAD

**Issue by CossackDex** [saleor/saleor#11553]
### What are you trying to achieve?

I'm trying to add a digital product to the draft order without an assigned warehouse with stock.

### Steps to reproduce the problem

1. Create a digital product type and follow up that with a product with the mentioned product type
2. Assing it to the channel and set prices
3. Don't assign warehouse OR assign warehouse but set the quantity to 0
4. Create a draft order and try to add created product

### What did you expect to happen?

I should be able to add digital products without a warehouse assigned/ with 0 quantity available products 

### Environment

dashboard v3.9.5
core v3.9.5

**Comment by timuric** [comment]
duplicate https://github.com/saleor/saleor/issues/7531

**Comment by nnthuanegany** [comment]
It's still not working for me. I'm using the cloud version of Saleor with the Developer pricing
