### ISSUE TITLE
Bug: countryArea filed validation in addressCreate mutattion

### ISSUE THREAD

**Issue by szczecha** [saleor/saleor#11572]
### What are you trying to achieve?

addressCreate mutation should validate countryArea like in other mutations and return normalized countryArea

### Steps to reproduce the problem

Request
```
mutation CreateCustomerAddress($id: ID!, $input: AddressInput!) {
  addressCreate(userId: $id, input: $input) {
    errors {
      field
      message
      code
    }
    address {
      id
      countryArea
      postalCode
    }
    user {
      id
    }
  }
}

```
Variables:
```
{
  "id": "VXNlcjoxNjE0",
  "input": {
    "city": "test",
    "cityArea": "test",
    "companyName": "test",
    "country": "US",
    "countryArea": "Indiana",
    "firstName": "test",
    "lastName": "test",
    "phone": "",
    "postalCode": "46802",
    "streetAddress1": "test",
    "streetAddress2": ""
  }
}
```
<img width="1366" alt="Screenshot 2022-12-26 at 14 46 19" src="https://user-images.githubusercontent.com/30683248/209641418-9a45fd04-e795-4751-8799-b9b3a89108e3.png">

<img width="1323" alt="Screenshot 2022-12-27 at 09 54 48" src="https://user-images.githubusercontent.com/30683248/209642566-a1548ad0-4180-40b3-9258-ee432df52091.png">

### What did you expect to happen?

I expect each mutation with addresses to return a normalized country area e.g 
addressUpdate mutation:
<img width="1414" alt="Screenshot 2022-12-26 at 14 46 51" src="https://user-images.githubusercontent.com/30683248/209641473-60861f77-d464-473a-a9a1-524e225df1a6.png">

checkoutCreate
<img width="1741" alt="Screenshot 2022-12-27 at 10 09 09" src="https://user-images.githubusercontent.com/30683248/209642456-785f6309-0829-41fd-afc9-c456efd234ce.png">

### Environment

Saleor version: core v3.10.0-a
OS and version: …

**Comment by karolm-saleor** [comment]
@jakubkuc is there any progress with this task?
