### ISSUE TITLE
Bug: Misused a dataloader in graphql shipping module

### ISSUE THREAD

**Issue by iamleson98** [saleor/saleor#11588]
### What are you trying to achieve?

Take a look at this dataloader:
https://github.com/saleor/saleor/blob/f1c00de75df0244e887746c32cc89fbe49ec9772/saleor/graphql/shipping/dataloaders.py#L99

I think you are using the argument `keys` the wrong way.
keys has form of
```python
List[Tuple[str, str]]
```

### Steps to reproduce the problem

go to this link and see yourself:
https://github.com/saleor/saleor/blob/f1c00de75df0244e887746c32cc89fbe49ec9772/saleor/graphql/shipping/dataloaders.py#L99

### What did you expect to happen?

I think we should do like below instead:
```python
shipping_zone_ids = []
channel_slugs = []

for item in keys:
    shipping_zone_ids.append(item[0])
    channel_slugs.append(item[1])

ShippingMethod.objects.filter(shipping_zone_id__in=shipping_zone_ids)
```

If I was wrong, please kindly let me know.

Thank you, ms. @IKarbowiak , mr. @maarcingebala 

### Environment

Saleor version: production
OS and version: linux ubuntu

**Comment by peelar** [comment]
Hello @iamleson98 👋 

It appears this is, in fact, a bug. Good catch! We will be sure to keep you posted regarding this issue. Thank you

**Comment by iamleson98** [comment]
Hellor mr. @peelar.

I'm glad I can contribute to such a good opensource software as Saleor.

I would like to ask for an explanation from you on a bit of code am confused. 

Please take a look at this code:
https://github.com/saleor/saleor/blob/bf1d57a9d65238686553c5032a7de4497a299217/saleor/graphql/discount/types.py#L123

I can see the type `ChannelContext` is used in pretty much graphql type resolve methods.

Let say when I have the following query

```graphql
sale {
    categories(first: 5) {
        id
        slug
    }
}
```

How does the code know the first param root is `ChannelContext[models.Sale]` but not models.Sale ?

Could you please explain that to me ?

Thank you in advance!

**Comment by Henatesjr** [comment]
Stop sending me emails

**Comment by iamleson98** [comment]
@Henatesjr, unwatch the project yourself then nothing will disturb you. I did not mean to spam your inbox.

**Comment by IKarbowiak** [comment]
Hi @iamleson98,

I appreciate your willingness to contribute! The `ChannelContext` is created in the query resolvers. 
Take a look at `resolve_sale` here:

https://github.com/saleor/saleor/blob/bf1d57a9d65238686553c5032a7de4497a299217/saleor/graphql/discount/schema.py#L103

It calls the other `resolve_sale` which attaches the `ChannelContext`
https://github.com/saleor/saleor/blob/bf1d57a9d65238686553c5032a7de4497a299217/saleor/graphql/discount/resolvers.py#L25

I hope it helps! 🙂
