### ISSUE TITLE
Drop hardcoded sphinxcontrib-applehelp version

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#11664]
`sphinxcontrib-applehelp` was hardcoded [due to this issue](https://github.com/coddingtonbear/python-measurement/issues/75). in the Pytest workflow. Once it's resolved we can drop the extra requirement.

https://github.com/saleor/saleor/blob/main/.github/workflows/pytest.yml#L57

**Comment by ogunheper** [comment]
Hi @maarcingebala ,

They have recently published [3.2.1](https://github.com/coddingtonbear/python-measurement/releases/tag/3.2.1) to fix the issue.

You might consider using that.

Best,
Ogün
