### ISSUE TITLE
Bug: Heroku configs are outdated

### ISSUE THREAD

**Issue by vitalii-bulyzhyn** [saleor/saleor#11723]
### What are you trying to achieve?

Deploy to Heroku

### Steps to reproduce the problem

1. Click on "Deploy to Heroku" button
2. Set up needed env variables
3. Click "Deploy App"

### What did you expect to happen?

App being deployed

### Logs

There was an issue setting up your app environment.

- invalid app.json
- The heroku-postgresql:hobby-dev plan is no longer available. Choose a different plan. See all available plans in the Elements Marketplace at elements.heroku.com.
- The heroku-redis:hobby-dev plan is no longer available. Choose a different plan. See all available plans in the Elements Marketplace at elements.heroku.com.

### Environment

Saleor version: …
OS and version: …

**Comment by maarcingebala** [comment]
Deployemnt to Heroku is no longer supported out of the box.

**Comment by amityweb** [comment]
I know this is an old thread, but I cant find info about this statement: "_Deployemnt to Heroku is no longer supported out of the box."

What does one do when they already have deployed to Heroku using your previous recomnended deployment method to Heroku? I cannot update Saleor, when I do it does not work on Heroku anymore.
