### ISSUE TITLE
Bug: Unable to create a new attribute value for multiselect attribute 

### ISSUE THREAD

**Issue by CossackDex** [saleor/saleor#11776]
### What are you trying to achieve?

I'm trying to create a new value for multi-select attribute 

### Steps to reproduce the problem

1. Create a new multi-select attribute.
2. By using GraphQL mutation, try to add a new value to it
3. Saleor returns that "value" field can be defined only for swatch attributes.

### What did you expect to happen?

I want to be able to assign add a new attribute value by using mutation above the 

### Logs

Query

 ```
fragment AttributeValue on AttributeValue {
  id
  name
  slug
  inputType
  boolean
  date
  richText
  __typename
}

mutation AttributeValueCreate($attribute: ID!, $input: AttributeValueCreateInput!) {
  attributeValueCreate(attribute: $attribute, input: $input) {
    attributeValue {
      ...AttributeValue
      __typename
    }
    errors {
      field
      message
      __typename
    }
    __typename
  }
}
```

Vars

```
{
  "input": {
    "value": "Mogul",
    "name": "Golum"
  },
  "attribute": "QXR0cmlidXRlOjEwNA=="
}
```

### Environment

Saleor version: 3.10.1

**Comment by IKarbowiak** [comment]
@CossackDex it's expected behaviour, the `value` field is reserved for the `swatch` attribute, in the case of `multiselect` you should provide just the `name` of the value. Remove `value` from the input and it'll be working properly.
