### ISSUE TITLE
Bug: Giftcard created event is not triggered when gift card is bought 

### ISSUE THREAD

**Issue by CossackDex** [saleor/saleor#11828]
### What are you trying to achieve?

I'm trying to inform the external system about the creation of the gift card. 

### Steps to reproduce the problem

1. Create a Product type of Gift card
2. Create gift card -> Product
3. Create webhook which triggers on gift card creation 
4. Create draft order and add newly gift card 
5. Finalize draft order 

### What did you expect to happen?

Saleor should properly send a webhook after the gift card is created.

### Environment

Saleor version: 3.10

**Comment by rafalp** [comment]
I'll work on this.
