### ISSUE TITLE
Bug: Sending empty email when email template is empty string

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#11830]
### What are you trying to achieve?

I want to turn off the given type of email. To do that I need to leave the given template as an empty field. As on the screenshot:
![image](https://user-images.githubusercontent.com/23282005/215036686-b35d7118-3851-4531-81c2-a687368eb8ce.png)
If by mistake I will leave space there, Saleor will send empty email

### Steps to reproduce the problem

1. Activate email plugin(if disabled)
2. Remove template for single email. Add there single space
3. Save plugin
4. Trigger an email.
5. The email will be send with empty body.

### What did you expect to happen?

I would expect that empty template field and field with only single/multiple space(s) will not trigger the email.

### Environment

Saleor version: 3.0+
OS and version: …

**Comment by jalajk24** [comment]
Can I work on this issue? I am pretty new to this

**Comment by maarcingebala** [comment]
I think we can close this for now- we'll be sunsetting plugins soon and the recommended way to handle emails is via webhooks.
