### ISSUE TITLE
[RFC] Bulk order create / order import

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#11870]
# Order Import RFC

This document describes a mutation allowing users to create multiple orders in Saleor. Purpose of this mutation could be importing orders from other system. The main assumption is to allow the user to specify as many fields as possible and skip most of the logic and calculations that are done when creating orders from draft or checkout. Among the other things, the mutation allows specifying things like: order creation date, order number, order lines with net and gross line prices, payment transactions, and fulfillments. 

### Permissions

- The mutation requires a new permission: `MANAGE_ORDERS_IMPORT`. Since this operations is more powerful than regular order management, it is not automatically assigned to staff users or apps with `MANAGE_ORDERS` permission. Instead it is assigned only to “full access” users, if such a group exists in the system, or to `MANGE_SETTINGS` users.

### GraphQL Schema

```graphql
type Mutation {
  orderBulkCreate(
    errorPolicy: ErrorPolicyEnum,
    stockUpdatePolicy: StockUpdatePolicyEnum,
    orders: [OrderBulkCreateInput!]!
  ): OrderBulkCreate!
}

type OrderBulkCreate {
  count: Int!
  results: [OrderBulkCreateResult!]!
}

type OrderBulkCreateResult {
  order: Order!
  errors: [OrderBulkCreateError!]
}

type OrderBulkCreateError {
  path: String
  message: String
  code: OrderBulkCreateErrorCode!
}

enum OrderBulkCreateErrorCode {
    GRAPHQL_ERROR
    REQUIRED
    INVALID
    NOT_FOUND
    UNIQUE
    BULK_LIMIT
    TOO_MANY_IDENTIFIERS
    FUTURE_DATE
    INVALID_QUANTITY
    PRICE_ERROR
    NOTE_LENGTH
    INSUFFICIENT_STOCK
    NON_EXISTING_STOCK
    NO_RELATED_ORDER_LINE
    NEGATIVE_INDEX
    ORDER_LINE_FULFILLMENT_LINE_MISMATCH
    METADATA_KEY_REQUIRED
    INCORRECT_CURRENCY
}

enum OrderOriginEnum {
  BULK_CREATE
}

enum StockUpdatePolicyEnum {
  SKIP
  UPDATE
  FORCE
}

"""
If `id` is provided, try to get the user by ID. If `email`
is provided try to lookup the user by email; if not found,
set only the email in the Order instance.
"""
input OrderBulkCreateUserInput {
  id: ID
  email: String
  externalReference: String
}

input TaxedMoneyInput {
  gross: MoneyInput!
  net: MoneyInput!
}

"""
Accepts either warehouse or delivery method. Accepts denormalized 
names of delivery methods.
"""
input OrderBulkCreateDeliveryMethodInput {
  warehouseId: ID
  warehouseName: String
  shippingMethodId: ID
  shippingMethodName: String
  shippingPrice: TaxedMoneyInput
  shippingTaxRate: Float
  shippingTaxClass: ID
  shippingTaxClassName: String
  shippingTaxClassMetadata: [MetadataInput!]
  shippingTaxClassPrivateMetadata: [MetadataInput!]
}

input OrderBulkCreateNoteInput {
  message: String!
  date: DateTime
  userId: ID
  userEmail: String
  userExternalReference: String
  app: ID
}

input OrderBulkCreateInput {
  externalReference: String
  channel: ID!
  createdAt: DateTime!
  status: OrderStatus!
  user: OrderBulkCreateUserInput!
  trackingClientId: String
  billingAddress: AddressInput!
  shippingAddress: AddressInput
  currency: String!
  privateMetadata: [MetadataInput!]
  metadata: [MetadataInput!]
  customerNote: String
  notes: [OrderBulkCreateNoteInput!]
  languageCodeEnum: LanguageCodeEnum!
  displayGrossPrices: Boolean
  weight: WeightScalar
  redirectUrl: String
  lines: [OrderBulkCreateOrderLineInput!]!
  deliveryMethod: OrderBulkCreateDeliveryMethodInput!
  transactions: [TransactionCreateInput!]!
  promoCodes: [String!]
  discounts: [OrderDiscountCommonInput!]
  fulfillments: [OrderBulkCreateFulfillmentInput!]
  stockUpdatePolicy: StockUpdatePolicyEnum!
  invoices: [OrderBulkCreateInvoiceInput!]
}

input OrderBulkCreateOrderLineInput {
  variantId: ID
  variantSku: String
  variantExternalReference: String
  variantName: String
  productName: String
  translatedVariantName: String
  translatedProductName: String
  created: DateTime!
  isShippingRequired: Boolean!
  isGiftCard: Boolean!
  quantity: Int!
  totalPrice: TaxedMoneyInput!
  undiscountedTotalPrice: TaxedMoneyInput!
  warehouse: ID!
  metadata: [MetadataInput!]
  privateMetadata: [MetadataInput!]
  taxRate: Float
  taxClass: ID
  taxClassName: String
  taxClassMetadata: [MetadataInput!]
  taxClassPrivateMetadata: [MetadataInput!]
}

input OrderBulkCreateFulfillmentInput {
  trackingCode: String
  lines: [OrderBulkCreateFulfillmentLineInput!]
}

input OrderBulkCreateFulfillmentLineInput {
  variantId: ID
  variantSku: String
  variantExternalReference: String
  quantity: Int!
  warehouse: ID!
  orderLineIndex: Int!
}

input OrderBulkCreateInvoiceInput {
  createdAt: DateTime!
  number: String
  url: String
  privateMetadata: [MetadataInput!]
  metadata: [MetadataInput!]
}
```

### Implementation details

- `OrderBulkCreateInput.user` - add validation to require one of `id` or `email`.
- `OrderBulkCreateInput.status` - Allow to provide a status of an order; provide a validation for some of the statuses:
    - `UNFULFILLED` - cannot be set if there are any fulfillments in the input to be created
    - `PARTIALLY_FULFILLED` and `FULFILLED` - cannot be set if there are no fulfillments in the input.
- `OrderBulkCreateInput.number`
    - allow providing any string value as long as it is unique; it doesn’t have to be a number;
    - update the current value in the underlying database sequence after each batch, so it won’t try to assign a number that was already provided in the batch
- `OrderBulkCreateInput.created` - accept future time values but with a grace period for example, 5 mins from the current time; some systems might have incorrect time that is in the future compared to Saleor. At the same time, we don't want to create orders that are too far in the future.
- `OrderBulkCreateInput.lines` - add validation to require one of `variantID`, `variantSku`, or `variantExternalReference`. **Important: `lineTotalPrice` and `undiscountedLineTotalPrice` are the primary sources of truth about the order pricing - unit price, undiscounted unit price, discount amount, order total and subtotal should be calculated based on that.**
- `OrderBulkCreateInput.displayGrossPrices` - if not provided calculate it based on current tax settings (see how it is calculated when an order is placed and reuse the logic)
- `OrderBulkCreateInput.notes` - allow to provide a custom list of events that would be saved as `OrderEvent` instances in the order history. For each event, the user can provide a message, timestamp, and either a user or an app that is associated with the event. This has a similar effect to calling `orderAddNote` mutation, but with extra options and in bulk.
- `OrderBulkCreateInput.transactions` - a bulk version of `transactionCreate` mutation; implementation should reuse the logic from that mutation. Extract the logic to a common module and reuse it between both mutations.
- `OrderBulkCreateInput.gift_cards/voucher` - accepts a list of gift card codes and a single voucher code that should be associated with the order but it doesn’t trigger any price recalculation. Prices are based only on line totals.
- `OrderBulkCreateInput.fulfillments` - creates a fulfillment object similar to the `orderFulfill` mutation; the difference is that `orderFulfill` expects an order line ID, but here we don’t have it yet. Instead, we expect a variant identifier that is used to create an order line: either variant ID, SKU, or external reference (one of them needs to be provided).
- `StockUpdatePolicy` - Determine how stocks should be updated, while processing fulfillment.
      - `SKIP` - stocks are not checked and not updated
      - `UPDATE` - only do update, if there is enough stocks
      - `FORCE` - force update, if there is not enough stocks, 
- Extend `OrderOriginEnum` with the `BULK_CREATE` option and set it in the mutation.
- `Order.updatedAt` - set to the current timestamp after bulk creation is finished.
- Order total, subtotal, and order line unit prices are skipped - instead only order line total is provided, and other fields should be calculated based on that.
- Add a new webhook event to trigger for all “imported” orders: `ORDER_BULK_CREATED`
- `OrderBulkCreateError.path` - provide path to field related to error, ie. `fulfillments.1.lines.0.warehouse`

### Scope of work
The scope can be split into smaller phases, e.g. more "complex" fields such as `transactions` or `fulfillments` could be added separately.

**Comment by korycins** [comment]
@maarcingebala 
What is the expected behavior if one of the order imports will fail? I see that we return the error related to the order but the rest of the orders will be imported correctly, right?

----

Are we going to have any limits here of the number of the orders that can be imported at one mutation call?

----
Shouldn't we also allow to match user by using `externalReference`?

```graphql
input OrderBulkCreateUserInput {
  id: ID
  email: String
}
```

**Comment by maarcingebala** [comment]
@korycins 
1 - there is ErrorPolicyEnum which you can use to decide how to handle errors, either reject entire batch, reject only failed order, or try to save as much data as possible.
2 - Yes there will be limit for all bulk mutations.
3 - If there are external references for users then yes, we should do that.

**Comment by szczecha** [comment]
Integration tests to implement:
Should be able to do create order from imported draft

**Comment by korycins** [comment]
@zedzior @maarcingebala 

> Add a new webhook event to trigger for each “imported” order: ORDER_BULK_CREATED

Are you sure this is the correct approach? If you are importing a large number of orders and have five or more celery workers triggering webhooks, this will generate a high load that the app may not be able to handle. As a result, the app may start returning 500 code, causing us to resend the request.

Instead of sending the `ORDER_BULK_CREATED` webhook for each order, wouldn't it be better to send a single webhook with a list of all imported orders?
