### ISSUE TITLE
Include app ID to signature token (aud)

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#12036]
### What I'm trying to achieve
I want to ensure that the webhook received by the app was triggered for exactly this app. 

A malicious app can clone the webhook payload it received and send it to another app. The signature will be valid, but the recipient is not.

### Describe a proposed solution
The `signature` header is a jwt token that can contain an `aud` field that is an app identifier.

The app, after signature verification, will read `aud` and compare it to its own saved id

### Other solutions I've tried and won't work

The app can use `event.recipient.id` to do the same, but it requires an app developer to add in manually for every webhook handler, which is a leaky abstraction.

**Comment by przlada** [comment]
I propose to be consistent and extend the webhook JWS header with `app` field containing the app id. We can then verify webhooks the same way access tokens are verified based on comparing the app's own id with the one from JWS header.
Introducing `aud` field to webhook JWS is also a good idea, but in my opinion, we should make it propagate the value from `App.audience` the same as in access tokens.

**Comment by patrys** [comment]
@przlada I'm not sure if adding custom claims to the header is a good idea. What does the standard say about custom claims? I agree about the audience if it's specified, we should be consistent with the access token behavior. We could still use the app identifier if an explicit audience is not given.

**Comment by lkostrowski** [comment]
Now app-sdk is checking in the background app id from token claims
