### ISSUE TITLE
Product manufacturing and expiration dates

### ISSUE THREAD

**Issue by igiyazov** [saleor/saleor#12115]
### What I'm trying to achieve
Did not find the expiration date of the product in Saleor. There are a number of products, the expiration dates of which need to be monitored. I think you need to add expiration dates fields

### Describe a proposed solution
Add two fields:
```manufaturing_date```
```expiration_date```

### Other solutions I've tried and won't work
I tried to put all this in metadata, but the right solution would be to add them in product as separate fields

**Comment by maarcingebala** [comment]
These fields are specific to a particular use case, the recommended way of adding this is via metadata.
