### ISSUE TITLE
Bug: Uncaught error when pass invalid UUID as checkout token

### ISSUE THREAD

**Issue by fowczarek** [saleor/saleor#12160]
### What are you trying to achieve?

I try to fetch checkout via token but by accident use invalid token.

### Steps to reproduce the problem

1. Execute the query:
```
{
  checkout(token:"{38f75b23-5e53-4bd7-a6d8-8df1b506ef9a:''}"){
    id
  }
}
```

### What did you expect to happen?

Saleor should raise a validation error. 

### Environment

Saleor version: 3.11
OS and version: Cloud

**Comment by maarcingebala** [comment]
Validation error should be returned in a mutation, but in query we usually return GraphQL Error with message `      "message": "Couldn't resolve id: <id>"`. There is the `from_global_id_or_error` utility for that.
