### ISSUE TITLE
Async event substitute for send_gift_card plugin event

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor#12165]
### What I'm trying to achieve

Migrate customer emails plugin to the App. Currently, there's no available async event to `send_gift_card`. 

### Describe a proposed solution

Invoices already have a familiar behaving event - `INVOICE_SENT`.

### Other solutions I've tried and won't work

Gift card created doesn't seem to be the same event - creation and sending to the user are different actions.

**Comment by lkostrowski** [comment]
@krzysztofwolski as discussed with @timuric , this can be achieved without a new event, at least for now

We can explore payload of GiftcardCreated to infer if it was triggered by the user, or the staff.

It means, from this single event we can "route" it to "sub-events" and have them configured in the App
