### ISSUE TITLE
Bug: The shipping taxes in plugins are not calculated when the `TaxClass` is not set

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#12186]
### What are you trying to achieve?

Plugin shipping taxes calculation requires setting the `TaxClass`. The `TaxClass` might be even empty, but It has to be set. It's invalid behavior. The plugins should calculate shipping taxes whether the `TaxClass` is set or not. The default shipping code should be used. The similar behavior should be for `products`.

### Steps to reproduce the problem

1. Confugure the `Avalara` plugin
2. Create checkout with the item for which taxes are calculated
3. Add a delivery method without choosing `TaxClass`
4. Check the lines and shipping prices - the shipping tax will be 0

### What did you expect to happen?

 The plugins should calculate shipping taxes whether the `TaxClass` is set or not. The default shipping code should be used. 

### Environment

Saleor version: 3.9

**Comment by slawekmarszalek** [comment]
Reported by: https://saleorcommerce.slack.com/archives/C017L12TRJS/p1677678823914359
