### ISSUE TITLE
Bug: Invalid prices when discounting prices with active Avatax

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#12209]
### What are you trying to achieve?

The uni prices returned from Saleor should not in increase when I change the quantity or something inside the order.

### Steps to reproduce the problem

1. Activate Avatax
2. Create order in the channel where avatax is active
3. add adresses
4. add lines
5. add order discount - 100 % 
6. add shipping
7. change the number of quantity for one of the lines.
The prices will change from 0.00 to a different value. It is not true as the discount - 100% is still applied.

### What did you expect to happen?

I expect that the price of lines will change only when I add the discount. When I change the quantity the unit price should be the same.

### Logs

![image](https://user-images.githubusercontent.com/23282005/222731839-6b7266f0-2b97-4045-a439-8c61148c4e29.png)
![image](https://user-images.githubusercontent.com/23282005/222731880-936528b1-0da3-44d0-b3cd-3004dd4ebb0f.png)
I tested this locally and found that the issue occurs when Avatax is enabled, as it reduces the unit price (see the first screenshot). Additionally, the prices increase when the quantity for a specific line is increased. Even if I increase the quantity for line A, the prices for lines B and C also increase (see the first and second screenshots).

Link to internal discussion: https://saleorcommerce.slack.com/archives/C039MGJDWU8/p1677847853144589

### Environment

Saleor version: 3.9.28
OS and version: OSX

**Comment by slawekmarszalek** [comment]
Reported in: https://saleorcommerce.slack.com/archives/C017L12TRJS/p1677843900295369
