### ISSUE TITLE
checkoutComplete should finalize the checkout when payment is processed

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#12229]
### What I'm trying to achieve
During the checkout completion process, CheckoutComplete always calls the process_payment or confirm_payment functions on the payment plugin side. However, it is possible that the payment was already processed, but we did not create the order due to some issues. In this case, the next call of checkoutComplete will call the payment plugin logic without checking the status of the payment.

### Describe a proposed solution
The proposed solution is to add additional logic to the checkoutComplete function. This logic will check the current status of the payment object. If the payment is already charged or authorized, there is no need to call the plugin logic. We already have enough information to know that the payment has been processed. In that case, we should skip the payment processing block and move on to the next one.

**Comment by igiyazov** [comment]
When paying, an order is not created. The order is only created if when checkoutComplete is called.
Procedure:
1) checkoutCreate (an order isn't created)
2) checkoutPaymentCreate (charging and order has not been created yet)
3) checkoutComplete (an order is created)

**Comment by korycins** [comment]
Closing, as we are moving to transactionAPI
