### ISSUE TITLE
Bug: Product variant update webhook on channel listing removal doesn't work

### ISSUE THREAD

**Issue by orzechdev** [saleor/saleor#12247]
### What are you trying to achieve?

I want to remove availability of product variant from channel listing, which succeed, channel listing is removed from product variant, but product variant update webhook (`PRODUCT_VARIANT_UPDATED`) events are not sent (on the other hand, while adding or updating channel listing they are sent as expected).

### Steps to reproduce the problem

The video that shows the missing webhook call:
https://user-images.githubusercontent.com/9825562/223417013-0f09dcc6-0680-4d11-9c6f-cdcd34a81c77.mp4

Steps to reproduce (similarly as on the video):
1. Register webhook for product variant update (`PRODUCT_VARIANT_UPDATED`).
2. Create product with variant, add channel listing to variant (enable channel and assign any price to it).
3. Remove channel listing from variant (disable channel, remove it, make channel unavailable for this variant).
4. See that it failed to send a webhook event on successful removal of product variant channel listing.

The issue occurs when removing channel listings with the dashboard, in which it is caused most probably because channel listing is removed only via `ProductChannelListingUpdate`:
<img width="1680" alt="Screenshot 2023-03-07 at 12 51 29" src="https://user-images.githubusercontent.com/9825562/223414572-813631b4-3d53-41a2-b442-1eb6211e5b0d.png">

...which is not the case when updating channel listing or adding it, because the dashboard uses also `VariantDatagridChannelListingUpdate` in that case:
- create: <img width="1680" alt="Screenshot 2023-03-07 at 12 54 22" src="https://user-images.githubusercontent.com/9825562/223415169-b8add4ab-6ef4-49e3-bd21-95eb185d8c60.png">
- update: <img width="1680" alt="Screenshot 2023-03-07 at 12 56 22" src="https://user-images.githubusercontent.com/9825562/223415393-d01233d3-919a-45b7-a05e-78a870acabe6.png">

### What did you expect to happen?

I expect to receive events on the registered product variant update (`PRODUCT_VARIANT_UPDATED`) webhook with updated product variant payload on successful removal of product variant channel listing.

Most probably handler of `ProductChannelListingUpdate` mutation should infer which variants has had altered channel listings and send events to registered `PRODUCT_VARIANT_UPDATED` webhooks accordingly.

### Environment

Saleor version: v3.11.12
OS and version: MacOS 12.4

**Comment by jakubkuc** [comment]
Hi! 
Thank you for your report! 
We highly recommend you update to Saleor 3.12. In the newest version (3.12.11) you should no longer encounter this problem.

**Comment by maarcingebala** [comment]
@orzechdev Can you confirm if this works for you on the newest version?

**Comment by orzechdev** [comment]
@maarcingebala Yes I confirm it works with the newest version. So I close the ticket.
