### ISSUE TITLE
Bug: Incorrect error is raised when Avatax plugin has old data

### ISSUE THREAD

**Issue by szczecha** [saleor/saleor#12282]
### What are you trying to achieve?
I want to configuration errors to be more understandable to the user

### Steps to reproduce the problem

1. Avatax plugin is set to active in channel but data credentials are incorrect (generated new password in avatax not updated in saleor env) 
2. Create draft order, add products, add client 
3. Try to add shipping method 

orderUpdateShipping  return Internal Servier Error
<img width="1792" alt="Screenshot 2023-03-09 at 17 13 48" src="https://user-images.githubusercontent.com/30683248/224289998-4e80c6e1-e04a-4d9b-acf9-c0aba8c8bd68.png">

### What did you expect to happen?

Better error handling in such case.

### Environment

Saleor version: core v3.13.0-a
OS and version: …

**Comment by maarcingebala** [comment]
It was changed recently, and now the "Internal Error Message" is returned instead of the exception message with more details. I think this might be handled properly in tax apps since plugins will be getting deprecated soon.

**Comment by szczecha** [comment]
https://linear.app/saleor/issue/SHOPX-1173/misconfigured-avalara-plugin-caused-internal-server-error-on-draft
