### ISSUE TITLE
Bug: API is serving media under localhost

### ISSUE THREAD

**Issue by valiukasd** [saleor/saleor#12288]
### What are you trying to achieve?

I have a deployed a saleor core image to a VM, and set up the environment variables as mentioned below:
```env
ALLOWED_HOSTS=my-server-ip
ALLOWED_CLIENT_HOSTS=*
DEBUG=True
```
There are other variables like db, redis, but I feel like they are irrelevant to this issue. I have left other variables like `MEDIA_URL` and `STATIC_URL` as the defaults, but as far as I understand they should't create this problem.

### Steps to reproduce the problem

1. Deploy saleor to the cloud and set it up
2. Go to dashboard and set the `API_URL` to the server
3. The storefront succesfully connects and pulls data, but the images are server under localhost, so they are not loading, the same thing happens in the dashboard

### What did you expect to happen?

I expected for the images to be server under the url that the Saleor image is using, not under `localhost`

### Logs

No logs that are useful, here are screenshots of the problem though
<img width="1470" alt="Screenshot 2023-03-12 at 11 56 12" src="https://user-images.githubusercontent.com/57040831/224537423-bb785cbd-c5e1-4857-a317-c72b085d7d8c.png">
You can see that the Api is returning images under `localhost`, even though my Saleor core is not running under `localhost`
<img width="1468" alt="Screenshot 2023-03-12 at 11 54 01" src="https://user-images.githubusercontent.com/57040831/224537559-2dec1d83-136b-4c29-a9e3-6c845d57b45e.png">
Another image showing that the thumbnails are being shown as `localhost`

### Environment

Saleor version: 3.12.2
OS and version: The server is running `Canonical-Ubuntu-22.04-aarch64-2023.02.15`

**Comment by veve178** [comment]
i have encountered the same issue.
Please Help

**Comment by valiukasd** [comment]
> Hi, I think that changing Saleor's domain from the default `localhost:8000` will solve your problem. Let's say you are hosting Saleor at `example.com`. You can do that with `shopDomainUpdate` mutation:
> 
> ```graphql
> mutation ShopDomainUpdate{
>   shopDomainUpdate(input: {domain: "example.com"}){
>     shop{
>       domain{
>         host
>       }
>     }
>   }
> }
> ```
> 
> or by starting the Django shell (`python manage.py migrate`) and running:
> 
> ```python
> from django.contrib.sites.models import Site
> site = Site.objects.get_current()
> site.domain = "example.com"
> site.save()
> ```
> 
> also, remember to properly set `ENABLE_SSL` environment variable (`True` if you are using `https`) and to restart Saleor instances as `Site` objects are cached in memory.

Thank you, this helped with the issue, I do wonder why this mutation can't be changed in the dashboard?

**Comment by muhammadali286** [comment]
Thanks @przlada your solution is working for me.
