### ISSUE TITLE
Bug: App with `MANAGE_APPS` shouldn't be installable

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#12298]
### What are you trying to achieve?

App with MANAGE_APPS can be installed, but mutations related to apps (install, uninstall) will fail, because its designed not to work.

### Steps to reproduce the problem

Mutation is showing ambiguous errors

![image](https://user-images.githubusercontent.com/9268745/224708351-743ee599-3223-470d-88c1-bfaa4d77b3e2.png)
![image](https://user-images.githubusercontent.com/9268745/224708325-ddbc53a9-5481-402b-8b02-118cf6a20adb.png)

If these operations are prohibited, app installation should throw in the first place

### What did you expect to happen?

1. Make error better for apps that are already installed
2. Reject appInstall for apps with MANAGE_APPS

### Environment

Saleor version: …
OS and version: …

**Comment by kadewu** [comment]
As following of that issue, we need to ensure that app related webhooks (APP_DELETED, APP_INSTALLED, APP_UPDATED, APP_STATUS_CHANGED) are send only to that said app.

**Comment by lkostrowski** [comment]
despite strange error, I didn't manage to install the app with MANAGE_APPS, so I assume it works
