### ISSUE TITLE
Bug: Missing "app id" in app extension token

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#12335]
### What are you trying to achieve?

App (via app-sdk) is checking `app` field in user JWT token (sent from dashboard, via postmessage to appbridge) and compares it to registered app ID (that app persists). If app ID is different, app is rejecting the call.

However, there are also extensions that have their own token (they can have different permissions). **This token lacks `app` field**. 

For app, extension is its part, so its expected to have app ID in the token as well. Otherwise, app would require to persist all registered extensions to work, which is quite hard to implement.

## App token payload

```json
{
  "iat": 1679048767,
  "owner": "saleor",
  "iss": "https://automation-dashboard.staging.saleor.cloud/graphql/",
  "exp": 1679135167,
  "token": "M2irFmzVASR3",
  "email": "testers+dashboard@saleor.io",
  "type": "thirdparty",
  "user_id": "VXNlcjoxMDMz",
  "is_staff": true,
  "app": "QXBwOjY0",
  "permissions": [
    "MANAGE_PRODUCTS"
  ],
  "user_permissions": [
    "MANAGE_GIFT_CARD",
    "MANAGE_MENUS",
    "MANAGE_PAGES",
    "MANAGE_PAGE_TYPES_AND_ATTRIBUTES",
    "MANAGE_PLUGINS",
    "MANAGE_TAXES",
    "MANAGE_USERS",
    "MANAGE_CHECKOUTS",
    "MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES",
    "MANAGE_TRANSLATIONS",
    "MANAGE_APPS",
    "MANAGE_OBSERVABILITY",
    "MANAGE_STAFF",
    "HANDLE_TAXES",
    "MANAGE_CHANNELS",
    "HANDLE_CHECKOUTS",
    "MANAGE_SETTINGS",
    "HANDLE_PAYMENTS",
    "MANAGE_ORDERS",
    "MANAGE_PRODUCTS",
    "MANAGE_SHIPPING",
    "MANAGE_DISCOUNTS",
    "IMPERSONATE_USER"
  ]
}
```

## Extension token payload

```json
  "owner": "saleor",
  "iss": "https://automation-dashboard.staging.saleor.cloud/graphql/",
  "exp": 1679137338,
  "token": "M2irFmzVASR3",
  "email": "testers+dashboard@saleor.io",
  "type": "thirdparty",
  "user_id": "VXNlcjoxMDMz",
  "is_staff": true,
  "app_extension": "QXBwRXh0ZW5zaW9uOjQy",
  "permissions": [],
  "user_permissions": [
    "MANAGE_GIFT_CARD",
    "MANAGE_MENUS",
    "MANAGE_PAGES",
    "MANAGE_PAGE_TYPES_AND_ATTRIBUTES",
    "MANAGE_PLUGINS",
    "MANAGE_TAXES",
    "MANAGE_USERS",
    "MANAGE_CHECKOUTS",
    "MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES",
    "MANAGE_TRANSLATIONS",
    "MANAGE_APPS",
    "MANAGE_OBSERVABILITY",
    "MANAGE_STAFF",
    "HANDLE_TAXES",
    "MANAGE_CHANNELS",
    "HANDLE_CHECKOUTS",
    "MANAGE_SETTINGS",
    "HANDLE_PAYMENTS",
    "MANAGE_ORDERS",
    "MANAGE_PRODUCTS",
    "MANAGE_SHIPPING",
    "MANAGE_DISCOUNTS",
    "IMPERSONATE_USER"
  ]
}
```

### What did you expect to happen?

Extension token should contain `app` field

### Environment

Saleor version: …
OS and version: …

**Comment by korycins** [comment]
@lkostrowski  @przlada Wouldn't be better to have `app_identifier` instead of graphql app id? For graphql app id you need to make an additional call to fetch the graphql ID, right? 
Maybe would be worth adding `app_identifier` to both tokens?

**Comment by przlada** [comment]
@korycins adding `app_identifier` to both tokens is an interesting idea, but in my opinion, it won't help with what we are trying to achieve here. The main problem we want to mitigate is the JWT token repetition attacks. Using `app_identifier` for that requires a mechanism allowing only one app with a specific identifier installed simultaneously, which is not yet implemented. Also, the app would be vulnerable if it won't receive a signal that it was deleted/uninstalled from Saleor (uninstall event still needs to be implemented). Using an app id for this purpose is better, in my opinion, as it will change with every app installation.
Multitenant apps built with `app-sdk`, know their app id and store it in internal storage (APL) with data like app tokens, etc., so verification of JWT token would not require additional API call.
But I am open to further discussion on this subject 😄
