### ISSUE TITLE
Bug: Incorrect tax calculation in Order and Checkout total calculations

### ISSUE THREAD

**Issue by carlosa54** [saleor/saleor#12348]
### What are you trying to achieve?

The current implementation of the `update_order_prices_with_flat_rates` and `update_checkout_prices_with_flat_rates` functions is causing the tax calculation to be inaccurate. The functions calculate the gross and net amounts on a per-line basis and then sum up the gross amounts for all lines, which leads to a precision issue when rounding multiple items.

The cause of this issue is the rounding of the gross amounts, which is done on a per-line basis before summing them up. This leads to a loss of precision when rounding multiple items.

I was thinking that this could be fixed by calculating the tax on the entire order/checkout subtotal but there could be lines with different taxes. Given this I think that the logic should apply the rounding at the order/checkout total calculation and leave the line items without the rounding. This brings another issue with how the product gross amount is displayed in the dashboard already rounded up, not sure if this should be changed to only display the net amount

### Steps to reproduce the problem

I created an order showing the issue in a saleor environment: [GrapqhQL Playground here](https://test-org.saleor.cloud/graphql/#saleor/N4IgjiBc4K4KYCcCeACA8ggJogInALgIYCWANgM4AUAJMZpCgJI4CEAlCsADoB2KKAeyyJKdBrUwduffinJF8Mcr1koADoSQBbOD3wBlBUpWzyAC2Jq1xHgHMAKoQAeAJUL44J-vgFFSnL1kAYxgEBF0gpED+HgIAmVV+ELCIqITEwi0BGD1olABfPKIneMTg0PCeSLz+TOzc9P5CxpRbBAFyclKylGTK6pbarJz8PObVcYLefJAAGhABKBAMbAQ8IjJyOZAANyXpfi4QOiOGI-sAZgApAGsALQANRgA2AFkALxuAFlf7ADUtAA5ABWAE18GgcK8AEyA4gABnhoK0AFEvgAZADqKIA7ncAOIAVXwd2BtneoOhf1IgKJPy0AKO0xA+SAA)

```json
{
  "data": {
    "order": {
      "status": "FULFILLED",
      "paymentStatus": "FULLY_CHARGED",
      "shippingTaxRate": 0.07,
      "total": {
        "currency": "USD",
        "net": {
          "currency": "USD",
          "amount": 10
        },
        "tax": {
          "currency": "USD",
          "amount": 0.72 // This should be 0.70
        },
        "gross": {
          "currency": "USD",
          "amount": 10.72 // This should be 10.70
        }
      }
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 1,
      "maximumAvailable": 50000
    }
  }
}
```
**Order in Dashboard**
<img width="517" alt="image" src="https://user-images.githubusercontent.com/4250593/226153671-fbc320ed-d7f8-4f88-b0b1-15fff312fafb.png">

### What did you expect to happen?

This issue can be observed in the following example:

Given an order with four products priced at $2.5 each and a tax rate of 7%

|  | Expected Behavior | Current Behavior |
| ------------- | ------------- |  ------------- |
| Subtotal  | $10 | $10 
| Tax  |  $0.70  | $0.72
| Total  | $10.70  | $10.72

### Environment

Saleor version: …
OS and version: …

**Comment by carlosa54** [comment]
I added https://github.com/saleor/saleor/pull/12349 with a fix, let me know if that's the correct approach and feel free to use it as a base or add your own changes

**Comment by korycins** [comment]
Hey @carlosa54 
Thank you ❤️  for reporting and fully explaining the 
issue. 
According to the PR with the fix. I am not convinced that removing the quantize_price is a solution here. quantize_price gives you a price with a correct decimal number for a specific currency. It is useful especially when the sale or discount is applied first.

**Comment by maarcingebala** [comment]
Thanks for reporting this and for the PR @carlosa54, we will be looking into the issue and will recreate it on our side and confirm the solution.

**Comment by patrys** [comment]
After looking into this, it is behaving as expected. Let me explain:

There are three different, compliant ways to calculate taxes, each having different limitations and rounding errors:

1. Calculate taxes for each unit price, round the resulting net/gross unit price, and calculate line totals and order totals based on that.
2. Calculate taxes for each order line, round the resulting net/gross line total, and calculate order totals based on that. Unit net/gross prices must be derived from the line total and may not add up to the line total because of rounding errors. _This is how most tax calculation vendors (Avalara AvaTax, TaxJar, Stripe) operate. This is also the method Saleor implements._
3. Calculate taxes on order level, add up all lines subject to the same tax, and calculate the tax based on the sum, then round it. Line totals and unit prices must be derived and will not sum up to the total because of rounding errors. _This is the method you propose above._

All three produce slightly different results, but all three are valid. We implemented the method most commonly used in the industry as it makes interoperability easier.

**Comment by carlosa54** [comment]
@patrys thanks for looking into this

As for 
> This is how most tax calculation vendors (Avalara AvaTax, TaxJar, Stripe) operate.

I tested on Stripe and they don't use the approach you mentioned (See PDF example from below with the correct taxes)
<img width="614" alt="image" src="https://user-images.githubusercontent.com/4250593/226637286-5e16e550-935f-4688-8e3c-44b0b35769e4.png">

If they used the approach from `2.` the result would be the incorrect total of `10.88` given four items of $2.50 with a 8.625% tax.

I can double check later on the other platforms mentioned but  I don't think that the current Saleor implementation is correct.

**Comment by szczecha** [comment]
I tested Saleor from your branch today. There is a discrepancy in the total and subtotal after completing checkout.

e.g:
variant: net price 
DVD: 13,33
iTunes:  19,99
MP3: 4,5

```
        "checkoutComplete": {
            "errors": [],
            "order": {
                "subtotal": {
                    "gross": {
                        "amount": 54.74,
                        "currency": "USD"
                    },
                    "net": {
                        "amount": 51.15,
                        "currency": "USD"
                    }
                },
                "total": {
                    "gross": {
                        "amount": 54.73,
                        "currency": "USD"
                    },
                    "net": {
                        "amount": 51.15,
                        "currency": "USD"
                    }
                },
```
![image](https://user-images.githubusercontent.com/30683248/226712769-d7f283ba-12cb-4e9b-a713-a8e28fba6920.png)

**Comment by carlosa54** [comment]
@patrys I made some tests on each platform and here's what I found:

### Avalara AvaTax
I don't have access to the Avalara platform but from their docs I saw that they support both line-level rounding and order level rounding

[Change how AvaTax rounds the tax amount](https://knowledge.avalara.com/bundle/dqa1657870670369_dqa1657870670369/page/Change_how_AvaTax_rounds_the_tax_amount.html)

### Stripe
Given an invoice with 4 line items of $2.50 with a California Tax of 8.625% the total tax amount is $0.86 
[Invoice-8CAA9719-DRAFT.pdf](https://github.com/saleor/saleor/files/11035223/Invoice-8CAA9719-DRAFT.pdf)

<img width="781" alt="image" src="https://user-images.githubusercontent.com/4250593/226773789-f5df7546-27ba-41f3-a6c5-8ee55dafd6ec.png">

### TaxJar

Using the [TaxJar's Calculate sales tax for an order](https://developers.taxjar.com/api/reference/#post-calculate-sales-tax-for-an-order) POST endpoint I sent the following payload including 4 line items of $2.50 with a California Tax of 8.625% and the total tax amount is $0.86

```curl
curl https://api.sandbox.taxjar.com/v2/taxes \
  -H "Authorization: Bearer [bearer_token]" \
  -H "Content-Type: application/json" \
  -d '{
    "from_country": "US",
    "from_zip": "94132",
    "from_state": "CA",
    "to_country": "US",
    "to_zip": "94132",
    "to_state": "CA",
    "shipping": 0,
    "line_items": [
      {
        "id": "1",
        "quantity": 1,
        "product_tax_code": "20010",
        "unit_price": 2.5,
        "discount": 0
      },
      {
        "id": "2",
        "quantity": 1,
        "product_tax_code": "20010",
        "unit_price": 2.5,
        "discount": 0
      },
      {
        "id": "3",
        "quantity": 1,
        "product_tax_code": "20010",
        "unit_price": 2.5,
        "discount": 0
      },
      {
        "id": "4",
        "quantity": 1,
        "product_tax_code": "20010",
        "unit_price": 2.5,
        "discount": 0
      }
    ]
  }'
```

Response:
```json
{
    "tax": {
        "order_total_amount": 10.0,
        "shipping": 0.0,
        "taxable_amount": 10.0,
        "amount_to_collect": 0.86, // The tax amount to collect have the same behavior as the fix
        "rate": 0.08625,
        "has_nexus": true,
        "freight_taxable": false,
        "tax_source": "destination",
        "jurisdictions": {
            "country": "US",
            "state": "CA",
            "county": "SAN FRANCISCO",
            "city": "SAN FRANCISCO"
        },
        "breakdown": {
            "taxable_amount": 10.0,
            "tax_collectable": 0.86,
            "combined_tax_rate": 0.08625,
            "state_taxable_amount": 10.0,
            "state_tax_rate": 0.0625,
            "state_tax_collectable": 0.63,
            "county_taxable_amount": 10.0,
            "county_tax_rate": 0.01,
            "county_tax_collectable": 0.1,
            "city_taxable_amount": 0.0,
            "city_tax_rate": 0.0,
            "city_tax_collectable": 0.0,
            "special_district_taxable_amount": 10.0,
            "special_tax_rate": 0.01375,
            "special_district_tax_collectable": 0.14,
            "line_items": [
                {
                    "id": "1",
                    "taxable_amount": 2.5,
                    "tax_collectable": 0.22,
                    "combined_tax_rate": 0.08625,
                    "state_taxable_amount": 2.5,
                    "state_sales_tax_rate": 0.0625,
                    "state_amount": 0.16,
                    "county_taxable_amount": 2.5,
                    "county_tax_rate": 0.01,
                    "county_amount": 0.03,
                    "city_taxable_amount": 0.0,
                    "city_tax_rate": 0.0,
                    "city_amount": 0.0,
                    "special_district_taxable_amount": 2.5,
                    "special_tax_rate": 0.01375,
                    "special_district_amount": 0.03
                },
                {
                    "id": "2",
                    "taxable_amount": 2.5,
                    "tax_collectable": 0.22,
                    "combined_tax_rate": 0.08625,
                    "state_taxable_amount": 2.5,
                    "state_sales_tax_rate": 0.0625,
                    "state_amount": 0.16,
                    "county_taxable_amount": 2.5,
                    "county_tax_rate": 0.01,
                    "county_amount": 0.03,
                    "city_taxable_amount": 0.0,
                    "city_tax_rate": 0.0,
                    "city_amount": 0.0,
                    "special_district_taxable_amount": 2.5,
                    "special_tax_rate": 0.01375,
                    "special_district_amount": 0.03
                },
                {
                    "id": "3",
                    "taxable_amount": 2.5,
                    "tax_collectable": 0.22,
                    "combined_tax_rate": 0.08625,
                    "state_taxable_amount": 2.5,
                    "state_sales_tax_rate": 0.0625,
                    "state_amount": 0.16,
                    "county_taxable_amount": 2.5,
                    "county_tax_rate": 0.01,
                    "county_amount": 0.03,
                    "city_taxable_amount": 0.0,
                    "city_tax_rate": 0.0,
                    "city_amount": 0.0,
                    "special_district_taxable_amount": 2.5,
                    "special_tax_rate": 0.01375,
                    "special_district_amount": 0.03
                },
                {
                    "id": "4",
                    "taxable_amount": 2.5,
                    "tax_collectable": 0.22,
                    "combined_tax_rate": 0.08625,
                    "state_taxable_amount": 2.5,
                    "state_sales_tax_rate": 0.0625,
                    "state_amount": 0.16,
                    "county_taxable_amount": 2.5,
                    "county_tax_rate": 0.01,
                    "county_amount": 0.03,
                    "city_taxable_amount": 0.0,
                    "city_tax_rate": 0.0,
                    "city_amount": 0.0,
                    "special_district_taxable_amount": 2.5,
                    "special_tax_rate": 0.01375,
                    "special_district_amount": 0.03
                }
            ]
        }
    }
}
```

**Comment by carlosa54** [comment]
> I tested Saleor from your branch today. There is a discrepancy in the total and subtotal after completing checkout.
> 
> e.g: variant: net price DVD: 13,33 iTunes: 19,99 MP3: 4,5
> 
> ```
>         "checkoutComplete": {
>             "errors": [],
>             "order": {
>                 "subtotal": {
>                     "gross": {
>                         "amount": 54.74,
>                         "currency": "USD"
>                     },
>                     "net": {
>                         "amount": 51.15,
>                         "currency": "USD"
>                     }
>                 },
>                 "total": {
>                     "gross": {
>                         "amount": 54.73,
>                         "currency": "USD"
>                     },
>                     "net": {
>                         "amount": 51.15,
>                         "currency": "USD"
>                     }
>                 },
> ```
> 

@szczecha thanks for testing, I was able to replicate your behavior and fixed it in https://github.com/saleor/saleor/pull/12349/commits/95cbc0aecaa398c85cb809bd383fb2b641d9581c Should be working now.

**Comment by korycins** [comment]
Hey @carlosa54 
I have delved deeply into this problem and here is what I have found:

Using the same checkout values you provided, but with a tax rate of 23% and 4 lines each with a price of 2.5, Avatax with disabled rounding returns taxes of 0.58, 0.57, 0.57, and 0.58. This results in a total net of 10 and gross of 12.3, with a tax of 2.3.

When Avatax rounding is enabled, taxes of 0.58, 0.58, 0.58, and 0.58 are returned, resulting in a total net of 10 and gross of 12.32, with a tax of 2.32.

Regarding Taxjar, the `amount_to_collect` field returns `2.3`. However, if you iterate over the lines in `payload.breakdown.line_items`, you will see that each line has a `tax_collectable` value of 0.58. The sum of these lines gives `2.32`.

I also performed the same example with VAT tax and net prices using a Stripe Invoice. In my case, I received a tax of `2.32`.
![image](https://user-images.githubusercontent.com/23282005/235154314-27489904-d8ef-410b-9331-7d64bac41fdf.png)

cc @patrys

**Comment by carlosa54** [comment]
Awesome @korycins thanks for taking a deeper look. I wonder why I got different results with the same platforms (Stripe and TaxJar) maybe there's a difference between how they handle VAT vs US sales tax

**Comment by aniav** [comment]
I'll close this as it seems all works as expected. Feel free to reopen when it makes sense 🙌

**Comment by patrys** [comment]
@aniav Did we address the discrepancy discovered by @szczecha above?

**Comment by aniav** [comment]
As far as I understand from the conversation the discrepancy was on the PR that was fixing the issue. And in the end we found in the discussion here that the calculations are actually valid and we don't need to fix them. Or did I miss something?
