### ISSUE TITLE
Bug: KeyError 'countries'

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#12429]
### What are you trying to achieve?

Call `shippingZoneUpdate` mutation with `default: true` input.

### Steps to reproduce the problem

1. Call a mutation for some existing shipping zone and pass `default: true` in the input:
```
mutation {
  shippingZoneUpdate(id: "U2hpcHBpbmdab25lOjY3", input:{ default: true }) {
    errors {
      code
      field
      message
    }
    shippingZone {
      id
    }
  }
}
```

### What did you expect to happen?

Error should be handled.

### Logs

https://saleor.sentry.io/share/issue/24f38163cb244629a06367a230416631/

### Environment

Saleor version: 3.11.17

**Comment by slawekmarszalek** [comment]
Reported in: https://saleorcommerce.slack.com/archives/C038XPD8HLK/p1679413591787469

**Comment by Srinivasant97** [comment]
Shall I work on this bug? @maarcingebala  . If yes , Please assign this to me
