### ISSUE TITLE
Bug: Specific products voucher makes shipping method unavailable in checkout

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#12500]
### What are you trying to achieve?

Using a "specific products" voucher can make shipping methods with specific min/max order value requirements unavailable. 

### Steps to reproduce the problem

The data set that the case was tested with:
- a product that costs 55
- voucher for “specific products” with -50% discount for the above product
- shipping zone with two shipping methods:
  - “Shipping A” with a minimum order value is 0 and max order value is 49.99, the price of this method is 3.95.
  - “Shipping B - free shipping”, minimum order value is 50, no max order value, price is 0.

1st scenario:
- Create checkout with four pieces of the mentioned product; the order total should be 220.
- Add -50% voucher. The order total should now be 110.
- `shippingMethods` field for this checkout doesn’t include the “free shipping” method, although the total is above the min order requirement for that method.

2nd scenario:
- Create checkout with four pieces of the mentioned product; the order total should be 220.
- Add the “free shipping” method to that checkout (it is available at this step as no voucher is added)
- Add -50% voucher; the method remains selected for this checkout, although it is not present in the available shipping methods.

What looks suspicious is [this line](https://github.com/saleor/saleor/blob/main/saleor/checkout/fetch.py#L551), where we subtract the discount from the subtotal, while the discount should be already included in the subtotal since this is “specific products” voucher.

### What did you expect to happen?

In both scenarios, the "free shipping" method should be available in `Checkout.shippingMethods` field.

### Environment

Saleor version: 3.13.0-a

**Comment by slawekmarszalek** [comment]
Reported in: https://saleorcommerce.slack.com/archives/C017L12TRJS/p1680619627927279
