### ISSUE TITLE
[RFC] Minimal discounted product price refactoring

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#12502]
## Problem

We want to reduce the time required to get the discounted variant price. The solution is to keep the calculated discounted variant price in `VariantChannelListing` as it's done for the `Product`.

## 1. General Assumptions
- Extend the `VariantChannelListing` with the field that will keep normalized variant price with applied all sales that are applicable. Fulfill this field with correct values
- The variant and product prices will be updated regularly every time the related sale starts or ends. Create a scheduled task that will trigger the celery task for related variants for price recalculation.
- The price recalculation task will be also triggered any time the sale will be updated/deleted.
- User the normalized `Product` and `Variant` price fields for price calculation
- Ensure the zero-downtime. The migration for setting the correct field values and the logic responsible for triggering the price update should be introduced in the previous version

### Acceptance Criteria

- [ ] When the sale expires the corresponding variants and products have the correct pricing
- [ ] When the sale starts the corresponding variants and products have the correct pricing
- [ ] Then the sale has been updated/deleted the corresponding variants and products prices are updated
- [ ] Support for old versions: when moving from the previous version the prices should be up to date

⚠️ 
The time required for price calculation will depend on the celery queue

## 2. API changes

Changes in `ProductVariant.pricing` and `Product.pricing` resolvers

## 3. Database changes
- Add `discounted_price_amount` to `ProductVariantChannelListing`. Fulfill the field with correct values

## 4. To Do list

- [x] Add `discounted_price_amount` to `ProductVariantChannelListing`.
- [ ] Add migration for fulfilling `ProductVariantChannelListing.discounted_price_amount` will correct values
- [x] Add a task that will update the `discounted_price_amount` value
- [x] Trigger a task for updating the price each time related sales have been updated or deleted
- [x] Trigger a task for updating the price each time variant is deleted or the price has changed
- [x] Trigger a task for updating the product price each time product is deleted or the price has changed
- [x] Create a scheduled task that will trigger the celery task for price recalculation every time the related sale starts or ends for related variants. Consider joining this scheduler with `send-sale-toggle-notifications`
- [x] Update resolver for `ProductVariant.pricing` and `Product.pricing` to use normalized fields `discounted_price_amount`
- [ ] Check other places where the calculation can be simplified
- [ ] Add zero downtime support - the previous version should consist of migration with adding a new price field in `ProductVariantChannelListing`, the migration for setting the correct field values. and the logic responsible for triggering the price update
- [ ] Update docs - add the upgrade guide

## 5. To Test

- [ ] Check checkout with sales and discounts, separately and together

**Comment by starksid** [comment]
hello i want to contribute in this issue can you please assign me

**Comment by IKarbowiak** [comment]
@starksid  Thank you for your willingness to contribute! 🎊  However, this issue has already been assigned. We would be happy to assign you to another issue. Please take a look at issues marked with the good first issue label.

**Comment by starksid** [comment]
@IKarbowiak thanks for your response.
May I know how i can start contributing I am proficient in data structures and algorithms, python.
