### ISSUE TITLE
Bug: Order status remains as UNCONFIRMED after calling transactionEventReport

### ISSUE THREAD

**Issue by szczecha** [saleor/saleor#12531]
### What are you trying to achieve?

If auto-confirm is active Saleor should update the order status when a transaction is attached to the order

### Steps to reproduce the problem

Channel settings: 
```
            {
                "id": "Q2hhbm5lbDoyMjQz",
                "name": "Channel-USD",
                "slug": "default-channel",
                "isActive": true,
                "currencyCode": "USD",
                "hasOrders": true,
                "orderSettings": {
                    "automaticallyConfirmAllNewOrders": true,
                    "automaticallyFulfillNonShippableGiftCard": true,
                    "defaultTransactionFlowStrategy": "CHARGE",
                    "expireOrdersAfter": null,
                    "markAsPaidStrategy": "PAYMENT_FLOW"
                },
```

1. run `checkoutCreate`
2. run `orderCreateFromCheckout` as an app with handle checkouts
3. run `transactionCreate` without providing any amount as an app with handle payments 
variables:
```
{
  "id": "{{orderId}}",
  "transactionCreateInput": { 
    "pspReference": "PSP-ref123"
  }
}
```
4. run `transactionEventReport`  "type": "CHARGE_SUCCESS", as an app with handle payments

Actual result:
Orders status is still  "UNCONFIRMED",
```
            "id": "T3JkZXI6NTA0MjZiNzMtMzBlOC00YWRlLWI0MWQtYjQ4MTZhOTUzMTFm",
            "status": "UNCONFIRMED",
            "paymentStatus": "FULLY_CHARGED",
            "transactions": [
                {
                    "id": "VHJhbnNhY3Rpb25JdGVtOmQ0NzY0MTlhLTRmOTItNGY5MC1hYmI3LTQ2NDA5NGFmNjM4Yg==",
                    "chargedAmount": {
                        "amount": 361.0,
                        "currency": "USD"
                    },
```

### What did you expect to happen?

Order status should changed to Unfulfilled be changed

### Environment

Saleor version: core v3.13.0-a
OS and version: …

**Comment by starksid** [comment]
Hello,
i have learned data structures and algorithms and design patterns , Low Level Design in python
how i can start contribute in this issue
i am new to open source contribution 
i am not able to understand the codebase can you please me some guidance

**Comment by aniav** [comment]
This has been resolved in https://github.com/saleor/saleor/pull/16254 and ported to versions down to 3.14.
