### ISSUE TITLE
Bug: Missing validation in SHIPPING_LIST_METHODS_FOR_CHECKOUT webhook

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#12556]
### What are you trying to achieve?

I want to ensure that we always require a correct format for the response received from the app subscribed to `SHIPPING_LIST_METHODS_FOR_CHECKOUT`.

### Steps to reproduce the problem

1. Create the app subscribed to `SHIPPING_LIST_METHODS_FOR_CHECKOUT`.
2. The app should return an incorrect response, such as a missing `amount` field in the response.
```json
[  {
    "currency": "USD", 
    "id": "method-1", 
    "name": "Standard Shipping"
  }
]
```
3. call mutation checkoutCreate and request `shippingMethods` field in the response.
4. Saleor will return an unhandled exception: `conversion from NoneType to Decimal is not supported`

### What did you expect to happen?

I expect us to validate the app's response and provide sufficient feedback to help developers understand what went wrong.

### Logs

https://saleor.sentry.io/issues/4086906443/events/6c4452a9c3c741eab2cb507cbc8264c9/?project=6417854&query=is%3Aunresolved&referrer=next-event&stream_index=1

### Environment

Saleor version: 3.12
OS and version: …

**Comment by slawekmarszalek** [comment]
Reported in: https://saleorcommerce.slack.com/archives/C03HJ7Y1MCK/p1681465420972029?thread_ts=1681461221.947759&cid=C03HJ7Y1MCK

**Comment by maarcingebala** [comment]
- Figure out how Saleor should handle failing requests in sync webhooks
  - E.g., introduce the Circuit Breaker pattern
  - Document how Saleor behaves in this situation
- Add webhook event to listen to webhook failures

**Comment by lkostrowski** [comment]
Rel validation: https://github.com/saleor/saleor/issues/11905

https://github.com/saleor/saleor/pull/11477

**Comment by lkostrowski** [comment]
Re-assigning to @maarcingebala so @saleor/core can put it to the backlog

**Comment by korycins** [comment]
Solved by https://github.com/saleor/saleor/pull/14858/files# but
