### ISSUE TITLE
Possibility of caching invalid order/checkout totals due to errors in Avalara requests

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#12685]
There seems to be a problem with determining if values provided by the plugin are valid in case when a request to Avalara returns an error. Below are more details about the different problems we suspect:

- checkout price expiration - denormalized prices are stored in the checkout model. The issue occurs when the plugin cannot calculate taxes due to a failed request, missing data, etc. The plugin returns the previous value, which means that we return taxes=0. From Saleor’s perspective, we don’t know if returned 0 means that we could not calculate taxes or if total taxes are equal to 0.

- `preprocess_order_creation` - before version 3.9, `preprocess_order_creation` was used to validate the checkout and disallow the order creation when the order data was invalid or insufficient details to calculate the taxes. The plugin raised the exception when some mandatory details were required, or we could not fetch the taxes. The solution is not ideal as it doesn’t guarantee that the request calculating the taxes returned a correct response. In that case, there is a possibility that we didn’t calculate the taxes, but `preprocess_order_creation` passed successfully (the first request that calculates taxes failed, but `preprocess_order_creation` succeeded).

Taking the two above, we can have a situation where denormalized prices have taxes=0 because Avatax didn’t respond correctly. Saleor will treat these amounts as correct ones. When `preprocess_order_creation` finishes successfully and denormalized prices are still valid, we can end up with a situation where taxes are 0.

Related problem - Celery task that creates orders in the Avalara dashboard can be triggered when the Avalara plugin is active, but charging taxes is disabled in a channel. The task should take into account that taxes can be calculated via flat rates for the channel. In that case, we shouldn’t send the order to Avatax, even if Avatax is active.

**Comment by aniav** [comment]
Given we are going to be deprecating the plugin in favour of an app (which is already used by live clients, I am going to go ahead and close this issue.
