### ISSUE TITLE
Bug: Missing propagation of prices based on the Tax App response

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#12691]
### What are you trying to achieve?

I would expect that based on the response from tax app, all price details will be recalculated based on the response from TaxApp.

### Steps to reproduce the problem

- Install the tax app.
- Create a checkout and add some lines.
- The request to the tax app should be called at this moment.
- `checkoutLine.totalPrice` will include taxes, while the line's `unitPrice` and all checkout's `undiscountedX` will not include taxes.

---

- Installing the tax app is the first step.
- Next, create a checkout and add some lines to it.
- Then, add a voucher for the entire order to the checkout.
- At this point, the request to the tax app should be made.
- `checkoutLine.totalPrice` will include the taxes and the propagated entire order voucher (which is done by the TaxApp). The line’s `unitPrice` and all checkout’s `undiscountedX` will not include taxes. Propagated entire voucher discount will not be included in `unitPrice`.

### What did you expect to happen?

I expect the unit price to be calculated based on the line total received from the TaxApp. The `unitPrice` should include the entire voucher discount that is already included in the total amount received from the TaxApp.
Furthermore, I expect us to use the received `tax_rate` to calculate the correct `.net` and `.gross` amounts for the `undiscountedX` fields.

### Logs

More details of the problem can be found here: https://github.com/saleor/saleor/discussions/12607

### Environment

Saleor version: 3.9+
OS and version: …

**Comment by aniav** [comment]
@saleor/shopex-py is this fixed maybe already?
