### ISSUE TITLE
Bug: Inconsistencies between `CheckoutLineInput` and `CheckoutLineUpdateInput`

### ISSUE THREAD

**Issue by mmiszy** [saleor/saleor#12767]
### What are you trying to achieve?

`variantId` in `CheckoutLineUpdateInput` is deprecated and `lineId` should be used instead.
However, in `CheckoutLineInput` `lineId` doesn't exist and `variantId` is not deprecated:

https://docs.saleor.io/docs/3.x/api-storefront/checkout/inputs/checkout-line-input

https://docs.saleor.io/docs/3.x/api-storefront/checkout/inputs/checkout-line-update-input

### Steps to reproduce the problem

.

### What did you expect to happen?

.

### Environment

Saleor version: 3.13

**Comment by szczecha** [comment]
CheckoutLineInput is used checkoutCreate or CheckoutLinesAdd. When calling those 2 mutations you don't know the lineID you need to send the variantID and quantity to create a line. When the line is already created you should use lineID in checkoutLinesUpdate mutation to manage items. All fine here
