### ISSUE TITLE
Bug: subscription query cannot be cleared in webhookUpdate mutation

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#12822]
### What are you trying to achieve?

I'm trying to clear the subscription query for a webhook. Sending `null` or `""` in as the value doesn't do anything.

### Steps to reproduce the problem

1. Create a webhook with any event and a subscription query.
2. Send the `webhookUpdate` mutation for that webhook; provide `null` or `""` in `query` input field.
3. Subscription query is still being returned in the response.

### What did you expect to happen?

Query should be cleared in the webhook. The following values should clear the query: `null`, `""`. When the field is omitted in the input, it should not change the state of that field in DB.

### Environment

Saleor version: 3.12 and above

**Comment by lkostrowski** [comment]
Please verify with @patrys , AFAIK we want to have query required

**Comment by maarcingebala** [comment]
Closing as not planned.
