### ISSUE TITLE
Drop workaround for incorrect tax calculation received from Avatax for JPY checkout/orders

### ISSUE THREAD

**Issue by fowczarek** [saleor/saleor#12840]
# Problem
In #8004 was introduced a workaround for incorrect tax calculation received from Avatax for JPY checkout/orders. 
In #12832 I discover that The Avalara starts returning proper price precision for checkouts/orders in JPY. 
> **Warning**
> I found that only filed `totalAmount` could return the price without valid precision for JPY.  It required confirmation that Saleor flow uses this field.

# Scope of this task
- [ ] Confirm that all fields used by the Saleor return prices with proper price precision for JPY checkout/orders. 
- [ ] Confirm that Avalra on production also contains this fix for price precision.
- [ ] Drop all code related to a workaround for JPY checkout/orders.

**Comment by aniav** [comment]
Given we are going to be deprecating the plugin in favour of an app (which is already used by live clients, I am going to go ahead and close this issue.
