### ISSUE TITLE
Associate guest checkout created by orderCreateFromCheckout with an account if it exists 

### ISSUE THREAD

**Issue by szczecha** [saleor/saleor#12859]
## Problem
I have an active customer account at Saleor. When I place an order as a guest but use my account's email, the order is not associated with the account. If the email is confirmed (email confirmation is enabled), my order should be automatically associated with my account.

Fix for this issue https://github.com/saleor/saleor/issues/12443 should be applied also to the `orderCreateFromCheckout` mutation

`orderCreateFromCheckout` requires authToken from the app with HANDLE_CHECKOUTS permission. It can be created with mutation:
```
mutation {
  appCreate(
    input: { name: "App for payment and checkout", permissions: [HANDLE_CHECKOUTS, HANDLE_PAYMENTS] }
  ) {
    authToken
    app {
      id
      name
    }
    appErrors {
      field
      code
    }
  }
}
```

---

### Acceptance Criteria

- [ ]
- [ ]

### Mutations

```

```

### Types

```

```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by FremahA** [comment]
@szczecha This issue has been fixed. Check out the the usage of `assign_checkout_user` .
