### ISSUE TITLE
Warehouse assignment improvement

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#12888]
# Problem
Right now there is no way to decide for which warehouse the allocation is made.

## Requirements
We need a way to allow deciding which warehouse should be used for allocation in the checkout process.

## Proposed solution
- Allow explicitly picking a warehouse that should be used to allocate stock for a specific checkout line.
- Setting explicit warehouse will be allowed to apps with `HANDLE_CHECKOUTS` permission.

### API changes
- Add a new `warehouse: String / ID`  parameter to the `CheckoutLinesAdd` and `CheckoutLinesUpdate` - to discuss if the `warehouse` should require `ID`, `slug` or either of them. Restricted to apps with `HANDLE_CHECKOUTS` permission.
- Extend the `warehouse` query with the `slug` parameter that will allow query warehouse either by `slug` or `ID`.
- Adding lines with the same variant but different warehouses results in separate checkout lines.
- When the line for variant A and warehouse B is updated with warehouse A, and there is already a line for variant A and warehouse A - we will end up with two the same lines ~the lines will be merged - we will get one line instead of two with summed quantities~

```graphql
type Query {
  warehouse(
    id: ID
    slug: String
  ): Warehouse
}

input CheckoutLineInput {
  warehouse: ID/String
}

input CheckoutLineUpdateInput {
  warehouse: ID/String
}
```

**Comment by maarcingebala** [comment]
Moved from https://github.com/saleor/saleor/pull/10195

**Comment by pkucmus** [comment]
This is highly anticipated. Thanks for picking this up!
If I may, I'd like to add and ask a few things:

1. Querying and assigning warehouses by slug is less useful than doing so by `externalReference`
2. Will the API error out immediately when an item is out of stock in the chosen warehouse?
3. Docs should explicitly state what does this mean to the channel-level allocation strategy (I assume is overwritten completely?)
4. Should one be able to remove the warehouse assignment? Like `warehouse: ID/String/null`?
5. Will the metadata of the split checkout line be split/copied over?

A complementary feature could be to force allocation on the createOrderFromCheckout mutation which would try to allocate in the specified warehouse (or raise `InsufficientStock` if even one item is not available) this might feel redundant but probably more often than not - in the context of overselling - it's less important to do that check when adding to cart than it is right before touching the customers money - a final check that would prevent oversell.

**Comment by krzysztofwolski** [comment]
Love to see this one!

Heads up - selecting multiple warehouses might impact shipping costs for the store owner.
One of the use cases I was working on lately:
- user buys 2 products. One is available immediately, and the second one is in another warehouse far away, which would impact delivery time
- during the checkout user can choose:
  - have a cheaper shipment, by choosing single fulfillment
  - have a two separate shipments from both warehouses (one will be faster due to location)

It would be good to consider how to handle such a situation.

**Comment by maarcingebala** [comment]
Closing as not planned for the near future.
