### ISSUE TITLE
Bubble up sync webhook errors to the response

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#12896]
## Problem

When the app fails with a sync webhook error (e.g. Tax provider is down, the app is not configured...), there must be some way of "breaking the circuit".

The app must be able to return an error (best if it can be parsed), and Saleor must read this error and attach it to the response.

This way storefront can break the payment flow, instead selling with wrong prices.

rel https://github.com/saleor/saleor/issues/12556

---

### Acceptance Criteria

- [ ]
- [ ]

### Mutations

```graphql

```

### Types

```graphql

```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by przlada** [comment]
Following a brief analysis, it appears we may need to adjust our business logic. 
From my perspective, our current tax calculation system doesn't properly handle synchronous webhook errors. If a webhook plugin fails to return any `TaxData` (after gathering app responses), no taxes are applied to the checkout or order, which is understandable. However, this approach doesn't consider scenarios where the tax app is either non-responsive or has returned an invalid response.
To address this, I propose that our webhook plugin should throw an error under such circumstances, similarly as it is done with payment webhooks (`PaymentError`, `GatewayError`). These errors should then be handled within the tax calculation logic, likely by propagating them up as GraphQL API errors.

**Comment by przlada** [comment]
Furthermore, this may be an opportune moment to reconsider our approach toward synchronous webhook handling. A potential strategy could involve dependency injection to pass response validation logic directly to methods in charge of creating and managing `EventDeliveryAttempt`s. With this approach, we could achieve the following:
- Mark `EventDeliveryAttempt`s as failed if the content of the response is invalid.
- Allow the synchronous webhook response validator to work with raw responses, providing scope for custom JSON parsing. This could, for example, enable parsing of a `JSON float` as a Python `Decimal`, thereby resolving https://github.com/saleor/saleor/issues/12280

Looking forward to your thoughts on this.

**Comment by peelar** [comment]
> From my perspective, our current tax calculation system doesn't properly handle synchronous webhook errors.

I will throw in my two cents:

There are states in the US [that have no sales tax](https://www.taxjar.com/resources/sales-tax/states) (e.g. Delaware). **When we are calculating taxes for those states, the user experience is identical to when we have an error**:

1. We trigger the `calculate_taxes` webhook, and we wait for the result
2. We see prices stay the same, and the "taxes" field is populated with "0"

So one time this result can be completely fine, and another it may mean that something went wrong while calculating.

**Comment by maarcingebala** [comment]
Please have a look at this RFC, it aims at resolving the issue discussed here: https://github.com/saleor/saleor/issues/12942

**Comment by lkostrowski** [comment]
> Please have a look at this RFC, it aims at resolving the issue discussed here: #12942

Good, I'm closing it as a duplicate, it can still be referenced
