### ISSUE TITLE
Allow to query channel-related objects with channel ID too

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#12945]
## Problem

Queries like `products()` requires channel slug. However, slug is mutable. So, if other service, like App, stores channel slug and it changes, reference will break.

App wants to store channel ID to be sure that its unique and correct event if name or slug changes.

`slug` field can stay as another way to reference channel

---

### Acceptance Criteria

- [ ]
- [ ]

### Mutations

```graphql

```

### Types

```graphql
products(
  filter: ProductFilterInput
  sortBy: ProductOrder
  channel: String # Deprecate
  channelID: ID # Add this
  channelSlug: string # Add this - the same as channel but explicit name
  before: String
  after: String
  first: Int
  last: Int
): ProductCountableConnection
```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by krzysztofwolski** [comment]
```graphql
products(
  filter: ProductFilterInput
  sortBy: ProductOrder
  channel: String @deprecated("Use channelSlug instead")
  channelID: ID # Add this
  channelSlug: String # Add this
  before: String
  after: String
  first: Int
  last: Int
): ProductCountableConnection
```
Probably both changes could be implemented same time with the proper deprecation timeline. It would completely eliminate any confusion.

**Comment by lkostrowski** [comment]
> Probably both changes could be implemented same time with the proper deprecation timeline. It would completely eliminate any confusion.

Thanks, edited

**Comment by maarcingebala** [comment]
What about keeping the `channel: String` field and making it more clever and accepting both `slug` and `id`? A bit less explicit behavior but would keep the API more tidy IMO. It would be documented in the description of course.

**Comment by lkostrowski** [comment]
@maarcingebala I think its a good one to make it compatible on v3 ✅ 

In V4 we can revisit this topic. Maybe we should have a bigger discussion od DX if we prefer more or less explicit fields

The only downside I see of having this field to understand both ID and slug is that app will not know that

For example - we have app that works for Saleor 3.14 and 3.15, where 3.15 has it implemented

App will try this behavior on 3.14 and it will not work, but there will be no explicit error (just "404" like)

If this is new field, app will have to explicitly manage queries and 3.15 will have another input. It will be explicit in code that app must check Saleor version first and chose proper strategy.

However I don't think its critical issue - if its described well in docs

**Comment by lkostrowski** [comment]
https://linear.app/saleor/issue/IFREQ-32/allow-to-filter-collections-by-channel-id-not-only-slug
