### ISSUE TITLE
Add more units to numeric fields

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#13002]
Expand metric units to support more types of products.

Add metric units:

Metric -> Distance -> mm
Metric -> Distance -> dm
Metric -> Area -> mm2
Metric -> Area -> dm2

**Comment by sumitgirwal** [comment]
Hello, @timuric 
Can I Take on the Issue? Need more info on its status and details.

**Comment by timuric** [comment]
Hey @sumitgirwal thank you for interest, this is already PR for this issue. If you are interested in contributing in general to Saleor we will be adding more `good first issue` labels soon
