### ISSUE TITLE
Add metadata to shop object

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#13022]
Add metadata to shop object to store shared configurations across different integrations. For example domain names of a strorefronts, or kind instance type such as staging, prod, test etc.

**Comment by hossain-sazzad** [comment]
> Hi @hossain-sazzad metadata is a class that is shared among many objects, which allows users to define their own key values

Thank you. I am working on this issue

**Comment by korycins** [comment]
Hey @cyborg7898, most of the data available in  `Shop` type is stored in `saleor.site.models.SiteSettings` model. 
You can also take a look at some of the resolvers on the `Shop` type that are wrapped with `@load_site_callback` (these resolvers are fetching the data from `SiteSettings` model)

**Comment by cyborg7898** [comment]
It helps Thanks @korycins

**Comment by maarcingebala** [comment]
@cyborg7898 Can you paste the full traceback from the Python console for this error? It's the right direction to extend `SiteSettings` with `ModelWithMetadata`, but there might be more places we need to update e.g. [MODEL_TO_TYPE_MAP](https://github.com/saleor/saleor/blob/99e4b88c3e5545a80f784217e35d6b37cba13611/saleor/graphql/meta/resolvers.py#L47).

**Comment by cyborg7898** [comment]
@maarcingebala It was happening because I forget add resolver method for metadata 
```
    @staticmethod
    @load_site_callback
    def resolve_metadata(root: ModelWithMetadata, info: ResolveInfo,site):
        return ObjectWithMetadata.resolve_metadata(site.settings,info) 
```
Now it's working fine but I've couple of doubt 
1. `private_metadata` I'm getting permission error. Is private metadata accessible by staff user ?
2. While adding metadata required other resolver like `resolve_metafield`?

Thanks !

**Comment by maarcingebala** [comment]
Yes, `private_metadata` is accessible by staff only. Regarding the resolver, I think using `interfaces = [ObjectWithMetadata]` should automatically add them to the type, there should be no need for adding them manually in a type 🤔

**Comment by cyborg7898** [comment]
> Yes, `private_metadata` is accessible by staff only. Regarding the resolver, I think using `interfaces = [ObjectWithMetadata]` should automatically add them to the type, there should be no need for adding them manually in a type thinking

Even I'm staff user getting permission error. 
By default resolver take `site` as a argument but we need `site.settings` that's why i defined resolver .
