### ISSUE TITLE
Simplify channel permission rules

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#13026]
## Problem

As a user I find it hard to understand how `permissionGroupCreate` operate in regards of `restricted_access_to_channels` or `channels`

As a front end engineer API doesn't provide enough information to render channel settings control in Permission group screen

## Desired behavior

`restricted_access_to_channels` or `channels` in `permissionGroupCreate` mutation should only be controlled by users with `MANAGE_STAFF` and `MANAGE_CHANNELS`

### Acceptance Criteria

- [ ]
- [ ]

### Mutations

```graphql

```

### Types

```graphql

```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by tomaszszymanski129** [comment]
Moved couple of days due to another red flag

**Comment by maarcingebala** [comment]
Closing for now, it was agreed with the frontend team that these changes are unnecessary.
