### ISSUE TITLE
Add translation deleted webhook

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#13061]
Currently, there is only `created` and `updated` translation event

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this

**Comment by cyborg7898** [comment]
@timuric Can you please provide steps or way to use existing translation webhook? It will help us to understand the webhook flow.

**Comment by maarcingebala** [comment]
We decided not to add this for now since there is no explicit mutation for deleting translations. It's possible to listen to the "update" event and check if it was set to an empty string as a workaround.
