### ISSUE TITLE
Bug: Variant editor, changing attribute parameters, usability improvement

### ISSUE THREAD

**Issue by genox** [saleor/saleor#13087]
### What are you trying to achieve?

The variant editor is hard to use with a lot of data and is frustrating for editors.

Once a value has been added using a dropdown for example, changing it requires clicking in to the field and deleting the value before it is possible to select a new value.

### Steps to reproduce the problem

Create any product with variant attributes and try to modify a variant

### What did you expect to happen?

Clicking into the field at least selects the existing value. Better: Show me all possible values instead of the currently selected one.

### Environment

Saleor SaaS

**Comment by maarcingebala** [comment]
Transferring to [saleor-dashboard](https://github.com/saleor/saleor-dashboard/) as this is a UI issue.
