### ISSUE TITLE
Search query for giftcards

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#13082]
## Problem

Customer support needs to able to find gift cards by the name or email of customers. 

`usedBy` filter field doesn't help as it only accepts IDs of existing accounts, which doesn't cover anonymous users.

Another pain point is that admins want to use generic search that accepts any input instead of filters, the same way as product search works
```[tasklist]
### Tasks
```

**Comment by maarcingebala** [comment]
- `GiftCard` model changes:
  - Add `search_index_dirty = models.BooleanField(default=False, db_index=True)` field
  - Add `search_vector = SearchVectorField(blank=True, null=True)` field.
    - Fields to include in the search vector:
      - `GiftCard.code`
      - `GiftCard.used_by_email`
      - `GiftCard.created_by_email`
      - `GiftCard.used_by` - user's email, first name and last name
      - `GiftCard.createdBy` - user's email, first name and last name
    - See `prepare_product_search_vector_value` for a reference
- Update logic to mark `search_index_dirty=True` whenever parts of the search vector change.
- Add a Celery task that looks for dirty search indexes and updates the search vector value. The task should update a batch of gift cards in a single run and check if there are still gift cards to update and schedule itself in the queue to process the remaining ones in separate tasks.
