### ISSUE TITLE
Task update_product_discounted_price_task is memory consuming

### ISSUE THREAD

**Issue by tomaszszymanski129** [saleor/saleor#13096]
### What are you trying to achieve?

The task update_product_discounted_price_task is used in many places so it should put as low memory pressure on system as possible

### Steps to reproduce the problem

1. Run many update_product_discounted_price_task hitting a lot of records
2. Notice that some of SQL statements fetch a lot of data
3. Data is computed in python causing high memory pressure

### What did you expect to happen?

The task is optimized to be less memory instensive

### Environment

Saleor version: 3.9+
OS and version: any

**Comment by aniav** [comment]
This has been resolved since the report as it was causing production problems.
