### ISSUE TITLE
Document channel parameter

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#13094]
`products` query has channel parameter which influences the visibility of the products, however documentation doesn't provide explanation of the effect of this parameter
> Slug of a channel for which the data should be returned.

**Comment by DevilsAutumn** [comment]
Can i work on this?

**Comment by timuric** [comment]
Hey @DevilsAutumn feel free to pick this one, thank you!

**Comment by aniav** [comment]
This has been addressed in: https://docs.saleor.io/developer/products/api
