### ISSUE TITLE
Bug: Tax class field is empty on new product, even though a default was defined in product type

### ISSUE THREAD

**Issue by genox** [saleor/saleor#13090]
### What are you trying to achieve?

When creating a new product, the tax class field is empty, even though a default value was defined in the product type the new product is based on.

I assume having an option to define such a default implies that it should be taken into account while creating a new product based on such types.

### Steps to reproduce the problem

1. create a product type
2. set tax class to some existing value
3. create product based on type
4. notice the empty tax class field

### What did you expect to happen?

tax field containing tax setting defined in product type

### Environment

Saleor SaaS

**Comment by maarcingebala** [comment]
Hey @genox, it is expected behavior - even though the product's tax class is not set, the tax calculations would use the one from the product type. Setting tax class at the product level is more like overriding the product type's setting. Maybe it needs to be clarified in the docs or GraphQL descriptions.

**Comment by genox** [comment]
> Hey @genox, it is expected behavior - even though the product's tax class is not set, the tax calculations would use the one from the product type. Setting tax class at the product level is more like overriding the product type's setting. Maybe it needs to be clarified in the docs or GraphQL descriptions.

I understand. But it is unintuitive. As a user, I see the tax field being empty and set it, because I want taxes set, right? Empty field means it is not set from my perspective, because I do not know the inner workings and I do not need to know them, because I just enter product data and want to make sure everything is correctly set.

Once a product is saved, the default is correctly displayed as I just noticed, just not during the initial product creation form. Why not set the default already on the creation view instead of only after the first save if the result will be the same?

**Comment by maarcingebala** [comment]
I think this issue can be solved in UI, e.g., by a help text in the product creation form informing about this (and better docs).

**Comment by maarcingebala** [comment]
Closing this ticket as this is not a core issue. Thanks for reporting!
