### ISSUE TITLE
Bug: addressValidationRules query returns Internal Server Error

### ISSUE THREAD

**Issue by typeofweb** [saleor/saleor#13129]
### What are you trying to achieve?

```graphql
query A {
  addressValidationRules(countryCode: EU) {
    countryAreaChoices {
      raw
      verbose
    }
  }
}
```

```json
{
  "errors": [
    {
      "message": "Internal Server Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addressValidationRules"
      ],
      "extensions": {
        "exception": {
          "code": "ValueError"
        }
      }
    }
  ],
  "data": {
    "addressValidationRules": null
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 1,
      "maximumAvailable": 50000
    }
  }
}
```

### Steps to reproduce the problem

https://master.staging.saleor.cloud/graphql/#saleor/N4IgjiBc4K4KYCcCeACAgi4AdAdilAhgCZEJwDO5AagQDYCWRBALvQPY4BKMtFAFAGM2MHM2QBhNkTiQUAUQCqASky58+ISLFI0ZAuIAWbegIqq86-AgIB3NZZQA3RACM25OPfwBfe75zeIAA0IGxQIGgg3kA

### What did you expect to happen?

-

### Environment

-

**Comment by maarcingebala** [comment]
In this case, I think we should:
- deprecate `EU` as the enum option (but now I'm not sure we can deprecate enum values, maybe we can mention that in the GraphQL description)
- the query should return `null` for `EU`

**Comment by patrys** [comment]
@maarcingebala We should be able to deprecate enum entries when we upgrade to GraphQL core 3.x. For now, best we can do is add a comment.

**Comment by aniav** [comment]
This has been addressed in https://github.com/saleor/saleor/pull/16301
