### ISSUE TITLE
Add missing descriptions in types

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#13142]
Review the objects in the schema and add missing descriptions:
- input types
- "output" types (those that are returned by mutations and queries)
- mutations
```[tasklist]
### Tasks
- [x] Account
- [x] App
- [x] Attribute
- [x] Channel
- [x] Checkout
- [x] Core
- [x] Csv
- [x] Discount
- [x] Gift card
- [x] Invoice
- [x] Managment
- [x] Menu
- [x] Meta
- [x] Notifications
- [x] Order
- [x] Page
- [x] Payment
- [x] Plugins
- [x] Product
- [x] Shipping
- [x] Shop
- [x] Site
- [x] Tax
- [x] Translations
- [x] Warehouse
- [x] Webhook
```

**Comment by fowczarek** [comment]
To consider:
- [ ] Descriptions for `CountableConnection`

**Comment by fowczarek** [comment]
I can't find any missing descriptions in the core module.

**Comment by maarcingebala** [comment]
Added `good first issue` for the community. If anyone wants to pick this up, please provide changes in smaller PRs, for example, each module in a separate PR. It's easier to review and improve in review.

**Comment by DevilsAutumn** [comment]
@maarcingebala Can you please assign me this? I'll complete the remaining descriptions.

**Comment by maarcingebala** [comment]
@DevilsAutumn Assigned, you can look at other PRs for this ticket for inspiration, as I wrote above, it's best to provide separate PRs for different modules. Thanks!

**Comment by DevilsAutumn** [comment]
> @DevilsAutumn Assigned, you can look at other PRs for this ticket for inspiration, as I wrote above, it's best to provide separate PRs for different modules. Thanks!

Sure, thanks. 👍

**Comment by DevilsAutumn** [comment]
@maarcingebala mypy is giving the following error on pre-commit, which, i think is obvious since `warn_unused_ignores = True` in setup.cfg ?
![Screenshot 2023-06-30 015415](https://github.com/saleor/saleor/assets/83907321/6a29616a-a3b6-4fe9-a70b-53d3892f1fa0)

**Comment by Smit-Parmar** [comment]
@DevilsAutumn Can I assist you on this?

**Comment by DevilsAutumn** [comment]
> @DevilsAutumn Can I assist you on this?

Sure! just mention here the module on which you're working so that our work doesn't clash.

**Comment by Smit-Parmar** [comment]
Last 7 will work

**Comment by DevilsAutumn** [comment]
Cool 👍. I'll do from discount to plugins then.

**Comment by maarcingebala** [comment]
@DevilsAutumn TBH I'm not sure why this error happens, but sometimes mypy returns it. To fix it I usually do:
```
mypy saleor --exclude=tests/
```
and then commit again, and somehow magically it works then :D

**Comment by DevilsAutumn** [comment]
I think `Management`, `Meta`, `Notification` and `Plugins` does not have missing desctiption.

**Comment by Smit-Parmar** [comment]
Description for `Warehouse` already added and for `Site` and `Tax` I think no description is required.

**Comment by DevilsAutumn** [comment]
This issue is finally completed ! 🥳

**Comment by maarcingebala** [comment]
Yes, thank you so much for all contributions, great work!
