### ISSUE TITLE
Release 3.15

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#13212]
This issue tracks the release progress of Saleor 3.15.

Planned release data: 23.08.2023.

## Steps

- [x] Confirm scope related to Apps is ready to be released - @lkostrowski
- [x] Release alpha tag - @maarcingebala
- [x] Inform about the alpha tag - @maarcingebala
- [x] Release alpha tag - @andrzejewsky
- [x] Inform about the alpha tag - @andrzejewsky
- [x] Prepare environments for the new minor and trigger deployments - @cmiacz
- [x] Inform about finished deployment - @cmiacz
- [x] Perform alpha tests migration on staging - @michalina-graczyk
- [x] Cypress tests review - @michalina-graczyk
- [x] Check the change log and do smoke tests - @michalina-graczyk
- [x] Inform the team about the results of the tests - @michalina-graczyk
- [x] Perform smoke check on demo and storefront - @michalina-graczyk
- [x] Inform about finished tests - @michalina-graczyk
- [x] Release stable tag - @maarcingebala
- [x] Release stable tag  - @andrzejewsky
- [x] Accepts release PR to the sandbox - @michalina-graczyk
- [x] Inform about approved release PR to the sandbox  - @michalina-graczyk
- [x] Merge release PR to the sandbox - @cmiacz
- [x] Merge release PR to the production -  @saleor/cloud 
- [x] Inform about the stable release (sandbox and production) - @cmiacz
- [x] Make the new version public in Saleor Cloud - @saleor/cloud

**Comment by lkostrowski** [comment]
Related Dashboard milestone https://github.com/saleor/saleor-dashboard/milestone/6
