### ISSUE TITLE
Improve performance of products query

### ISSUE THREAD

**Issue by kadewu** [saleor/saleor#13231]
## Problem
Currently, `query products` is taking to long to execute which can possibly cause https errors.
We should try to improve performance of said query.

Logs:
https://app.datadoghq.com/apm/trace/10252852077981374087

---

## 1. General Assumptions
- Improve performance of `query products`

### Acceptance Criteria
- [ ] Query `products` will not have changed logic.

## 2. API changes

No changes needed.

## 3. To Test

- [ ] Query still works the same as before changes
- [ ] Performance test

**Comment by patrys** [comment]
@kadewu How do we know it's the `products` resolver? The trace you linked to does not show any long spans.

**Comment by Dumi23** [comment]
I would like to ask if you are using something like Stellate configuration in between your frontend client and API it generally improves performance by a massive amount

**Comment by patrys** [comment]
@Dumi23 This ticket is to optimize the underlying core, a caching layer can paper over the problem but it can't fix it as it still needs to be recalculated from time to time.

**Comment by maarcingebala** [comment]
The issue still happens, [here is a newer example trace](https://app.datadoghq.com/apm/trace/5934910646291945523?colorBy=service&env=production&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=17277150772713653386&spanViewType=metadata&timeHint=1700652804605.678), more can be found by filtering by query fingerprint.

**Comment by maarcingebala** [comment]
This is the same problem as this one: https://github.com/saleor/saleor/issues/13996, closing.
