### ISSUE TITLE
Improve the way how we label the metadata fields

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#13247]
## Problem

Currently, when having a type with `ModelObjectType`, some metadata fields by default gets the label `ADDED_IN_33`. It is not true for the objects that received the metadata fields in Saleor 3.4+. 

There is a field for the class's `Meta` - `metadata_since` that can control the metadata description, but it is optional, and probably some of the developers don't know or forget about it.
 
---

## Proposed solution

- We could change the implementation, and in case of using `ModelObjectType`,  we could always require providing `metadata_since`. 
- The changes require us to go through all types that use `ModelObjectType` and try to check when `metadata` was attached to the type.
- `metadata_since` could be `Optional[str]`. We could do `metadata_since=None` for all types that have metadata introduced before 3.1
- If `metadata_since` < 3.3, then fields like `privateMetafield`, `privateMetafields`, `metafield`, `metafields` should have label added in 3.3 (in 3.3 we extended a metadata interface and introduced the `privateMetafield`, `privateMetafields`, `metafield`, `metafields`)

**Comment by Smit-Parmar** [comment]
@korycins what about metadata introduced after 3.3?

**Comment by korycins** [comment]
@Smit-Parmar Then we need to find the correct version that added the metadata for a specific type and include it in `metadata_since`.. 
Let's take `CheckoutLine` as an example.
graphql schema says: metadata was added to `CheckoutLine` in 3.3, but `CheckoutLine` received metadata support in 3.5. 
(This can be easily checked by switching the version branches - `git checkout 3.x` )
```graphql
"""Represents an item in the checkout."""
type CheckoutLine implements Node & ObjectWithMetadata {
  ...
  """
  A single key from private metadata. Requires staff permissions to access.
  
  Tip: Use GraphQL aliases to fetch multiple keys.
  
  Added in Saleor 3.3.
  
  Note: this API is currently in Feature Preview and can be subject to changes at later point.
  """
  privateMetafield(key: String!): String
}

**Comment by korycins** [comment]
Closing, as this is already solved
