### ISSUE TITLE
Add metadata to checkoutShippingAddressUpdate & checkoutBillingAddressUpdate

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#13248]
It would be convenient to pass extra metadata upon adding shipping & billing addresses for the checkout using `checkoutShippingAddressUpdate` & `checkoutBillingAddressUpdate` this would allow us to store non-standard address fields without calling separate `metadataUpdate` mutation

**Comment by maarcingebala** [comment]
Proposed schema:
```graphql
checkoutShippingAddressUpdate(
  id: ID
  metadata: [MetadataInput!]
  privateMetadata: [MetadataInput!]
  shippingAddress: AddressInput!
  validationRules: CheckoutAddressValidationRules
): CheckoutShippingAddressUpdate
```

For readability, I've skipped the deprecated input fields in the example. `metadata` and `privateMetadata` fields would need a description that makes it clear that this metadata would be set for the address, not the checkout. `checkoutBillingAddressUpdate` would follow the same schema changes.

Question - addresses can be added to the checkout also in the `checkoutCreate` mutation which doesn't support setting any metadata. We we want also to provide support for setting metadata there? It's possible, but we would have to differentiate checkout metadata and addresses' metadata.

**Comment by korycins** [comment]
@maarcingebala Have you considered adding metadata and privateMetada to the `AddressInput` type? This would solve the issue:
```
[we] would need a description that makes it clear that this metadata would be set for the address, not the checkout.
```
We would also have a nice support for checkoutCreate. Also what about permissions for retrieving the privateMetadata? Who can access to it?

**Comment by maarcingebala** [comment]
Yes, that would be a much cleaner API, except these fields would have no effect in some queries where AddressInput is used, but I think that's fine. We already have permission rules for address metadata: https://github.com/saleor/saleor/blob/main/saleor/graphql/meta/permissions.py#L121

**Comment by maarcingebala** [comment]
So the schema would look like this:
```graphql
input AddressInput {
  firstName: String
  lastName: String
  companyName: String
  streetAddress1: String
  streetAddress2: String
  city: String
  cityArea: String
  postalCode: String
  country: CountryCode
  countryArea: String
  phone: String

  # new fields
  metadata: [MetadataInput!]
  privateMetadata: [MetadataInput!]
}
```

**Comment by Air-t** [comment]
@timuric For now using `updatePrivateMetadata` mutation for `Address` we are checking if updated address:

1. belongs to staff member then `AccountPermissions.MANAGE_STAFF`
2. is a warehouse address or site address then `PermissionDenied`
3. belongs to customers `AccountPermissions.MANAGE_USERS` (Manage customers)

core team suggests that for mentioned mutations only public metadata should be allowed.

It would be helpful if you could describe the use case of adding `privateMetadata`(with current permissions) in shipping and billing mutations.

**Comment by maarcingebala** [comment]
Discussed with @timuric and we agreed we could skip privateMetadata in this case.
