### ISSUE TITLE
Add zero-downtime support

### ISSUE THREAD

**Issue by aniav** [saleor/saleor#13309]
Part of https://github.com/saleor/saleor/issues/12539

### Migration plan
- **3.16.X**
    - old sales are created
    - recalculation based on old sales
-  **DB migration from 3.16.X - 3.16.X+1** 
    - migrate sales to promotions (including discount, transaction objects)
- **3.16.X+1**
    - **transitional version - we will have both old Sale and new Promotion instances**
    - migrate sales to new promotion models (the new price recalculation methods are called)
    Solutions for handling Sale and Promotion at the same time:
    1. Operate on sale on mutations and types.
      - when a new sale is created, create new promotion as well, when the sale is updated, update corresponding promotion as well. The same in case of other mutations:
      `saleCreate`, `saleUpdate`, `saleDelete`, `saleAddCatalogues`,`saleRemoveCatalogues`,`saleChannelListingUpdate`. If the synchronisation with the promotion model will be time consuming/will generate lot's of DB requests - delegate the synchronisation to the celery task
      - when the discounted_prices are changed - update or create `VariantChanelListingPromotionRule` objects as well
      - ensure `OrderLineDiscount` is created when `sale_id` is assigned to `OrderLine`

### Previous version (3.16.X+1) - instances: old sales and new promotions

- [x] - Add Promotion models
- [x] - Add migration that will call celery task for migrating current sales to promotions
- [x] - When a new sale (`saleCreate` mutation)  is created, create new promotion as well.
- [x] - When the sale is updated, update corresponding promotion as well. The same in case of other mutations: `saleUpdate`, `saleDelete`, `saleAddCatalogues`,`saleRemoveCatalogues`,`saleChannelListingUpdate`
- [x] - The catalogue mutations should call the old sale method for recalculation.
- [x] - Update the `update_products_discounted_price` to create the `VariantChannelListingPromotionRule` object
- [x] - Ensure `OrderLineDiscount` is created when `sale_id` is assigned to `OrderLine`

### Current version (3.17) - only new promotions
- Move the sale migration celery task to the code to do the update synchronously in the migration code
- Add promotion mutations
- Add promotion types
- Drop Sales models from ORM (leave in the DB) 
- Add new `handle-promotion-toggle` schedule task
- Deprecate old celery tasks including `handle-sale-toggle`
- `handle-sale-toggle` - make it empty
- rest of celery tasks should still have the code to run
- tasks for price recalculation should call the promotion task

### Next version (3.18) - only new promotions
- Drop Sales models from the DB
- Drop the sale related webhooks
- Drop `handle-sale-toggle`
- Drop all deprecated celery tasks

**Comment by IKarbowiak** [comment]
We should ensure with the Cloud team what is the best option for removing old and adding new schedule in context of zero-downtime approach.

**Comment by zedzior** [comment]
We need to ensure that the sequence is created after migration is completed.
https://github.com/saleor/saleor/pull/13659#discussion_r1291225685
