### ISSUE TITLE
Update sale mutations to use the `Promotion` objects instead of `Sale` - allow using the old sale mutations only on promotions with `old_sale` set to `True`

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#13319]
Part of https://github.com/saleor/saleor/issues/12539

Update sale mutations to use the Promotion objects instead of Sale - allow using the old sale mutations only on promotions with old_sale set to True

**Comment by aniav** [comment]
@zedzior noticed we also need to fetch the Promotions migrated from Sales by their corresponding id, so we'll add sale id to be stored on the Promotion model instead of `old_sale` and we'll make sure only Promotions with sale id are returned in the old queries and mutations.

**Comment by zedzior** [comment]
[saleCreate](https://github.com/saleor/saleor/pull/13624)
[saleUpdate](https://github.com/saleor/saleor/pull/13633)
[saleDelete](https://github.com/saleor/saleor/pull/13635)
[saleChannelListingUpdate](https://github.com/saleor/saleor/pull/13659)
[saleAddCatalogues & saleRemoveCatalogues
](https://github.com/saleor/saleor/pull/13701)
[saleBulkDelete](https://github.com/saleor/saleor/pull/13716#event-10120185971)
[saleTranslate](https://github.com/saleor/saleor/pull/13721#pullrequestreview-1584672147)
[metadata mutations](https://github.com/saleor/saleor/pull/13717)
