### ISSUE TITLE
Add no-cache headers for checkout process

### ISSUE THREAD

**Issue by artursmet** [saleor/saleor#1334]
Currently the backend is not setting any cache-control headers by default. 
It's important to set those headers in sections that should never be cached, like dashboard, cart, checkout or profile.

### What I'm trying to achieve

...

### Steps to reproduce the problem

1. On demo page where caching layer (cloudfront) is used the cart is loaded from cache

### What I expected to happen
Cart or checkout should never be cached, a header `Cache-Control: no-cache` should be used.

### What happened instead/how it failed
Backend is not setting `Cache-Control` headers, that's why Cloudfront sets default caching policy on all views.

**Comment by aquaerius** [comment]
Hello, Is this still an issue? Can you post the steps to reproduce it?

**Comment by maarcingebala** [comment]
This is no longer an issue in headless Saleor, where the mentioned views were removed.
