### ISSUE TITLE
Bug: Memory pressure too high on gunicorn pods 

### ISSUE THREAD

**Issue by jakubkuc** [saleor/saleor#13394]
### What are you trying to achieve?

Memory pressure is too high in pods. They have a limit of 1.5 GB memory and it is causing them to shut down.  The change appeared between commits `9261400` and '89ab5e4f45'. It is most probably caused by #13173 (the only commit that did something more than cosmetic changes in core) 

### Steps to reproduce the problem

Master staging has pods that hit 1.5 GB memory limit. I wasn't able to reproduce it.

### What did you expect to happen?

Find what causes the memory overload. Fix it

### Environment

Saleor version: 3.15
OS and version: …

**Comment by aniav** [comment]
This has been addressed through various improvements 🙌
