### ISSUE TITLE
Bug: Order is not confirmed when using transactionAPI

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#13422]
### What are you trying to achieve?

With enabled `automatically_confirm_all_new_orders`, the orders paid with transactionInitialize, transactionProcess should be marked as confirmed

### Steps to reproduce the problem

1. enable auto-order-confirm
2. Create the order from checkout by calling `orderCreateFromCheckout`
3.Process the payment with transactionAPI - transactionInitialize, transactionProcess
4. The order is fully paid, but the status of it is still unconfirmed.

### What did you expect to happen?

In the case of calling orderCreateFromCheckout, the order is marked as unconfirmed.  The Transaction API for processing the payment  (transactionInitialize, transactionProcess) should validate the order status & order settings and update the order status to unfulfilled.

### Environment

Saleor version: …
OS and version: …

**Comment by szczecha** [comment]
This is also the case for `transactionEventReport` https://github.com/saleor/saleor/issues/12531

**Comment by aniav** [comment]
This has been resolved in https://github.com/saleor/saleor/pull/16254 and ported to versions down to 3.14.
