### ISSUE TITLE
Bug: Allow to query checkout by ID as unauthorized user when checkout.user is set

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#13454]
### What are you trying to achieve?

The `checkout` query doesn't allow fetching the checkout by ID when the `checkout.user` field is set and an unauthorized user sends the request. This is inconsistent behavior with mutations, where it is possible to modify checkouts as long as the user knows the ID. We want to unify this behavior between queries and mutations and allow resolving all checkouts in active channels by ID by unauthorized users.

Resolved: https://github.com/saleor/saleor/pull/16001

### Steps to reproduce the problem

1. Create a checkout as an authenticated customer in an active channel.
2. Try to fetch the checkout by ID using the following query, but send the request as unauthenticated user:
```graphql
{
  checkout(id: $ID) {
    id
  }
}
```
As a result, null is returned:
```json
{
  "data": {
    "checkout": null
  }
}
```

### What did you expect to happen?

Instead of returning `null` the API should return the checkout data.

We should update the checkout resolver always to return the checkout instance when the channel is active - see the following `if` block: https://github.com/saleor/saleor/blob/a24c91626a76193430e6ca5bf83143b03c6cb49a/saleor/graphql/checkout/resolvers.py#L33 
This logic in this block can be removed and replaced with returning the checkout.

Note: if the channel is inactive, we should still be requiring proper permissions, which happens now after the requester is resolved: 
https://github.com/saleor/saleor/blob/a24c91626a76193430e6ca5bf83143b03c6cb49a/saleor/graphql/checkout/resolvers.py#L44

### Environment

Saleor version: 3.14

**Comment by i-so-late** [comment]
Hello, I've just submitted my pull request (#15768) to address this problem. It's my first time to contribute to this project and I'm looking forward to your feedback on the pull request.

**Comment by Air-t** [comment]
Ticket resolved along with other changes [here](https://github.com/saleor/saleor/pull/16001)
