### ISSUE TITLE
Drop workaround for `datetime.fromisoformat` after moving to python3.11+

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#13451]
The PR: https://github.com/saleor/saleor/pull/13440 added a workaround for using `datetime.isoformat`.  When we will move to python >= 3.11, it will not be needed anymore.

---

`datetime.fromisoformat` supports only formats of the objects that were created by date.isoformat() or datetime.isoformat(). It is fixed in 3.11.
ref: https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat
![image](https://github.com/saleor/saleor/assets/23282005/4cfba6be-2512-41f6-a4a3-845679bf2e1c)

**Comment by aniav** [comment]
This has been addressed in https://github.com/saleor/saleor/pull/16858
