### ISSUE TITLE
[RFC] Setup data for backend tests

### ISSUE THREAD

**Issue by aniav** [saleor/saleor#13494]
## Problem
Saleor is using `pytest` with `fixtures` to prepare data for tests. We now have more than 10k tests and around 800 fixtures. The fixtures contain a lot of repetition and became hard to maintain. For any db change adding a new field there are multiple fixtures that have to be updated. We need a way to make them easier to maintain without adding complexity.

## General Assumptions
- We'd like a way to avoid overhead of multiple changes in fixtures after a single change in Django models.
- Proposed changes should be easy to introduce and shouldn't require rewriting a lot of code.

## Proposed changes
I'd like to propose a concept of model helper functions. A helper function would prepare a model instance with predefined defaults.

Let's look at an example of a helper function for the `Address` model
```python
def create_address(
    first_name="John",
    last_name="Doe",
    company_name="Mirumee Software",
    street_address_1="Tęczowa 7",
    city="WROCŁAW",
    postal_code="53-601",
    country="PL",
    phone="+48713988102",
    country_area="test_country_area",
    city_area=None,
    ):
    return Address.objects.create(
        first_name=first_name,
        last_name=last_name,
        company_name=company_name,
        street_address_1=street_address_1,
        city=city,
        postal_code=postal_code,
        country=country,
        phone=phone,
        country_area=country_area,
        city_area=city_area,
    )
```

This way the fixtures for address will go from an example from current code:
```python
@pytest.fixture
def address(db):
    return Address.objects.create(
        first_name=first_name,
        last_name=last_name,
        company_name=company_name,
        street_address_1=street_address,
        city=city,
        postal_code=postal_code,
        country=pl,
        phone=phone,
        country_area=country_area,
        city_area=city_area,
    )
```

To the following
```python
@pytest.fixture
def address(db):
    return create_address()


@pytest.fixture
def address_with_areas(db):
    return create_address(city_area="test_city_area")


@pytest.fixture
def address_other_country():
    return create_address(
        street_address_1="4371 Lucas Knoll Apt. 791",
        city="BENNETTMOUTH",
        postal_code="13377",
        country="IS",
        phone="+40123123123",
    )


@pytest.fixture
def address_usa():
    return create_address(
        street_address_1="2000 Main Street",
        city="Irvine",
        postal_code="92614",
        country_area="CA",
        country="US",
        phone="",
    )
```

This way:
- Each model has just one entry point with defaults and each fixture or test function can then decide which fields are meaningful for their case.
- We can decide if we want the helper functions to create the instance in the db or just prepare it without saving.
- We can put the functions outside of tests so we could also use them to generate demo data (which now use similar functions that also have to be maintained).

### factory_boy
[Factory_boy](https://factoryboy.readthedocs.io/en/stable/) is a popular choice used for preparing data for tests. It has many benefits coming from readable representation of default data and a mature set of tools around it. It has been well tested and has been around for years.

It has been rejected for the following reasons:
- The main idea behind tools like factory_boy is to generate random data which is not what we want in our tests. We'd like to always know exactly against what data we're going tu write a test.
- Automated factories save a few lines of code once while making debugging harder every single time. We should optimize code for ease of reading, not ease of writing.
- There are cases where generating a lot of various instances will make sense but most of our tests don't operate on large number of objects with randomised values.
- Creating factories for each of the models means we need to maintain two places representing a single database table. Combining that with already existing fixtures means 3+ places for every model before we'd fully move to factory_boy (or a similar tool).
- Any custom logic placed in factory definition is invisible when we read the tests after they fail. So whatever custom logic or relation is added to factory `post_generation` means harder debugging when a test fails. And more code to maintain for logic that's unique to factories.

### factories/generators as fixtures
[Pytest docs mention](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#factories-as-fixtures) factories as fixtures.

While pytest does suggest that approach, making a fixture out of a simple python function doesn't seem to add any benefit for us on top of the suggested function approach.

**Comment by maarcingebala** [comment]
I like this idea. We also wanted to explore ways of reducing DB queries in tests. Would creating the model instance without saving it to DB be enough here? I'm also wondering if we should somehow differentiate such fixtures/functions, perhaps by using different naming conventions.

**Comment by aniav** [comment]
There was a different approach applied on the repo recently, so closing this now.
