### ISSUE TITLE
Increased memory pressure

### ISSUE THREAD

**Issue by kadewu** [saleor/saleor#13540]
## Problem

In 3.15 there is increased memory pressure in comparison to previous versions. We should check what is causing it and optimize if possible.

Logs when memory pressure increased:
https://app.datadoghq.com/logs?query=message%3AWorker%20with%20pid%20%2A%20was%20terminated%20due%20to%20signal%20%3F%20kube_namespace%3Acloud-staging&agg_m=count&agg_q=kube_namespace%2Cpod_name&agg_t=count&cols=host%2Cservice&index=%2A&messageDisplay=inline&source=monitor_notif&stream_sort=desc&viz=stream&from_ts=1689840284862&to_ts=1690445084862&live=true

Logs from QA tests when observed memory pressure:
https://app.datadoghq.com/s/pyppqluqng2nvvuv/kqv-g82-5te

**Comment by maarcingebala** [comment]
We confirmed that the issue happens on older versions of Saleor as well (3.14) which unlocks the 3.15 release.

**Comment by maarcingebala** [comment]
Closing as we're missing details to reproduce the issue.
