### ISSUE TITLE
Add `notifyUser` flag to the `FULFILLMENT_CREATED` webhook payload

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#13559]
The `FULFILLMENT_CREATED` webhook is triggered via the `orderFulfill` mutation when a new fulfillment is created. Mutation accepts the `notifyCustomer` flag, which determines whether a notification should be sent to customer. This flag needs to be passed to webhook so that apps can read it and based on that send notifications.

Extend the `FulfillmentCreated` type with the `notifyCustomer` flag:

```graphql
type FulfillmentCreated implements Event @doc(category: "Orders") {
  issuedAt: DateTime
  version: String
  issuingPrincipal: IssuingPrincipal
  recipient: App
  fulfillment: Fulfillment
  order: Order

  """Informs whether a notification should be sent to the customer."""
  notifyCustomer: Boolean!
}
```

**Comment by Air-t** [comment]
@maarcingebala should `notifyCustomer` be required? or rather a optional value with a default_value?

**Comment by maarcingebala** [comment]
I would try to make it required and always determine a meaningful value that is easier to handle for consumers. Otherwise, it would be either a boolean or `null`, which adds additional logic to consumers.
