### ISSUE TITLE
Add `APP_UNINSTALLED` event.

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#13556]
## Problem

App, after being uninstalled must clean up after itself:
1. Clean APL 
2. Unregister external services, webhooks etc

---

## 1. General Assumptions

App should receive an new async webhook `APP_UNINSTALLED` that will provide `App` object in the subscription.
With `App` object app can query its own metadata so in case app uses metadata as a persistency layer, it will be able to access it.

Webhook must be triggered only for the app it was meant to be delivered (app should know about its own uninstallation, but not other apps).

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add new webhook `APP_UNINSTALLED`
```

**Comment by maarcingebala** [comment]
What actions trigger the app uninstallation in the API? Is it the `appDelete` mutation or is there some other trigger? I see that currently the `appDelete` mutation sends APP_DELETED event, is that anyhow helpful here?

**Comment by lkostrowski** [comment]
Looks like we missed that - let me check and I will reopen if we need something extra here
