### ISSUE TITLE
Allow adding multiple codes per voucher

### ISSUE THREAD

**Issue by aniav** [saleor/saleor#13606]
Part of https://github.com/saleor/saleor/issues/13582

---

## 1. General Assumptions

- Introduce new `VoucherCode` model that will keep voucher codes

### Mutations
Update voucher mutations:

**VoucherInput**:
- deprecate `code` field
- add `codes: List[str]` field

```graphql
input VoucherInput @doc(category: "Discounts") {
    code: String @deprecate

    # new fields
    codes: [String!]
}

```

#### Deprecate:
- fields on `Voucher` type:
  - `code`
  - `used`

 - For `code`, `used` we should take the first voucher code and return those valued for this instance.
 - Add the above information in field descriptions.

#### Voucher changes
- Add `VoucherCode` type
- Extend `Voucher` with `codes` field

```graphql
type VoucherCode @doc(category: "Discounts") {
  id: String!
  code: String!
  used: Int!
  is_active: Bool!
}

type Voucher {
   codes: [VoucherCode!]
}

```

#### Voucher changes
Create `VoucherCode` model with relation to voucher
```python
class VoucherCode:
    id = models.UUIDField(primary_key=True, editable=False, unique=True, default=uuid4)
    is_active = models.BooleanField(default=True)
    code = models.CharField(max_length=255, unique=True, db_index=True)
    used = models.PositiveIntegerField(default=0, editable=False)
    voucher = models.ForeignKey(Voucher)
```

**Voucher** changes:
- drop `code` from `Voucher` model
- drop `used` from `Voucher` model

#### Migrations:
- migrate current voucher codes and `used` field to `VoucherCode` objects

## 4. Calculations
- Update releasing and setting voucher usage.

**Comment by SzymJ** [comment]
added info about moving `usage_limit` to `VoucherCode` model

**Comment by SzymJ** [comment]
Updated schemas, after reverting `usage_limit` to `Voucher` and adding `is_active` to `VoucherCode`
