### ISSUE TITLE
500 during staff members search

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/saleor#13611]
### What are you trying to achieve?

I want to search staff member by name on https://v314.staging.saleor.cloud/dashboard/

### Steps to reproduce the problem

1. Go to staff members 
2. In search type 'marcin'
 As a result I am getting Test Test user and `500`

Video: 
https://watch.screencastify.com/v/UU0BdDSuCP1rdgPXofUD
Request URL: https://v314.staging.saleor.cloud/thumbnail/VXNlcjo2MjUyNzdiZS1jNzZiLTRhZTUtOGQ3OC05Njk5ZTk0OTA0MTg=/128/

<img width="963" alt="image" src="https://github.com/saleor/saleor/assets/25908728/4ef56c28-b270-4b80-a620-04e50c9da420">

![image](https://github.com/saleor/saleor/assets/25908728/5eb9a333-5b7e-43d4-a185-cc6c56e06a50)

Additionaly when I am looking for someone else who is in the list, the results are empty
<img width="802" alt="image" src="https://github.com/saleor/saleor/assets/25908728/82289115-22ea-4c17-98ed-f4b14df42277">

### What did you expect to happen?

I expect to have w working search 

### Logs

In attachments 

### Environment

Saleor version: … 
dashboard 3.14-58069c9
core v3.14.7
OS and version: …13.4.1

**Comment by maarcingebala** [comment]
[Thread](https://saleorcommerce.slack.com/archives/C039MGJDWU8/p1689581233929839) with some more context.

**Comment by maarcingebala** [comment]
This should be resolved by now, there were problems with Celery on this env.
