### ISSUE TITLE
Bug: Cannot add product to checkout with track inventory disabled and no stock

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#13616]
### What are you trying to achieve?

I'm trying to create and complete a checkout for a product with track inventory disabled and no stock records defined. 

### Steps to reproduce the problem

1. In a product variant, switch `trackInventory` flag to `False` and remove all stock records. This can be easily done in the dashboard- go to a variant page, in the "Inventory" section disable "Track inventory" and remove stock records in the table below.
2. Create a checkout and try to add the above variant.
3. Error is raised:
```
"errors": [
  {
    "field": "quantity",
    "message": "Could not add items <variant>. Only 0 remaining in stock.",
    "code": "INSUFFICIENT_STOCK"
  }
]
```

### What did you expect to happen?

The error is raised because there are no stock records. Since inventory tracking is disabled, we should check the existence of stock records and allow adding such variant to checkout. 

Notes:
- Since up to this point every order created from checkout had stock allocations present (`OrderLine.allocations` field in the schema), making this change is considered a **breaking change**. Any integration that relied on the fact that allocations were always present must adapt to orders without allocations. This change needs to be released in a minor release.
- More context can be found in [this](https://saleorcommerce.slack.com/archives/C039MGJDWU8/p1690894302840149) discussion.
- Logic responsible for checking the quantity that needs to be fixed is in the `check_stock_quantity_bulk` function.

### Environment

Saleor version: 3.14

**Comment by EduardoNogueira** [comment]
Hello, I am currently facing this issue, Is there a workaround available?
