### ISSUE TITLE
Reduce the number of database fetch count from PluginManager

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#13657]
The plugin configurations are fetched for every GraphQL requests which scales poorly and wastes resources: https://github.com/saleor/saleor/blob/65349faa97dc6d4666813719c7fb03b51389bf3e/saleor/plugins/manager.py#L158-L162

Figure out a way to reduce the number of calls (e.g. caching)

**Comment by maarcingebala** [comment]
Much of that time is spent in Python code, not DB calls.

- PluginsManager fetches all channels from the (writer) database during initialization and then, once again, fetches channels from the (reader) database in `_get_db_plugin_configs`:
        1. https://github.com/saleor/saleor/blob/0d21c08210ea9e1785d0f19638840cca35047a23/saleor/plugins/manager.py#L143
        2. https://github.com/saleor/saleor/blob/0d21c08210ea9e1785d0f19638840cca35047a23/saleor/plugins/manager.py#L163

- We need to profile PluginsManager with representative data (e.g. has 100 plugin configurations across 25 channels, it’s fast when we test it with just one plugin and one channel)

**Comment by maarcingebala** [comment]
- Drop prefetch_related in favor of map in Python.
- Use the reader database instead of the writer.
