### ISSUE TITLE
Bug: argument of type 'NoneType' is not iterable in mutation productChannelListingUpdate

### ISSUE THREAD

**Issue by djkato** [saleor/saleor#13694]
### What are you trying to achieve?

mutation productChannelListingUpdate. When executing the mutation, one of the fields breaks if value is null. I think it's either "removeChannels" or "removeVariants", not sure which tho, if not both. 
Similar issue to #13512

### Steps to reproduce the problem

1. query:
```json
{
  "operationName": "ProductChannelListingUpdate",
  "query": "mutation ProductChannelListingUpdate($id: ID!, $input: ProductChannelListingUpdateInput!) {
  productChannelListingUpdate(id: $id, input: $input) {
    errors {
      field
      message
      code
    }
  }
}

",
  "variables": {
    "id": "UHJvZHVjdDoyMg==",
    "input": {
      "removeChannels": null,
      "updateChannels": [
        {
          "channelId": "Q2hhbm5lbDoy",
          "isAvailableForPurchase": true,
          "isPublished": true,
          "removeVariants": null,
          "visibleInListings": true
        }
      ]
    }
  }
}
```

### What did you expect to happen?

Execute mutation without error due to a null in one of the variables. 

### Logs

```rust
errors: Some(
        [
            GraphQlError {
                message: "'NoneType' object is not iterable",
                locations: Some(
                    [
                        GraphQlErrorLocation {
                            line: 2,
                            column: 3,
                        },
                    ],
                ),
                path: Some(
                    [
                        Field(
                            "productChannelListingUpdate",
                        ),
                    ],
                ),
                extensions: Some(
                    IgnoredAny,
                ),
            },
        ],
    ),
    ```

### Environment

dashboard v3.14.4
core v3.14.2

**Comment by maarcingebala** [comment]
Sentry logs: https://saleor.sentry.io/share/issue/a00047bb4ab04111ae9c654396b98978/

It crashes in this function where `None` is passed as `values` argument: https://github.com/saleor/saleor/blob/c17271564292662fd634a91e090d5049a44ff9c5/saleor/graphql/core/utils/__init__.py#L38

**Comment by patrys** [comment]
@maarcingebala I think the issue is in `clean_channels`. It should not have to call validators if no values are provided.

**Comment by maarcingebala** [comment]
Yep, maybe it can be fixed at an earlier point. It would also be useful to fix the typing in these functions.
