### ISSUE TITLE
Bug: `productBulkCreate` optimization issue

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#13700]
### What are you trying to achieve?

Running the `productBulkCreate` mutation to create a single product with 5-10 variants, where each has around 20 attributes, takes over 20 seconds.

### Steps to reproduce the problem

```
mutation($products:[ProductBulkCreateInput!]!){
  productBulkCreate(
    errorPolicy:IGNORE_FAILED,
    products:$products
  ) {
    errors{
      code
      message
      values
    }
    results{
      product{
        id
      }
      errors{
        code
        message
        values
      }
    }
  }
}
```

### What did you expect to happen?

20 seconds is an unacceptable time for this mutation.

### Logs

Context: https://saleorcommerce.slack.com/archives/C02LMJV6GGM/p1691754728176669
Trace: https://app.datadoghq.com/apm/trace/4092933743730849626?colorBy=service&env=production&filteredType=web&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=8068242235606102362&spanViewType=metadata&timeHint=1692268081392.753

### Environment

Saleor version: 3.14.9

**Comment by tomaszszymanski129** [comment]
Most of it was handled in https://github.com/saleor/saleor/pull/13792 and https://github.com/saleor/saleor/pull/13850, there is still a case when it is rather slow - richtext attributes and product media.
