### ISSUE TITLE
Extend length of attribute translation fields

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#13735]
There is a mismatch between the length of char fields for attribute values. The max lengths are as follows:

`AttributeValue` model:
- `name`: 250
- `value`: 100

`AttributeValueTranslation` model:
- `name`: 100

Limit on the `AttributeValueTranslation.name` doesn't allow saving translations for long attribute value names. To fix it we can make all these fields use a maximum available length of 255.

**Comment by aniav** [comment]
This will actually be `250` to allow it to be consistent with other places where a `slug` is generated based on the name and has a suffix added.
