### ISSUE TITLE
Unsafe redirect to URL with protocol 'https'

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#13749]
Possibly affected class of: HttpResponseRedirect or a function that uses it under the hood (e.g. render)

Sentry errors: 
https://saleor.sentry.io/issues/3853339977/?project=6417854&referrer=project-issue-stream&statsPeriod=7d

Example trace: https://app.datadoghq.com/apm/traces?query=env%3A%22production%22%20service%3A%22core%22%20resource_name%3A%22tenants.middleware.SaleorTenantMiddleware.__call__%22%20host%3A%22i-07a9430cb955ae8c0%22%20%40version%3A%223.9.29-60f9135%22&env=production&graphType=flamegraph&historicalData=true&shouldShowLegend=true&trace=a50cb3ed5652c718&traceID=17467183125630341282&start=1678286090486&end=1678286150486&paused=true

**Comment by patrys** [comment]
I found the culprit, the Adyen plugin is accidentally modifying the `HttpResponseRedirect` class:

https://github.com/saleor/saleor/blob/9d4df5e2ae6926ff95fd347e5fb8309263d8f069/saleor/payment/gateways/adyen/webhooks.py#L1074-L1075
