### ISSUE TITLE
Use separate socket and read timeouts when making external calls

### ISSUE THREAD

**Issue by patrys** [saleor/saleor#13770]
Throughout the codebase, we pass a single number as the` requests.*`'s `timeout` argument. The number is used as the socket connection timeout, and the remainder is used as the read timeout. We never want to wait for 20 or 30 seconds for a socket connection to be established, so I'd like to see Saleor always pass a tuple, explicitly splitting the time budget into a connection and read time limit.

Example:

```python
# allow up to 2 seconds for a connection to be established
# and up to 18 seconds for the response to be sent over
requests.get(
    manifest_url, headers=headers, timeout=(2, 18), allow_redirects=False
)
```

While at it, we should also ensure all timeouts are named constants instead of magic numbers.

**Comment by NyanKiyoshi** [comment]
[RFC 8305](https://www.rfc-editor.org/rfc/rfc8305) recommends two seconds as the connect timeout which should be more than enough in most cases, I thus suggest using 2s as the default value (users should be able to adjust the value as needed through `settings.py` for flexibility).
In most cases, the request would get acknowledged within that connect timeout and be put in queue in the remote target's system/infra.

**Comment by patrys** [comment]
Agreed, that's precisely why I want them separate. If we cannot get the connection accepted within 2 seconds, something is broken, and there's no point in waiting for the entire timeout.

**Comment by maarcingebala** [comment]
Not sure if this is the same problem but, seems related (it was reported on Clickup):

Some synchronous webhooks don't always respect the timeout depending on which layer failed (see below screenshots for the errors):
- https://webhook.site:10/ - times out after 20s
- https://master.staging.saleor.cloud:10/ - times out after 1:20mn

Steps to reproduce:
- Add webhook for "list payment methods"
- Endpoint: "https://master.staging.saleor.cloud:10/"
- Query will return HTTP 504:
```
{
  shop {
    availablePaymentGateways {
      name
      id
      config {
        value
      }
      currencies
    }
  }
}
```
