### ISSUE TITLE
Introduce the flag for products to mark the objects that needs recalculation

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#13840]
We should refactor the way that the product prices are recalculated.

### Problem
Currently the discounted price recalculation method is called each time the related sale is changing. This may result in calling recalculation multiple times for single product what is not efficient.

## Solution
We should introduce similar solution as we already have for search index.
Add the flag on `Product` model to mark the products that needs recalculation. Then we should add a task that will be run each 20 seconds (as it's done for search vector, or maybe other frequency - to discuss) and recalculate the discounted prices only for those products.

**Comment by maarcingebala** [comment]
Task functions to refactor:
- `update_products_discounted_prices_for_promotion_task`
- `update_products_discounted_prices_of_promotion_task`

**Comment by maarcingebala** [comment]
We could try to use a custom Celery scheduler that will schedule the task only if there are products that need recalculating. An example custom schedule based on this logic was added in [this commit](https://github.com/saleor/saleor/pull/14823/commits/c4ed78c6fd984ef271878f811d3087bdf0bc753d#diff-6724102dbc2ea88d9de3ffdef217f9f4ac654211597696902f8aaf0d26bc5637R165).
