### ISSUE TITLE
Adjust Order model to keep info about used voucher code

### ISSUE THREAD

**Issue by SzymJ** [saleor/saleor#13887]
`Order` model needs to keep information about the used voucher code to correctly decrease `used` value when `expire_orders_task` is run. 

- Extend `Order` and `OrderDiscount` model with `voucher_code` as a string.
- Extend `Order` type with `voucher_code`
- Deprecate `voucher` on `DraftOrder` mutation inputs. Allow providing `voucher_code`.
- Add migration to populate `voucher_code` from existing `voucher` field in `Order` model
- Add migration to populate `voucher_code` from existing `voucher` field in `OrderDiscount` model. This one is done [here](https://github.com/saleor/saleor/issues/14341)
Part of #13582

**Comment by IKarbowiak** [comment]
> Deprecate voucher on DraftOrder mutation inputs. Allow providing voucher_code.

Update mutations `draftOrderCreate` and `draftOrderUpdate` to assign `code` to `voucher` when the `voucher_id` is provided in input.
