### ISSUE TITLE
Add application information to Adyen requests

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#13899]
Add application information to Adyen requests, as described here https://docs.adyen.com/development-resources/application-information/?programming_language=py

`externalPlatform.name`: Saleor or Saleor Commerce
`externalPlatform.integrator`: Saleor or Saleor Commerce,
`externalPlatform.version`: Saleor version
`merchantApplication.name`: SaleorAdyenPlugin/ SaleorAdyenApp (TBD)
`merchantApplication.version`: version of AdyenPlugin/AdyenApp

The data that we pass in AdyenPlugin should be the same as for AdyenApp

**Comment by aniav** [comment]
Do we actually want to add anything to the plugin? We're moving towards deprecating it, right?

**Comment by korycins** [comment]
@aniav  Here is link to the internal discussion: https://saleorcommerce.slack.com/archives/C039MGJKKHN/p1693981546040109

It looks like a business decision if we want to extend it also for plugin. As Adyen can use it to discover the request that comes from specific partner.

**Comment by witoszekdev** [comment]
This was already added to Adyen App integration, I think we can close this ticket since Adyen plugin is marked as deprecated: https://docs.saleor.io/docs/3.x/developer/app-store/legacy-plugins/adyen
