### ISSUE TITLE
Bug: Table django_prices_openexchangerates_conversionrate is not dropped in migrations

### ISSUE THREAD

**Issue by cmiacz** [saleor/saleor#13896]
### What are you trying to achieve?

Clean up database schema of Saleor environments upgrated to v3.15 from older versions.

https://github.com/saleor/saleor/pull/13175 drops `django_prices_openexchangerates` from installed apps.
Django has no build-in mechanism for dropping unexpected tables.

Please introduce addition migration that cleans DB schema.

Unexpected table in schema breaks database replicaion tools

### Steps to reproduce the problem

1. Setup Saleor v3.14 envrionment
2. Update to v3.15 and run migrations
3. List all DB tables, `django_prices_openexchangerates_conversionrate` is still present

**Comment by maarcingebala** [comment]
More tables that should be dropped:
- `django_prices_vatlayer_ratetypes`
- `django_prices_vatlayer_vat`

These are left after removing Vatlayer package: https://github.com/saleor/saleor/pull/13179
