### ISSUE TITLE
Bug: Add USE_X_FORWARDED_HOST = True to prevent graphql playground from qurying to localhost behind a proxy

### ISSUE THREAD

**Issue by Youssefbenhammouda** [saleor/saleor#13919]
### What are you trying to achieve?

WHen setting the Saloer core docker image with the appropriate environment variable and changing the app domain using the mutation, the graphql playground still queries localhost:8000.

I fixed that by setting: USE_X_FORWARDED_HOST = True.

Please include it in the setting.py

### Steps to reproduce the problem

1- Set a reverse proxy in nginx pointing to localhost:8000 with the appropriate headers.
-2 Graphql playground will still query localhost:8000 even when accessing with a domain

### What did you expect to happen?

The graphql playground must query to the domain name used to access it

### Environment

Saleor version: …
OS and version: …

**Comment by aniav** [comment]
This has been fixed in https://github.com/saleor/saleor/pull/16811
