### ISSUE TITLE
Bug: 'NoneType' object has no attribute 'strip' when using sort order by `RANK`

### ISSUE THREAD

**Issue by kadewu** [saleor/saleor#13918]
### What are you trying to achieve?

Trying to query products with `null` type search and ordering by `RANK`

### Steps to reproduce the problem

1. Execute query:
```graphql
query(search: $search){
   products(first: 5, filter: {search: $search}, sortBy: {field: RANK, direction: DESC}, channel: "default-channel") {
        edges {
          node {
            name
            slug
          }
        }
      }
```
Without providing variables

2. Backend fails unexpectedly

### What did you expect to happen?

To get error message that sorting by RANK is available only when using a search filter or search argument.

The same happens for: `orders` query.

### Environment

Saleor version: 3.14+
OS and version: …

**Comment by patrys** [comment]
Are you sure those examples are correct? `None` is not valid GraphQL.

**Comment by kadewu** [comment]
> Are you sure those examples are correct? `None` is not valid GraphQL.

Yes you are right, fixed the query to reproducible one.
