### ISSUE TITLE
Bug: Invalid default taxed value for calculate_checkout_line_unit_price in manager

### ISSUE THREAD

**Issue by jakubkuc** [saleor/saleor#13920]
### What are you trying to achieve?

In `calculate_checkout_line_unit_price` in manager.py the `default_taxed_value ` is invalid. 
It is set to: 
`net = <discounted unit price>` and `gross= <undiscounted_unit_price>` 
That problem occurs only when there are discounts on checkout, there are no plugins configured, or (e.g for avatax) when `charge_taxes` is set to False cause then, the default value is returned.

### Steps to reproduce the problem

1. Create checkout with discounts and products with quantity greater than one
2. Configure avatax plugin with charge_taxes as False
3. Fetch Checkout line unit price - it will be invalid 

### What did you expect to happen?

Price should be valid and the same for net and gross (since the taxes should not be charged)

### Environment

Saleor version: 3.14
OS and version: …

**Comment by maarcingebala** [comment]
Closing this for now, as we need to still confirm whether this problem is affecting anyone. We'll reopen if it's confirmed.
