### ISSUE TITLE
Add "canonical" app ID (manifest.id) to App object

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#13938]
## Problem

App object contains database ID, but it doesn't store ID declared by the app itself (manifest.id).

This "canonical" id should be added to the App object, so apps can rely on this field. At the moment database ID is randomly generated per installation.

Existing workaround is to rely on mutable app name.

---

## 1. General Assumptions

Add ID from installation manifest to App object

Field name to be established

### Acceptance Criteria

- [ ]
- [ ]

### Mutations

```graphql

```

### Types

```graphql
type App implements Node, ObjectWithMetadata {
  canonicalId: String // add this
  id: ID!
  privateMetadata: [MetadataItem!]!
  privateMetafield(key: String!): String
  privateMetafields(keys: [String!]): Metadata
  metadata: [MetadataItem!]!
  metafield(key: String!): String
  metafields(keys: [String!]): Metadata
  permissions: [Permission!]
  created: DateTime
  isActive: Boolean
  name: String
  type: AppTypeEnum
  tokens: [AppToken!]
  webhooks: [Webhook!]
  aboutApp: String
  dataPrivacy: String @deprecated
  dataPrivacyUrl: String
  homepageUrl: String
  supportUrl: String
  configurationUrl: String @deprecated
  appUrl: String
  manifestUrl: String
  version: String
  accessToken: String
  author: String
  extensions: [AppExtension!]!
  brand: AppBrand
}
```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by witoszekdev** [comment]
Saleor should additionally reject any installation of apps with the same ids (now it's possible, because the id is randomly generated)
