### ISSUE TITLE
Bug: wrong logic ?

### ISSUE THREAD

**Issue by leminhson2398** [saleor/saleor#13982]
### What are you trying to achieve?

Please take a look at this line:
https://github.com/saleor/saleor/blob/8c8d9db54d63d747bc5ec32807cb94361a952fe9/saleor/graphql/order/mutations/order_update.py#L97C36-L97C36

### Steps to reproduce the problem

main branch

### What did you expect to happen?

I think we are doing the wrong way.
The code should be like below instead:
```python
if user_email := cleaned_input["user_email"]:
       user = User.objects.filter(email=user_email).first()
       instance.user = user
```

otherwise, the provided `user_email` is of no use.
mr. @patrys 

### Environment

Saleor version: main branch
OS and version: any

**Comment by maarcingebala** [comment]
Hi @leminhson2398, in the `save` method of the mutation, the instance is already updated with cleaned data from the input, so there is no need to use the `cleand_input` dict at this step.
