### ISSUE TITLE
Bug: MENU and MENU_ITEM webhooks do not fire

### ISSUE THREAD

**Issue by khalibloo** [saleor/saleor#13983]
### What are you trying to achieve?

I've registered an external app in Saleor, trying to listen for the `MENU_*` and `MENU_ITEM_*` webhook events. Here is one of the webhook queries. The others are fairly similar.
```gql
subscription MenuUpdated {
  event {
    ... on MenuUpdated {
      menu {
        id
      }
    }
  }
}
```

This is the webhook entry in my manifest.
```json
{
      "isActive": true,
      "name": "MENU_CREATED webhook",
      "targetUrl": "http://host.docker.internal:8600/saleor/webhooks/menu-created",
      "asyncEvents": [
        "MENU_CREATED"
      ],
      "query": "\n    subscription MenuCreated {\n  event {\n    ... on MenuCreated {\n      menu {\n        id\n        slug\n      }\n    }\n  }\n}\n    "
    },
```

### Steps to reproduce the problem

1. Register an external app with a MENU_CREATED webhook
2. Create a new menu in the admin dashboard

### What did you expect to happen?

The webhook should have fired and made a request to my application.

Curiously, if I manually register the same webhook from Configuration > Webhooks & Events, then the webhook fires when I create/update/delete a menu or menu item.

### Environment

Saleor version: 3.15.4 (running from saleor-platform in docker with no modification)
OS and version: Windows 10

**Comment by lkostrowski** [comment]
Can you try with a permission `MANAGE_MENUS`?

https://docs.saleor.io/docs/3.x/api-reference/users/enums/permission-enum#code-style-fontweight-normal-permissionenumbmanage_menusbcode

**Comment by khalibloo** [comment]
Goodness, that actually worked. I figured if it was a permission issue, I'd have got an error of some kind in the logs or during the webhook registration. Thanks a lot.

**Comment by lkostrowski** [comment]
> Goodness, that actually worked. I figured if it was a permission issue, I'd have got an error of some kind in the logs or during the webhook registration. Thanks a lot.

We are aware of this problem. In the future we want to get rid of explicit permissions and infer them from subscription queries and event types.
