### ISSUE TITLE
Investigate why PostgresSQL planner did not choose index during query

### ISSUE THREAD

**Issue by aniav** [saleor/saleor#13996]
Planner did not choose index during query as it would take longer to do it with index.
https://saleorcommerce.slack.com/archives/C039MGJDWU8/p1686734768009849?thread_ts=1685724759.578499&cid=C039MGJDWU8

Currently no action is needed

**Comment by maarcingebala** [comment]
Once this is investigated and fixed, we should also add a memory usage test to our test suite to prevent regression.

**Comment by maarcingebala** [comment]
To be revisited after Postgres version upgrade is done.

**Comment by maarcingebala** [comment]
Related trace: https://app.datadoghq.com/apm/trace/9592556471211187893

**Comment by tomaszszymanski129** [comment]
The product filtering was optimized in one of IR-s. We are at a point where it should not kill us, however we still need to think of something faster like search engine. In context of Christmas traffic, we should survive.

**Comment by maarcingebala** [comment]
Closing as it's solved for now, if there are any other issues related to that, we will open separate tickets.
