### ISSUE TITLE
[RFC] Apps protected from deletion

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#13990]
## Problem

Saleor is moving towards replacing plugins with Apps. 

Some plugins are very critical to use Saleor itself:
- Admin emails (critical to reset password etc)
- OpenID / auth

And also some future integrations, like integration dashboard with infra or Saleor Cloud

Migration of these plugins to apps is possible, but it will introduce a footgun - app can be uninstalled and recovery will be very difficult.

That is why I'd like to propose "un-uninstallable apps" (naming things are hard)

---

## 1. General Assumptions

1. Apps can be installed both by user and by a script, e.g. Saleor Cloud can pre-install Saleor Cloud app or some on-premise Saleor can install emails service that will connect some SMTP server
2. App object will have a new field `canBeDeleted: boolean`
3. Mutation `appDelete` will not work if `canBeDeleted` is `true`.
4. IDs of apps that can't be deleted will be provided in env variable `APPS_PROTECTED_FROM_DELETION=saleor.app.admin-emails,saleor.app.openid`

### Mutations

```graphql

```

### Types

```graphql
App {
  # Rest of the App object...
  canBeDeleted: Boolean!
}
```

## 3. Database changes

Apps will be migrated to have `canBeDeleted` `True` value

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by kadewu** [comment]
- I think we should decide how changing env `APPS_PROTECTED_FROM_DELETION` will impact apps, e.g. will removing app from that env, change `canBeDeleted` of that `App` to `True`?
- Maybe database field is not needed if we are going to store information in `env var`

**Comment by krzysztofzuraw** [comment]
* Can third-party apps be deletable?
* Releasing new version of not deletable app - new version will be overridden by cloud install script? or it should be first removed in order to install new version?

**Comment by lkostrowski** [comment]
>I think we should decide how changing env APPS_PROTECTED_FROM_DELETION will impact apps, e.g. will removing app from that env, change canBeDeleted of that App to True?

I think this is reasonable approach. So we can treat env as a database field. 
We can also model this 100% in the database but we need some kind of protection from being removed by the user

>Maybe database field is not needed if we are going to store information in env var

Good point

>Can third-party apps be deletable?

All apps can be deleted. There is a little confusion we need to consider:
- In the API we have LOCAL and THIRD PARTY apps ( [docs](https://docs.saleor.io/docs/3.x/api-reference/apps/enums/app-type-enum)). Apps with manifests are THIRD PARTY
- On the business layer we have something like "Saleor app" or "official saleor app" or "1st party app" which are also instances of THIRDPARTY. 

But this should not be our concern here

>Releasing new version of not deletable app - new version will be overridden by cloud install script? or it should be first removed in order to install new version?

Apps are updating themselves so there is no need for a script. We still need to write some APIs around updating for major changes (e.g. how app can add itself new permissions etc), but I don't think update flow changes that it can't be uninstalled.

**Comment by lkostrowski** [comment]
https://linear.app/saleor/issue/IFREQ-22/api-for-pre-installed-apps
