### ISSUE TITLE
[RFC][Draft] Static, readonly global metadata / object

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#14029]
## Problem

All Saleor entities are driven by graphQL, so a "build time" configuration must be performed in the runtime - and also can be broken (be deleting/updating).

There are some cases of metadata that Saleor should expose to help integrating it with other parties.

One example is "public environment". Its common in software services that there are different envs like production, staging, test etc.

For Saleor, especially Saleor Cloud, there is no way to tell for sure which env is used (other than guessing the domain).

One use case is a field `PUBLIC_ENV` that can be empty by default, but e.g. Saleor Cloud can set there `SALEOR_CLOUD_PROD` or `SALEOR_CLOUD_SANDBOX`. This field can be used by Apps to read it and help to integrate, but mapping tokens/keys to sandbox/prod automatically for users. This field shouldn't be changed - should be set via some kind of env variable, json etc.

Another example is Dashboard. It consumes `IS_CLOUD` env. Its not elegant solution. It doesn't say what is the consequence of this env and also open source project has a tight coupling to its infra context.

Instead Dashboard can read this field and extend based on exact fields

---

## 1. General Assumptions

Some sort of solution to statically set values or dictionary that will be exposed via graphQL.

### Idea 1 - extend Shop object

Some field could be statically mapped to Shop object or null if not set

### Idea 2 - a new custom "global" object 

Instead of making Shop a god object, create some dedicated "Global" context

### Idea 3 - drop graphQL, expose some json file 

Saleor can just serve static file with json

### Open Questions 

- Should we allow untyped dictionary without schema, or define exact fields and add more in the future?
- What are use cases other than PUBLIC_ENV?
- Should we use Shop / Global object / static json / something else?
- What is relation to feature flags?

### Acceptance Criteria

- [ ]
- [ ]

### Mutations

```graphql

```

### Types

```graphql

```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by cmiacz** [comment]
In Cloud environments we can use these global metadata to expose an environment type (sandbox or prod) or request rate limit for Dashbaord users. 

Globala metadata should be configurable by env varialbles and if apps or other integrations are about to relay on that, we should not allow dashbaord users to change this data.

I think we need a way to determine if the data is exposed publicly (like schemaVersion in Shop query) e.g env type or availalbel only for staff users  (like detailed `version` in Shop query) e.g. rate limit.

**Comment by lkostrowski** [comment]
> In Cloud environments we can use these global metadata to expose an environment type (sandbox or prod) or request rate limit for Dashbaord users.
> 
> Globala metadata should be configurable by env varialbles and if apps or other integrations are about to relay on that, we should not allow dashbaord users to change this data.
> 
> I think we need a way to determine if the data is exposed publicly (like schemaVersion in Shop query) e.g env type or availalbel only for staff users (like detailed `version` in Shop query) e.g. rate limit.

Good examples. Instead of relying on docs only, Saleor can expose its settings. Rate limiting is a good one. Another one can be URL to JWKS

Good question is about privacy. Do we want to have "all protected", "all public" or "mixed"?
