### ISSUE TITLE
Add filter and sorting options to me.orders

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#14078]
## Problem

Display a page with all not delivered orders (aka pending orders page) orders to user. It requires using a backend token to fetch orders via admin API, instead of doing it via front end.

### Acceptance Criteria

- [ ] `me.orders` should allow for the same filtering and sorting as [`orders`](https://docs.saleor.io/docs/3.x/api-reference/orders/queries/orders) query

### Mutations

```graphql

```

### Types

```graphql

```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by maarcingebala** [comment]
More context in [thread](https://saleorcommerce.slack.com/archives/C0373831YBC/p1698067094099679).

**Comment by aniav** [comment]
Closing in favour of #14563
