### ISSUE TITLE
Test performance with large datasets

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#14087]
Test the Saleor's performance with a large database and traffic load:
- Propose which fields of a production database need to be anonymized to remove PII.
- Use [Snaplet](https://www.snaplet.dev/) for data anonymization.
- Build a script to take a production-like database and anonymize it for local testing.

**Comment by fowczarek** [comment]
We have storage for such dumps.  
https://drive.google.com/drive/folders/0ALBmAPHj2iSWUk9PVA
Part of this ticker should be uploading the prepared dataset to this drive.

**Comment by NyanKiyoshi** [comment]
> Use [Snaplet](https://www.snaplet.dev/) for data anonymization.

There is also https://postgres.ai/ that could be potentially used

**Comment by maarcingebala** [comment]
Closing for now, a script using Snaplet was created in [this repo](https://github.com/saleor/toolbox/tree/main/anonymize_db) and can be used locally. As a separate action we should figure out a way to include testing with large DBs in our workflows, infra etc.
