### ISSUE TITLE
Inspect database performance with a database profiler

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#14086]
Use a DB profiler against our databases to see if there are any performance issues we didn't know about before, e.g. find out if there are any missing indexes.

**Comment by aniav** [comment]
Don't forget to look into: https://saleorcommerce.slack.com/archives/C039MGJDWU8/p1695821433907429

**Comment by maarcingebala** [comment]
Closing the issue, as DB profiler was added and is actively used to monitor and inspect DB performance (also for the problem linked above - IR-127).
