### ISSUE TITLE
Avoid redirects when fetching images

### ISSUE THREAD

**Issue by khalibloo** [saleor/saleor#14081]
## Problem

Loading thumbnails from the URLs provided in the graphql API requires a redirection before we reach the actual image URL. This hurts the UI performance a lot. As an example, my Saleor instance takes ~200-300ms to redirect but my cloudfront only takes ~40-50ms to serve the image itself.

---

## API changes

Image URLs in graphql should point directly to image source.

**Comment by patrys** [comment]
The redirect only happens when the thumbnail is not present and must be generated. All future API calls return a direct link to the media file.

**Comment by khalibloo** [comment]
Ah that makes sense, thanks. In that case, for my use case, I can get around this by updating my BFF's data on the THUMBNAIL_CREATED event.
