### ISSUE TITLE
Speed up CI workflows

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#14096]
Currently, the [pytest](https://github.com/saleor/saleor/blob/main/.github/workflows/pytest.yml) workflow takes 30 to 40 mins to execute. We should look into possible optimizations of that workflow and speed it up. There are different areas to investigate:
- Pytest is taking too long but may be difficult to optimize quickly, as it may require tests/fixtures refactoring. We should see if we can reuse the database between different runs or not run all migrations with each PR.
- Check if backend packages are cached properly; now each PR installs all dependencies on its own.
- Introduce a flag (label) to speed up CI for critical PRs (e.g. if some steps could be omitted).

**Comment by korycins** [comment]
We could also investigate the possibility of introducing the cache for pre-commit. 
![image](https://github.com/saleor/saleor/assets/23282005/00db98f4-da0b-4bd5-800c-50faa61a0ad7)
It looks like, we're always installing the packages. 

Also we could consider squashing the migrations. It should reduce a few minutes of preparing to test run:
https://docs.djangoproject.com/en/4.2/topics/migrations/#squashing-migrations

**Comment by maarcingebala** [comment]
Multiple tasks around CI improvements are tracked in Python Guild Linear, so closing this.
