### ISSUE TITLE
Bug: Possibility to run mutation checkoutLinesAdd on checkout that have assigned user to it.

### ISSUE THREAD

**Issue by DamianCzajkowski** [saleor/saleor#14104]
### What are you trying to achieve?

I'm trying to add a checkoutLine as an unregistered user to the checkout that has already been assigned a user. 
Currently I'm not getting any errors executing this mutation and I can access some checkout data executing this mutation. On the getCheckout query, I can't access this checkout for a comparison.,

### Steps to reproduce the problem

1. Create checkout with the assigned user to it
2. Try to add checkout lines using the `checkoutLinesAdd` mutation without any authorization.
3. You will get the checkout data easily without any permissions

### What did you expect to happen?

I expect that some error should be raised that this checkout doesn't exist.

### Environment

dashboard v3.14.12 core v3.14.18

**Comment by maarcingebala** [comment]
We want to change it so that users can query and modify checkouts as long as they know the ID, see: https://github.com/saleor/saleor/issues/13454

**Comment by maarcingebala** [comment]
Closing in favor of #13454.
