### ISSUE TITLE
Bug: Channel countries are not localized

### ISSUE THREAD

**Issue by piotrgrundas** [saleor/saleor#14114]
### What are you trying to achieve?

I would like to retrieve the list of supported countries for a channel for the shipping address form. Using `channel.countries` I am able to retrieve them, but names are not localized. 
Whereas retrieving all of the countries using `shop.countries`  gives me the ability to localize returned names.
<img width="598" alt="image" src="https://github.com/saleor/saleor/assets/5078402/d46bbd95-b783-45c9-ba9d-7a87ce775fbe">
<img width="593" alt="image" src="https://github.com/saleor/saleor/assets/5078402/a3a830ae-0701-4a0e-a4f0-5485ce8a983d">
<img width="1118" alt="image" src="https://github.com/saleor/saleor/assets/5078402/6c1923e7-3d33-46d1-8e63-7e5cf8e26b07">

### Steps to reproduce the problem

1. Query for `channel.countries`
2. There is no option to localize the `CountryDisplay` type.

### What did you expect to happen?

`channel.countries` should accept a `languageCode: LanguageCodeEnum` argument which allows to retrieve localized country names.

### Environment

core v3.14.19

**Comment by piotrgrundas** [comment]
For any1 interested. 
I found an alternative using [purely JS](https://bobbyhadz.com/blog/javascript-get-country-name-from-country-code)

**Comment by maarcingebala** [comment]
I'll close the ticket since we won't be introducing this change.
