### ISSUE TITLE
Bug: Saleor does not load product images

### ISSUE THREAD

**Issue by feliperosenek** [saleor/saleor#14169]
### What are you trying to achieve?

When installing Saleor via Docker on Ubuntu 20 it does not load product images.
The only changes made were to the docker-compose.yml file

  - DASHBOARD_URL=http://216.238.116.173:9000/
  -ALLOWED_HOSTS=localhost,api,216.238.116.173
 - MEDIA_URL=http://216.238.116.173:8000/media/
 
   dashboard:
     environment:
       - API_URL=http://216.238.116.173:8000/graphql/

Even making changes to the Dashboard URL, the images still have "localhost:8000".

![image](https://github.com/saleor/saleor-platform/assets/5494788/3d45e918-bc7f-4c88-b6dd-caf2adc03a44)
![image](https://github.com/saleor/saleor-platform/assets/5494788/3f8cebc0-8849-4428-b7ef-7d3f51c1feff)

When you click on get image link, it looks like this http://localhost:8000/thumbnail/UHJvZHVjdE1lZGlhOjM4/4096/.

![image](https://github.com/saleor/saleor-platform/assets/5494788/3c8fd2d6-c770-4a49-b255-2ab9713d4248)
When I open the link in the browser and replace localhost with my IP, the image loads, and when I return to Saleor, it is there.
![image](https://github.com/saleor/saleor-platform/assets/5494788/0b04e26c-d0ac-43a1-b89a-b7dbd79e9eb6)

Only when opening the image link on another page and changing localhost to the IP does the image load, when I go back to Saleor and reload it, the image appears.

Could it be some kind of cache error?

### Steps to reproduce the problem

Normal installation via docker

### What did you expect to happen?

Being able to load images using my server's IP address

### Environment

Saleor version: latest
OS and version: Ubuntu 20

**Comment by jonathan-franzen** [comment]
I remember I had some issue like this when I did my own docker deployment... I'm not sure if this helps you or not, but I think you need to update your SITE_DOMAIN in the DB if you have not.

Go to the graphql playground and first

Generate Auth Token:
```
mutation {
  tokenCreate(email: "hello@example.com", password: "password") {
    token
    refreshToken
    errors {
      field
      message
    }
  }
}
```

And then update your SITE Domain

Update Domain:
```
mutation UpdateDomain {
  shopDomainUpdate(input: {domain: "api.mysite.com"}) {
    shop {
      domain {
        url
      }
    }
  }
}
{
  "Authorization-Bearer": "ADMIN_TOKEN_HERE"
}
```

**Comment by feliperosenek** [comment]
Yes, this solved my problem, thank you very much friend!!!
