### ISSUE TITLE
orderGrantRefundCreate should be clear about already refunded lines

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#14188]
### What are you trying to achieve?

I want to improve experience with granted refunds

At the moment mutation `orderGrantRefundCreate` allows attaching line. 
Called 2nd time with the same line ID, it will error with 

```
 {
          "message": "Provided input for lines is invalid.",
          "field": "lines"
        }
```

I belive the reason is conflict - this line was already refunded.
Error is not clear

(this is assumption of 1 product in order. If multiple products, behavior is the same until grant refunds exceed limit of quantity)

### Steps to reproduce the problem

Create a refund 

```
mutation {
  orderGrantRefundCreate(
    id: "T3JkZXI6ZjdkYTFkY2ItOTVlNS00YjQ1LWJmMzUtNDNmNGVhOGYwMDg2"
    input: {reason: "global reason", lines: [{id: "T3JkZXJMaW5lOjRmMzMwN2UzLTc0ODUtNDdmOS05OTIzLTYzMjIxZmQyOGRhNw==", quantity: 1, reason: "line reason"}]}
  ) {
    errors {
      message
      field
    }
    order {
      errors {
        message
      }
      grantedRefunds {
        reason
        id
        lines {
          id
          reason
          orderLine {
          
            id
          }
        }
      }
    }
  }
}
```

Call it twice

### What did you expect to happen?

I expect message to be clear that line was already granted

### Environment

Saleor version: 3.16.1
OS and version: …

**Comment by korycins** [comment]
@lkostrowski 
These details are already there. The error code that you provided is generic, as you can have different errors for each line. 
The details about line error, can be found in the error field dedicated to specific line. 
```python
{
	"data": {
		"orderGrantRefundCreate": {
			"grantedRefund": null,
			"order": null,
			"errors": [
				{
					"field": "lines",
					"code": "INVALID",
					"message": "Provided input for lines is invalid.",
					"lines": [
						{
							"lineId": "T3JkZXJMaW5lOjdlNzg5NzY0LTUyZWMtNDU3Mi05NWNkLTM5ZjQ0OTJmZDk4Z1==",
							"field": "id",
							"message": "Invalid ID: T3JkZXJMaW5lOjdlNzg5NzY0LTUyZWMtNDU3Mi05NWNkLTM5ZjQ0OTJmZDk4Z1==. Expected: OrderLine.",
							"code": "GRAPHQL_ERROR"
						},
						{
							"lineId": "T3JkZXJMaW5lOjdlNzg5NzY0LTUyZWMtNDU3Mi05NWNkLTM5ZjQ0OTJmZDk4ZA==",
							"field": "quantity",
							"message": "Cannot grant refund for more than the available quantity of the line (4).",
							"code": "QUANTITY_GREATER_THAN_AVAILABLE"
						}
					]
				}
			]
		}
	},
	"extensions": {
		"cost": {
			"requestedQueryCost": 0,
			"maximumAvailable": 50000
		}
	}
}
```

**Comment by lkostrowski** [comment]
Thanks. I'd expect that root error will be more self-explaining, I was not aware about nested errors.
