### ISSUE TITLE
Order transaction is unclear

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#14185]
### What are you trying to achieve?

1. Manual transaction with a message created two "events" - success and info, that contains only message. Technically its one event. "Capture" type can be enriched with additional message
2. "Info" from previous point is visible as order event, but capture event is not. This event doesn't have any context (like message "Manual transaction captured with message: asdf")
3. API doesn't respond with capture event and custom message event doesn't contain amount of money

![Zrzut ekranu 2023-10-5 o 11 17 59](https://github.com/saleor/saleor/assets/9268745/19878cfa-5c84-4c2c-adbb-7fcfe7848a75)
![Zrzut ekranu 2023-10-5 o 11 18 02](https://github.com/saleor/saleor/assets/9268745/fd2dc10c-9b64-4c3e-a398-8e0ca9f684f8)
![Zrzut ekranu 2023-10-5 o 11 18 09](https://github.com/saleor/saleor/assets/9268745/14b34d60-0719-452c-aa2e-1243787115c9)

### Steps to reproduce the problem

1. Use transaction payments in channel
2. Create order
3. Capture a transaction for full amount

### What did you expect to happen?

I expect clear information about transactions, mainly merged events into single one

### Environment

Saleor version: 3.16.1

**Comment by korycins** [comment]
@lkostrowski  Dashboard uses `transactionCreate` to create manual transactions. 
The mutation has multiple fields for amounts: `authorized`, `charged`, `refunded` and `canceled`.  Ref:https://docs.saleor.io/docs/3.x/api-reference/payments/inputs/transaction-create-input
If you provide any of these amounts (you can also provide all of them), Saleor will create a separate TransactionEvent for each. To keep the correct flow of recalculation process: Ref https://docs.saleor.io/docs/3.x/developer/payments#event-types-explanation

Saleor creates a separate `info` event when fields from https://docs.saleor.io/docs/3.x/api-reference/payments/inputs/transaction-event-input are provided. We didn't want to propagate a psp-reference from the input to events, as it could have an impact on re-calculations (we rely on matching the events based on the `pspReference`).
 This is why we decided to keep a separate event: INFO, which can contain the details, that don't have an impact on amounts. (We didn't propagate `message`, as it could look strange, when you would have 4 amount events, with the same message). 
 
 I believe that these events should be better represented on dashboard side (for example, having amount field there, doesn't make sense).

Also. There is mutation: `OrderMarkAsPaid` which creates the `Payment` or `TransactionItem`(depends on channel settings: ref https://docs.saleor.io/docs/3.x/api-reference/miscellaneous/objects/payment-settings#code-style-fontweight-normal-paymentsettingsbdefaulttransactionflowstrategybcodetransactionflowstrategyenum--) to mark if order is paid. 
 
![image](https://github.com/saleor/saleor/assets/23282005/f2651592-966b-440b-a2c8-4b66f7186642)

Created the task on dashboard side for using `orderMarkAsPaid` - https://github.com/saleor/saleor-dashboard/issues/4421

**Comment by lkostrowski** [comment]
Maybe we can somehow nest INFO within parent even. Agree that this can look better on the frontend side. cc @andrzejewsky

**Comment by korycins** [comment]
Closing, as I believe this should be resolved on the dashboard side. The `INFO` event is created only when you provide the `TransactionEventInput`.  Additionally, dashboard should use a dedicated mutation for marking as paid. 
@lkostrowski If you don't agree, please re-open the issue.

**Comment by lkostrowski** [comment]
@korycins I am reopening and assigning myself for future refinement
