### ISSUE TITLE
Accept `automatic_payment_methods` in Stripe plugin.

### ISSUE THREAD

**Issue by piotrgrundas** [saleor/saleor#14268]
## Problem

While playing with Stripe and the old checkout flow, I found that using the Stripe plugin, we cannot utilize Stripe's cool feature, which automatically serves enabled payment methods from the Stripe dashboard via [PaymentElement](https://stripe.com/docs/payments/payment-element).

The issue is that Saleor ignores the payment intent [automatic_payment_methods](https://stripe.com/docs/api/payment_intents/create#create_payment_intent-automatic_payment_methods) passed via checkoutComplete
https://github.com/saleor/saleor/blob/main/saleor/payment/gateways/stripe/plugin.py#L228

I know we are moving towards apps, but this could be greatly beneficial for people who are still using the old checkout flow, and I think that the change needed should be marginal - consuming extra param `automatic_payment_methods` upon intent creation.

```
mutation CheckoutComplete {
  checkoutComplete(
    id: "Q2hlY2tvdXQ6OGJmZGVkNjUtY2UyYy00MDA3LTgyMjMtYzJjYWJlMjRjZGZm"
    paymentData: "{\"automatic_payment_methods\": {\"enabled\": true, \"allow_redirects\":\"always\"}}"
  ) {
    confirmationNeeded
    confirmationData
    order {
      id
    }
    errors {
      field
      message
    }
  }
}
```

**Comment by maarcingebala** [comment]
It seems that the Stripe App already supports it [here](https://github.com/saleor/example-nextjs-stripe/blob/de4668053c8ebb5f31ce41d9319d41c39cd32281/src/app/app-router/cart/page.tsx#L27). I would recommend switching to apps as the plugin is unlikely to be developed anymore.
