### ISSUE TITLE
Bug: Incorrect `order.paymentStatus` when used with granted refund + refunded transactions

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#14278]
### What are you trying to achieve?

I'm marking the fulfillment as returned and creating a granted refund to refund customer. After granting refund, I request a refund on a transaction which is successful.

### Steps to reproduce the problem

1. Create new order
2. Mark order as paid (make sure the channel has `orderSettings.markAsPaidStrategy` set to `TRANSACTION_FLOW`)
3. Fulfill the order
4. Now return the fulfilment
5. Grant new refund for order's total
6. Create a manual refund for order's total

### What did you expect to happen?

`paymentStatus` on my order doesn't reflect that it's `NOT_CHARGED` instead of `FULLY_REFUNDED`.

This is also valid if I don't refund the full order total, the status will be `PARTIALLY_CHARGED` instead of `PARTIALLY_REFUNDED`.

### Notes
In Payments (plugin) the fulfillment looked like this:

```json
{
"fulfillments": [
        {
          "id": "RnVsZmlsbG1lbnQ6MTU0",
          "status": "REFUNDED_AND_RETURNED",
          "statusDisplay": "Refunded and returned"
        }
      ]
}
```

We linked refunds with fulfillment and thus it had a different status

In Transactions (app) the fulfillment looks like this:
```json
{
 "fulfillments": [
        {
          "id": "RnVsZmlsbG1lbnQ6MTUz",
          "status": "RETURNED",
          "statusDisplay": "Returned"
        }
      ]
}
```

It doesn't have status `REFUNDED_AND_RETURNED`, because we no longer link fulfillment with a refund, we use GrantedRefund instead.

### Environment

Saleor version: 3.16.7
OS and version: Saleor Cloud

## IMPORTANT

> **Warning**
>
> Fix for this bug should be back ported, staring from Saleor 3.14

**Comment by witoszekdev** [comment]
Probably related: https://github.com/saleor/saleor/issues/12757

**Comment by witoszekdev** [comment]
@korycins We need to discuss this further

**Comment by korycins** [comment]
Closing as I believe this was solved here: https://github.com/saleor/saleor/issues/14462
