### ISSUE TITLE
Add `refundStatus` to Order

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#14279]
## Problem

Currently, there is no way to retrieve information if the Transactions on the order were refunded or not.
`paymentStatus` doesn't respect transactions: https://github.com/saleor/saleor/issues/14278
and we don't have a similar field like `chargeStatus` or `authorizeStatus`

---

## 1. General Assumptions

We add a new field to Order, `refundStatus`

### Acceptance Criteria
- Order has `refundStatus` field, it has a separate enum valus for the following cases:
  -  Each transaction in the order was fully refunded  ( refundStatus  == FULL)
  -  Some transactions in the order were fully or partially refunded ( refundStatus == PARTIAL )
  -  None of the transactions in the order was refunded ( refundStatus == None )

### Types

```graphql
enum OrderRefundStatusEnum {
  NONE
  PARTIAL
  FULL
}

type Order {
  # ...
  refundStatus: OrderRefundStatusEnum
}
```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by witoszekdev** [comment]
@korycins We need to discuss it further

**Comment by korycins** [comment]
We need to take into account situations when we have transactions with amounts bigger than order's total.
For example TR1 with chargedAmount:100, refundedAmount:100, where order.total is 100.  So we have the order which is fully-charged, previously it was overcharged, as chargedAmout was 200. What should be the value for `refundStatus`? 
Do we treat such cases as `PARTIAL` or maybe it is `NONE` as order is fully-charged.

**Comment by witoszekdev** [comment]
Migrated https://linear.app/saleor/issue/IFREQ-41/deprecate-paymentstatus-add-statuses-for-refund-cancel-chargeback
