### ISSUE TITLE
Bug: appDelete can be slow when deleting app with many delivery attempts 

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#14297]
### What are you trying to achieve?

The `appDelete` mutation can be extremely slow when deleting an app that has a few hundred thousand delivery attempts (`EventDeliveryAttempt` model) in DB. E.g. if there are webhooks that are failing and being re-triggered for a long time, it might generate such an amount of events. These events are stored for a certain amount of time (see `EVENT_PAYLOAD_DELETE_PERIOD`) and cleaned up by a Celery task, but even with this, it's possible to accumulate a huge amount of events.

When `appDelete` is run, it does a cascading delete of its webhooks, their payloads, event deliveries and attempts. If there are huge amounts of these, the appDelete can slow down to over 30 seconds due to trying to remove these rows at once.

### Steps to reproduce the problem

This might be difficult to reproduce without preparing some data on a local machine. E.g.: 
1. Create an app and a webhook.
2. Generate a few hundred thousand event deliveries and attempts.
3. Try to delete the app and monitor the execution time of SQL queries that are run underneath.

### What did you expect to happen?

There are a few ways to approach this.

1. Look into rewriting the cascading delete into a solution when deliveries are scheduled for deletion in a Celery task.
2. ~~We should also look into providing a circuit breaker solution that would disable a webhook that is not responding, thus creating multiple failed/pending delivery events that are stored in DB. (success events are removed instantly).~~ [Issue#14298](https://github.com/saleor/saleor/issues/14298)

### Logs

See Sentry logs: https://saleor.sentry.io/issues/4543088602/events/edd8b7f4777f4e68a8840854e6adb6a9/

### Environment

Saleor version: 3.15

**Comment by fowczarek** [comment]
2nd point of "What did you expect to happen?" should be done in separate PR.
[Issue#14298](https://github.com/saleor/saleor/issues/14298)

**Comment by fowczarek** [comment]
Consider using `_raw_delete` in this case.

**Comment by maarcingebala** [comment]
Fixed in https://github.com/saleor/saleor/pull/14536 for 3.14, will be ported to other versions as well.

**Comment by maarcingebala** [comment]
@Air-t Will handle porting to versions from 3.14 to the newest.
