### ISSUE TITLE
Circuit breaker for webhooks that are not responsing

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#14298]
Add a circuit breaker pattern to webhooks to disable them when they're not responding for some time. Currently, if a webhook is not responding, or responding with 4xx errors, Saleor will be trying to deliver it as new events happen. in such a case, we could disable the webhook and notify the user, so they have to reenable it when the webhook is fixed on the app side.
```[tasklist]
### Tasks
- [ ] https://github.com/saleor/saleor/issues/14559
- [ ] https://github.com/saleor/saleor/issues/14561
```

**Comment by lkostrowski** [comment]
@maarcingebala I think we should divide this to smaller pieces so we can quicker implement this and reduce some blockers:
 
I suggest following:

1. Stop retrying anything other than 5xx code. This is "Pareto" rule and should be quick to implement using existing APIs
2. Wait for https://github.com/saleor/apps/issues/51 that will add API to inform the user about app status / events
3. Disable failing webhook and inform user with an event that it happened via https://github.com/saleor/apps/issues/51

Step 2 & 3 are more complex, all apps must be updated to "re-enable" webhooks for them

**Comment by maarcingebala** [comment]
Steps [2](https://github.com/saleor/apps/issues/1087) and [3](https://github.com/saleor/apps/issues/51) can be done separately, but they do not block implementing circuit breaker in core, so I'm removing them as subtasks from this ticket.

**Comment by maarcingebala** [comment]
Already in progress here: https://github.com/saleor/saleor/pull/16658
