### ISSUE TITLE
Allow filtering orders that are expired

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#14300]
## Problem

There is no way to filter orders if they have value `OrderStatus.EXIPRED`

---

## 1. General Assumptions

`EXPIRED` should be added to `OrderStatusFilter`

### Types

```graphql
enum OrderStatusFilter {
  # ...
  EXPIRED
}
```

**Comment by korycins** [comment]
For draft orders we have a separate query: `draftOrders`. The `orders` query doesn't return the draft orders. So maybe we should have the same query for `expiredOrders`?

**Comment by witoszekdev** [comment]
Migrated https://linear.app/saleor/issue/SHOPX-1765/add-filter-for-expired-orders
