### ISSUE TITLE
Bug: Empty `amount` in cancel/charge/refund sync webhook request

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#14337]
# Describe the problem

When customer triggers a refund request without providing an amount, Saleor allows it as valid input and doesn't set any value in webhook payload.

Github issue: [https://github.com/saleor/saleor/issues/14337](https://github.com/saleor/saleor/issues/14337)

# Describe possible solutions

* Make field `amount` required for `CHARGE` and `REFUND` transaction actions in `transactionRequestAction` mutation
* *or* Calculate amount sent to the app in webhook: use "full" amount that we know from history
  * for REFUND: Use `TransactionItem.chargedAmount`
  * for CHARGE: Use `TransactionItem.authorizedAmount`

# What is the impact

- [ ] Is customer/buyer affected? *(If not or not sure, please elaborate)*

Payment apps have to do workarounds to handle requests with missing amounts, that are possible through Saleor's API.

For example: Adyen app fetches TransactionItem events history to determine which amount should be used. This is not ideal, becasue we might introduce differences in behavior between apps, which would add non-deterministic behavior for actions in Saleor.

Handling this correctly on payment app side, requires making additional requests, which in turn add a risk of timeouts to sync webhooks.

### Does it affect one of critical areas?

- [ ] Data privacy of customers
- [ ] Security
- [ ] Data integration

If yes, immediately raise this issue and escalate

### Is there a viable workaround?

Calculating amounts on app side, which is problematic

# What must be done after this issue is delivered

Update implementation in Adyen app to not calculate amounts on its own, always use Saleor amounts. 

# What is the cost of not doing this?

* Possibility of timeouts in sync webhooks - e.g. when requesting refund, charge, cancel
* Unexpected behavior for Saleor users - each app could treat missing amount differently

# Definition of Done

Once the issue is being worked on, we define it as *done* when all below are met:

- [ ] Change is merged and available on production
  - [ ] Core: Backports are merged
  - [ ] Core: Staging is released
- [ ] Unit tests pass and new functionality is tested
- [ ] E2E/integrations tests pass, new tests added if needed (contact QA/PO)
- [ ] Metrics, logs are added, Datadog monitors and dashboards are set
- [ ] Docs are updated
- [ ] Changelogs are added
- [ ] Linters and static analysis pass
- [ ] Relevant issues, like tech debt proposals, are added to triage
- [ ] Code Review is accepted
- [ ] Feature is manually tested within the team
- [ ] CX team is informed about meaningful changes
- [ ] Migrations work
- [ ] Apps: Works in supported Saleor versions

**Comment by witoszekdev** [comment]
It could be that this is expected behavior, but in such case we should remove the `amount` field for `TransactionCancelationRequested`, not to cause confusion

**Comment by korycins** [comment]
There was an assumption, that `TransactionCancelationRequested` always cancels the whole transaction's amount, but you're right, we can make it better.
In that case we could always send the `amount` set based on `transaction.authorizedAmount` value. 
Then the `TransactionCancelationRequested .amount` could be converted to the required field. Conversion from optional field to required one should be safe and non-breaking API change.
So DoD for this will be:
- make sure that we always pass `amount` for `TransactionCancelationRequested` webhook. 
- make sure that the legacy payload also provides the `amount` (just for compatibility between approaches)
- make sure, that the `amount` for cancel is the `transaction.authorizedAmount` value.
- convert the `TransactionCancelationRequested.amount` from optional to required.

**Comment by lkostrowski** [comment]
https://linear.app/saleor/issue/SHOPX-110/bug-empty-amount-in-transaction-cancelation-requested-sync-webhook
