### ISSUE TITLE
Bug: Search do not return new created products

### ISSUE THREAD

**Issue by szczecha** [saleor/saleor#14330]
### What are you trying to achieve?

I want to be able to search for products that I added a few minutes ago.

### Steps to reproduce the problem

1. [Create new product ](https://master.staging.saleor.cloud/graphql/#saleor/N4IgjiBcILYK4BcCGCCWB7AdgAgAoCd0ATOAYwQGF8BTFagCgBJVMAHRSPQk8q2hagEk2iAIQBKbMAA6ObK25lKNOvRbsEnZiISSZc7Nmr5C+AM5TZh69gBmqagBsiVm9hjUzZpAHNqrm1JifwNsAF8A+UVyS1DDVBc47FIACyRMTCcAGVQzNEwfC303a1T0zMdYkpszRzgfSJsIpPizXDgAI0dclOpE6uxcgEEANyRURyQu6gAxdHx2-DKzEIGR3NRp4Ry8lkLG8IOx-FR0hCKD+P7qzCQPS+S0jOzc-MKqgcfypw-P7Fr6g9DM0BiC3GDga5mmEQAAaEDoKAgAjEJR8OhwkAjJHFbDSEDqRD4zi4wz4lAIE4dRCeYnYADaAF1YZF8aQ6D55gBPOn4gCKACYZgAGABaAHUiCNSJgANYANgA8kMALwq-Es0Js9CORzUcgYTBmOlMzU2fFETykE6sNBYOmYOC6s3WfG3e5QPEgAR5FE8BAa1kgBSo8gAFS5rH8nvxAFUABIAKRGovjADUAFZEGYAJQArKQAOKx+UAWTDAFF1XCg-gUHs6cKXWSQCt0HTSa6QJazNbULbDbyQIGkvi0Ag9UP8ZEws2vQCGjHhzWtd6kAAPCiTLxTlfmkAAd2oqB8KQDnsduqhshhYSAA)
2. [Run query products](https://master.staging.saleor.cloud/graphql/#saleor/N4IgjiBc4K4KYCcCeACAynAhggxgCwAoASAMwEsEBnAF0hQEkA7agGhSMq1zzrWoTKMA5myIB3PIjh0ACggD2AExg5qAdUkI4TAA4xW7SvIS0UcpSuoB5BIsQBKFMAA6jFCh0LlqygVfv3cipTUgoafwDObHw6Di58CPcJKVjkrUSUIxMAISRYrOoIxxc3AOp5akwAGwBheRhmDLhFIThKJwz3RiU4DtKAgLJFToDGTABbOBH3HC1MambplBgdRXnmgEFC-oCAXwz90sPdkBYQeSgQDGi8U5AAN0uS92cQIPCoFAAmAAYWCNeaSmn2Au3+pVeUW4rzorwWNHM3kKpwBIAKML6A1eigocFUZHkjAxrwAIgBRNA1V7grFvMhwKrDT6kjYAFTJrwixxAuyAA) with created product name in the search 

Result:  product does not appear in search result
<img width="1260" alt="Screenshot 2023-10-17 at 11 49 03" src="https://github.com/saleor/saleor/assets/30683248/e19081e1-196b-4f4c-8ce3-479d01d6e0ea">

but it is visible when querying about all products
<img width="1425" alt="Screenshot 2023-10-17 at 11 49 19" src="https://github.com/saleor/saleor/assets/30683248/19ed46b0-b8e4-4ab2-be4e-bf2b8a312678">

### What did you expect to happen?

Product should be possible to find

### Environment

Saleor version: core v3.18.0-a.0
OS and version: …

**Comment by maarcingebala** [comment]
Search vectors are updated asynchronously via a Celery worker. Is the Celery running on this env where the issue was seen? Also it may take some time (e.g. 20-30 seconds) to wait for the task to start, as it's running periodically with 20s intervals be default.

**Comment by szczecha** [comment]
After 1 hour of the creation issue, the product still does not appear in the search result. I'm testing it on our cloud staging https://master.staging.saleor.cloud/ so celery should work there

**Comment by szczecha** [comment]
I launched Saleor locally. I added 3 products and 1 sale, I don't see that the celery job `saleor.product.tasks.update_products_search_vector_task` started beside the job that started when I first started celery.
[log_celery_18102023.txt](https://github.com/saleor/saleor/files/12999262/log_celery_18102023.txt)

**Comment by szczecha** [comment]
fixed here https://github.com/saleor/saleor-multitenant/issues/976
