### ISSUE TITLE
Add migration to populate voucher_code in BaseDiscount

### ISSUE THREAD

**Issue by michal-macioszczyk** [saleor/saleor#14341]
This is a second part of https://github.com/saleor/saleor/issues/13887

- Add migration to populate voucher_code from existing voucher field in `BaseDiscount` class so we need to update all related models like `OrderDiscount`, `OrderLineDiscount`, `CheckoutLineDiscount`

Part of https://github.com/saleor/saleor/issues/13582

**Comment by IKarbowiak** [comment]
You also need to ensure that the `voucher_code` is properly set each time the `voucher` is assigned on those objects
