### ISSUE TITLE
Add Idempotency Key to Transaction sync webhooks and mutations

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#14358]
## Problem

Transaction webhooks can be triggered by customer / staff member multiple times by accident (e.g. network error, bug in storefront / dashboard, missclick).

We should allow adding a idempotency key in Transaction related mutations and pass an idempotency key in the webhook event so that the app can determine if it should process the request or skip it, because it was called multiple times.

Example of idempotent requests in Stripe API: https://stripe.com/docs/api/idempotent_requests

### What is Idempotency Key?

**Idempotency** in web API design allows the same action to be repeated without changing the outcome. This ensures safe retry of API requests, especially when the first attempt fails due to network issues, offering a mechanism for clients to reconcile failed requests with the server.

An idempotency key, created by the client, serves as a distinctive value enabling the server to identify subsequent retries of the identical request. It should be a UUID or another random string with sufficient entropy to prevent collisions.

Results are only saved when an API endpoint begins executing. If the mutation fails validation or conflict with a concurrent request, no idempotent result is saved. Retrying these requests is safe.

## 1. General Assumptions

We add `idempotencyKey` as a parameter to the following mutations:
- `transactionInitialize`
- `transactionProcess`
- `transactionRequestAction`
- `transactionRequestRefundForGrantedRefund`

We add `idempotencyKey` property to subscription events in following webhooks:
- `TRANSACTION_INITIALIZE_SESSION`
- `TRASANCTION_PROCESS_SESSION`
- `TRANSACTION_CHARGE_REQUESTED`
- `TRANSACTION_REFUND_REQUESTED`
- `TRANSACTION_CANCELATION_REQUESTED`

### Acceptance Criteria

- Mutation changes
	- `idempotencyKey` is added to `transactionInitialize`
	- `idempotencyKey` is added to `transactionProcess`
	- `idempotencyKey` is added to `transactionRequestAction`
	- `idempotencyKey` is added to `transactionRequestRefundForGrantedRefund`
- Webhook changes
	- `idempotencyKey` is added to `TransactionInitializeSession`
	- `idempotencyKey` is added to `TransactionProcessSession`
	- `idempotencyKey` is added to `TransactionChargeRequested`
	- `idempotencyKey` is added to `TransactionRefundRequested`
	- `idempotencyKey` is added to `TransactionCancelationRequested`

### Mutations

```graphql
  """
  Request an action for payment transaction.

  Added in Saleor 3.4.

  Note: this API is currently in Feature Preview and can be subject to changes at later point.

  Requires one of the following permissions: HANDLE_PAYMENTS.
  """
  transactionRequestAction(
	# ...

    """
    Unique key used to de-duplicate requests made to Saleor
    If two identical requests are made, the request is processed only once.

    If not provided, Saleor will generate a random string.
    """
    idempotencyKey: String
  ): TransactionRequestAction @doc(category: "Payments")
```

Analogically, the same parameter is added to the remaining mutations

### Types

```graphql
type TransactionInitializeSession extends Event {
  # ...
  idempotencyKey: String!
}
```

Analogically, it is added to the remaining webhook events

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by lkostrowski** [comment]
Related https://github.com/saleor/saleor/issues/14251

**Comment by witoszekdev** [comment]
Migrated https://linear.app/saleor/issue/IFREQ-45/add-missing-idempotency-keys-to-all-transaction-related-actions
