### ISSUE TITLE
Drop requirement for trailing slash when accessing /graphql/ endpoint

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor#14474]
## Problem

Is there a reason for the mandatory slash in the API address (`example.com/graphql/`)? 

I've seen multiple issues caused by using an address without it, especially when exploring the API or creating an app for the first time.

---

### Acceptance Criteria

- [ ] The API is accessible with, and without trailing slash in the request

### Mutations

```graphql

```

### Types

```graphql

```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by patrys** [comment]
We don't want the same resource to be reachable using different resource locators. It breaks assumptions about HTTP, including how caches should behave. We could switch to requiring no trailing slash, but it would break all existing storefronts and integrations.

Ultimately, I consider the endpoint to be a DSN, a magic string you copy and paste into code. Not something you should ever need to construct programmatically or have an opinion on. It should not matter if it ends with `/graphql/` or a random string of letters and numbers.
