### ISSUE TITLE
Bug: Voucher discount is not included in draft orders for channel with `flat rates` taxes

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#14615]
### What are you trying to achieve?

The voucher discount should be included.

### Steps to reproduce the problem

1. Create draft order for channel with `flat_rates` tax strategy
2. Add voucher
3. Check `total` and `undiscountedTotal` prices

### What did you expect to happen?

The voucher discount should be included.
Probably the solution is to add `_update_order_discounts_and_base_undiscounted_total` at the beginning of `update_order_prices_with_flat_rates` method

### Environment

Saleor version: main

**Comment by zedzior** [comment]
Fix: https://github.com/saleor/saleor/pull/14846
