### ISSUE TITLE
Bug: Multiple apps with the same `identifier` can be installed in Saleor

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#14612]
### What are you trying to achieve?

I am testing multiple instances of a Payment App, each one has the same `id` defined in the manifest.	

### Steps to reproduce the problem

1. Create an app with some `identifier` in the manifest
2. Install 1st instance of the app (e.g. URL: `http://my-app-1.test.com`)
3. Install 2nd instance of the app (e.g. URL: `http://my-app-2.test.com`) note that it has the same `identifier` as the 1st instance

### What did you expect to happen?

I expect the 2nd installation to fail or the 1st app to be removed / disabled in favor of the 2nd app

### Environment

Saleor version: 3.17.3
OS and version: Cloud Sandbox

**Comment by korycins** [comment]
The change should be documented as a breaking change, and delivered in minor version.

In case of installing app with the same identifier second time, we should overwrite the configuration of the existing one, and send the webhook app-installed. 
We don't make DB migration, so if someone already has such case we will leave it as it is. 
The logic responsible for app installation should be changed to overwrite the existing app.

**Comment by aniav** [comment]
This has been addressed in https://github.com/saleor/saleor/pull/16322
