### ISSUE TITLE
Bug: Disabled apps aren't handled when requesting a refund

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#14613]
### What are you trying to achieve?

I want to request a refund for a transaction created by an app that has been disabled. I got a misleading error that suggested there isn't an app that can handle the refund request.

### Steps to reproduce the problem

1. Install a payments app
2. Create a `TransactionItem` on an order that has `createdBy` attached to the payment app and `actions` that includes `[REFUND]`
3. Disable payment app
4. Request refund for the `TransactionItem`

### What did you expect to happen?

I expected a different error message

### Logs

No app or plugin is configured to handle payment action requests.
Error code MISSING_TRANSACTION_ACTION_REQUEST_WEBHOOK

### Environment

Saleor version: 3.17.3
OS and version: Saleor Cloud Sandbox

**Comment by korycins** [comment]
Transaction API is a preview so we can improve the errors that we return.
We should have separate errors like:
- missing-app
- app is misconfigured
- app is disabled

Additionally, we should provide the upgrade-guide with the info, that the previous error will be replaced in a future version. 
In the meantime, the mutations should return the "old" error, and the "new" one. The previous error should be dropped in next released Saleor version - we want to provide a grace period that will allow users to update their implementation

**Comment by witoszekdev** [comment]
https://linear.app/saleor/issue/SHOPX-1752/misleading-error-message-when-requesting-action-when-payment-app-is
