### ISSUE TITLE
Bug: Voucher usage is not updated upon checkoutComplete

### ISSUE THREAD

**Issue by yellowee** [saleor/saleor#14661]
### What are you trying to achieve?

I was trying to test checkout with voucher.

### Steps to reproduce the problem

1. Run `voucherCreate `and `voucherChannelListingUpdate`
2. [Create checkout](http://localhost:8000/graphql/#saleor/N4IgjiBcILYK4BcCGCCWB7AdgAgMICcBTFQ3AC0IGMBrdRACgBJKKa6EBJTAB0Uj1a1EBYgkJdeCAIQBKbMAA6ObCypCEIkvVQ8+2ZoPYTEcxcuzZC+fOnwBneUovPsAM1SEANgBMnL7DCEdnZIAOaEfi6U6N4R5tgAvpEqhoiO8RYAdNnkauzJScqFhUqu+GGBmAjYAAr4qJSE2FjYACpIAB6E3gCyWIQAnukWoTbBw85IMHRVyZRw1oSYlAN+hRaYhNVmLlMzCHMLRMurRX7IHRMWe3Cz8fOLJ2tKJZhlFUvVdTFwlAgAakh6kgqs0cN9vL8AUDUCDtn5UL5lJgpnELHZqHA-GA4HDUAgBgBBABuSFQniQACNPGjsNx6pQdKErmCAMpIGnJekNQgAVUw3lQdmitzE3hZWWydR5BS5DKaO382Uy0sasrOynpPz+LMRyRRgWSdk8cFCz0wr3eoUq1VybEQABkdE0Wnb1E7NhM9cocXiCed0MhPKqFcllSHzRZbviQ4rJSr5ZHsLdBcL9t1WoGOSGWTc7hZ1smBUKRVVuvyY-Lc9NRYdHisk6TgaC49hwzZIX9Ac2DhrLeVrZ9sITvN4iOMWiOx0EHIrvRZ3PYEAA5VF+Cl2Fdr5TRGDcEEDVeG5SbohbKfjuwARj8p8I59Hl4ATH5Gf7NehNxzcDFaaWEPgQyttEsRzPsgFJv+gGEkQSB+NwZD9AidgACKEK4SBwJ4CAAELkp4TIXjOyFoRhWEIKyZCoNw3CEY+xEWkopQDja2CUdRtGYKEPRbIh4otOxNFMjxCB8V6SIbNuFjco0LIPMcDbxHmvYFi8TFvCxQ41EgAw2gA4iQADuOlgrUOn6UZJlzhJ2AGn+WDuMyrbuF4NkWKSJq0oW8lLIyQRqZgzEfKCbrsKZoVpIqCDoNQSwIjZ0VBjmrbtjKGronAlKJdmVYpVKibpdglL4XR07jHlmREcESZ2FRQlcVVs5htkjVJoQMBkp4fhIKS5JUjSgmcdxvExE18TKoNwkjTZha1RxU2iTELITXVQ0iXxNWrUyyXNQmaWqcoBGbGNLjKhFCAel5yGTVxABKhA4qgRA2am-5yUcvmnLsNb5okfivfsR60gBILGiQ3goSWgNSdgxJ0Ko+A-qByg9Z1-WENpumfAZYjGQMJ3OOG5nY5ZX1-RaIAADQgMSUAgHGCggKo9qcLoBxQK2FiMywIKbF1UCM7EZHYQAtDzmB84zlPJFzIDtZ1jOQNzcCbuggT4AAAiENK2JkGBSzL2CM0d-lQAA2obzic-4su+lU+KrFAADM0sZDbRs0zCcIcL4AsgLyAASABSxIAFoB-8ABW3gAGKh2QlAwJ4ZCUpgACKABsPQAF6hAADIzlsFq77sWNbNuM3baD+s7Jel84jNNrCVQ+4rjOByH4dR7H8eJ8nqeZznacACyF27ziFi4AC6dcuIzc31aErUc0XHtvo7SsgMuhCGdgACatjUAb4+y1BG-t6yx-19z4FErBbdb3vV+l4zi6bkDD9B+gZCBVTq-G0gd+a4-ashgPiMgz93aMwQkhP2ABqK8T5EEAFY84AE5h5oLQcgyBFcQDcE-EGJGEQ-ZXjzuQm8f8T4ezvA+Mq14H4AA5kHILQdgB0SBYoOBJEsOAJDDYJFng3EAxVPBHSXvRaqK9qHcwdg-beu8D74CPlQ6+TNb4P15JfVRL91GimgvfP2y4n46KgSAN+W5DR+y-j-XB-gAFAKsZvUB4C7Fz3wYhTYD8EFIKfKgjBWCcGmLwQQr8nhiEPzIRQtxwjaEIEapQzezDWHsM4UEYcxJeH8LdpPYoIAEhAA) with valid shipping and billing address, valid lines.
3. [Add shipping method to the checkout.](http://localhost:8000/graphql/#saleor/N4IgjiBcILYK4BcCGCCWB7AdgAgKoAcATFAUwGEALEgYwGt1EAREgG1QDcSAnATwFkSCCukIAKACTUqdBggCShSNjmMAhABps4wqw7d+g4YQVKVASmzAAOjmxSa9Jrs68BQkQWIISom9n-YqIpa9jKICn4BOmwuBu7GwdrO+m5GEbYW1rb+oY4IlpEB2AB0pZQOsoXYAL5V3FzoXADOBdkBpcXlYQgAolwNXFW1tsPDNgBmXEgA5jAkmPkAClyo1CTYWNgAKkgAHiSEfFgkPK3+0w1NLVlFSDAMC1XUcP3z1DyRw-6YgmcBdw8EE8Xlw3h8RpFkLs-v4AXBHm1nq9MO9PjYxpgJlNZvN8l08gAZVA-DY4fGyIkkm6BQiRMBwJALVAIcH+BDoZAsZardbU-wdblrNG2eHMwUkPntUri4UYyYzOYLbAAQUIhFBV1JKrVGuukSCkXGqGaCAAcncSJEWEgmmaLZFqOgYPhGTxzXNIrbQYJVeqSFcAIyehDehC+3UAJgdzNZ2Hw6FtSBYZBEltsjvhIdOksdOiegN4wpyBZ4ytBSEi+GEP31TWY4yQcBYCAAQqgWGxMNNw-6mrX643mwBlCiofD4YndnW99E2LEK3HYEdjidd1IiLXL8eT9eEP4G2yYe22fArNYwuwgsFVOEI-yjOeYeU4pWLJA8RUIADipAA7u+tTfD9cR-bx-2zfVaUPY9iyfVBpgvI1WCgop2CTOA03vB0rxRVB-VnTEn2xT9sHJRAtTI-JqQPNkOSTcULwFM9MJqKpoj0VxDA3SUOi3Vdpl3ItsEIVAmgzJUcxw1E2lvIEIVsESxMBd0WJDRkmmtbxCEYUTxLtD1bHYBh7C4FM81sJo4AAI3ZTkGJ46VmKEppR23Lt7KqJieSEqz207Kc-U1Bzih7K5nNc-jQr1NoOiioSSBgJB209CKdy4whoqKXjUrXdKhPY2Jd0Y0o+LS+IqgAfQqll8HmGCAiEzt-WKzppEJYkWK+QImlKrsACUSHpY0DkiRS9IvJFQRRWNYXuTN8t05T6rUzANNIbTFszFTIiMuATLMlikDQ9skCslgSCAz9QJIcDMqlYpLpAv931lR9nxIyi+gGCi2tkL7Gj+XMWKQlgUOwOYrhmNNqhAdQQHYKAQGpKwQFyWQIigbAUeAYA0fCQhqlqWHIhRgqUnSjGlBR3AIwofBqAACRbfArJgQhTQALQADT69ArIjABFAA2PgtlwABeFH0RAaogA)
4. [Add created voucher to the checkout.](http://localhost:8000/graphql/#saleor/N4IgjiBcILYK4BcCGCCWB7AdgAgIIBN8BhACwFMBjAa3UQAUAndGdI9fMgCgBILzraCAJL5I2IQBEAhABps3AA5MWbDmIDKCBqkwBzKQEpswADo5sfSjUQF8jZq3ZdUo+ZYGIRcpQ9VkxisqOHEam5tgW-NYIxmYR8dgucQnY+KgAzhS0mAhhKfFILHA5yQkAvqXxaZnZCAByhWSVEQjoyAA2jKgUZHn58bpM6el9-SmFtc0pFeHxM-ntOmQjUy1tSJ3aPaP9g+jDO2MTxQirc2fz-cXVWSdk+AAq65vdvWcRxyWz5WfFqAhdbbvbB7A7Aj5FL5jCKXfKwlLXDK3HL3ACqmH+gLe33GkNOOJhU3hEXSJFQCgUOl0WMOKVBKwJ-U++Oh2GJbMq8LIDCYDHSsRxWQ4UwAZqgyO18FMYMt0khdE1ZpcZmUQDIQAA3KAgPomEDuaIiPViPUGwRGtXJPU+FROY3Ya1BPx6syqspAA)
5. [Create payment for the checkout's total.](http://localhost:8000/graphql/#saleor/N4IgjiBcILYK4BcCGCCWB7AdgAgMYCcBTFQgBSQE8ZDMEAKAEgAdLraBJTJxSbcqmgk7cEAQgA02BrgAWhXAGt0idgBNe7ACKiAlNmAAdHHjmLlCfmwQBhIiTqouPKSwEcnCSanVTZ8pSqqeobG2NiE+Pjo+ADO+kZhidgAZqiEADaqCUnY1DExSADmhNlhAL6l2K5WITmJ3pVJskj4xQDKyAhwMY2JuEhMXUSqAIIwyrS1dTlI43C0veWLeHYIhFmhOYUkAO6Uy9WCALKECDLoqgAqFEwlm0nLlRXGz88g4iAAblAgU2EGID8ZkCAN4AKBASEWXelQBh3cIlB8XuiQBswmCCRAIQ6GQ6QB4keIG2az2FCxsFQ+Dg1EIADp4QgYnTVDSYOSYSj-iAcQoaBTknB0ukKAB9ZqtdYEp5GMogMpAA)
6. [Run checkoutComplete.](http://localhost:8000/graphql/#saleor/N4IgjiBcILYK4BcCGCCWB7AdgAgMIAsBTAYwGt1Fd0YAHAG0IUIAoASYosihASQBNI2HgBEAhAEpswADo5sHEuUrV6jFqgHZ2nJbz6SZc7NkIAnU+lMBnKbOP3sMQlatIA5oTsPsAM1SE6Pi8HYnQ+TyNsAF9g+Sw-UxgUDEwAOUJCcKDI0MwEpLQsYRQkWMtw01tI4w1Y4ytkBDgrOuxmsyrve0Ik1DpWmOrsVCsAZXxUGhpUTDcAJUIwOFRTTNaEdGQ6Tq7sNwsXHd3sJBgKTARW40HjzEZDY4dT88uh66vsZAAPB8fjZ7gFw+N28IJCOm4-FaADcKApTL9jqFwh9jO1sl0wfY+CNQoCEFZEbsEABPGgRP7QpB0OAUx5UmmEAAqZLpxwGrXCdFQ0LMJIAsox8GEjt4AHQS7BYbDjSbTWaChDCviirq1N7RD4SsVSnAAdSQq2F7VV3nVxyx7yG3LuhI+5t2gNQCGEuJeRK6AKBGst9idLrd+JZ5I+-tdVjxFwWSCsWFDmGd4cjCAAatTafGcRGXpkAKoJhAABVMqGIhA93juCArnrO+NRmp9HMiIMGURAABoQNCoCBftIQAouIgoVAB0PdKPsLJ21EgA)
7. Check voucher's status by running voucher query.

### What did you expect to happen?

Expected:
`used:1`

Actual:
`used:0`

### Logs

[Playground with all requests](https://master.staging.saleor.cloud/graphql/#saleor/N4IgjiBcILYK4BcCGCCWB7AdgAgMYAsBTXAa3UQEEATKgBQCd0Z0BhdKw7YAHRzyNLkE1Oo2ZsOACl7ZZ2AA5jW7QpGzcQAFQCiAZU0BaAAwBGDQBoZc1FTUaAigCZ8AGwCajhADcqADXsAbACyACJUMABaAOIAagBWAHJxAKoIbgDqAFIkQbpGRm6aFEYAMukAkgCsCSEkCAkwbiYJUVURIQDmAMwJmvEaVgCUXFayhPSM9ADOI3xyeCqjcjCEU1NIHYRLAL5Wu5jbIOYg6FAgBMRklDQMTMocINtAA)

### Environment

Saleor version: core v3.18.0-a.0

**Comment by szczecha** [comment]
If voucher is 'usageLimit': null then voucher.codes[x].used remains 0
