### ISSUE TITLE
Use prepare shop helper in all e2e

### ISSUE THREAD

**Issue by szczecha** [saleor/saleor#14693]
## Problem

Right now we have prepare_shop utils that create a basic store, we want to extend this function to allow creating a more flexible shop config and use it in all tests.

### General Assumptions
Channels
- [ ] creating more than 1 channel (with different currencies)
- [ ] setting stock/payment/order

Warehouses
- [ ] creating more than 1 warehouse

Shipping zones
- [ ] creating more than 1 shipping zone
- [ ] adding many countries to the shipping zone

Shipping methods (shippingPriceCreate)
- [ ] possibility of creating 2 or more shipping methods with different prices
- [ ] possibility to add postal code rules
- [ ] possibility to set min/max order weight, delivery time

Shop
- [ ] possibility to update shop settings

Taxes
- [ ] possibility to update strategy, priceEnterWithTaxes, country rate

**Comment by yellowee** [comment]
https://github.com/saleor/saleor/pull/14779
