### ISSUE TITLE
Add more pricing fields into channelListings

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#14748]
## Problem

I want to read variant pricing data every time webhook event is informing about its change (PRODUCT_VARIANT_DELETED).

Following query: 

```graphql
fragment VariantPricing on ProductVariant {
  # this is null, because parent query doesn't have channel. Subscription doesn't have channels
  # with channel provided, this object contains price, discount, onSale, priceUndiscounted
  pricing {} 
  
  channelListings {
    # It contains only "price". Missing discount, onSale, priceUndiscounted
  }
}

```
---

## 1. General Assumptions

Add same pricing model into channelListing

### Acceptance Criteria

- [ ]
- [ ]

### Mutations

```graphql

```

### Types

```graphql

```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by patrys** [comment]
Pricing is a storefront-facing field and is always calculated within the context of a channel. Discounts, the price after discounts, etc., are dynamic, depend on the currently active sales, and are not part of the variant or its listings. When the discounted price changes, the variant is not considered "updated," so no such event is emitted.

Can you provide a use case where you need storefront pricing so we can determine where it belongs?

**Comment by lkostrowski** [comment]
> Pricing is a storefront-facing field and is always calculated within the context of a channel. Discounts, the price after discounts, etc., are dynamic, depend on the currently active sales, and are not part of the variant or its listings. When the discounted price changes, the variant is not considered "updated," so no such event is emitted.
> 
> Can you provide a use case where you need storefront pricing so we can determine where it belongs?

Sure. I'm working on Algolia app. Storefront is likely rendered with Algolia index, filtering, etc is likely done via Algolia. 

Products are synchronized to Algolia when product-related events are triggered. 

I see there are more problems - even if the field exists, it will not be updated when the price is changed.
