### ISSUE TITLE
Add `referer` field to webhook events

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#14818]
## Problem

We cannot determine the origin from which the request was made that triggered the webhook. For example: if we trigger `TRANSACTION_INITIALIZE_SESSION` webhook from `transactionInitialize` mutation inside a web browser that is viewing a `https://my-awesome-app.com` we have no way to tell the website that the user was browsing was `https://my-awesome-app.com` in the app that will handle the webhook.

This is needed, for example in 3D Secure payments, that require the `origin` of a page that made the request for calculating risk score. Example in Adyen docs: https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-origin

---

## 1. General Assumptions

We need the `referer` (note typo in RFC 2068 single `r`) HTTP header to be passed in the webhook event.

Since this is considered PII and might not always be present on the request (e.g. not called in web browser) we should add this only to transaction related webhook events

### Acceptance Criteria

- [ ] `referrer` property is added to listed webhook events

### Types

```graphql
type TransactionProcessSession {
  # ...
  referrer: String
}
```

We add `referrer` the same way to other user-facing webhook event types:
- `TransactionInitializeSession`
- `PaymentGatewayInitializeSession`
- `PaymentMethodProcessTokenizationSession`
- `PaymentMethodInitializeTokenizationSession`
- `PaymentGatewayInitializeTokenizationSession`

**Comment by patrys** [comment]
My initial thought is that information belongs to something other than the event level. Most events are not triggered through HTTP requests, so the concept of "referrers" (funny story: the HTTP header has a typo in its name, but there was no way to fix it, so it's stuck with an "r" missing) does not translate well to events in general. It could also leak information that apps don't need to know to operate. If it's specifically required for payments, I'd make it part of the payment protocol, the same way we convey information about IP addresses.
