### ISSUE TITLE
Bug:  Incorrect discount amount displayed for orders with both discountable and non-discountable products

### ISSUE THREAD

**Issue by DidoMarchet** [saleor/saleor#14810]
### What are you trying to achieve?

Hi,
I added a 25% discount to an order with both a discountable and a non-discountable product. The discount became 0 even though the order total changed.

When I remove the non-discountable product, the discount shows the correct amount.

Here's the payload:

{
    "checkout": {
        "token": "XXX",
        "id": "XXXX",
        "email": "davide@myemail.it",
        "totalPrice": {
            "gross": {
                **"amount": 266.25,**
                "currency": "EUR"
            },
            "net": {
                "amount": 218.24,
                "currency": "EUR"
            }
        },
        "subtotalPrice": {
            "gross": {
                "amount": 266.25,
                "currency": "EUR"
            },
            "net": {
                "amount": 218.24,
                "currency": "EUR"
            },
            "tax": {
                "amount": 48.01,
                "currency": "EUR"
            }
        },
        "billingAddress": { ... },
        "shippingAddress": { ... },
        "shippingMethods": [...],
        "availableCollectionPoints": [ ... ],
        "deliveryMethod": {...},
        "shippingMethod": {...},
        "shippingPrice": {...},
        "lines": [
            {
                "id": "Q2hlY2tvdXRMaW5lOmNlZTU0Yjg3LWQ3ZDEtNDgzNS1iYWUzLTQ1NTgwOGZhMzkzYw==",
                "quantity": 1,
                "totalPrice": {
                    "gross": {
                        **"amount": 261.75,**
                        "currency": "EUR"
                    },
                    "net": {
                        "amount": 214.55,
                        "currency": "EUR"
                    }
                },
                "undiscountedTotalPrice": {
                    **"amount": 349,**
                    "currency": "EUR"
                },
                "variant": { ... },
                    "attributes": [...],
                    "product": {...}
                }
            },
            {
                "id": "Q2hlY2tvdXRMaW5lOjBkNjk5NjRjLTVmM2ItNGYzMy1hNmY0LTA0NDhhOTZhNDMyMg==",
                "quantity": 1,
                "totalPrice": {
                    "gross": {
                        **"amount": 4.5,**
                        "currency": "EUR"
                    },
                    "net": {
                        "amount": 3.69,
                        "currency": "EUR"
                    }
                },
                "undiscountedTotalPrice": {
                    **"amount": 4.5,**
                    "currency": "EUR"
                },
                "variant": {... },
                    "attributes": [...],
                    "product": {...}
                }
            }
        ],
        "isShippingRequired": true,
        **"discount": {
            "currency": "EUR",
            "amount": 0
        },**
        "giftCards": [],
        "discountName": null,
        "translatedDiscountName": "",
        **"voucherCode": "EXPO25",**
,
        "metadata": []
    }
}

Can this be fixed? Many customers are confused about whether their coupon is correctly applied or not.

### Steps to reproduce the problem

Add a discountable product and a non-discountable product to the cart. Apply a percentage discount.

The discount amount for the order shows as 0.

### What did you expect to happen?

The correct amount of discount not 0.

### Environment

core v3.12.0-a

**Comment by DidoMarchet** [comment]
Hi, do you have any updates?

Thanks and kind regards,
Davide

**Comment by maarcingebala** [comment]
Hi, what kind of discount is this? Is this a discount that applies to specific products, or an entire category/collection? If it's a specific-product discount, these are applied on specific checkout/order lines and are not included in the general "discount" field. As a side note, I would recommend upgrading to a newer version, recent one is 3.18.

**Comment by DidoMarchet** [comment]
Hi, 
thank you for your feedback.

Yes, the copuon it's applied to applies to specific products. 
I've observed that it only applies to the line items and know you configrm it's the normal behaviour. 

So we should focus on making changes and improvements on the frontend side to address this matter.

Applies to specific products.

Kind regards,
Davide
