### ISSUE TITLE
Apply order line fixed manual discount to total price, instead of unit price. 

### ISSUE THREAD

**Issue by zedzior** [saleor/saleor#14817]
## Problem

Currently, fixed manual discounts applied to order line, are reflected in its unit price. I want to make them apply to order line total price instead. I propose to change the behaviour of `update_discount_for_order_line` function.

It will be a breaking change and require to recalculate discount prices.

**Comment by IKarbowiak** [comment]
Related https://github.com/saleor/saleor/issues/14879
