### ISSUE TITLE
Fix missing subscription payload handling

### ISSUE THREAD

**Issue by jakubkuc** [saleor/saleor#14834]
At the moment configuring subscription queries in webhook incorrectly for sync events is causing Saleor to crash and raise `PaymentError`due to empty payload generated from subscription.

Way to reproduce: 
1. Create a Webhook with registered two events but only one defined in subscription query:
e.g. 

```
mutation {
  webhookCreate(
    input: {
      app: "<appid>"
      name: "test_subscription"
      targetUrl: "<URL>"
      syncEvents: [SHIPPING_LIST_METHODS_FOR_CHECKOUT, CHECKOUT_FILTER_SHIPPING_METHODS]
      query: "subscription{event{...on CheckoutFilterShippingMethods{__typename}}}"
    }
  ) {
    errors {
      field
      message
    }
    webhook {
      id
    }
  }
}
```
2. Fetch checkout querying the event missing from subscription query

Result: Saleor crashes and query returns internal error 

Expected result: 
We should handle empty payloads (caused by either incorrect subscription queries or crashing apps) without crashing. 
- If the subscription results in an empty payload, we want to ignore the webhook and proceed as if it didn't exist.
- If the subscription is correct but the app is broken (down, returns an incorrect result etc.), proceed as if it didn't exist (see above)

**Comment by maarcingebala** [comment]
A [thread](https://saleorcommerce.slack.com/archives/C0373831YBC/p1700652262051419) with more context.
