### ISSUE TITLE
Bug:  It seems that there is no requirements.txt file in order to install the dependencies

### ISSUE THREAD

**Issue by NotThorz** [saleor/saleor#14859]
### What are you trying to achieve?

I might have missed something but in the documentation it says to run the py pip install -r requirements.txt and there is no such file .

### Steps to reproduce the problem

git clone https://github.com/saleor/saleor.git
cd saleor
python -m venv saleor-venv
saleor-venv\Scripts\activate.bat
python -m pip install -r requirements.txt

The file doesn't exist

### What did you expect to happen?

Install the dependencies

### Environment

Saleor version: …
OS and version: …

**Comment by liwenz** [comment]
but all the tutorial say the requirement.
poetry install is enough?
