### ISSUE TITLE
Implement Open Telemetry

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor#14868]
## Problem

Open telemetry is a standard spec/framework for telemetry, including backend-agnostic distributed tracing.

At the moment, Saleor is connected to Datadog and Sentry, which are commercial platforms. OTEL can be implemented in a similar way and connected to Datadog and Sentry

https://blog.sentry.io/introducing-opentelemetry-support/
https://docs.datadoghq.com/opentelemetry/

Since Saleor leverages a microservices approach (due to the composable commerce model), its valuable to observe the entire distributed trace. 

For example:
Storefront (service 1) → Saleor (service 2) → Saleor App (service 3) → Saleor (service 2) → database (service 4) → storefront (service 1).

The entire request flow can be visible as a trace if every service is instrumented.

---

## 1. General Assumptions

The saleor should implement Open Telemetry standard. Saleor will optionally accepts collector params and send traces, logs, metrics to the collector.

Dependencies like postgres or redis can be instrumented on collector level.

To link Saleor with other services, it must implemented [Trace Context](https://www.w3.org/TR/trace-context/) in outcoming requests

### Acceptance Criteria

- [ ]
- [ ]

### Mutations

```graphql

```

### Types

```graphql

```

## 4. UML diagrams

```mermaid

```

## 5. To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

- [ ]
- [ ]

**Comment by maarcingebala** [comment]
We track this task already here: https://github.com/saleor/saleor/issues/14831

**Comment by lkostrowski** [comment]
@maarcingebala thanks, closing then.
