### ISSUE TITLE
Bug: product with same name as (recently) deleted product does not get created

### ISSUE THREAD

**Issue by sjoerdvanbekhoven** [saleor/saleor#14871]
### What are you trying to achieve?

Adding a product.

### Steps to reproduce the problem

1. Create a product with name `test`
2. Delete the product
3. Execute this mutation:
```
mutation {
  productCreate(
    input: {
      productType: "YOUR_PRODUCT_TYPE_ID", name: "test"
    }
  ) {
    product {
      id
      name
    }
  }
}
```
4. If all goes well, the response is something like this:
```
{
   "data":{
      "productCreate":{
         "product":{
            "id":"UHJvZHVjdDoyMDQ=",
            "name":"test",
            "__typename":"Product"
         },
         "errors":[
            
         ],
         "__typename":"ProductCreate"
      }
   },
   "extensions":{
      "cost":{
         "requestedQueryCost":1,
         "maximumAvailable":50000
      }
   }
}
```
All good, you'd say. Unfortunately, (for me) the product does not get added. It is not visible in the UI, nor does it show up when querying the DB.

### What did you expect to happen?

I expected the product to get added.

### Environment

Saleor version: 3.18.2

**Comment by maarcingebala** [comment]
Hi @sjoerdvanbekhoven I was going to check this issue today but I see it's closed now, is it resolved? What was the problem here? Thanks!

**Comment by sjoerdvanbekhoven** [comment]
The queries I executed (with Apollo) were being cached by Next.js (they extended the native fetch API to cache requests on default). I fixed it by adding `export const dynamic = 'force-dynamic';` to the route/page, which disables caching altogether.
