### ISSUE TITLE
Bug: Missing length validation for `ProductMedia.alt` field.

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#14886]
### What are you trying to achieve?

Create a product media.

### Steps to reproduce the problem

1. Run mutation to create productMedia and pass long value as `alt` (over 128 chars):
```graphql
mutation productMediaCreate {
  productMediaCreate(
  	input: {
      alt: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua enima.",
      mediaUrl: "https://abbasite.com/uploads/2023/10/headerthevisitors.png",
      product: "UHJvZHVjdDoyMTc1"
    }
  ) {
    errors {
      code
      message
      field
    }
  }
}
```
2. Python error is returned:
```
{
  "errors": [
    {
      "message": "value too long for type character varying(128)\n",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "productMediaCreate"
      ],
  ...
}
```

### What did you expect to happen?

Mutation should return a handled error instead of a Python exception. Fix should be implemented all the mutations that allow creating/updating product media:
- productMediaCreate
- productMediaUpdate
- productBulkCreate

### Logs

https://saleor.sentry.io/issues/3878623132/events/0e9ec2b072c14777b6e7ebc2c54958ad/

### Environment

Saleor version: 3.17

**Comment by jakubkuc** [comment]
fixed in https://github.com/saleor/saleor/pull/15094
