### ISSUE TITLE
If voucher discount on specific products is applied, the discount amount does not count towards shipping method thresholds.

### ISSUE THREAD

**Issue by TurkaljGoran** [saleor/saleor#14896]
### What are you trying to achieve?

Hello Saleor team, 

We're using Saleor 3.5.35 for a project, and I noticed a peculiar behavior which I'm not sure if it is a bug (or a feature, and I'm doing something wrong).

A checkout has only 1 product in it, price of the product is 45,00 euros. 
A shipping method - FREE SHIPPING is available to checkouts with 45,00 euros or more. 
Anything below, a PAYED DELIVERY shipping method is used, costing 5,00 euros. 

EXAMPLE 1: 
If a voucher discount gets applied to this checkout, 20% discount, **to the entire order**: 
- checkout subtotal is now 36,00 euros
- discount on the checkout itself is 9,00 euros
- PAYED DELIVERY shipping method is valid and is 5,00 euros
- total amount is 41,00 euros  

This works, the order can be made.

EXAMPLE 2:
But, if voucher discount is used on **specific products** and I add this same product and repeat the process, the following happens:
- checkout subtotal is 36,00 euros, same as above, 
- discount on the checkout itself is 0,00 euros, 
- discount on the checkout line for the product is 9,00 euros
- **PAYED DELIVERY shipping method is NOT VALID** and Saleor says that FREE SHIPPING is the only shipping method that can be used with this checkout, even though this checkout has a subtotal of 36,00 euros, and the minimum for FREE SHIPPING shipping method is 45,00 euros. 

Does Saleor not count discounts on checkout lines towards shipping method thresholds?
Does Saleor only count discounts on the checkout itself towards shipping method thresholds - like in the first example?

### Steps to reproduce the problem

1. set payed delivery shipping method maximum to be 44,99 euros
2. set free shipping method minimum to be 45,00 euros
3. create product A with a price of 45,00 euros
4. create discount voucher 20%, check "for specific products", add product A to the list of specific products
5. add product A to cart
6. apply voucher discount
7. try to complete the rest of the checkout process and the checkoutDeliveryMethodUpdate mutation will fail if it receives an ID for the payed delivery shipping method - even though checkout is small enough to warrant its use, and free shipping method minimum has not been reached

### What did you expect to happen?

I expected that if the subtotal price of the checkout (36,00 euros) is below the  minimum amount for a free shipping method to be valid (45,00 euros), that  BOTH voucher discount chosen (specific products or entire order), the payed delivery shipping method would be valid, since both discounts bring the subtotal to 36,00 euros. 

### Environment

Saleor core 3.5.35

**Comment by aniav** [comment]
Hey @TurkaljGoran we no longer support Saleor 3.5 and we didn't support it at the time of reporting the issue. We are not able to provide support for versions blow 3.14 at this point. Please upgrade to the newest version and reopen the issue if it's still happening 🙌
