### ISSUE TITLE
Idempotency for the transactions API

### ISSUE THREAD

**Issue by patrys** [saleor/saleor#14926]
## Problem

It's possible for a customer to accidentally pay twice for a checkout if they refresh the page during checkout. We need a mechanism for checkouts to enforce the "at most once" strategy for payments.

The proposed solution is to introduce an optional idempotency key that the storefront can pass when initiating payments that would result in both Saleor and the payment service provider (PSP) attempting to deduplicate the request.

The proposed flow would be as follows:

1. Storefront calls `transactionInitialize` with an optional idempotency key
2. If the key is not given, Saleor generates one
3. If a previous transaction for the same checkout matches the provided key, Saleor returns that transaction without further processing
4. Saleor emits `TransactionInitializeSession`, passing the idempotency key
5. The payment handling app passes the key to the PSP (for example, both Adyen and Stripe support it through the `idempotency-key` HTTP header)
6. If the PSP finds a previous transaction, it gets returned without further processing
7. Saleor proceeds as usual

---

### Acceptance Criteria

- Idempotency keys are present for all newly created transactions
- If provided, user-generated keys take precedence
- Automatically generated keys are unique at least within the last 24 hours
- It may be wise to wipe the keys after a few days to reduce the risk of collisions
- If present, the keys are forwarded to the apps handling payments
- A similar mechanism should guard `TransactionProcessSession`, but I'm not sure if it should allow the client to override the idempotency key. We need to evaluate the risk of duplicate processing versus the risk of implementors reusing the same key they used for session initialization and thus breaking some apps.

### Types

```graphql
type TransactionInitializeSession implements Event {
  # …
  idempotencyKey: String!
}

type TransactionProcessSession implements Event {
  # …
  idempotencyKey: String!
}
```

## 3. Database changes

<!-- New models or changes in existing models  -→

## 4. UML diagrams

<!-- You can render UML diagrams using [Mermaid](https://mermaidjs.github.io/). -→

```mermaid

```

## 5. To Do list

<!-- Everything from developer perspective -→

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## 6. To Test

<!--
Put here additional info of what it would be good to check along with new changes.
e.g.:
- Check feature with tax systems
- Test with overrode prices
 -→

- [ ]
- [ ]

**Comment by lkostrowski** [comment]
A few cents:

1. How this mechanism will be compatible if idempotency is introduced as a core feature for all events, not only sync transactions. Can we plan API to be consistent? For transactions, there is a single key, but for async webhook, like order_created, we have one key identifying unique order creation, another one for subscription, to duplicate retried delivery attempts. Hence maybe `eventIdempotencyKey` and `deliveryIdempotencyKey` may be something that fits both APIs? Also wiping keys and uniqueness will have to cover much longer time and amount
2. Probably we should have similar behavior in some other events, like refunds. AFAIK now if a refund is sent to the app, Saleor doesn't set any state on it (like isDuringRefund: boolean, or refundState: idle | progress | done, etc). Clicking button 5 times can result with 5 refunds. Dashboard can generate such idempotency key.

related:
https://github.com/saleor/saleor/issues/14251
https://github.com/saleor/saleor/issues/14358

https://docs.adyen.com/development-resources/api-idempotency/

**Comment by korycins** [comment]
@patrys  few questions:

> Automatically generated keys are unique at least within the last 24 hours
> It may be wise to wipe the keys after a few days to reduce the risk of collisions

Maybe we could have a default key with a random uuid, with the assumption that this is unique across all transactions assigned to checkout/order.
Then we don't need a logic to wipe the keys to reduce the collision. What do you think?

---

>A similar mechanism should guard TransactionProcessSession, but I'm not sure if it should allow the client to override the idempotency key. We need to evaluate the risk of duplicate processing versus the risk of implementors reusing the same key they used for session initialization and thus breaking some apps.

You could have multiple additional actions so transactionProcess could be called multiple times, before finalizing the payment process. If we want to store the idempotency key for transactionProcess, we need to store idempotency key for each unique `transactionProcess` call. On executing transactionProcess, we don't know which mutation call is unique and which one is duplicated. We could accept the optional idempotency-key, and create the TransactionRequest event with the key as a first step of the mutation, to have a possibility to de-duplicate calls.

---

Another thing that I am worried about is calling transactionInitialize/transactionProcess twice with the same idempotency key but with very small time window.
Assuming flow like below, everything should work as expected:
```mermaid
sequenceDiagram
    Storefront->>+Saleor: TransactionInitialize<br>with<br>idempotency:123
    Saleor ->>+ App: Process request
    App -->>- Saleor: Data
    Saleor ->>- Storefront: TransactionItem,<br>event and<br>data
    Storefront->>+Saleor: TransactionInitialize<br>with<br>idempotency:123
    Saleor ->> Saleor: Get existing<br>transaction with<br>last event
    Saleor ->>- Storefront: TransactionItem,<br>event and<br>data
```
But a more possible case is having two mutation calls in small period of time. Where one is not fully processed (we are making a request to provider). So in that case for the second call we can return data without all details of the request.

```mermaid
gantt
    dateFormat HH:mm
    axisFormat %H:%M
    Initial milestone : milestone, m1, 17:49, 2m
    section transaction<br>Initialize1
    Mutation : 17:51, 20m
    Create Transaction: 17:52, 2m
    Create TransactionEvent: 17:54, 2m
    transactionInitializeSessionrequest: 17:56, 10m
    creater/update transactionEvent: 18:06,3m
    recalculation: 18:09,2m
    section transaction<br>Initialize2
    Mutation : 17:53, 3m
    Return existing transaction: 17:54, 2m
    section transaction<br>Initialize3
    Mutation : 18:00, 3m
    Return existing transaction: 18:01, 2m 
    Final milestone : milestone, m2, 18:12, 1m
```

> [!IMPORTANT]  
> I am aware that we can apply the lock when creating the transaction or transactionEvent. But having lock only on moment of creation transaction & transactionEvent would not solve the problem as to return proper response, we need to have the response from the payment provider.

So based on the second diagram. Second and third transactionInitialize calls would return the transactionItem but without all details - transactionEvent created based on the response from the payment provider.

We could assume, that for cases like the 2nd and 3rd we could return only transaction and event set to None (the one that we create based on the response from paymentApp). This will be different behavior from the one that we currently have - error or transaction&event as a response. But this would happen only when you're provide an idempotency-key.

What do you think?

---

Also, what about `data` (JSON) that app returns as a response and we pass it to the storefront? We don't store it, so second/third transactionInitialize call will not return it.  Storing the `data` in transactionEvent would not cover all cases:
See the second diagram - we could have a 2nd/3rd mutation call before processing the response from payment provider, so no `data` to return.

**Comment by witoszekdev** [comment]
@korycins I don't think we need to do deduplication on Saleor level. I think we should pass it through to the App, and later to the Payment Provider (Adyen, Stripe, etc.) as they support it:
- Adyen: https://docs.adyen.com/development-resources/api-idempotency/
- Stripe: https://stripe.com/docs/api/idempotent_requests
- PayPal: https://developer.paypal.com/api/rest/reference/idempotency/
- Mollie: https://docs.mollie.com/overview/api-idempotency

As you said, we don't store `data` which is necessary for storefronts to handle the payments via native SDKs (e.g. Adyen Dropin). By passing idempotency keys to platforms, we'll avoid this issue altogether.

**Comment by patrys** [comment]
@lkostrowski IMO, completely unrelated. Event delivery idempotency is a matter of sending the event ID along with the payload.

**Comment by korycins** [comment]
Closing as idempotencyKey was introduced to `transactionInitialize` in 3.14+
