### ISSUE TITLE
Add the possibility to check if a transaction was created in checkout

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor#14946]
## Problem

In `Order` the users can check the pending amounts (authorization / charge / refund). However, this is not possible in `Checkout`. As a result, the storefront can charge the customer multiple times.

For example, if the storefront had made a `transactionInitialize` mutation request and during the processing of that mutation the page was refreshed, there is no trace of a Transaction being in progress on `Checkout`.

---

## 1\. General Assumptions

Add fields to `Checkout` that would allow checking if a Transaction is in progress without exposing all `TransactionItem` details.

### Types

```
enum CheckoutPaymentStatusEnum {
  NOT_STARTED
  IN_PROGRESS
  ALL_SETTLED
}

type Checkout {
  # ...
  paymentStatus: CheckoutPaymentStatusEnum
} 
```

**Comment by korycins** [comment]
Link to internal discussion: https://saleorcommerce.slack.com/archives/C039MGJDWU8/p1702646264290639

**Comment by witoszekdev** [comment]
Migrated https://linear.app/saleor/issue/SHOPX-1764/add-possibility-to-check-if-a-payment-is-pending-on-checkout
