### ISSUE TITLE
Bug: Cannot create new customer

### ISSUE THREAD

**Issue by kesimlimert** [saleor/saleor#14956]
### What are you trying to achieve?

To create new customer.

### Steps to reproduce the problem

1. Execute the following query
```
mutation CustomerCreate($input: UserCreateInput!) {
    customerCreate(input: $input) {
        errors {
            field
            message
        }
        user {
            email
            firstName
            lastName
        }
    }
}
``` 
2. Returns error message:"To access this path, you need one of the following permissions: MANAGE_USERS"

### What did you expect to happen?

If I should to grant permission, I don't know how. Only added from dashboard to staff members.

### Environment

Saleor version:3.18.3

**Comment by IKarbowiak** [comment]
Hi @kesimlimert,

The `customerCreate` mutation is for the staff users with `MANAGE_USERS` permission. If you want to create an account as a anonymous user you should use `AccountRegister` mutation. Please review [the docs](https://docs.saleor.io/docs/3.x/developer/users#registration-without-email-confirmation).
