### ISSUE TITLE
Bug: Installing psycopg2 (2.9.9): Failed

### ISSUE THREAD

**Issue by ghost** [saleor/saleor#14990]
### What are you trying to achieve?

I aim to configure Saleor Core on my local machine and am in the process of installing packages using poetry.

### Steps to reproduce the problem

Clone the latest Saleor from the Git repository.

- Activate the Poetry shell.

`poetry shell`

- Install dependencies using Poetry.

`poetry install`

### What did you expect to happen?

Install all packages within the newly created Poetry environment.

### Logs

• Installing psycopg2 (2.9.9): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-39
  creating build/lib.linux-x86_64-cpython-39/psycopg2
  copying lib/_ipaddress.py -> build/lib.linux-x86_64-cpython-39/psycopg2
  copying lib/pool.py -> build/lib.linux-x86_64-cpython-39/psycopg2
  copying lib/_json.py -> build/lib.linux-x86_64-cpython-39/psycopg2
  copying lib/__init__.py -> build/lib.linux-x86_64-cpython-39/psycopg2
  copying lib/extensions.py -> build/lib.linux-x86_64-cpython-39/psycopg2
  copying lib/extras.py -> build/lib.linux-x86_64-cpython-39/psycopg2
  copying lib/errors.py -> build/lib.linux-x86_64-cpython-39/psycopg2
  copying lib/_range.py -> build/lib.linux-x86_64-cpython-39/psycopg2
  copying lib/errorcodes.py -> build/lib.linux-x86_64-cpython-39/psycopg2
  copying lib/sql.py -> build/lib.linux-x86_64-cpython-39/psycopg2
  copying lib/tz.py -> build/lib.linux-x86_64-cpython-39/psycopg2
  running build_ext
  building 'psycopg2._psycopg' extension
  creating build/temp.linux-x86_64-cpython-39
  creating build/temp.linux-x86_64-cpython-39/psycopg
  x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC "-DPSYCOPG_VERSION=2.9.9 (dt dec pq3 ext lo64)" -DPSYCOPG_DEBUG=1 -DPG_VERSION_NUM=160001 -DHAVE_LO64=1 -DPSYCOPG_DEBUG=1 -I/tmp/tmpqozmvz6h/.venv/include -I/usr/include/python3.9 -I. -I/usr/include/postgresql -I/usr/include/postgresql/16/server -I/usr/include/libxml2 -c psycopg/adapter_asis.c -o build/temp.linux-x86_64-cpython-39/psycopg/adapter_asis.o -Wdeclaration-after-statement
  In file included from psycopg/adapter_asis.c:28:
  ./psycopg/psycopg.h:35:10: fatal error: Python.h: No such file or directory
     35 | #include <Python.h>
        |          ^~~~~~~~~~
  compilation terminated.
  
  It appears you are missing some prerequisite to build the package from source.
  
  You may install a binary package by installing 'psycopg2-binary' from PyPI.
  If you want to install psycopg2 from source, please install the packages
  required for the build and try again.
  
  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).
  
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  

  at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with psycopg2 (2.9.9) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "psycopg2 (==2.9.9)"'.

### Environment

Saleor : 3.18.3
Poetry (version 1.6.1)
Environment Information:

Operating System: Ubuntu 22.04.3 LTS
Python Version: 3.9.18

**Comment by patrys** [comment]
>It appears you are missing some prerequisite to build the package from source.

Your computer is missing Python development headers. Possibly also PostgreSQL development headers.

Unless you have development experience with the tools, please use the recommended way of installing Saleor using Docker.

**Comment by DevAlbinJo** [comment]
@patrys Thank you for your reply. As of now, Docker doesn't seem to have any issues, at least from what we can discern since we can't access the installation log. This issue hasn't impacted the functionality of Saleor thus far. However, I do need to configure the project using poetry and install packages accordingly. I've attempted the commands in Docker

`sudo apt-get -y update && apt-get install -y gettext && apt-get clean && rm -rf /var/lib/apt/lists/*`
  
  and 
  `sudo apt-get update \
  && apt-get install -y \
  libcairo2 \
  libgdk-pixbuf2.0-0 \
  liblcms2-2 \
  libopenjp2-7 \
  libpango-1.0-0 \
  libpangocairo-1.0-0 \
  libssl3 \
  libtiff6 \
  libwebp7 \
  libxml2 \
  libpq5 \
  shared-mime-info \
  mime-support \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*`
  
  but still im getting this error:
  
  Installing psycopg2 (2.9.8): Failed
  
  Please let me know what else packages should i install for psycopg2

**Comment by patrys** [comment]
I think you may need to check the documentation of `psycopg2`. The best I can offer is the `apt-get` command you already pasted from `Dockerfile`. At Saleor, we use macOS, and I don't have access to any desktop machine running Ubuntu.

**Comment by aniav** [comment]
I will close the issue for now as we can't do anything about it without further details. Feel free to reopen when you think it makes sense 🙌
