### ISSUE TITLE
Bug: Graphql schema Check Failed after latest release

### ISSUE THREAD

**Issue by ghost** [saleor/saleor#15001]
### What are you trying to achieve?

In the pre-commit configuration, there are problems with the GraphQL schema check following the most recent release.

### Steps to reproduce the problem

- Clone the latest salero repo
- `cd saleor`
- `python manage.py get_graphql_schema | diff saleor/graphql/schema.graphql -`

### What did you expect to happen?

The schema check should yield no variances between the result obtained from the `get_graphql_schema` method and the `saleor/graphql/schema.graphql` file

### Logs

< Event sent when user requests to delete a payment method.
< 
< Added in Saleor 3.16.
< 
< Note: this API is currently in Feature Preview and can be subject to changes at later point.
< """
< type StoredPaymentMethodDeleteRequested implements Event @doc(category: "Payments") {
<   """Time of the event."""
<   issuedAt: DateTime
< 
<   """Saleor version that triggered the event."""
<   version: String
< 
<   """The user or application that triggered the event."""
<   issuingPrincipal: IssuingPrincipal
< 
<   """The application receiving the webhook."""
<   recipient: App
< 
<   """
<   The user for which the app should proceed with payment method delete request.
<   """
<   user: User!
< 
<   """
<   The ID of the payment method that should be deleted by the payment gateway.
<   """
<   paymentMethodId: String!
< 
<   """Channel related to the requested delete action."""
<   channel: Channel!
< }
< 
< """
< Event sent to initialize a new session in payment gateway to store the payment method. 
< 
![Screenshot from 2023-12-13 12-45-44](https://github.com/saleor/saleor/assets/59693895/b3b98e41-f245-445b-ac2b-2c0966e29545)

### Environment

Saleor : 3.18.3
Poetry (version 1.6.1)

Operating System: Ubuntu 22.04.3 LTS
Python Version: 3.9.18

**Comment by patrys** [comment]
Arę you sure `python manage.py get_graphql_schema` is not crashing for you?

**Comment by DevAlbinJo** [comment]
@patrys I'm confident that python manage.py get_graphql_schema is not causing any crashes on my end.

- I don't think it's crashing because I haven't made any modifications.
- What steps can I take to confirm that manage.py is running smoothly without any crashes?
- Previously, it was functioning well with my custom modifications.
- To validate, I cloned the repository freshly with the latest releases and attempted to run it, but there's a significant difference in the output, and it doesn't seem to make sense.

**Comment by patrys** [comment]
Can you run the command without the ` | diff …` part and check if it outputs the schema?

**Comment by DevAlbinJo** [comment]
@patrys  Yes it does 

"""
Event sent when user continues a tokenization of payment method.

Added in Saleor 3.16.

Note: this API is currently in Feature Preview and can be subject to changes at later point.
"""
type PaymentMethodProcessTokenizationSession implements Event @doc(category: "Payments") {
  """Time of the event."""
  issuedAt: DateTime

  """Saleor version that triggered the event."""
  version: String

  """The user or application that triggered the event."""
  issuingPrincipal: IssuingPrincipal

  """The application receiving the webhook."""
  recipient: App

  """The user related to the requested action."""
  user: User!

  """Channel related to the requested action."""
  channel: Channel!

  """Payment gateway data in JSON format, received from storefront."""
  data: JSON

  """
  The ID returned by app from `PAYMENT_METHOD_INITIALIZE_TOKENIZATION_SESSION` webhook.
  """
  id: String!
}

**Comment by patrys** [comment]
Is that all the command returns? it should output many screens of text, starting with:

```graphql
schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
```
