### ISSUE TITLE
Add test cases for Stripe plugin refunds

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor#15028]
As mentioned in the PR comment, additional tests should be added to stripe plugin to cover the case without refunds:

https://github.com/saleor/saleor/pull/14951#discussion_r1422064107

**Comment by aniav** [comment]
Given we are unlikely to invest in the Stripe Plugin any more in favour of the [saleor-app-payment-stripe](https://github.com/saleor/saleor-app-payment-stripe) I will close this issue.
