### ISSUE TITLE
Bug: Unable to calculate taxes based on the billing country for digital product when shipping address is provided [Flat Rates]

### ISSUE THREAD

**Issue by yellowee** [saleor/saleor#15024]
### What are you trying to achieve?

It is related to https://github.com/saleor/saleor/issues/13140:

I was trying to create e2e test for calculating simple taxes based on the billing country for digital product.

### Steps to reproduce the problem
Tax configuration:
```
"chargeTaxes": true,
"taxCalculationStrategy": "FLAT_RATES",
"pricesEnteredWithTax": false,
```

Channel default country United States - country rate 20%
Shipping country: Chechia - country rate 21%
Billing country: Germany -  country rate 19%

addresses:
```
"shippingAddress":{
         "city":"Melc",
         "country":"CZ",
         "firstName":"John",
         "lastName":"Muller",
         "phone":"+420722274643",
         "postalCode":"74784",
         "streetAddress1":"Sluneční 1396"
      },
"billingAddress":{
         "city":"Pollenfeld",
         "country":"DE",
         "firstName":"John",
         "lastName":"Muller",
         "phone":"+4908421499469",
         "postalCode":"85131",
         "streetAddress1":"Potsdamer Platz 47"
      }
```

Scenario I: Shipping address is set along with the digital product during the checkout creation.
1. Create a checkout with a digital product in lines and a shipping address.
2. Update billing address.
3. Check the total price tax amount.
```
"isShippingRequired": false,
"totalPrice": {
    "gross": {
        "amount": 12.1,
        "currency": "USD"
    },
    "net": {
        "amount": 10.0,
        "currency": "USD"
    },
    "tax": {
        "amount": 2.1,
        "currency": "USD"
    }
}
```
Tax rate taken from the shipping address but shipping is not required 

Scenario II: Create checkout for digital product without addresses:
```
"isShippingRequired": false,
"totalPrice": {
    "gross": {
        "amount": 12.0,
        "currency": "USD"
    },
    "net": {
        "amount": 10.0,
        "currency": "USD"
    },
    "tax": {
        "amount": 2.0,
        "currency": "USD"
    }
}
```
tax correct 10*20%=2 - tax rate is taken from the default channel address

Scenario III: Create checkout for digital product with the billing address
```
"isShippingRequired": false,
"totalPrice": {
    "gross": {
        "amount": 11.9,
        "currency": "USD"
    },
    "net": {
        "amount": 10.0,
         "currency": "USD"
    },
    "tax": {
        "amount": 1.9,
        "currency": "USD"
    }
}
```
tax correct 10*19%=2 tax rate taken from the billing address

### What did you expect to happen?
The tax is calculated based on the billing address since the shipping is not required, the shipping address is ignored.

### Environment

Saleor version:
dashboard 3.19.0-dev-d02dcf9
core v3.19.0-a.0
OS and version: Apple M2, Sonoma 14.1

Core core v3.15.18

**Comment by szczecha** [comment]
Closing as it is expected.

Change order of resolving country code in checkout - [#13159](https://github.com/saleor/saleor/pull/13159)
Until now, checkout mutations ignored the provided shipping address when shipping was not required. After this change, the shipping address is always set when supplied in the input. It might be breaking, as the shipping address affects the country code used for tax calculation.
The order of resolving the checkout country code is always as follows:
Shipping address
Billing address
The channel's default country
