### ISSUE TITLE
Bug: Blank page issue 

### ISSUE THREAD

**Issue by NotThorz** [saleor/saleor#15083]
### What are you trying to achieve?

after having a saleor core instance running and  installing the dependencies, setting up the variables  and running the dashboard all I get is a blank page 
![image_2023-12-18_212744350](https://github.com/saleor/saleor/assets/76731890/00d1d1bc-2c11-4a1a-95f4-73ddc2c2dec3)
In all browsers the only issue I get is this :
![image_2023-12-18_212819250](https://github.com/saleor/saleor/assets/76731890/e7421938-1fa1-4441-87f7-0d34d9933342)
I m mainly a backed guy so I just want to visualize this .

### Steps to reproduce the problem

...

### What did you expect to happen?

...

### Environment

Saleor version: 3.19 latest (main branch)
OS and version: Windows 10

**Comment by timuric** [comment]
Hey @NotThorz have you tried to run docker image instead?

**Comment by aniav** [comment]
I will close the issue for now as we can't do anything about it without further details. Feel free to reopen when you think it makes sense 🙌
