### ISSUE TITLE
Bug: Internal server error when generating invoice

### ISSUE THREAD

**Issue by wojteknowacki** [saleor/saleor#15125]
### What are you trying to achieve?

Generate invoice from existing order

### Steps to reproduce the problem

Send InvoiceRequest with existing order id.

[Request and response can be found here](https://www.graphdev.app/share/clqnlk3nc00060ux2a7wn3s6t)

### What did you expect to happen?

Correct invoice response

### Environment

Saleor version: 3.19

**Comment by IKarbowiak** [comment]
Related [sentry issue](https://saleor.sentry.io/issues/4765368794/?alert_rule_id=11198640&alert_type=issue&notification_uuid=6f4de3ab-e5cf-445d-8d7d-7a77ee69d7b2&project=6417854&referrer=slack)
