### ISSUE TITLE
Do not allow to create catalogue promotion rule with `reward_value` not set

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#15146]
Currently, there is a possibility to create a catalog `PromotionRule` with unset `reward_value`. We shouldn't allow that.

We need to find out where is the option to create such a rule and not allow it anymore.

**Comment by aakashkejriwal** [comment]
Hi - I think this happens you create a variant promotion rule via the dashboard. 

It creates a promotion rule with below:
```
{
          "node": {
            "id": "UHJvbW90aW9uOjI1NGExMTYzLTI3OGUtNDFkNi04NDgwLWY1MzdiODEzYTRhMw==",
            "name": "Test Rule",
            "startDate": "2024-01-04T17:51:00+00:00",
            "endDate": null,
            "events": [],
            "rules": [
              {
                "cataloguePredicate": {
                  "OR": [
                    {
                      "variantPredicate": {
                        "ids": [
                          "UHJvZHVjdFZhcmlhbnQ6NDg4"
                        ]
                      }
                    }
                  ]
                },
                "id": "UHJvbW90aW9uUnVsZTo3OTQwNDg3NC05MTk3LTRlZjYtYTE0Ny1iYmFhYWUyMzIwOWE=",
                "rewardValueType": "PERCENTAGE",
                "rewardValue": null
              },
              {
                "cataloguePredicate": {
                  "OR": [
                    {
                      "variantPredicate": {
                        "ids": [
                          "UHJvZHVjdFZhcmlhbnQ6NDg4"
                        ]
                      }
                    }
                  ]
                },
                "id": "UHJvbW90aW9uUnVsZTo0NGUxZTU2Yi0wYzA4LTRhYzYtYjNjMS00Njk3MmJiYTdmMDA=",
                "rewardValueType": "PERCENTAGE",
                "rewardValue": 50
              }
            ]
          }
        }
```

**Comment by aakashkejriwal** [comment]
Also, another thing I noticed is if I use the `promotionCreate` mutation with only variant ids in the predicate it sometimes works and sometimes doesn't (API is always successful, but discounts don't reflect).

For example,

```
{
  "input": {
    "name": "GraphQL Test",
    "rules": [
      {
        "channels": ["Q2hhbm5lbDoy"],
        "rewardValue": 20,
        "rewardValueType": "PERCENTAGE",
        "cataloguePredicate": {
          "variantPredicate":{
              	"ids": "UHJvZHVjdFZhcmlhbnQ6Mzk0"
                }
          
        }
      }
    ]
  }
}
``` 

this works sometimes but fails most of the time. The rule is always created but the price and discount never reflects!

Incase anyone knows what could be going wrong would be helpful!

**Comment by IKarbowiak** [comment]
Thank you @aakashkejriwal, we will check that!

**Comment by korycins** [comment]
From what I see, sale interface uses the PromotionRule to store some data. In that case, objects will have reward_value=None. I don't think that there is any easy way, which could solve this. I think we need to leave the filters which exclude reward_value=None. 

---

Additionally, @aakashkejriwal pointed out the issue with re-calculation:

> Also, another thing I noticed is if I use the promotionCreate mutation with only variant ids in the predicate it sometimes works and sometimes doesn't (API is always successful, but discounts don't reflect).

The issue here is related to triggering the celery task inside the DB transaction. I've created the task for this: https://github.com/saleor/saleor/issues/15265

@aakashkejriwal  thanks again!
