### ISSUE TITLE
Possibility to run e2e test against cloud env

### ISSUE THREAD

**Issue by szczecha** [saleor/saleor#15168]
## Problem
We want to be able to run e2e tests on the deployed application

## General Assumptions

- Possibility provide a URL to run the tests on. It's a good idea to use a variable that can be retrieved from the workflow in the future
- By default, they run in the terminal as before.
- Make sure about data security (no passwords to test instances in the code)

## To Do list

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by gsamanidharreddy** [comment]
## Steps

1. **Configuration Update**: Add the `appUrl` configuration option to `e2e-config.json`. This makes the URL easily configurable.

   ```json
   {
     "appUrl": "https://your-deployed-app-url.com",
     // any other configuration options
   }


**Dynamic URL Retrieval:**
The logic for dynamically retrieving the URL during test execution is well implemented.


 ```
   {
     const appUrl = Cypress.env("appUrl") || require("../e2e-config.json").appUrl;
   }
```
**Security Considerations:**
 It's excellent that sensitive information, such as passwords, is now retrieved from environment variables. This enhances data security.

```
const username = Cypress.env("username");
const password = Cypress.env("password");
```
**Testing Command:**
 The testing command is clear and helpful for anyone who wants to run the e2e tests with the updated configuration.

```
npx cypress run --config-file path/to/e2e-config.json
```

## Additional Notes

Ensure that the testing environment matches the deployed application environment.
If you encounter any issues during testing, feel free to reach out for assistance.
Thank you
