### ISSUE TITLE
Bug: Not able to assign Product from  Collection Modification page.

### ISSUE THREAD

**Issue by jyo-this** [saleor/saleor#15182]
### What are you trying to achieve?

From Collection Modification page, unable to assign the collection to a product which is not having any variant. 

### Steps to reproduce the problem

1. Open Saleor GraphQL Playground or POSTMAN. Use TokenCreate API to get Token.
2. Use the token generated to call CreateProduct API.
3. Create a new product (eg; "New Product") without variant.
4. Use the token generated to call CreateCollection API.
5. Create a new collection (eg; "New Collection").
6. Try to assign the previously created Product to the Collection using CollectionAssignProduct API.
    We will get error "CANNOT_MANAGE_PRODUCT_WITHOUT_VARIANT".

### What did you expect to happen?

We should be able to assign Collection to a Product without Variant.

### Logs

Please find below CollectionAssignProduct mutation, input and response,
mutation CollectionAssignProduct($collectionId: ID!, $productIds: [ID!]!, $first: Int, $after: String, $last: Int, $before: String) {
  collectionAddProducts(collectionId: $collectionId, products: $productIds) {
    collection {
      id
      products(first: $first, after: $after, before: $before, last: $last) {
        edges {
          node {
            ...CollectionProduct
            __typename
          }
          __typename
        }
        pageInfo {
          endCursor
          hasNextPage
          hasPreviousPage
          startCursor
          __typename
        }
        __typename
      }
      __typename
    }
    errors {
      ...CollectionError
      __typename
    }
    __typename
  }
}

fragment CollectionProduct on Product {
  id
  name
  productType {
    id
    name
    __typename
  }
  thumbnail {
    url
    __typename
  }
  channelListings {
    ...ChannelListingProductWithoutPricing
    __typename
  }
  __typename
}

fragment ChannelListingProductWithoutPricing on ProductChannelListing {
  isPublished
  publicationDate
  isAvailableForPurchase
  availableForPurchase
  visibleInListings
  channel {
    id
    name
    currencyCode
    __typename
  }
  __typename
}

fragment CollectionError on CollectionError {
  code
  field
  message
  __typename
}

{
  "first": 20,
  "collectionId": "Q29sbGVjdGlvbjox",
  "productIds": [
    "UHJvZHVjdDoxMw=="
  ]
}

Response of mutation,
{
    "data": {
        "collectionAddProducts": {
            "collection": null,
            "errors": [
                {
                    "code": "CANNOT_MANAGE_PRODUCT_WITHOUT_VARIANT",
                    "field": "products",
                    "message": "Cannot manage products without variants.",
                    "__typename": "CollectionError"
                }
            ],
            "__typename": "CollectionAddProducts"
        }
    },
    "extensions": {
        "cost": {
            "requestedQueryCost": 100,
            "maximumAvailable": 50000
        }
    }
}

### Environment

Saleor version: 3.18.10
OS and version: Ubuntu 22.04.3 LTS

**Comment by jyothis-moz** [comment]
Hi Team, please let me know if any further details are required regarding this issue or to recreate the issue.

**Comment by IKarbowiak** [comment]
Hi @jyo-this,

This is expected behavior. You cannot update the product without any variant.
