### ISSUE TITLE
Move prefetched_for_webhook to payload serializers

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#15188]
Many product-related mutations use the method `prefeteched_for_webhook` to run prefetches needed by legacy webhook payload generators. This is inefficient since these prefetches are heavy and are unnecessarily run for webhook using subscription paylaods. To fix this, we should move the `prefetched_for_webhook` call to legacy payload generators.

Example: 
- [prefetched_for_webhook is called](https://github.com/saleor/saleor/blob/1df99ed89df3d4ee8db00e2280dcb98995e5551b/saleor/graphql/product/mutations/product/product_create.py#L222) in the `post_save_action` in the `productCreate` mutation
- Instead, it should be moved to the [legacy payload generator](https://github.com/saleor/saleor/blob/1df99ed89df3d4ee8db00e2280dcb98995e5551b/saleor/webhook/payloads.py#L713) where it's actually needed

To do:
- Analyze all usages of `prefeteched_for_webhook` (both for product and for variant) and move them to proper payload generators.
- Remove prefetch of [product_type__product_attributes__values](https://github.com/saleor/saleor/blob/1df99ed89df3d4ee8db00e2280dcb98995e5551b/saleor/product/managers.py#L230) which is not used by the product payload generator.
- Update tests that check the number of DB queries; after these changes, the DB query count should be lower when subscription webhooks are enabled (note: in tests, make sure to use products with some attributes and values assigned).
- Port changes to versions from 3.14 to latest.

Context: https://saleorcommerce.slack.com/archives/C06C6UWV45V/p1704470719634879

**Comment by AjmalPonneth** [comment]
@maarcingebala Kindly review the PR.
