### ISSUE TITLE
Bug: billing address is used for tax calculation for Click&Collect orders

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#15209]
### What are you trying to achieve?

Create an order via checkout that uses C&C as the delivery method and has correctly calculated taxes. 

### Steps to reproduce the problem

1. Prepare tax configuration: enable flat rates in a channel and add default tax rates for two countries, A and B (for easier reproduction, choose two with different tax rates).
2. Configure Click & Collect: prepare a warehouse with the "Pickup" option enabled (e.g. set to "Local stock"), add it to the channel, add stock for a product in this warehouse. For the warehouse, configure an address to use one of the two countries, e.g. country A.
3. Create a checkout with a product and set only the billing address; use country B (Australia in this case). Example:
```graphql
mutation checkoutCreate {
  checkoutCreate(
    input: {
      email: "test@example.com",
      channel: "default-channel",
      lines: [
        { variantId: "UHJvZHVjdFZhcmlhbnQ6Mzg0", quantity: 1 },
      ],
      billingAddress: {
        firstName: "Test",
        lastName: "Test",
        streetAddress1: "Test",
        city: "Test",
        country: AU,
        countryArea: "VIC",
        postalCode: "3189"
      }
    }
  ) {
    checkout {
      id
      availableCollectionPoints {
        id
        name
      }
      totalPrice {
        gross {
          amount
        }
        net {
          amount
        }
      }
    }
  }
}
```
At this point billing address country is used for tax calculation.

4. Assign the collection point to a warehouse that is in country A:
```graphql
mutation checkoutAddShipping {
  checkoutDeliveryMethodUpdate(
    id: "Q2hlY2tvdXQ6YmNmMWI0ODItZTM3MS00M2I3LWFjY2EtYmViZGRlMDczZDgy"
    deliveryMethodId: "V2FyZWhvdXNlOjA0NTAwNTlmLWMzMzQtNGUxMi05YWU5LWQ2YmU3NzQ5OTY5YQ=="
  ) {
    checkout {
      shippingAddress {
        country {
          code
        }
      }
      billingAddress {
        country {
          code
        }	
      }
      deliveryMethod {
        ... on Warehouse {
          address {
            country {
              code
            }
          }
        }
      }
      totalPrice {
        net {
          amount
        }
        gross {
          amount
        }
      }
    }
  }
}
``` 

Response:
```json
{
  "data": {
    "checkoutDeliveryMethodUpdate": {
      "checkout": {
        "shippingAddress": null,
        "billingAddress": {
          "country": {
            "code": "AU"
          }
        },
        "deliveryMethod": {
          "address": {
            "country": {
              "code": "PL"
            }
          }
        },
        "totalPrice": {
          "net": {
            "amount": 1.99
          },
          "gross": {
            "amount": 2.19
          }
        }
      }
    }
  }
}
```
Check the total price - tax is 10%, which is the rate for AU, but the pickup point is in PL, where 23% should be applied. The shipping address is not set, and the billing address is used for tax calculation, which is incorrect. Instead, the C&C pickup address should be used.

### What did you expect to happen?

To fix the issue, we can do the following:
- When `checkoutDeliveryMethodUpdate` is used to set C&C delivery, override the checkout's shipping address with the warehouse address. Make sure that price recalculation is triggered afterwards, and the shipping address is used for tax calculations. Update the mutation's description to mention that behavior.
- In all mutations where the shipping address can be set, add validation to raise an error when the user is trying to override the shipping address if C&C is selected. Update descriptions accordingly.
- Update the changelog to describe behavior changes (in PR to the `main` branch).

Edge cases:
- Changing the address of a warehouse that is used as a collection point should update all checkouts where this address was set as shipping address.

### Logs

Context: https://saleorcommerce.slack.com/archives/C0373831YBC/p1704467414278619

### Environment

Saleor version: 3.14.47

**Comment by Air-t** [comment]
@maarcingebala in terms of edge case with ` Warehouse.address` update - `Checkout.shipping_address` will point to the same `Address` instance in database - is there any action to take? Or would you happen to think of a case where Warehouse gets a new `Address` instance?
I found one mutation which can update the shipping_address `CheckoutShippingAddressUpdate`
