### ISSUE TITLE
Bug: Demo isn't working

### ISSUE THREAD

**Issue by Raytle** [saleor/saleor#15211]
### What are you trying to achieve?

I clicked on demo at https://github.com/saleor/saleor#demo.

The link was dead.

I mean the word "demo" located at https://github.com/saleor/saleor#table-of-contents.

### Steps to reproduce the problem

I clicked on demo at https://github.com/saleor/saleor#demo.

The link was dead.

### What did you expect to happen?

I clicked on demo at https://github.com/saleor/saleor#demo.

The link was dead.

### Environment

I clicked on demo at https://github.com/saleor/saleor#demo.

The link was dead.

**Comment by pitkes22** [comment]
@mmiszy So there is not going to be a public demo anymore?

**Comment by mmiszy** [comment]
@pitkes22 Demo in the previous form didn't play any usable role and we didn't want to confuse our users so we simply removed it a few months ago.
There's a storefront example and a bunch of other examples available (https://github.com/saleor/examples). For the dashboard and cloud you can create a free sandbox account. It's even better than the previous demo we had because you actually try Saleor instead of looking at it through a glass, so to say (the previous demo was readonly).
I hope that helps.

**Comment by Raytle** [comment]
The lack of a demo clear indicates you guys are egregiously failing to market Saleor properly. As a result, I suppose that Saleor is unlikely to gain sufficient traction to make it worthwhile for me to consider.

**Comment by mmiszy** [comment]
Feel free to reach out to our sales team for a walkthrough and demo 💪

**Comment by Raytle** [comment]
You are an arrogant ignoramus.

**Comment by pitkes22** [comment]
@mmiszy I find it quite disappointing for multiple reasons. First, I think having a demo was a really quick and easy way to explore Saleor. I can confidently say that, for me personally, it played a huge role in choosing Saleor two years ago. Having an easily accessible demo is a very transparent way of presenting the product and seems to be aligned with the open-source nature of the Saleor project. I completely understand the decision to replace the prime landing page real estate with "Book a demo," which leads to the sales funnel, but not having the demo elsewhere on the page is something I would not expect from an open-source project to do, especially when it was already implemented and available.

Currently, when I looked through the new Saleor page, I could not find any screenshots of the current dashboard. There are some images of parts of it, but they are far from something representative of the current user interface and experience. The Saleor dashboard is an inseparable part of the Saleor platform. My employees spend many hours daily on it, and I am more than aware of its strengths and weaknesses, but I find it concerning that it seems like there is an effort to "hide" it from the webpage and replace it with flashy images that represent more of a vision than the reality of the current dashboard.

The solution of using a free cloud account, of course, works, but it definitely requires more effort to get to the dashboard and even more effort to see it connected to the storefront. I used the demo quite often to try the new features without setting anything up. Also, this option of trying the dashboard using a free account is not very clearly explained. There is a mention of free sandboxes, but I am not sure if I would understand from it that I can spin up a Saleor+dashboard instance in a minute.

**Comment by Raytle** [comment]
I appreciate your carefully considered arguments; however, I doubt the arrogant ignormouses who maintain this project will be persuaded to create a demo.

**Comment by pitkes22** [comment]
@Raytle I have been using Saleor for more than two years, with half of that time in production, and based on my experience, I must disagree with you. I have opened many issues and asked numerous questions, and the Saleor team has always been very professional, helpful, and quick to respond. Many times, the experience of opening an issue felt like asking a colleague for help, and I am referring to issues opened on GitHub, not any paid support they offer. I genuinely find the team very welcoming, and the only reason I am raising my concerns about the removal of the demo is that I genuinely miss it. For the last couple of months (including today), I have ended up multiple times clicking on a dead link and wishing I could quickly check the demo.

**Comment by Raytle** [comment]
**"Use our software... even though we have failed to create a demo!"** is inane on its face. For decades, a demo, for almost all user facing software, has been [table stakes](https://en.wikipedia.org/wiki/Table_stakes#:~:text=In%20business%2C%20%22table%20stakes%22,market%20or%20other%20business%20arrangement.).

I'll essentially repeat what I posted previously...

The lack of a demo clear indicates the guys at Saleor are egregiously failing to market Saleor properly. As a result, I suppose that Saleor is unlikely to gain sufficient traction to make it worthwhile for me to consider.

and

I appreciate your carefully considered arguments; however, I doubt the arrogant ignormouses who maintain this project will be persuaded to create a demo.

**Comment by Raytle** [comment]
Some other FOSS ecommerce project maintainers seem to understand the importance of having a demo.

1. https://github.com/vendure-ecommerce/vendure?tab=readme-ov-file#vendure
2. https://github.com/evershopcommerce/evershop?tab=readme-ov-file#evershop

**Comment by timuric** [comment]
@Raytle the downside of having a demo that is that it is read-only which leads to confusing user experience. You can easily try out the product using free cloud account which allows you to try all features of the platform which doesn’t take much effort.

**Comment by Raytle** [comment]
Why not create a demo that is **_not_** read-only, which automatically resets every, say, 24 hours?

In such a case, perhaps it might be a good idea to post a notice at the top such as, "This demo is programmatically reset every 24 hours. Therefore, all changes you make to it will be lost when this demo is reset."

This is not an idea I dreamt up; rather, many demo websites I have visited over the years have had similar messages.

**Comment by Raytle** [comment]
If you were to want to ensure users who are demoing Saleor don't unexpectedly lose data you might consider posting the following message at the top of the demo (and of course include the functionality it alludes to), 

"This demo is programmatically reset every 24 hours. **This demo will next reset in X hours and Y minutes [where X and Y would decrease minute by minute].** Therefore, all changes you make to it will be lost when this demo is reset."

**Comment by timuric** [comment]
@Raytle this is not as simple as you think, while one person might be trying to configure a product the other person can delete a product type, channel or attribute, which would lead to errors, same goes for warehouses, taxes and dozens of objects that rely on each other.

**Comment by timuric** [comment]
Thanks for the constructive feedback @pitkes22 

I agree that dashboard interface needs to be featured on the website, we are in the process of making cosmetic changes to the UI after which we will use the screenshots more freely. The reason why homepage has abstract UI is to communicate concepts more effectively as many concepts are quite complex.

The point about lack of clarity regarding starting a sandbox quickly is solid and we will think about, thanks for bringing that up.

**Comment by Raytle** [comment]
> his is not as simple as you might think, 

It is obviously much simpler than you seem to think it is. You are being so remarkably illogical and obstinate it's painful to read your vacuous assertions.

My duuuude! Obviously, if necessary, you could give each user who wants to test tryout the demo a block of time, say, one hour to exclusively use a demo. 

Also, my duuuude... used i7 4th-6th generation machines with 8GB of RAM can be purchased for around 100 US dollars here in the USA on eBay. If you were to buy 1/2 a dozen of them, and set each of them up behind a Cloudflare Tunnel, you could have 1/2 a dozen more demo sites.

That's assuming each user needed an entire, bar metal i7 4th-6th generation machine with 8GB to run a demo. My guess is that if you were to spend 150 US dollars for used i7  4th-6th generation machine with 16GB, you could probably run several demos on the same machine.

"We don't need demos!" said no shrewd software project manager for at least the last two decades.

Your project will almost certainly fail to gain sufficient traction. I've got no interest in dealing with you because you are an arrogant, foolish, ignoramus.

Goodbye and good riddance.
