### ISSUE TITLE
When will paypal be supported?

### ISSUE THREAD

**Issue by Theo-messi** [saleor/saleor#15270]
As mentioned, the existing Adyen is very unfriendly to me. I hope to support Paypal payment as soon as possible. Or is there any way to access it currently?
Currently I use vercel+saleor to create a store

**Comment by maarcingebala** [comment]
Hi, We have no plans for direct integration with PayPal; so far, we are supporting it via Adyen.
The [authorize.net](http://authorize.net/) payment gateway will also support PayPal, but it's currently under development and will be shared as a community-supported app (self-deployment) in the future.
