### ISSUE TITLE
Optimize user fetching by email (retrieve_user_by_email func)

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#15281]
User fetching performed by func retrieve_user_by_email which is calling `users = list(User.objects.filter(email__iexact=email))`
the Django's iexact does an SQL filter `WHERE UPPER("account_user"."email"::text) = UPPER('admin@example.com')`
There is no upper index on that, that would help but it's preferable NOT to create it, instead filter by email.
The issue is there are duplicates in the database (case sensitivity) which potentially might return multiple emails. 

1. We should create a migration that will normalize existing emails to be unique (all lowercase), TBD: how to handle dup emails case.
2. Optimize the function, not to use `iexact` but just a `.filter.first()` (beware of using get!)

The above 2nd point task part is because when Django does `.objects.get()` it actually sets SQL part `LIMIT 21` which generates a massive scan only to potentially raise `MultipleObjectsReturned`.

**Comment by maarcingebala** [comment]
Tracked in Linear: https://linear.app/saleor/issue/PE-390/optimize-user-fetching-by-email-retrieve-user-by-email-func

**Comment by AjmalPonneth** [comment]
@maarcingebala These Lenear issues can only be tracked internally only?

**Comment by maarcingebala** [comment]
Yes, we use Linear internally to plan roadmaps for our teams, especially for more low-level performance fixes like this one. In case of bigger changes or features, we tend to publish RFCs publically, but currently, we're mostly focused on performance improvements instead of features.
