### ISSUE TITLE
Assigning attribute as variant attributes triggers overriding variant name

### ISSUE THREAD

**Issue by KarolJagodzinski** [saleor/saleor#15318]
### What are you trying to achieve?

Assigning attributes shouldn't have any impact on variant name

### Steps to reproduce the problem

1. Create a product with variants.
2. There are two cases: Create a variant with SKU, and a variant without SKU
3. Assign an attribute to product type as a variant attribute
4. You will notice that variant name without SKU is changed to Saleor ID, and a variant name with SKU is changed to SKU

### What did you expect to happen?

There shouldn't be any impact on variant name

### Environment

Saleor version: dashboard v3.18.2, core v3.18.12

**Comment by teddyondieki** [comment]
I was able to reproduce this bug and would like to help fix it @maarcingebala

**Comment by IKarbowiak** [comment]
Go on @teddyondieki 🚀. I assigned you to this issue

**Comment by teddyondieki** [comment]
@IKarbowiak I propose adding a checkbox on the ProductType page that would let users `Overwrite Product Variant Names`. What do you think about the approach? Can I go ahead?

**Comment by teddyondieki** [comment]
@IKarbowiak I have a [PR](https://github.com/saleor/saleor/pull/15670) that addresses this issue. I would appreciate your review.

**Comment by vhejda** [comment]
@IKarbowiak  is the fix merged into 3.19? It's driving us crazy :(

**Comment by IKarbowiak** [comment]
Hi, it has been released in 3.20
