### ISSUE TITLE
Refactor discount utils.py file

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#15371]
Refactor [saleor](https://github.com/saleor/saleor/tree/main)/[saleor](https://github.com/saleor/saleor/tree/main/saleor)/[discount](https://github.com/saleor/saleor/tree/main/saleor/discount)
/[utils.py](https://github.com/saleor/saleor/blob/main/saleor/discount/utils.py) as after introducing promotions logic it gets too big.

We can split this file into smaller files one with `voucher` specific logic and second with `promotion` specific logic.

**Comment by aniav** [comment]
This has been delivered ✨
