### ISSUE TITLE
DB performance improvements in attribute dataloaders

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#15405]
As noticed in [this PR](https://github.com/saleor/saleor/pull/15404/) there are some performance improvements that could be made in attribute dataloaders, to use subqueries instead of joins.

- https://github.com/saleor/saleor/pull/15404/files/0b97162a4503fac6153ef2cd2d37b6a80aeb32a4#r1489110075
- https://github.com/saleor/saleor/pull/15404/files/0b97162a4503fac6153ef2cd2d37b6a80aeb32a4#r1489110459
- https://github.com/saleor/saleor/pull/15404/files/0b97162a4503fac6153ef2cd2d37b6a80aeb32a4#r1489110819

**Comment by AjmalPonneth** [comment]
@maarcingebala Can you please assign this issue for me?

**Comment by maarcingebala** [comment]
@AjmalPonneth Assigned 🚀

**Comment by AjmalPonneth** [comment]
@maarcingebala Please review the PR.
