### ISSUE TITLE
Apple authentication

### ISSUE THREAD

**Issue by dhminh0310** [saleor/saleor#15434]
## Problem

Does Saleor support authenticating using Apple authentication?

---

## 1. General Assumptions
- I was able to sign in using Google account, but couldn't find a way to sign in using Apple account
- Searched Saleor's documentation but couldn't find any help
- Does Saleor support logging in with an Apple account?

**Comment by aniav** [comment]
You can sign in using Apple, as per screenshot 🙌 
<img width="503" alt="Screenshot 2024-10-16 at 22 29 21" src="https://github.com/user-attachments/assets/af179b07-2976-4cd4-92f4-38da414acae4">
