### ISSUE TITLE
Bug: Performance issue : Urgent: Performance Issues with Saleor Core App Deployment 

### ISSUE THREAD

**Issue by Ramesh534** [saleor/saleor#15499]
### What are you trying to achieve?

I hope this message finds you well. We are currently experiencing performance issues with the Saleor Core app deployed inside an EC2 instance using Docker containers. Some API requests are processing with significantly lower latency than others, and we are seeking your assistance to identify and resolve these discrepancies.

Despite monitoring the system, we have observed that the CPU and memory utilization do not seem to align with the latency issues we are encountering. We have attached a screenshot for your reference to provide additional information.

Key Details:

SDK Version:
"@apollo/client": "^3.9.2"
"graphql": "^16.8.1"
Issue Description:

Inconsistent latency with API requests.
CPU and memory utilization appear normal, but certain requests are taking longer than expected.
Attached screenshot for further insights.
Requested Assistance:
We kindly request your support in identifying the root cause of the latency discrepancies and optimizing the performance of our Saleor Core app. As this issue is affecting the user experience, we consider it urgent and appreciate your prompt attention to this matter.

Attached Screenshot:
[Attach screenshot here]

Thank you for your immediate attention to this matter. We are eager to work collaboratively with you to resolve these performance issues and ensure the seamless operation of our Saleor Core app.

### Steps to reproduce the problem

Install the mobile app and run the application. 
![image (1)](https://github.com/saleor/saleor/assets/38880890/5331893f-3cd8-4c42-9de6-84dd3fc3beed)

### What did you expect to happen?

I want to achive all the api's should be respond in less then 1 sec. 

### Environment

Saleor version: 3.18.3
![image (1)](https://github.com/saleor/saleor/assets/38880890/3d228ee3-9c25-4123-924c-a05efeca1545)

OS and version: DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by aniav** [comment]
Thank you for your report @Ramesh534. We have made a lot of inprovements to Saleor's performance in 3.20, feel free to test the newest version and reopen if this still happens 🙌
