### ISSUE TITLE
Add metadata to channel listings

### ISSUE THREAD

**Issue by timuric** [saleor/saleor#15567]
From Discord discussion:

> Sales channels,(marketplaces) are huge part of the ecommerce especially in the US. For my setup I would definitely need a url field of the listing linking directly to the sales channel listing. Also, different title and description requirements can apply to listings from different marketplaces. It would be very flexible to add a metafields to the ProductVariantChannelListing and ProductChannelListing entities

**Comment by saqibmehmood** [comment]
Hi Timuric, 
I want to work on this bug. Please let me know when you are available to discuss in details

**Comment by aniav** [comment]
Hey @saqibmehmood nobody is working on this ticket currently, you are free to pick it up 🙌

**Comment by SarthakNikhal** [comment]
@aniav @saqibmehmood Is this issue resolved? I can help if not

**Comment by mayixiaobai248** [comment]
Hello, I want to work on this issue.

**Comment by chinmay1596** [comment]
@aniav can i pick this one

**Comment by aniav** [comment]
I looked at this issue now and I think it would be good to understand the initial problem someone wanted to solve. We have metadata on `ProductVariant`, we have translations for `ProductVariant` so it seems what the initial commenter might have wanted could have been achieved from a different angle. I'll try to dig out the conversation and create a relevant issue based on it.
