### ISSUE TITLE
Bug: 500 when using a fragment on `OrderOrCheckout`

### ISSUE THREAD

**Issue by typeofweb** [saleor/saleor#15568]
### What are you trying to achieve?

Sending the following fragment causes the GraphQL endpoint to 500:

```graphql
fragment OrderOrCheckoutLines on OrderOrCheckout {
  ... on Node {
    __typename
  }
}
```

### Steps to reproduce the problem

https://master.staging.saleor.cloud/graphql/#saleor/N4IgjiBcIGYE4EMDmBbApgOwC4AIDycAJmnAQMIAWaAxgNYD2ArlgDICWGaAzjvRvkRLkqdJrmAAdfjgB0c3vwBy9YjknScOAPpasATwAOmBOimaAvlPMhzQA

### What did you expect to happen?

Not 500.

### Environment

.

**Comment by aniav** [comment]
This has been fixed.
