### ISSUE TITLE
Bug: Stock query returns null despite being present in the database

### ISSUE THREAD

**Issue by supersilverlemonhaze** [saleor/saleor#15738]
### What are you trying to achieve?

I am simply trying to get the stocks of a warehouse ...
Looking at the API reference and code it's supposed to be possible.

### Steps to reproduce the problem

Starting from a point of a preconfigured saleor instance containing example products etc.:

Run stocks Query to validate existing stocks:
```graphql
query getStocks {
  stocks(first: 10) {
    edges {
      node {
        id
        quantity
        warehouse {
          id
        }
      }
    }
  }
}
```
Take any warehouse ID for some stock with a high quantity and run the stock Query:
```graphql
query getStocks($warehouseID: ID!) {
  stock(id: $warehouseID) {
    warehouse {
      id
    }
  }
}
```
Output:
```graphql
{
  "data": {
    "stock": null
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 1,
      "maximumAvailable": 50000
    }
  }
}
```
### What did you expect to happen?

In the first step I verify that the warehouse contains stock. Using that same warehouse ID in the stock query is logically supposed to give me the stocks of the warehouse.

Also: The APIs documentation is horrible! Look at the docs of the stock query:
-----
Look up a stock by ID

Requires one of the following permissions: MANAGE_PRODUCTS.
Type
[Stock](https://development.weedster.app/graphql/#)
Arguments
id: [ID](https://development.weedster.app/graphql/#)!
ID of a(n) warehouse
-----

'Look up a stock by ID' One might think its own ID, but its the warehouse ID Be a bit more professional please. Fighting such this horrible docs has cost me already days of work. The product is so immature I'm really thinking of switching to something else. Please fix this, querying the stock is the bare minimum an ecommerce backend should be able to allow.

### Environment

Saleor version: ghcr.io/saleor/saleor:3.19

**Comment by teddyondieki** [comment]
I can help with this by:
1. Updating the documentation to fix the said discrepancy
2. Add a `stocks` field to the `warehouse` type to allow the fetching of stocks related to a particular warehouse

**Comment by supersilverlemonhaze** [comment]
> I can help with this by:
> 
> 1. Updating the documentation to fix the said discrepancy
> 2. Add a `stocks` field to the `warehouse` type to allow the fetching of stocks related to a particular warehouse

Also not just stocks type in warehouse (which is a good idea), but also please make the stock query work in standalone and specified in docs
Thanks

**Comment by teddyondieki** [comment]
> > I can help with this by:
> > 
> > 1. Updating the documentation to fix the said discrepancy
> > 2. Add a `stocks` field to the `warehouse` type to allow the fetching of stocks related to a particular warehouse
> 
> Also not just stocks type in warehouse (which is a good idea), but also please make the stock query work in standalone and specified in docs Thanks

I was able to fetch a single `stock` using it's id (not a warehouse ID which seems to be a mistake in the docs):

<img width="710" alt="Screenshot 2024-04-06 at 12 03 19" src="https://github.com/saleor/saleor/assets/28693198/5a072bff-dd9f-4263-b311-1b0983e7b31c">

**Comment by supersilverlemonhaze** [comment]
Okay then in this case please add the stocks property to warehouse. It is
crucial to be able to see a warehouses stock without having to load the
entire stock from the database and then filter by warehouse.
Please provide a timeline also 🙏

Teddy Ondieki ***@***.***> schrieb am Sa. 6. Apr. 2024 um
16:05:

**Comment by teddyondieki** [comment]
@korycins mind reviewing [this](https://github.com/saleor/saleor/pull/15771)?

**Comment by aniav** [comment]
Thank you for fixing this @teddyondieki 🙌
