### ISSUE TITLE
Bug: 'NoneType' object is not iterable when TransactionUpdateInput field is null

### ISSUE THREAD

**Issue by djkato** [saleor/saleor#15803]
### What are you trying to achieve?

```json
{
  "query":"mutation TransactionUpdate($id: ID!, $transaction: TransactionUpdateInput) {
  transactionUpdate(id: $id, transaction: $transaction) {
    transaction {
      id
      actions
      externalUrl
      message
    }
    errors {
      field
      message
      code
    }
  }
}",
  "variables": {
    "id":"VHJhbnNhY3Rpb25JdGVtOjJiZmE5NDBhLWYzM2QtNGJkZC1hZmM3LWE1ZmM4MWZjM2Y0ZA==",
    "transaction": {
      "name":null,
      "message":"{\"payment_method\":\"cash\"}",
      "pspReference":null,
      "availableActions":null,
      "amountAuthorized":null,
      "amountCharged":null,
      "amountRefunded":null,
      "amountCanceled":null,
      "metadata":null,
      "privateMetadata":null,
      "externalUrl":null
    }
  },
  "operationName":"TransactionUpdate"
}
```

### Steps to reproduce the problem

Try to update a transaction, set some of the fields mentioned above to null. Not sure which, can't test that right now, but I know that's the issue like I had before #13694 

### What did you expect to happen?

It to not fail, those fields are described as optional in TransactionUpdateInput

### Environment

Saleor version: 3.19.0
OS and version: Linux, but saleor runs in docker containers

**Comment by maarcingebala** [comment]
Thanks for reporting, we'll look into that.

**Comment by SarthakNikhal** [comment]
@maarcingebala Can I work on this issue?

**Comment by tomaszszymanski129** [comment]
@SarthakNikhal Sorry, we had that in our cycle and while I was fixing small bugs I fixed that as well. I'll take care of this one and backport it.
