### ISSUE TITLE
Unclear  “We’re sorry, something went wrong when attempting to sign up” error message for cases when a username has already been taken

### ISSUE THREAD

**Issue by bkemboi394** [saleor/saleor#15879]
### What are you trying to achieve?

I get a “We’re sorry, something went wrong when attempting to sign up” error message when I attempt to sign up to Lush's, a Saleor-powered online store, website with an already registered email address, which is not a user-friendly error message. A more appropriate error message would let a customer know the specifics of the problem so they can act accordingly. I believe it is probably in its source code.

### Steps to reproduce the problem

Test through Lush's front-end URL page.

### What did you expect to happen?

I expected to get a more specific error message like "That username has already been taken."

### Environment

Sign up page of Saleor-powered online cosmetics store, Lush.

**Comment by Akash5908** [comment]
Hii @timuric is this error resolved ? if not, could you please assign this issue to me?

**Comment by divyanshu-in** [comment]
@timuric I can't find such error anywhere in codebase, I assume that Lush is a fork of saleor, in that case this issue is not relevant to the repo.

**Comment by aniav** [comment]
@bkemboi394 the source of this error message is not coming from Saleor. You could try reporting to Lush directly [through their Customer care](https://www.lush.com/uk/en/faq/contact-us) 🙌
