### ISSUE TITLE
Bug: requirements.txt file missing 

### ISSUE THREAD

**Issue by MrShahidBabar** [saleor/saleor#15871]
### What are you trying to achieve?

Bug: requirements.txt file missing

### Steps to reproduce the problem

Bug: requirements.txt file missing

### What did you expect to happen?

Bug: requirements.txt file missing

### Environment

Saleor version: …
OS and version: …

**Comment by patrys** [comment]
It's not missing, it's not supposed to be there. Use `poetry` to install the dependencies.
