### ISSUE TITLE
saleor.product.tasks.recalculate_discounted_price_for_products_task doesn't auto trigger.

### ISSUE THREAD

**Issue by jottunn** [saleor/saleor#15892]
### What are you trying to achieve?

I'm trying to add discounts to products but no matter how long I wait, the discounts don't get applied.
Manually triggering the task saleor.product.tasks.recalculate_discounted_price_for_products_task works though.

### Steps to reproduce the problem

1. Go to dashboard->Discounts->Create Discount->Add rule: fill in name, channel->Add condition: Products; is; product.-> Save.
2. Wait for celery beat schedule to kick in.

### What did you expect to happen?

Price to be recalculated.

### Environment

Saleor version: latest saleor-platform
OS and version: docker from saleor-platform

**Comment by leena-valoriz** [comment]
@jottunn  CELERY_BEAT_SCHEDULER = "saleor.schedulers.schedulers.PersistentScheduler"

This line should be included in the settings.py file so the periodic task scheduler works by default.

**Comment by LeenaSomanS** [comment]
@jottunn 
CELERY_BEAT_SCHEDULER = "saleor.schedulers.schedulers.PersistentScheduler"

This line should really be included in the settings.py file so the periodic task scheduler works by default

**Comment by jottunn** [comment]
> @jottunn CELERY_BEAT_SCHEDULER = "saleor.schedulers.schedulers.PersistentScheduler"
> 
> This line should really be included in the settings.py file so the periodic task scheduler works by default

It worked. THANKS!
