### ISSUE TITLE
Bug: I can't get credit card information on order details mutation

### ISSUE THREAD

**Issue by ttvan20** [saleor/saleor#16000]
### What are you trying to achieve?

I tried to get credit card information on querying [order detail](https://docs.saleor.io/docs/3.x/api-reference/orders/objects/order), but it always returns empty for payments object and I can't get credit card information from it, not sure why? Do I missing anything?

### Steps to reproduce the problem

Query:
```
{
  order(id: "T3JkZXI6...") {
    payments {
      creditCard {
        brand
        expMonth
        expYear
        firstDigits
        lastDigits
      }
    }
  }
}
```

Response:
```
{
  "data": {
    "order": {
      "payments": []
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 2,
      "maximumAvailable": 50000
    }
  }
}
```

### What did you expect to happen?

I can get credit card information on order details mutation

### Environment

Saleor version: 5.15

**Comment by korycins** [comment]
Hey @ttvan20  
Did you mean Saleor in 3.15 version - You provided 5.15. 

From the sample that you provided, it looks like you have an order without `payments` objects. It means that you created the order from a draft or with the help of App. In the case of using App to process a payments, `payments` list will be empty as this field is related to PaymentAPI. App to process the payments uses [TransactionAPI](https://docs.saleor.io/docs/3.x/developer/payments#payment-app).

For PaymentAPI (used by payment plugins), credit card details are set by PaymentPlugin (but from the above example, this field is empty, so you probably don't use payment plugins). 
For TransactionAPI, we don't have fields to explicitly store the payment details (as described [here](https://github.com/saleor/saleor/issues/15247)). As a workaround, your payment app can store it in the metadata of TransactionItem.
To clarify, if the order from the example was created from a draft, it will not have any credit card details as we don't have any payment related to the order.

**Comment by aniav** [comment]
I will close the issue for now as it's lacking details. Feel free to reopen when you are ready 🙌
