### ISSUE TITLE
Bug: Having trouble white 'Installing and Managing Apps'

### ISSUE THREAD

**Issue by dev-shajid** [saleor/saleor#16108]
### What are you trying to achieve?

I was following all the steps to extend saleor app. But i was not able to connect server api with client, then i realized i skiped 'Installing and Managing Apps' steps. So, I was trying to follow, but i am not getting sufficient instruction. Please help me to do this step by step.🙏🥺

### Steps to reproduce the problem

.

### What did you expect to happen?

I was expecting to connect my extended app for dashboard with server

### Environment

Saleor version: …3.19
OS and version: …mac os

**Comment by aniav** [comment]
Hey @dev-shajid we will need more details to be able to help you 🙌
