### ISSUE TITLE
Bug: Product quantity in cart cannot be adjusted when it exceeds the available quantity

### ISSUE THREAD

**Issue by khalibloo** [saleor/saleor#16155]
### What are you trying to achieve?

When a user adds a certain quantity of a product to their cart, then the product quantity subsequently falls below that value, the cart cannot be checked out nor updated to return to the new quantity limit.

### Steps to reproduce the problem

1. Add 10 units of a product to cart
2. From the admin dashboard, decrease the available quantity of that product to 5

### What did you expect to happen?

The user should be able to update the quantity of that product in their cart to 5 or lower.

### Environment

Saleor version: 3.15.0
OS and version: Docker on Windows 10

**Comment by maarcingebala** [comment]
@khalibloo What happens when you try to update this quantity as per the steps provided? Is there any error thrown? Could you provide an example API response?

**Comment by khalibloo** [comment]
@maarcingebala we were getting the following error when following the steps above
```
{
    code: 'INSUFFICIENT_STOCK',
    field: 'quantity',
    message: 'Could not add items 352847529757. Only 5 remaining in stock.'
}
```

However, now I'm not able to consistently reproduce it in a different Saleor instance. I'll close it for now, as it seems like it might only affect some products/configurations but not others. I'll try to narrow down the exact circumstances first.

**Comment by maarcingebala** [comment]
Thanks. Also, I recommend upgrading to a newer version of Saleor, which has more bugfixes but also more performance improvements.
