### ISSUE TITLE
Multi Vendor

### ISSUE THREAD

**Issue by arimtiaz** [saleor/saleor#16187]
I want to build a marketplace using Saleor but could'nt find anyway to build the multi-vendor system. I want allow sellers to open up stores in my marketplace, how do i it?

**Comment by maarcingebala** [comment]
Hey @arimtiaz, Saleor does not currently support multi-vendor setup, and it is not on our roadmap to introduce such a feature. For more information, you can refer to [other tickets](https://github.com/saleor/saleor/issues/1251) on GitHub.

**Comment by arimtiaz** [comment]
Is there anyway to extend saleor to build this feature if i want?

**Comment by maarcingebala** [comment]
This feature hasn't been refined, and there's no RFC or anything similar, so the extent of the change is unknown, but I assume it would involve a significant scope of changes.
