### ISSUE TITLE
Bug: Cannot query order.user with custom app

### ISSUE THREAD

**Issue by khalibloo** [saleor/saleor#16199]
### What are you trying to achieve?

Query an order and the ID of the user it belongs to.

### Steps to reproduce the problem

1. Create a custom saleor app with MANAGE_ORDERS permission
2. Query an order that belongs to an authenticated customer, and include the order.user.id field

### What did you expect to happen?

The user should be returned as part of the order. However, while the other fields are populated, the user field is null in the response. Even granting the app MANAGE_USERS does not fix the issue. However, the same query run using a superadmin token to fetch the same order, will return the user.

### Logs

Query
```gql
{
  order(id: $id) {
    id
    number
    user {
      id
      email
    }
  }
}
```

### Environment

Saleor version: 3.19
OS and version: Docker on Windows 10

**Comment by korycins** [comment]
Hey @khalibloo 
Can you provide more details? 
I just tested the app with MANAGE_USERS, and app with MANAGE_ORDERS. In both cases, I've received the order.user details. Are you sure that the user is assigned?
![image](https://github.com/saleor/saleor/assets/23282005/5e25d2b7-82a3-4be3-9604-6a4440b24d5e)
![image](https://github.com/saleor/saleor/assets/23282005/ec289f7f-f58e-4bba-a3a0-ed6512bc8388)

**Comment by khalibloo** [comment]
Thanks for checking. That led me to the solution. I was sure that my app's token was being applied to the requests because if it wasn't, I shouldn't have been able to query the order itself. But it actually was not being applied. When I queried app permissions like you did, app was also null.

I tried querying the order without a token, and while there was an error, I still got the order data in the response, just with user and app being null. That should probably not be the case, right?

**Comment by korycins** [comment]
The order ID is UUID, so it is not guessable as an int value. So if you have an orderID, you can fetch the order details. 

>  I still got the order data in the response, just with user and app being null. That should probably not be the case, right?

As you didn't have a permission to fetch the user/app details you received the error, but you still had access to the rest of the fields, this is why you get partial results. Same behaviour as here:
![image](https://github.com/saleor/saleor/assets/23282005/f810f470-f6d6-4f6c-a547-896e92a27e7a)
