### ISSUE TITLE
Allow to translate ProductType name

### ISSUE THREAD

**Issue by pawelromanskidajar** [saleor/saleor#16224]
## Problem

I would like to display product type name on the storefront to keep consistent product names. However, product types are not translatable, which means that it will not work in multilanguage setup 

---

## 1. General Assumptions

Allow to translate ProductType name

## 2. API changes

Add PRODUCT_TYPE to TranslateableKinds
Add translation to ProductType

**Comment by maarcingebala** [comment]
Product types are meant for internal use to organize products and assign their attributes. If you want to organize products in the storefront, you might use Categories, which are translatable.

**Comment by pawelromanskidajar** [comment]
I can work around this limitation for sure, but I am not fully convinced to your approach. Note that querying product type doesn't require any permissions, so it is not purely internal. For instance: product type defines what filters are available to the user. Being able to display product type name helps to explain client why given product has certain attributes. Tax class is also defined there, etc. Wouldn't it make sense in some cases to display to a client "VAT rate for this product is X, because it is XYZ" ? 

I would not say this feature is a must have, but adding it would make Saleor more consistent imho.
