### ISSUE TITLE
Clarification on Permissions via Graphql API

### ISSUE THREAD

**Issue by navinkrishna-tb** [saleor/saleor#16223]
### What are you trying to achieve?

I have installed saleor platform with docker. From dashboard I am able to add a new product. But from api I am getting permission error. I have granted all the permission from dashboard. Still I am getting the same error. Please let me know how to resolve the issue.

### Steps to reproduce the problem

**Query.**
mutation ProductCreate($input: ProductCreateInput!) {
  productCreate(input: $input) {
    errors {
      ...ProductErrorWithAttributes
      __typename
    }
    product {
      id
      __typename
    }
    __typename
  }
  
}

fragment ProductErrorWithAttributes on ProductError {
  ...ProductError
  attributes
  __typename
  
}

fragment ProductError on ProductError {
  code
  field
  message
  __typename
}

**Variables**
{
  "input": {
    "attributes": [
      {
        "id": "QXR0cmlidXRlOjM2",
        "values": [
          "cotton"
        ]
      }
    ],
    "category": "Q2F0ZWdvcnk6MjU=",
    "collections": [
      "Q29sbGVjdGlvbjo1"
    ],
    "description": "{\"time\":1719572752120,\"blocks\":[{\"id\":\"8LfOJVHp94\",\"type\":\"paragraph\",\"data\":{\"text\":\"sdfsdf\"}}],\"version\":\"2.24.3\"}",
    "name": "Hello",
    "productType": "UHJvZHVjdFR5cGU6MjE=",
    "rating": "5",
    "seo": {
      "description": "",
      "title": ""
    },
    "slug": "",
    "taxClass": "VGF4Q2xhc3M6Mg==",
    "weight": 34
  }
}

Header
{
  "Authorization": <"token">
}

### What did you expect to happen?

Create product without any permission error.

### Environment

Saleor version: …
OS and version: …

**Comment by delemeator** [comment]
Hey,

Aren’t you missing „Bearer” part in authorization header?

https://docs.saleor.io/docs/3.x/api-usage/authentication

POST /graphql/ HTTP/1.1
...
Authorization: Bearer <app-token>

**Comment by navinkrishna-tb** [comment]
Hi delemeator,
Thanks for your awesome response. The issue is resolved.

Regards,
Navin Krishna T B
