### ISSUE TITLE
Bug: Creating order with 0 total (voucher applied) and no transactions results in "UNCONFIRMED" order that is "FULLY PAID"

### ISSUE THREAD

**Issue by vhejda** [saleor/saleor#16238]
### What are you trying to achieve?

**Background**

In our setup, we allow users to apply vouchers that result in the order total being zero. In that scenario, we are skipping `transactionInitialize` and `transactionProcess` calls, and immediately call `completeCheckout`.

**Current behaviour:**

This results in order being created in the system in the `UNCONFIRMED` state, while having `FULLY_PAID` payment status.
In comparison with a non-zero order, that has a transaction linked to it, that leads to order being created in `UNFULFILLED` state.
This not only forces us to manually confirm the zero orders, but it also has a negative impact on other apps - for example our Fulfilment app rejects an unconfirmed order, so the goods are not dispatched from the warehouse.

### Steps to reproduce the problem

1. Set up a channel with `Allow unpaid orders` and `Use Transaction flow when marking order as paid` both set to true.
2. Set up discount voucher for fixed amount
3. Create checkout with items total lower than the voucher, and apply the voucher
4. Call `completeCheckout`.

### What did you expect to happen?

I am struggling to see how this is the desired behaviour. This would be what I would expect:

1. `completeCheckout` is called
2. System checks if there is authorized transaction OR the total is 0
3. Order is created with `UNFILFILLED` state

### Environment

Saleor version: v3.19.40 (self-hosted)

**Comment by IKarbowiak** [comment]
Hi @vhejda,

Thank you very much for reporting this issue. You are right; the behavior you described is not expected. The created order should be in `UNFILFILLED` status, just as it is when the `Use Transaction flow when marking the order as paid` flag is set to False. We will look into it. However, if this is an important issue for you, feel free to prepare a fix yourself—PRs are welcome! :)

**Comment by vhejda** [comment]
Hi @IKarbowiak ,
Thank you for the confirmation on the business logic there! And we really appreciate Saleor, it's been great working with it so far :)

My python skills are a bit rusty but I'll see if I can pinpoint the problematic place in the code.

**Comment by IKarbowiak** [comment]
It's great to hear that ❤️ 

Regarding the issue, it looks like [here](https://github.com/saleor/saleor/blob/main/saleor/checkout/complete_checkout.py#L1239) is the place that should be changed - instead of `checkout_info.checkout.payment_transactions.exists()` we could check if the authorize status is `FULL` (`checkout.authorize_status == CheckoutAuthorizeStatus.FULL`)

**Comment by vhejda** [comment]
Also, not sure if I should create a separate bug for this, but the `ORDER_CONFIRMED` event is fired regardless of the order status, if the `automatically_confirm_all_new_orders` is set to true.
So currently it happens to us that we receive this event and in the payload there is `UNCONFIRMED` order.

**Comment by IKarbowiak** [comment]
That's related to this issue, so I think you can just extend the issue description with this founding 🙂

**Comment by IKarbowiak** [comment]
Hi @vhejda.

It looks like your problem is already solved from v[3.19.58](https://github.com/saleor/saleor/releases/tag/3.19.58) (fixed by this [PR](https://github.com/saleor/saleor/pull/16244)), so I'm closing the issue.
