### ISSUE TITLE
checkoutCreate fails with error { "field": "discountAmount",  "code": "INVALID"}  if I set DEFAULT_DECIMAL_PLACES = 0

### ISSUE THREAD

**Issue by ilonamanole** [saleor/saleor#16273]
### What are you trying to achieve?

I want to display the prices on the webshop with no decimals. I changed settings.py with DEFAULT_DECIMAL_PLACES = 0
After this change, checkoutCreate mutation fails with error. 

### Steps to reproduce the problem

1. Update DEFAULT_DECIMAL_PLACES = 0 in settings.py
2. Use GraphQL playground and run a checkoutCreate mutation
3. The result:  {
  "data": {
    "checkoutCreate": {
      "checkout": null,
      "errors": [
        {
          "field": "discountAmount",
          "code": "INVALID"
        }
      ]
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 5,
      "maximumAvailable": 50000
    }
  }
}

### What did you expect to happen?

No errors and checkout be created

### Environment

Saleor version:  v3.19.58
OS and version: docker from saleor-platform

**Comment by IKarbowiak** [comment]
Hi @ilonamanole,

Thank you for reporting the issue. Can you describe what is your use case for setting `0` as `DEFAULT_DECIMAL_PLACES`?

**Comment by ilonamanole** [comment]
Hi @IKarbowiak ,
I would like to display and use prices without any decimal points. So, all the prices, including discounted prices, should not contain any decimals. If for e.g. I apply 15% to  3642, the price should be calculated as 3095 and not 3095.7 
Is this what you are asking me, or need more info? I apppreciate any help with this.

Thank you!

**Comment by IKarbowiak** [comment]
@ilonamanole, the `DEFAULT_DECIMAL_PLACES` shouldn't be changed. It only determines how many decimal places will be saved on DB. In the API the prices are returned with the rounding that depends on the currency, so e.g. if your prices are in `JPY` 0 decimal places will be returned. I hope it helps 😊

**Comment by ilonamanole** [comment]
@IKarbowiak thank you for your answer. 
My currency is RON, that means 2 decimals. So, it's not possbile for me to have the prices calculated and saved in DB with no decimals? I have to choose JPY to achieve this? Changing DEFAULT_DECIMAL_PLACES to 0, behaves as expected. The prices are calculated ok, they are saved with no decimals in DB, everything is fine, until I want to add a product to cart (create new checkout)

I looked in the  sourcecode, and I found the field (for which I receive the error) in /saleor/checkout/models.py 
    discount_amount = models.DecimalField(
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=Decimal("0.0"),
    )
As you can see its default is Decimal("0.0") and it takes decimal_places from settings.DEFAULT_DECIMAL_PLACES
All the other prices defined in models.py that use settings.DEFAULT_DECIMAL_PLACES, have  default=Decimal(0)
On contrary, those with default=Decimal("0.0"), have decimal_places=4 and max_digits=5 (so, they don't take their values from settings)

I made a test and build the container with a changed models.py, run the migrations etc. The prices are all saved correctly, a new checkout can be created with success. 
I am not sure if there is any reason that only discount_amount, although it takes DEFAULT_DECIMAL_PLACES  has the default=Decimal(0,0), but it seems this triggers the error for a new checkout when I set DEFAULT_DECIMAL_PLACES=0


Thank you again for looking into this.

**Comment by aniav** [comment]
@ilonamanole you don't need to modify `DEFAULT_DECIMAL_PLACES` at all. You should configure a channel to use with `RON` `currencyCode` and the prices will be saved and returned with the right currency.

I'll close the issue for now, feel free to reopen if this won't work for your case 🙌
