### ISSUE TITLE
Bug: It is no longer possible to reinstall the application

### ISSUE THREAD

**Issue by i-n-n-k-e-e-p-e-r** [saleor/saleor#16387]
### What are you trying to achieve?

After [3.20.1](https://github.com/saleor/saleor/releases/tag/3.20.1) it is no longer possible to reinstall the application (cloud and self hosted).
I think it's all because [#16272](https://github.com/saleor/saleor/pull/16272).

### Steps to reproduce the problem

1. Delete the existing application from dashboard.
2. Try not to install the same application again.

### What did you expect to happen?

Be able to uninstall the application and install it again, especially when developing using tunnels where the domain name may be changed.

### Logs

![reinstall_app_bug](https://github.com/user-attachments/assets/dca0c2bc-cdf7-4dc4-892d-f0420bbca6c1)

### Environment

Saleor version: >=3.20.1, >=3.19.61
OS and version: …

**Comment by maarcingebala** [comment]
Thanks for reporting, we also discovered the issue internally, and we'll be working on a fix 🙌

**Comment by aniav** [comment]
This has been fixed in 1a5d82fd938ff2b91c5a9c3c4b5e0535041d664b and 3.20.4+
