### ISSUE TITLE
Allow for localized/translated slugs

### ISSUE THREAD

**Issue by delemeator** [saleor/saleor#16449]
## Problem

For multi language e-commerce store I would like to be able to use localized urls for each language. At the moment this requires creating a separate service with slug translation logic which would impact both performance and convenience for the staff (having to translate slugs in another application)

Url design is a matter preference, but it is not uncommon to use loclalized urls and it is recommended by Google:
```
Recommended: Localized words in the URL, if applicable.

https://www.example.com/lebensmittel/pfefferminz
```
https://developers.google.com/search/docs/crawling-indexing/url-structure

---

## 1. General Assumptions

Allow to translate slugs and to query on them

### Acceptance Criteria

- [ ] Allow to translate slugs for product, category, collection and page
- [ ] Allow to query product/category/collection/page by translated slug
- [ ] Ensure backward compatibility - current way of using slug should not be affected by the changes

### Types

Add slug to TranslationInput and PageTranslationInput for use in mutations:
- categoryTranslate
- collectionTranslate
- productTranslate
- pageTranslate

### Queries

Add optional argument slugLanguageCode for queries:
- product
- category
- collection
- page

If slugLanguageCode is provided, those queries should return product with specified slug translation. Otherwise, it would use regular slug field

## 3. Database changes

Add field slug (nullable) to:
- product_collectiontranslation
- product_categorytranslation
- product_producttranslation
- page_pagetranslation

Add unique constraint on languageCode and slug (conditional on slug not null)

Please let me know if you would accept such change. I would be happy to contribute on that

**Comment by korycins** [comment]
Related discord thread: https://discord.com/channels/864066819866624010/1266378575250980955

**Comment by kadewu** [comment]
LGTM!

From my side, when implementing this feature please remember about adding indexes concurrently: https://docs.saleor.io/developer/community/zero-downtime-migrations#adding-the-index-to-the-database

I'm mentioning this cause unique constraint creates `UNIQUE INDEX` and such index needs to be added as explained above.

And maybe small note, no need for explicitly creating conditional unique constraint depending if slug is null or not.
