### ISSUE TITLE
Bug: Discounts not working

### ISSUE THREAD

**Issue by supersilverlemonhaze** [saleor/saleor#16485]
### What are you trying to achieve?

Create a discount in the dashboard for either a product a variant or a category

### Steps to reproduce the problem

1. Created a product in default category w variant, price stock etc.
2. Created discount with rule percentage 10% and applied to category. when it didnt work added product and then variant. Tried with either of these and all together.
3. When querying simply the product it should onSale: false under product variant pricing. discount: null. when querying a category that a discount is applied to and then its products with variants also shows the same.
I was only able to see a discount when i applied promoCodes inside the checkout thats it

### What did you expect to happen?

That discounts are working ...

### Environment

Saleor version: 3.20 ...
OS and version: …

**Comment by korycins** [comment]
The discounted prices are calculated in the [background](https://docs.saleor.io/developer/discounts/promotions#saleor-319). You need to have a proper set up of celery and celery-beat.
Here, you can find additional info: https://github.com/saleor/saleor/discussions/14617#discussioncomment-9126977

**Comment by aghobrial** [comment]
I noticed the same thing in a local development environment. I restarted the containers and then started seeing discounts on the correct products.

**Comment by supersilverlemonhaze** [comment]
Crazy that this is still not on the main branch.

We were even thinking of starting without displaying product price
discounts …

Andrew Ghobrial ***@***.***> schrieb am Do. 8. Aug. 2024 um
09:03:

**Comment by aniav** [comment]
I'll close the issue for now. The changes are available in Saleor versions from 3.18.70 and all the newer versions. The changes are available on the main branch since April 2024.

We will see how we can make it more visible in the docs that you have to have celery running in order to get up to date prices from promotions. Sorry you had to learn the hard way!

Feel free to reopen if you encounter problems again 🙌
