### ISSUE TITLE
RFC: Avatax & manual discounts compatibility

### ISSUE THREAD

**Issue by zedzior** [saleor/saleor#16613]
## Problem

The Avatax app does not have enough information on how to distribute order-level discounts over the lines, resulting in incorrect tax calculations. 

Saleor sends taxation data to Avatax in a form of `TaxableObject` type, which contains all order level discounts inside a single list with two attributes only:`name` and ` amount`. Therefore Avatax doesn't have information if the discount should reduce the value of subtotal, shipping or both. 

Currently, it distributes all the discounts in the same way: proportionally reduce all the lines including shipping (in Avalara, shipping is treated as an order line). 
Saleor offers following order-level discounts:

- manual (applied to both subtotal and shipping price)
- entire order voucher (applied to subtotal)
- shipping voucher (applied to shipping price)
- order promotion on subtotal (applied to subtotal)

### Core
1. Enrich `TaxableObjectDiscount` with `type` field which would be an enum with two values: `SUBTOTAL` and `SHIPPING` 
2. Adjust `TaxableObject.resolve_discounts` to split manual discounts into two `TaxableObjectDiscount` objects: subtotal portion of type `SUBTOTAL` and shipping portion of type `SHIPPING`
3. All order level discounts should be type of `SUBTOTAL`, except shipping portion of manual discount (shipping vouchers are already included in shipping base price)

### App
1. Sum all discounts of type `SUBTOTAL` and place the value in the `discount` field.
2. Sum all discounts of type `SHIPPING` and deduct it from the line representing shipping.
3. All order lines, except shipping line, should be flagged `discounted=True` if any `SUBTOTAL` discount exists.
4. Shipping line should be always flagged as `discounted=False`

## 2. API changes

```graphql
type TaxableObjectDiscount(BaseObjectType):
    name = graphene.String(description="The name of the discount.")
    amount = graphene.Field(
        Money, description="The amount of the discount.", required=True
    )
    type = TaxableObjectDiscountType(   # new field
        required=True,
        description="Indicate which part of the order the discount should affect: SUBTOTAL or SHIPPING.",
    )
```

```graphql
enum TaxableObjectDiscountType {  # new enum
    SUBTOTAL
    SHIPPING
}
```

## 3. Database changes

no changes

## 4. Example

- Line 1: 30$
- Line 2: 50$
- Subtotal: 80$
- Shipping: 20$
- Manual discount with fixed value 10$
- Voucher entire order 20$
- Manual discount subtotal portion: 8$
- Manual discount shipping portion: 2$

	
TaxableObject.discounts should return:

```json
{
    "discounts":	[
	{
            "name": "voucher name",
 	    "amount": 20,
	    "type": "subtotal",
         },
	{
            "name": "manual discount name",
 	    "amount": 8,
	    "type": "subtotal",
         },
	{
            "name": "manual discount name",
 	    "amount": 2,
	    "type": "shipping",
         },
]}
```

App should convert it to Avalara payload:

```json
{
	…
	"discount": 28
        "lines": [
	     {"amount": 30, "discounted": true, "description": "Line 1", ...},
	     {"amount": 50, "discounted": true, "description": "Line 2", …},
             {"amount": 18, "discounted": false, "description": "shipping line", …}
         ]
          …
}
```

**Comment by krzysztofwolski** [comment]
Would like to suggest adding "hard references" (voucher and discount) to `TaxableObjectDiscount`, name alone is not enough:
- its not translatable
- no way to pull more data from souce object (discount/voucher) like:
    - metadata
    - code
    - percentage value (if it was percantage type discount)
- debugging will be harder without it (names are not unique in the system)

The same interace will be on both checkout and order?

**Comment by IKarbowiak** [comment]
@zedzior shouldn't be closed?
