### ISSUE TITLE
Bug: Product quantity not updated to zero after order fulfillment

### ISSUE THREAD

**Issue by supreetha789** [saleor/saleor#16663]
### What are you trying to achieve?

We encountered an issue where, after fulfilling an order, the product quantity is supposed to be set to zero but remains at 1, causing the product to still appear as available for future orders. This results in users being able to place orders for products that are actually unavailable.

### Steps to reproduce the problem

1. Fulfill an order where the remaining product quantity should go to zero.
2. Check the product availability after the order is fulfilled.
3. Observe that the product quantity shows as 1 instead of 0.

### What did you expect to happen?

The product quantity should be set to zero after the order is fulfilled and should not be available for further orders.

### Environment

Saleor version: 3.18.10

**Comment by IKarbowiak** [comment]
@supreetha789 thank you for reporting the issue. 😊  We will verify this problem with the team.

**Comment by supreetha789** [comment]
Worked on updating to higher version of Saleor

**Comment by kadewu** [comment]
@supreetha789 Hello! Can you share your `Channel.orderSettings`? I'm unable to reproduce the issue.
You said that it only happens when you set quantity to `0`, but otherwise decreasing stocks works fine I suppose?
