### ISSUE TITLE
Bug: Category-specific Promocode Not Working in Checkout

### ISSUE THREAD

**Issue by supreetha789** [saleor/saleor#16722]
### What are you trying to achieve?

We encountered an issue where a promocode created for a specific category is not working during checkout. When the promocode is applied, the system throws an error instead of applying the discount.

### Steps to reproduce the problem

1. Create a promocode and associate it with a specific product category.
2. Add products from the specified category to the cart.
3. Proceed to checkout.
4. Apply the promocode.
5. The system throws an error instead of applying the discount.

### What did you expect to happen?

The promocode should apply successfully to items from the specified category during checkout, reducing the total amount as per the discount rules.

### Logs

This is the response we get for  when we apply Promocode though we have selected the products from the same category.
{
    "data": {
        "checkoutAddPromoCode": {
            "checkout": null,
            "errors": [
                {
                    "code": "VOUCHER_NOT_APPLICABLE",
                    "field": "promoCode",
                    "message": "Voucher is not applicable to this checkout.",
                    "variants": null,
                    "lines": null,
                    "__typename": "CheckoutError"
                }
            ],
            "__typename": "CheckoutAddPromoCode"
        }
    },

### Environment

Saleor version: 3.18.22

**Comment by supreetha789** [comment]
Category based promocode works on the subcategory level but not on selecting the parent category.

**Comment by tomaszszymanski129** [comment]
Hi @supreetha789, thanks for rising as issue, we have established in the team that this is intended behavior though. When you pass `categories` as a predicate, Saleor will look just for those specific, it's not looking for the subcategories of those categories.

**Comment by patrys** [comment]
I'd like to reopen this topic since I don't agree with the premise of this being the expected behavior.
