### ISSUE TITLE
Bug: Saleor apps installed using django command do not show up in the Saleor Dashboard

### ISSUE THREAD

**Issue by ceresnam** [saleor/saleor#16872]
### What are you trying to achieve?

Saleor apps installed using the Django command `manage.py install_app --activate <manifest_url>` do not show up in the Saleor Dashboard under Apps / Installed Apps, even if the installation using the Django command completed successfully.

### Steps to reproduce the problem

1. install Saleor app using Django command `manage.py install_app --activate <manifest_url>`
2. check new row was successfully added into `SELECT * FROM public.app_app`
3. open Saleor Dashboard / Apps
4. and section Installed Apps will be empty

### What did you expect to happen?

This is due to App.is_installed being False

Apps installed from Saleor dashboard end up handled in celery task install_app_task(), where this boolean gets set to True
https://github.com/saleor/saleor/blob/main/saleor/app/tasks.py#L34

### Logs

![image](https://github.com/user-attachments/assets/eff5fdf7-1e15-4703-a46b-b3a5216a086d)

### Environment

Saleor version: 3.20.37, git head

**Comment by ceresnam** [comment]
Proposed fix https://github.com/saleor/saleor/pull/16873

**Comment by korycins** [comment]
Solved by https://github.com/saleor/saleor/pull/16873
