### ISSUE TITLE
Bug: Invalid or expired token.

### ISSUE THREAD

**Issue by linhkiubo98** [saleor/saleor#16884]
### What are you trying to achieve?

I'm using the setPassword mutation and unable to reset the password for an account.

![image](https://github.com/user-attachments/assets/a3ac2f47-7152-4923-8d3b-a3370f73dd5d)

![image](https://github.com/user-attachments/assets/44b177db-9bf7-4430-a231-60039a1d2236)

### Steps to reproduce the problem

![image](https://github.com/user-attachments/assets/7ce1230a-493e-4547-89f9-8baa3fc38252)

### What did you expect to happen?

I want to change my password

### Logs

{
  "data": {
    "setPassword": {
      "accountErrors": [
        {
          "field": "token",
          "message": "Invalid or expired token.",
          "code": "INVALID"
        }
      ],
      "user": null
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 0,
      "maximumAvailable": 50000
    }
  }
}

**Comment by aniav** [comment]
Hey @linhkiubo98 how have you obtained the token that you are using? It doesn't seem like a problem with the mutation at a first glance, more like an expired token. In order to help we need more details.

**Comment by aniav** [comment]
I will close the issue for now as it's lacking details. Feel free to reopen when you are ready 🙌
