### ISSUE TITLE
Bug: The graphl fragment structure is not being updated.

### ISSUE THREAD

**Issue by oqildev** [saleor/saleor#17003]
### What are you trying to achieve?

I changed the graphl fragments according to the new structure. And I did "npm run fetch-schema". And I cleared the browser cache and restarted saleor. The site worked, but if I refresh the browser again or after a while, graphl sends a request to the api for the old fragment structure. I changed all the file structures inside /fragments. And I did npm run fetch-schema and npm run dev. The problem was not solved.
![Screenshot_10](https://github.com/user-attachments/assets/60ee507a-3b02-4d1e-925d-1b4d336df8d1)
![Screenshot_11](https://github.com/user-attachments/assets/9286ac92-879e-4c5f-91c7-f9049177956b)

### Steps to reproduce the problem

1. I modified the fragments using Playground in Saleor.
2. Run npm run fetch-schema, npm run dev
3. When the browser refreshes the page, the old Saleor structure is requested again.

### What did you expect to happen?

I want to change the graphl fragment structure. According to our backend structure.

### Environment

Saleor version: 3.21.0-dev
OS and version: windows 10

**Comment by maarcingebala** [comment]
Hi @oqildev, I'm not sure if this is a problem precisely with the Saleor API. Saleor doesn't provide the `npm run fetch-schema` command that you describe. I think the problem may be related to that command or to the way your frontend app makes calls to the Saleor API.

**Comment by oqildev** [comment]
So how do we update and generate graphl fragments?  In what order is it done?
