### ISSUE TITLE
[FEATURE REQUEST] Add e2e test

### ISSUE THREAD

**Issue by anon-pradip** [saleor/saleor#17033]
## Problem

 The repository currently lacks any end-to-end (e2e) tests. I recommend adding e2e tests to the repository to ensure code robustness and I propose adding e2e tests to the repository utilizing Playwright and Cucumber. These tools offer a robust framework for Behavior-Driven Development (BDD) testing, allowing us to define test scenarios in plain language and automate interactions with the application. Adding e2e tests will significantly enhance the quality of the codebase by identifying potential issues early in the development cycle. It will also increase confidence in code changes and facilitate smoother deployments.

**Comment by aniav** [comment]
Hey @anon-pradip inside Saleor we work with various levels of testing:
- unit tests (13 000+ of those in this repository)
- e2e tests (181 of those [in this repository](https://github.com/saleor/saleor/tree/main/saleor/tests/e2e))
- load tests, integration tests, migration ingegritity tests in various places in and outside of this repository
- we do have tests using Playwright outside of the core saleor repository, you can [check their config in saleor-dashboard repository](https://github.com/saleor/saleor-dashboard/blob/main/playwright.config.ts)

Feel free to reopen this issue if you find missing pieces that you think are still missing. I'll go ahead and close this for now 🙌
