### ISSUE TITLE
Bug: Apps page has issue

### ISSUE THREAD

**Issue by charleslcso** [saleor/saleor#17119]
### What are you trying to achieve?

First time user of Saleor. Exploring the application.

### Steps to reproduce the problem

Come across this error when trying to enter "Apps" page.
![Screen Shot 2024-12-02 at 3 35 00 PM](https://github.com/user-attachments/assets/f8bb8d52-3afd-41de-b161-50c30a66a30f)

### What did you expect to happen?

No error.

### Logs

No error in log.
No error in web browser console.

### Environment

dashboard v3.20.20
core v3.20.56

**Comment by aniav** [comment]
Thank you for the report @charleslcso. I've created a bug report for our team to address.

Internal link to track: https://linear.app/saleor/issue/MERX-1323/apps-marketplace-not-loading-in-dashboard-32020

**Comment by Cloud11PL** [comment]
Hi @charleslcso, 

can you confirm that you have correctly set up `APPS_MARKETPLACE_API_URL` environment variable for Saleor Dashboard? The alert you have attached appears when the url is incorrect. Please use the following value and let me know if that has fixed the issue for you 😸 
`APPS_MARKETPLACE_API_URL=https://apps.saleor.io/api/v2/saleor-apps`

**Comment by charleslcso** [comment]
@Cloud11PL Hello

I've added this line above.

`
root@saleor:/opt/saleor-platform# cat .env
APPS_MARKETPLACE_API_URL=https://apps.saleor.io/api/v2/saleor-apps
root@saleor:/opt/saleor-platform# 
`

Restarted the docker containers. Nope same error.

**Comment by Cloud11PL** [comment]
@charleslcso could you share what is in the `__SALEOR_CONFIG__` object from the console in your browser?

If you're using `saleor-platform` the `APPS_MARKETPLACE_API_URL` should be set with default values. Do you modify environment variables in any way? Did you follow our guide regarding [running Saleor locally](https://docs.saleor.io/quickstart/running-locally)?

**Comment by charleslcso** [comment]
me bad. i was putting that line in .env. Now i put it in backend.env. Restarted the container. Same issue.

Here is the console warning

![Screen Shot 2024-12-09 at 11 17 02 PM](https://github.com/user-attachments/assets/d0117587-1681-48fb-b295-30ebc19a5791)

Here are the output of backend.env:

`root@saleor:/opt/saleor-platform# cat backend.env `
`CELERY_BROKER_URL=redis://redis:6379/1`
`DATABASE_URL=postgres://saleor:saleor@db/saleor`
`DEFAULT_FROM_EMAIL=shopadmin@tourdefarm.com`
`EMAIL_URL=smtp://shopadmin@tourdefarm.com:thickkid12345@mail.tourdefarm.com:25/?tls=True`
`SECRET_KEY=changeme`             <- as "changeme", no actual key value
`PUBLIC_URL=https://saleor.tourdefarm.com`
`DASHBOARD_URL=https://saleor.tourdefarm.com/dashboard/`
`broker_connection_retry_on_startup=true`
`APPS_MARKETPLACE_API_URL=https://apps.saleor.io/api/v2/saleor-apps`

**Comment by charleslcso** [comment]
> @charleslcso could you share what is in the `__SALEOR_CONFIG__` object from the console in your browser?
> 
> If you're using `saleor-platform` the `APPS_MARKETPLACE_API_URL` variable should be set with a default value. Do you modify environment variables in any way? Did you follow our guide regarding [running Saleor locally](https://docs.saleor.io/quickstart/running-locally)?

Here the __SALEOR_CONFIG__ object is not pointing to the correct URL.

![Screen Shot 2024-12-10 at 12 02 17 PM](https://github.com/user-attachments/assets/002475d7-2321-49dd-94c4-0a5be73458a1)

This instance of saleor-platform is rebuilt using the guide "running Saleor locally". 

Searched the keyword `APPS_MARKETPLACE_API_URL` in `docs.saleor.io` and it is not found.

Which file should I put this `APPS_MARKETPLACE_API_URL`? backend.env or common.env? I'm sure it is a quick fix. 

Thank you.

**Comment by aniav** [comment]
Good that this is figured then 🎉

**Comment by charleslcso** [comment]
BTW, can you advise what key I should use for the dashboard to connect to backend? I can't use `API_URL` in this case...

**Comment by andrzejewsky** [comment]
@charleslcso what do you mean by saying "_key_", an env variable? why can't you use API_URL? this is exactly what sets the backend api.

**Comment by charleslcso** [comment]
From the result of putting API_URL=https://saleor.tourdefarm.com/graphql/, this overwrites the value in APPS_MARKETPLACE_API_URL. 

Dashboard can't run properly without connecting to my instance of Saleor Platform, and once I get it working I cannot connect to the Market Place.

Can you see the dilemma?
