### ISSUE TITLE
Bug: All thumbnails broken

### ISSUE THREAD

**Issue by charleslcso** [saleor/saleor#17120]
### What are you trying to achieve?

Try to upload another image into product "Gift card 50". 

Upon upload, under Media in the Product page blinked with a small version of the image, then it should the broken graphic.

![Screen Shot 2024-12-02 at 3 40 49 PM](https://github.com/user-attachments/assets/9e1ab23e-2826-4160-8d7e-409b5f53b286)

### Steps to reproduce the problem

1. open any product under Products
2. to the right of Media there is the Upload button. click it
3. upload an image
4. then you see a new graphic place holder, with broken image icon

### What did you expect to happen?

* thumbnail to be uploaded and displayed 

### Logs

Standard output: dashboard_1  | 192.168.1.101 - - [02/Dec/2024:07:40:10 +0000] "GET /thumbnail/UHJvZHVjdE1lZGlhOjUw/1024/ HTTP/1.1" 404 555 "https://shop.tourdefarm.com/dashboard/products/UHJvZHVjdDoxNjQ%3D" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" "-"
dashboard_1  | 2024/12/02 07:40:10 [error] 37#37: *59 "/app/dashboard/thumbnail/UHJvZHVjdE1lZGlhOjUw/1024/index.html" is not found (2: No such file or directory), client: 192.168.1.101, server: localhost, request: "GET /thumbnail/UHJvZHVjdE1lZGlhOjUw/1024/ HTTP/1.1", host: "shop.tourdefarm.com:9000", referrer: "https://shop.tourdefarm.com/dashboard/products/UHJvZHVjdDoxNjQ%3D"

Console output: 404

### Environment

dashboard v3.20.20
core v3.20.56

**Comment by aniav** [comment]
And thank you for the report one more time @charleslcso. Sorry you had to encounter so many things broken at your initial encounter with Saleor.

Internal link to track the bug report: [MERX-1325: saleor/saleor#17120 — Bug: Thumbnails link broken](https://linear.app/saleor/issue/MERX-1325/saleorsaleor17120-bug-thumbnails-link-broken)

**Comment by charleslcso** [comment]
> And thank you for the report one more time @charleslcso. Sorry you had to encounter so many things broken at your initial encounter with Saleor.
> 
> Internal link to track the bug report: [MERX-1325: saleor/saleor#17120 — Bug: Thumbnails link broken](https://linear.app/saleor/issue/MERX-1325/saleorsaleor17120-bug-thumbnails-link-broken)

Thank you.

I've just set up storefront, and the thumbnails are also broken there too.

Output from shop.tourdefarm.com linking to saleor.tourdefarm.com:
 ✓ Compiled /not-found in 6s (820 modules)
 ⨯ upstream image response failed for https://saleor.tourdefarm.com/thumbnail/UHJvZHVjdE1lZGlhOjE3/1024/webp/ 404
 ⨯ upstream image response failed for https://saleor.tourdefarm.com/thumbnail/UHJvZHVjdE1lZGlhOjQ0/1024/webp/ 404
 ⨯ upstream image response failed for https://saleor.tourdefarm.com/thumbnail/UHJvZHVjdE1lZGlhOjM0/1024/webp/ 404
 ⨯ upstream image response failed for https://saleor.tourdefarm.com/thumbnail/UHJvZHVjdE1lZGlhOjI=/1024/webp/ 404

Here saleor.tourdefarm.com is the Dashboard and platform. Storefront is at shop.tourdefarm.com.

**Comment by nawajar** [comment]
@charleslcso  If you saleor run with production mode, djungo will not handle media for you, It is static file  in saleor path ,
you have to handle it by yourself eg. by nginx to access

**Comment by michalina-graczyk** [comment]
Hi @charleslcso I was checking it on the same environment and I couldn't reproduce your issue 
![image](https://github.com/user-attachments/assets/5f634247-5916-4a66-9e31-a9eee4cb5a1f) . Uploading images and uploading via URL is working fine on my side. Which browser did you use?

**Comment by charleslcso** [comment]
I used Brave for macOS. After getting your reply I tried to use FireFox. Same broken thumbnails.

Here is the output from FF.

![Screen Shot 2024-12-10 at 6 39 14 PM](https://github.com/user-attachments/assets/1c4abcfe-4489-4ea8-a2b5-372cfe437564)

From @nawajar he said I need to handle to static media myself. Let me check Saleor's doc on how to set this up and try again.

**Comment by michalina-graczyk** [comment]
I just wanted to let you know that I can see the same problem when I am uploading using a direct URL.  It's reported, I will be back when it is fixed

**Comment by charleslcso** [comment]
> I just wanted to let you know that I can see the same problem when I am uploading using a direct URL. It's reported, I will be back when it is fixed

Great news!

Wondering how it works... at first you said URL is fine. Then direct URL is broken.

Should I know the difference for setting it up correctly?

**Comment by michalina-graczyk** [comment]
> > I just wanted to let you know that I can see the same problem when I am uploading using a direct URL. It's reported, I will be back when it is fixed
> 
> Great news!
> 
> Wondering how it works... at first you said URL is fine. Then direct URL is broken.
> 
> Should I know the difference for setting it up correctly?

My mistake, I confused environments.

**Comment by NyanKiyoshi** [comment]
Hi @charleslcso! It looks like a NGINX misconfiguration:

1. Check you are forwarding the `/thumbnail/` path to the Saleor Backend, e.g.:
    ```nginx
     location /thumbnail/ {
         # [...]
         proxy_pass http://backend.local:1234;  # (dummy backend, replace this)
     }
     ```
     From the logs, it currently looks like NGINX is trying to serve a file from the disk rather than forwarding it to the backend.
2. If the issue is still present, could you post the NGINX configuration you are running?

Hope it helps!

**Comment by charleslcso** [comment]
> Hi @charleslcso! It looks like a Nginx misconfiguration:
> 
> 1. Check you are forwarding the `/thumbnail/` path to the Saleor Backend, e.g.:
>    ```nginx
>     location /thumbnail/ {
>         # [...]
>         proxy_pass http://backend.local:1234;  # (dummy backend, replace this)
>     }
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    From the logs, it currently looks like Nginx is trying to serve a file from the disk rather than forwarding it to the backend.
> 2. If the issue is still present, could you post the Nginx configuration you are running?
> 
> Hope it helps!

Hello, which port number should I use for thumbnails?

**Comment by NyanKiyoshi** [comment]
> > Hi @charleslcso! It looks like a Nginx misconfiguration:
> > 
> > 1. Check you are forwarding the `/thumbnail/` path to the Saleor Backend, e.g.:
> >    ```nginx
> >     location /thumbnail/ {
> >         # [...]
> >         proxy_pass http://backend.local:1234;  # (dummy backend, replace this)
> >     }
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    From the logs, it currently looks like Nginx is trying to serve a file from the disk rather than forwarding it to the backend.
> > 2. If the issue is still present, could you post the Nginx configuration you are running?
> > 
> > Hope it helps!
> 
> Hello, which port number should I use for thumbnails?

Hey! By default the Saleor backend listens on `8000`

**Comment by charleslcso** [comment]
Add the /thumbnail/ path to Nginx. Uploaded a new photo to saleor-platform via Dashboard. 

Still broken.

Here is Nginx's config.


      server {
        server_name saleor.tourdefarm.com;

        root /var/www/html/saleor/;

        access_log /var/log/nginx/saleor.tourdefarm.com.access.log;
        error_log /var/log/nginx/saleor.tourdefarm.com.error.log;

        index index.html index.php;

        keepalive_timeout 70;
        gzip on;
        gzip_min_length 10240;
        gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml;

        location / {
                proxy_pass http://saleor.tourdefarm.com:9000/;
                #proxy_set_header X-Forwarded-Host \$host;
                #proxy_set_header X-Forwarded-Server \$host;
                #proxy_set_header X-Real-IP $remote_addr;
                #proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                #proxy_set_header Host $host;
                proxy_http_version 1.1;
                #proxy_set_header   Upgrade $http_upgrade;
                #proxy_set_header   Connection "upgrade";
                client_max_body_size 60M;
                proxy_connect_timeout 300;
                proxy_send_timeout 300;
                proxy_read_timeout 300;
                send_timeout 300;
        }

        location /thumbnail/ {
                proxy_pass http://saleor.tourdefarm.com:8000/;
                proxy_http_version 1.1;
        }

        location /graphql/ {
                proxy_pass http://saleor.tourdefarm.com:8000/graphql/;    # <- must end with /!
                #proxy_set_header X-Forwarded-Host \$host;
                #proxy_set_header X-Forwarded-Server \$host;
                #proxy_set_header X-Real-IP $remote_addr;
                #proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                #proxy_set_header Host $host;
                proxy_http_version 1.1;
                #proxy_set_header   Upgrade $http_upgrade;
                #proxy_set_header   Connection "upgrade";
                client_max_body_size 60M;
                proxy_connect_timeout 300;
                proxy_send_timeout 300;
                proxy_read_timeout 300;
                send_timeout 300;
        }

        location /graphql {
                proxy_pass http://saleor.tourdefarm.com:8000/graphql/;    # <- must end with /!
                #proxy_set_header X-Forwarded-Host \$host;
                #proxy_set_header X-Forwarded-Server \$host;
                #proxy_set_header X-Real-IP $remote_addr;
                #proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                #proxy_set_header Host $host;
                proxy_http_version 1.1;
                #proxy_set_header   Upgrade $http_upgrade;
                #proxy_set_header   Connection "upgrade";
                client_max_body_size 60M;
                proxy_connect_timeout 300;
                proxy_send_timeout 300;
                proxy_read_timeout 300;
                send_timeout 300;
        }

        listen 443 ssl http2; # managed by Certbot
        ssl_certificate /root/.acme.sh/saleor.tourdefarm.com_ecc/fullchain.cer;
        ssl_certificate_key /root/.acme.sh/saleor.tourdefarm.com_ecc/saleor.tourdefarm.com.key;
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

      }

**Comment by nawajar** [comment]
Like i said if you are running saleor on production mode, It will not serve static file on http server , so it is only a file path on you machine you have to setting route to serve.

![Screenshot 2567-12-18 at 10 25 12](https://github.com/user-attachments/assets/e8a7736f-561e-4819-8fe5-d3d46a53fbb3)


 server {
        server_name _;
        listen 80;

         location /media/ {
              autoindex on;
              root  /path/to/you/media/file
            }

         location /static/ {
              autoindex on;
              root  /path/to/you/static/file
            }

   }
   
   
  more info https://docs.djangoproject.com/en/4.2/howto/static-files/deployment/

**Comment by NyanKiyoshi** [comment]
@charleslcso could you double check that you get an HTTP 302 on `/thumbnail` endpoint? (by checking the network inspector). HTTP 302 (HTTP redirect) would mean the endpoint is working as expected, and thus that it is `/media/` failing.

- If you don't get HTTP 302 on `/thumbnail`: check the nginx access and errors logs for potential issues, as well as the Saleor backend logs. You can also try to visit directly `http://saleor.tourdefarm.com:8000/thumbnail/<ID>/<size>` to see whether the backend works and thus whether the issue is around NGINX or not.
- If you get HTTP 302 on `/thumbnail` and then get HTTP 404 on `/media`, then @nawajar's answer should resolve the issue

Additionally, attach:
- Screenshots or logs from the network inspector
- NGINX logs
- Saleor backend logs
- Any settings/environment variables you changed in the Saleor backend (but remove all secrets such as `DATABASE_URL`)

Should make it easier to troubleshoot 🙂

**Comment by charleslcso** [comment]
> @charleslcso could you double check that you get an HTTP 302 on `/thumbnail` endpoint whenever an image is fetched from the dashboard? (by checking the network inspector). HTTP 302 (HTTP redirect) would mean the endpoint is working as expected, and thus that it is `/media/` failing.
> 
> * If you don't get HTTP 302 on `/thumbnail`: check the nginx access and errors logs for potential issues, as well as the Saleor backend logs. You can also try to visit directly `http://saleor.tourdefarm.com:8000/thumbnail/<ID>/<size>` to see whether the backend works and thus whether the issue is around NGINX or not.
> * If you get HTTP 302 on `/thumbnail` and then get HTTP 404 on `/media`, then @nawajar's answer should resolve the issue
> 
> Additionally, attach:
> 
> * Screenshots or logs from the network inspector
> * NGINX logs
> * Saleor backend logs
> * Any settings/environment variables you changed in the Saleor backend (but remove all secrets such as `DATABASE_URL`)
> 
> Should make it easier to troubleshoot 🙂

Hello @NyanKiyoshi I followed your guide, and I get 404 in web browser console and from Saleor-platform console output, no matter i choose `Upload Images` or `Upload URL`

I can see that there are 2 POSTs, then a GET from /thumbnail (404).

![Screen Shot 2024-12-20 at 12 13 39 PM](https://github.com/user-attachments/assets/f2f322fb-3d33-44b5-85e2-aad8a552effb)

Saleor-platform console output shows:
```
api-1        | 2024-12-20 03:38:47,917 WARNING django.request Not Found: /UHJvZHVjdE1lZGlhOjMx/1024/ [PID:25:ThreadPoolExecutor-86_3]
api-1        | 2024-12-20 03:38:47,929 WARNING django.request Not Found: /UHJvZHVjdE1lZGlhOjM1/1024/ [PID:25:ThreadPoolExecutor-86_9]
api-1        | 2024-12-20 03:38:47,929 WARNING django.request Not Found: /UHJvZHVjdE1lZGlhOjM0/1024/ [PID:25:ThreadPoolExecutor-86_9]
api-1        | 2024-12-20 03:38:47,929 WARNING django.request Not Found: /UHJvZHVjdE1lZGlhOjM2/1024/ [PID:25:ThreadPoolExecutor-86_9]
api-1        | 2024-12-20 03:38:47,930 WARNING django.request Not Found: /UHJvZHVjdE1lZGlhOjI3/1024/ [PID:25:ThreadPoolExecutor-86_9]
```

Trying to load the thumbnail directly I get 404.

![Screen Shot 2024-12-20 at 12 18 11 PM](https://github.com/user-attachments/assets/926b5641-5452-4ce2-ab6f-8d23accd0c8d)

Now I assume the 2 POSTs will upload the images (either from URL or from local upload) successfully. Then the thumbnails will be placed in /thumbnail, /static and /media locations.

After reading the Django's static assets configuration page, and following @nawajar 's info, I've set up /media and /static. You can load these:

```
https://saleor.tourdefarm.com/static/static.html
https://saleor.tourdefarm.com/media/media.html
```

Container `saleor-platform-api-1` has no .log files. Nginx error.log in `saleor-platform-dashboard-1` has no error.

The problem should be in `api-1` server.

No more idea.

**Comment by charleslcso** [comment]
> @charleslcso I see it tries to access the path `/UHJvZHVjdE1lZGlhOjMx/1024/` whereas the path should be `/thumbnail/UHJvZHVjdE1lZGlhOjMx/1024/`
> 
> It's caused by the trailing `/` in your Nginx configuration.
> 
> Change this:
> 
> ```nginx
>     location /thumbnail/ {
>             proxy_pass http://saleor.tourdefarm.com:8000/;
>     }
> ```
> 
> To:
> 
> ```nginx
>     location /thumbnail/ {
>             proxy_pass http://saleor.tourdefarm.com:8000; # <-- removed the trailing '/'
>     }
> ```

@NyanKiyoshi Thanks for the info.

![Screen Shot 2024-12-20 at 11 04 01 PM](https://github.com/user-attachments/assets/84457abc-fe43-4e58-a366-2a5b70798454)

Should the full path now be `https://saleor.tourdefarm.com/media/thumbnails/products/Untitled-1_2bb15bf3_thumbnail_1024.jpg`, with /media in front of /thumbnails? Removing the trailing / now gives me /media/thumbnails/.



With /media/, it actually goes to `/app/dashboard/thumbnails/products/Untitled-1_2bb15bf3_thumbnail_1024.jpg`, which I don't think is correct.

**Comment by NyanKiyoshi** [comment]
> Should the full path now be `https://saleor.tourdefarm.com/media/thumbnails/products/Untitled-1_2bb15bf3_thumbnail_1024.jpg`, with `/media` in front of `/thumbnails`? Removing the trailing / now gives me `/media/thumbnails/`.

@charleslcso Yes! It should be doing that, that means the `/thumbnail/` endpoint is now working correctly!

It works like so:

1. If Saleor doesn't have a thumbnail generated yet for the image, then:
    1. It goes to `/thumbnail/` to generate a new thumbnail (e.g., `/thumbnail/XXXX/1024`)
    2. It redirects to the thumbnail it just generated (media storage backend thus `/media/XXXX_1024.png` in your case)
3. If it already generated a thumbnail, then it directly goes to the media storage backend to fetch the image (`/media/XXXX_1024.png` in your case)

Since you are running with debug/development mode enabled (`DEBUG=True`), you can just do this:

```nginx
        location /media {
                proxy_pass http://saleor.tourdefarm.com:8000;  # <-- leaves it up to the Saleor backend to serve the file
        }

        location /thumbnail/ {
                proxy_pass http://saleor.tourdefarm.com:8000;
        }
```

Instead of serving the files via Nginx directly, this should simplify the set-up if you only want to test things.

**Comment by charleslcso** [comment]
> > Should the full path now be `https://saleor.tourdefarm.com/media/thumbnails/products/Untitled-1_2bb15bf3_thumbnail_1024.jpg`, with `/media` in front of `/thumbnails`? Removing the trailing / now gives me `/media/thumbnails/`.
> 
> @charleslcso Yes! It should be doing that, that means the `/thumbnail/` endpoint is now working correctly!
> 
> It works like so:
> 
> 1. If Saleor doesn't have a thumbnail generated yet for the image, then:
>    
>    1. It goes to `/thumbnail/` to generate a new thumbnail (e.g., `/thumbnail/XXXX/1024`)
>    2. It redirects to the thumbnail it just generated (media storage backend thus `/media/XXXX_1024.png` in your case)
> 2. If it already generated a thumbnail, then it directly goes to the media storage backend to fetch the image (`/media/XXXX_1024.png` in your case)
> 
> Since you are running with debug/development mode enabled (`DEBUG=True`), you can just do this:
> 
> ```nginx
>         location /media {
>                 proxy_pass http://saleor.tourdefarm.com:8000;  # <-- leaves it up to the Saleor backend to serve the file
>         }
> 
>         location /thumbnail/ {
>                 proxy_pass http://saleor.tourdefarm.com:8000;
>         }
> ```
> 
> Instead of serving the files via Nginx directly, this should simplify the set-up if you only want to test things.


Finally! It is working! You are da man!

![Screen Shot 2024-12-21 at 7 54 27 AM](https://github.com/user-attachments/assets/90d52fb1-e0a0-4399-8289-858dcc9739ec)

Next step is that I'll turn off debug mode and get the thing working again.

So I should just keep my existing 2 Nginx configs, turn off DEBUG and try and see.
