### ISSUE TITLE
Staff users shouldn't be able to set permissions they don't have

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#1966]
Hello,

If a staff user, which has high permissions, let's say, this user is the HR. This user may have some of the highest group permissions but not everything (example: edit site settings). 
But this user has the permission to manage groups and add staff users. Which means, this user can set his/ her own permissions and then gain access to higher privileges. And also, give permissions he/ she shouldn't give to new staff members with lower hierarchy than him.

What I propose:
- Forbid staff users to edit groups they are in, or groups that have too high privileges;
- Set the queryset of the field `groups` in `StaffForm` to only contain permissions the current user has.

**Comment by Pacu2** [comment]
It should be easier to implement now, as we removed groups

**Comment by jxltom** [comment]
We can implement this, but we need to make sure we have a staff who has all kinds of permissions initially.

**Comment by maarcingebala** [comment]
This has been implemented for a long time - staff users now cannot grant themselves permission they do not have.
