### ISSUE TITLE
Allow GraphQL clients to specify the language they'd like to receive responses in

### ISSUE THREAD

**Issue by patrys** [saleor/saleor#1995]
When using mutations that return a list of errors, the message should be translated to the same language the client uses to present the UI. I propose that we either add a mutation that sets the language of a transaction (not sure how viable that is) or we add an optional `lang` field to all mutations.

For the former I imagine something like:

```graphql
mutation {
  setLanguage(lang: "pl")
  tokenAuth(input: { email: "test@example.com", password: "secure" }) {
    errors {
      field
      message
    }
  }
}
```

**Comment by patrys** [comment]
Eventually we should provide the client with an error enum type so that messages can be part of client code (and be reused for client-side validation where applicable).

**Comment by maarcingebala** [comment]
Closing as this seems irrelevant now. Messages are translated in the frontend. Backend allows querying backend-added translations with special parameters.
