### ISSUE TITLE
Implement size based shipping methods

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#2029]
Hello,

I'm planning on implementing calculated shipping methods around this week. I need help and thoughts about the process that should be implemented to cover most cases.

#### 1.1. — Product variants
- Product variants will have **package dimensions** (in centimeters for now at least);
- Product variants will have a **package weight** (package + product weight).

#### 1.2. — Package types
We **can create package type** (a bit like `ProductType`), those are used to set the available packages so send. Boxes sizes.

- Saleor chose automatically by summing the cart weights and dimensions;
- If it fails: it splits the order (I don't think I will implement it).

Data of package type:
- **a name** (e.g.: heavy package);
- **empty weight**, the weight of the box when empty;
- **max weight**, the maximal weight for this box;
- **cost**, the base cost of this box.

#### 1.3. — Shipping methods per provider
- **provider name** (e.g.: Local DHL);
- **cost per kilogram** (e.g.: $4/ kg for DHL *irc*);
- **cost per amount/ value**, the fee from the package value (e.g. $0.01 per USD);
- **base cost** (e.g.: $15);
- **countries**, countries concerned by this provider;
- **available packages**, packages we can send with this provider;
- **price range**, price range required for this shipping method;
- **is free**, boolean, set the shipping as free.

##### 2.1.1. — Order
Let's imagine, we order from Amazon:

| product  | dimensions  |  weight | value |
|---|---|---|---|
| An Ethernet switch  | 15 x 10 x 7 cm  |  0.6 kg  | $ 20 |
| A light bulb  | 7 x 4.5 x 4.5  cm  |  0.3 kg  | $ 6 |

##### 2.1.2. — Available packages

| pk | name  | dimensions  |  weight | max weight | cost |
|---|---|---|---|---|---|
| 1 | Light package  | 20 x 15 x 5 cm | 0.100 kg  |  3 kg  | $ 1 |
| 2 | Medium package  | 40 x 20 x 15  cm  | 0.200 kg | 10 kg  | $ 2 |

##### 2.1.3. — Providers

| pk | name  | cost/ kg  |  cost/ $ | base cost | countries | available packages | price range | is free |
|---|---|---|---|---|---|---|---|---|
| 10 | Amazon  | $ 0.1 | $ 0  | $ 4 | France, Germany | all | < $ 25 | False |
| 11 | Amazon Free  | $ 0.1 | $ 0  | $ 4 | France, Germany | all | >= $ 25 | True |
| 12 | Amazon 1 day delivery | $ 0.5 | $ 0 | $ 10 | France, Germany | all | any | False |
| 13 | Amazon International (Fedex)  | $ 1 | $ 0.1 | $ 20 | Rest of the World | all | any | False |

##### 2.1.4. — Results
Shipping methods available: Amazon (sum of the cost), Amazon Free, Amazon 1 day delivery (sum of the cost).
Package to use: Medium package.

#### 2.2. — Newegg
On newegg, an American website, local shipping is free and international shipping is calculated using a base fee of $20 and around $1 per kg. A wide package has a fee of $50-70.

----

It's a really complex process trying to response to most cases and most providers don't really tell how they calculate their costs, I really would like to hear what you think we should do. I know you are planning on implementing providers' API as well.

**Comment by Pacu2** [comment]
Price & weight based shipping prices were introduced in #2529 
I'll leave this issue open, as size based shipping is under consideration, however, I cannot tell exact days as we wonder if this is not too much for most of the basic e-commerce businesses.

**Comment by thenewguy** [comment]
I need this feature and I have been looking at ways to implement it.  Would you accept a pull request that makes it possible for implementation specific shipping methods that apply to a particular cart or order?

My specific case needs shipping rate based on delivery address, origin address, and items shipped.  However, I think it could be implemented generically using a hash function that the implementation can override that can be modified for advanced needs.

**Comment by peelar** [comment]
@NyanKiyoshi What is the status of this feature? Has it been implemented? Do we have it on our roadmap?

**Comment by NyanKiyoshi** [comment]
Hi @peelar, it is not an implemented feature and I don't believe it's part of Saleor's roadmap
