### ISSUE TITLE
Inventory management view

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#2096]
Inventory view should give the staff a quick overview of all variants and quantities available in the storefront.

From a technical point of view it should be a list of variants with at least the following fields:
- name
- SKU
- quantity
- quantity allocated (?)

There should be some warning (maybe marking the quantity with red color is enough) when:
- available quantity is near zero
- allocated quantity is near the available one

Ideally, we should also provide a way to edit the quantity using inline inputs, but this would require a paginated formset, which may not be worth the effort since we're working on Dashboard 2.0. For now, we could as well add an "Edit" link redirecting to the variant form.

**Comment by maarcingebala** [comment]
A sneak peek into the future:

![Screenshot 2019-04-30 at 13 42 36](https://user-images.githubusercontent.com/5421321/56959516-e9c27580-6b4d-11e9-8ae2-7a948b353e2f.png)

**Comment by cwall0868** [comment]
The inventory dash looks great! Are you planning to support inventory by locations? Let's say your e-commerce operation has multiple distribution centers, or you have multiple local shops that share a centralized inventory?

**Comment by maarcingebala** [comment]
Locations are not supported yet but I'm sure we will add it in the future. It's not planned for a particular sprint or release yet though.

**Comment by iotmani** [comment]
> The inventory dash looks great! Are you planning to support inventory by locations? Let's say your e-commerce operation has multiple distribution centers, or you have multiple local shops that share a centralized inventory? The sku would be the same but the inventory would be tracked by location and be transferrable. Is there a way to do this already?

I believe that would tie-in to regional shipping zones as well, as currently you can define shipping zones at country level. Something I might have to work on sometime this year, so if you're interested in we can track it via a task/issue?

Thanks for the tremendous work!

**Comment by maarcingebala** [comment]
@iotmani It's on our internal roadmap to add support for more granular regions that you can create shipping zones for. It's required for any business in the US and many other countries.

**Comment by maarcingebala** [comment]
Issue tracked on the internal roadmap.
