### ISSUE TITLE
Ger error "Oops, it looks like we were unable to contact the selected payment service " when i try to config with stripe sandbox

### ISSUE THREAD

**Issue by nguyenvantiendat** [saleor/saleor#2106]
Here is config in setting.py
PAYMENT_VARIANTS = {
    'stripe': ('payments.stripe.StripeProvider', {
        'secret_key': 'sk_test_123456',
        'public_key': 'pk_test_123456'})}

CHECKOUT_PAYMENT_CHOICES = [
    ('default', 'stripe')]

when i proceed to payment then i got error message: "Oops, it looks like we were unable to contact the selected payment service "

**Comment by nguyenvantiendat** [comment]
it works well now, thanks

**Comment by luceroster** [comment]
Hello, here Im having the exact same error with paypal...I need some help please...

PAYMENT_VARIANTS = {
    'paypal': ('payments.paypal.PaypalProvider', {
        'client_id': 'luceroster-facilitator@gmail.com',
        'secret': 'secretkey123',
        'endpoint': 'https://api.sandbox.paypal.com',
        'capture': False})}

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

CHECKOUT_PAYMENT_CHOICES = [
    ('paypal', 'PaypalProvider')]
