### ISSUE TITLE
Migration from Magento and other ecommerce platforms

### ISSUE THREAD

**Issue by maltitco** [saleor/saleor#2152]
I wonder how to migrate from Magento to Saleor, i see that such a tool is planned for the future not only for Magento but also for other platforms.  I started to analyze what the structure of products looks like in Magento [1.9.x](https://docs.magento.com/m1/ce/user_guide/catalog/product-types.html) | [2.2.x](http://docs.magento.com/m2/ee/user_guide/catalog/product-types.html) and in [Saleor](https://saleor.readthedocs.io/en/latest/architecture/products.html#product-structure). 

I checked my structure and what my friends have in their stores and I came to the conclusion that it would not make sense to build an automatic migrator under each platform. On the example of these few stores, I see that the structure of products is so different that maintaining and adjusting the tool can be troublesome.

In my opinion, the ideal tool would be the ability to import data from the CSV format.
This will allow not only to migrate data but also to later import data from other systems such as ERP, CMR etc.

What tools or libraries are preferred by saleor developers for the construction of such an importer?

**Comment by gety9** [comment]
@maltitco hi,

We are also considering options to migrate from magento 1 (magento 2 is not an option)
Why do you consider Saleor and phyton based framework? What pros do you see comparing to php based ones?

**Comment by maltitco** [comment]
Hi @gety9,
With Magento, he's been working since version 0.6, during that time I modified them for my own needs but I always missed something and I did not like PHP myself.

I chose Saleor because I am learning python and I hope that the required modification will be done by myself. Its community grows and developers quickly answer questions. In my opinion, the project uses the best and proven mechanisms from other platforms.

**Comment by maltitco** [comment]
@NyanKiyoshi The solution you showed in the picture would be perfect and universal.
This would facilitate migration from less popular platforms.

**Comment by patrys** [comment]
There is a similar tool that converts CSV files for You Need a Budget using JavaScript: https://github.com/aniav/ynab-csv

We could handle most of the import on the client side and issue a series of GraphQL mutation for each row of the file while providing a live list of any rows that failed.

**Comment by ctailo** [comment]
> There is a similar tool that converts CSV files for You Need a Budget using JavaScript: https://github.com/aniav/ynab-csv
> 
> We could handle most of the import on the client side and issue a series of GraphQL mutation for each row of the file while providing a live list of any rows that failed.

How does someone import CSV files into Saelor? I have a number of products that I would like to import into Saelor, and it would be great to know how to do this.

**Comment by Pacu2** [comment]
Unfortunately at this moment we should no out-of-the-box solution ready

**Comment by ctailo** [comment]
> Unfortunately at this moment we should no out-of-the-box solution ready

Thanks for this information. How would I go about importing a CSV file then? One alternative that I thought about doing was to import it into the application in general. I am planning on adding Saleor to a Django project that will have other apps and I would like to use those products in the other apps.

Is there a way to include the products from the CSV in Saleor as well?

**Comment by Pacu2** [comment]
I think you might add an appropriate section in the dashboard, and the import itself could be handled asynchronously via Celery task.

**Comment by ctailo** [comment]
> I think you might add an appropriate section in the dashboard, and the import itself could be handled asynchronously via Celery task.

Thank you. What about a two sided marketplace. How would I do that with Saleor. Is it possible? Also, is it possible to include reviews and wishlists with Saleor?

**Comment by jdruiter** [comment]
+1 for the CSV way of importing

Django already has a pretty good open source solution that Saleor can build on to:

https://django-import-export.readthedocs.io/en/latest/

**Comment by EndermanAPM** [comment]
As much as the CSV importer tool would be convenient I think it would be cumbersome to express complex product structures. Maybe JSON would work better.
I currently use Prestashop (didn't choose it myself, but it's what i have to work with) and I'm looking for alternatives. saelor looks promising and I would like to contribute when you start working on the data importer.

**Comment by maarcingebala** [comment]
Still valid.

**Comment by ZeroCoolHacker** [comment]
When should I expect this feature? 
I have to build stores for clients and now I have to migrate thousands of products from Magento.

**Comment by robertology** [comment]
@ZeroCoolHacker  Have you scripted any of your migration process, or has it been completely manual copy/paste style?

This would be the ideal time to have an easy way to migrate from Magento 1 since it went EOL just a month ago. People have to decide what to do with their M1 installations.

I would vote for a very simple, works for M1 only, interface not even needed kind of solution to at least have something. That could look like:

1. A script to export from Magento (unless something suitable exists already)
2. Put the resulting file(s) on the server with Saleor
3. A script to import from that file into Saleor 

That would hit the majority of use cases. Then:
1. Do the same thing for something else such as Shopify
2. Consider making something in the dashboard for import with two options `[Magento 1, Shopify]`

Then look at those two import script to see how/if things can be abstracted. Or do a third one if it isn't obvious. At that point the path forward should be clear (hopefully).

I would volunteer but I'm still quite new to Saleor and would likely miss some details.

**Comment by ZeroCoolHacker** [comment]
Saleor just needs to implement product import from a csv file. OS community will develop the column manipulation script themselves.

**Comment by robertology** [comment]
Yes, that is a good end goal, but getting to the point where we understand the required data/structure needed in that file, how to handle references to dependent data (product attributes, categories, etc.), and things we can't even think of right now - is going to take some exploratory work.

For my own project, I will need to migrate from OpenCart. I had planned to start on that in maybe three weeks, but there isn't a real reason I couldn't bump that up. So, I might start looking into that sooner and we'll see what I learn.
