### ISSUE TITLE
Unable to localize VAT

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#2186]
Hi!

I'm unable to localize VAT information text (`XX EUR excluding XX% VAT`), despite having recompiled locales and javascript files. It seems to be an issue with `VariantPrice.js:52`.

Note that it does work for products with variants disabled.

### How to reproduce
1. Get the latest French translations from transifex for storefront (as the strings were translated);
2. Compile them;
3. Switch frontstore to French and make sure VAT support is enabled and properly set-up;
4. Go to a product page with variants;
5. VAT notes should not be localized properly;
6. Optionally, try on a product with variants disabled, VAT notes should be properly translated.

**Comment by patrys** [comment]
To add to this I'm not sure why we would ever say "excluding 20% VAT" instead of just "excluding taxes". This seems awkward for Europeans but is even more confusing for anyone outside of the EU VAT area.

**Comment by AlvaroMolano** [comment]
Just to add some help on bug resolution, I list related files:
/saleor/static/js/components/variantPicker/VariantPrice.js line 53  ... approx
/templates/product/details.html line 149 ... approx
