### ISSUE TITLE
Tax rates according to country of shop should be possible.

### ISSUE THREAD

**Issue by MacLake** [saleor/saleor#2279]
Hi again,
the documentation says:
> Taxes are charged according to the rates applicable in the country to which the order is delivered. If tax rate set for the product is not available, standard tax rate is used by default.

### What I'm trying to achieve
In the EU you are allowed to charge VAT according to your own (the shop’s) country’s rates up to a certain limit. We for example only charge German VAT for customers in all EU countries and no tax for B2B and customers outside EU.

### Describe a proposed solution
A checkbox should be available in the dashboard, so you can decide whether the tax rates of the shop’s country or the rates of the customer’s country apply.

It should be possible to charge no VAT for customers outside EU or in case of a shop in a non-EU country for foreign countries in general.

i know, things are getting more complicated then, but that’s the situation. Unfortunately we can’t use the VAT implementation like it’s now.

**Comment by MacLake** [comment]
Quick and dirty hack: Copy the tax of the shop’s country to the other EU countries’ VAT objects.

$ ./manage.py shell
from django_prices_vatlayer.models import *
vat_de = VAT.objects.get(country_code='DE')
for vat in VAT.objects.all():
    vat.data = vat_de.data
    vat.save()
```

Apparently for non-EU countries no tax (0 %) is applied and not the standard tax (like documented).

**Comment by MacLake** [comment]
The EU provides some information about [Cross-border VAT](https://europa.eu/youreurope/business/vat-customs/cross-border/index_en.htm). Depending on the country you sell goods to, the limit up to which you can apply your own tax rates and don’t have to register in the other EU countries is 35&nbsp;000 or 100&nbsp;000&nbsp;@.

In the meantime I have solved the issue in the code without the above mentioned trick of manipulating the JSON fields VAT.data. Should I make a pull request with a fix of this issue?

**Comment by maarcingebala** [comment]
Hey, how did you solve the issue? I like the solution you proposed at first - a checkbox switching between charging tax according to either shop's or customer's country.

As for the business customers from EU who are exempted from tax - there is currently no distinction between B2B or regular customers. The simple solution that I see is to add `vat_id` field to the `Address` model. This, along with `company_name` set in checkout would determine a B2B customer and apply some logic to not charge tax.

**Comment by eriktelepovsky** [comment]
+1

**Comment by adrienshen** [comment]
I've just recently built a similar integration like this for Shopify. Maybe I can take a crack at this?

**Comment by JustCreate3D** [comment]
+ 1

**Comment by starksid** [comment]
Hello 
I am exploring open source. I am proficient in Data Structures And Algorithms, DBMS, OS
How i can start contributing into saleor projects.

**Comment by maarcingebala** [comment]
For EU it's now best to use Flat Rates where rates and tax behavior can be customized per country and channel.
