### ISSUE TITLE
Issue on trying to insert huge total order payment

### ISSUE THREAD

**Issue by ygrip** [saleor/saleor#2301]
### What I'm trying to achieve
Hey i have created my customized Saleor, i have saved my custom product. and i want to insert the order from the command as usual. But when the system try to insert the total order that is exceeding 8 digits it fails in the **create_payment** method (as it should not be fail, the system should accept that amount) and i keep getting this error : `decimal.InvalidOperation:` [<class 'decimal.InvalidOperation'>]`

### Steps to reproduce the problem
1. Creating a custom product
2. Generating fake user
3. Generating fake order

### What I expected to happen
It can successfully save the order payment, and can handle a product with high price (eg. 10000000)

### Screenshots
![image](https://user-images.githubusercontent.com/22442215/41667821-19d90e9a-74d8-11e8-9b9a-df95acf45b02.png)
![image](https://user-images.githubusercontent.com/22442215/41667828-1f16c884-74d8-11e8-9f68-9e7877d1d234.png)

**System information**
Operating system: Windows 10 64bit
Browser: Chrome

### Edit
I have successfully solved my problem, by overriding the **Payment** model :
```
class Payment(BasePayment):
    total = models.DecimalField(max_digits=13, decimal_places=2, default='0.0')
    delivery = models.DecimalField(
        max_digits=13, decimal_places=2, default='0.0')
    captured_amount = models.DecimalField(
        max_digits=13, decimal_places=2, default='0.0')
    tax = models.DecimalField(max_digits=9, decimal_places=2, default='0.0')
```

**Comment by Pacu2** [comment]
Seems like the problem is related to `django-payments` package rather than Saleor (Thats where `BasePayment` class is coming from), glad to see that you've resolved it.

**Comment by NyanKiyoshi** [comment]
We have a little inconstancy between the `Order` model and the `BasePayment` model.

https://github.com/mirumee/saleor/blob/e2fb44dfcb466413bfc0c402d8b7e36f2cfcbca9/saleor/order/models.py#L78-L83


1. [django-payments: totals](https://github.com/mirumee/django-payments/blob/36d704233c9f2a0729cad7e4df7e32d628182c43/payments/models.py#L57-L60)
2. [django-payments: captured amount](https://github.com/mirumee/django-payments/blob/36d704233c9f2a0729cad7e4df7e32d628182c43/payments/models.py#L75-L76)

**Comment by Pacu2** [comment]
This issue would require changing `django-payments` package, as `decimal_places` should be equal to decimal places of the default currency

**Comment by Pacu2** [comment]
related: https://github.com/mirumee/django-payments/issues/188

**Comment by Pacu2** [comment]
I actually wonder if `max_digits` shouldn't be settable via settings as well, what if one's target is to sell F-22 Raptors airplanes in Venezuelan Bolivars? What do you think @patrys?

**Comment by patrys** [comment]
Agreed, quick fix would be to expose a setting like `MONEY_DIGITS = (12, 2)` defaulting to the currently used values in `django-payments` (so a migration is not required) and then override it in Saleor.

**Comment by NyanKiyoshi** [comment]
@patrys separating into two settings is probably cleaner. What do you think?

```python
MONEY_MAX_DIGITS, MONEY_DECIMAL_PLACES = getattr(settings, 'MONEY_DIGITS', (9, 2))
```

```python

MONEY_MAX_DIGITS = getattr(settings, 'MONEY_MAX_DIGITS', 9)
MONEY_DECIMAL_PLACES = getattr(settings, 'MONEY_DECIMAL_PLACES', 2)
```

**Comment by patrys** [comment]
Oh, I did not think about exposing it using settings. It's not something you'll be able to change without altering the database schema.

**Comment by NyanKiyoshi** [comment]
Oh! Okay, I see what you mean!

**Comment by maarcingebala** [comment]
The configuration has been moved to settings.py:

```
DEFAULT_DECIMAL_PLACES = 3
DEFAULT_MAX_DIGITS = 12
```
