### ISSUE TITLE
ProductAttribute slug index is named as product_productattribute_name_97ca2b51_like

### ISSUE THREAD

**Issue by MChiciak** [saleor/saleor#2358]
### What I'm trying to achieve
Fix ProductAttribute Slug Index

### Steps to reproduce the problem
1.  Try to add an index on ProductAttribute name
2.  An error gets thrown saying the index exists already
3. The reason it exists is because "slug" used to be named "name" already and had an index on it.  

### What I expected to happen
Migration should have been successful when db_index was added

### Screenshots
![image](https://user-images.githubusercontent.com/10173150/42301302-75fe71aa-7fe2-11e8-83cf-dbf4cd4fded1.png)

![image](https://user-images.githubusercontent.com/10173150/42301316-83777d54-7fe2-11e8-8b63-fcaee76664fc.png)

![image](https://user-images.githubusercontent.com/10173150/42301319-905385a4-7fe2-11e8-9627-fdbbd7aec1e9.png)

**System information**
Operating system:  Windows 10
Browser: N/A

**Comment by MChiciak** [comment]
In my own fork, I fixed this with this migration...

max_length is probably different in mine, but this sets all the indexes and constraints right.

operations = [
        migrations.RunSQL (
            "ALTER TABLE product_productattribute DROP CONSTRAINT IF EXISTS product_productattribute_name_key"
        ),
        migrations.RunSQL(
            "DROP INDEX IF EXISTS product_productattribute_name_97ca2b51_like"
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(max_length=200, unique=False)
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(max_length=200, unique=True)
        ),
    ]

**Comment by Mizaro** [comment]
Is the issue relevant today?

**Comment by kamikazebr** [comment]
Nice question @Mizaro, i'm looking for good first issues to work on.I want like know that too, it still a issue?

**Comment by maarcingebala** [comment]
Closing as the issue doesn't seem relevant anymore.
