### ISSUE TITLE
Restricting query costs and depth

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#2423]
Currently, we don't have limits for the number of requested edges or the depth of queries. We should figure out how to calculate the cost of queries to be able to later provide limits for maximum cost of a query.

**Comment by mirekm** [comment]
Possibly something that should be addressed in the future by mirumee/ariadne cc @rafalp

**Comment by maarcingebala** [comment]
Added in https://github.com/saleor/saleor/pull/8526.
