### ISSUE TITLE
Attribute filters are not available in subcategories

### ISSUE THREAD

**Issue by tadkondrat** [saleor/saleor#2697]
### What I'm trying to achieve

I'm trying to filter products in subcategories by attributes of this products

### Steps to reproduce the problem
1.  Create category and then create 2 or more subcategory
2.  Add product to last subcategory
3. Select category, than subcategory and try to filter products by attributes

### What I expected to happen

Attribute filters are not available in subcategories! Filters by attributes available only in last subcategory. For example, i have category "Phones" with subcategories by companies names -> phone model. If i select last subcategory "Iphone 8", i got all filters, but if i select subcategory "Apple", i got filter only by price range.

So, how to enable these filters? Can i modify some template or python code by myself, or you guys will do it some later?

### Screenshots
![nofitlers](https://user-images.githubusercontent.com/16798475/44631772-945c1600-a979-11e8-992b-7726533c37b3.png)
![filters](https://user-images.githubusercontent.com/16798475/44632055-33364180-a97d-11e8-97a0-289e9e960a1b.png)

**Comment by Pacu2** [comment]
https://github.com/mirumee/saleor/blob/master/saleor/product/filters.py#L91-L100
Those lines should be fixed, as `category` is the parent category that has no products assigned to it

**Comment by pitero92** [comment]
Am I understand correctly?
parent is `self.category = kwargs.pop('category')`
children are `_get_product_attributes_lookup` and` _get_variant_attributes_lookup`?

**Comment by Pacu2** [comment]
@pitero92 
Functions `_get_product_attributes_lookup`/ `_get_variant_attributes_lookup` are returning django's Q object https://docs.djangoproject.com/en/2.1/ref/models/querysets/#django.db.models.Q

`self.category` is the parent category. In Saleor categories are built with `django-mptt` package, for creating tree-like structure. 
so `self.category` can have a `child category`(so `self.category` is a parent of the `child category`)
this `child category` can have `grandchild category`
this `grandchild category` ...
etc

Lookup that happens in the above functions is taking product/variant attributes from products/variants assigned to `self.category`

But as self.category can have descendants categories, we should change the lookup, to take product/variant attributes from products/variants assigned to the `self.category` or its descendants.

**Comment by maarcingebala** [comment]
Proper solution was already implemented [here](https://github.com/mirumee/saleor/pull/2949/files#diff-1302fef4f54970a2c047714bdc3d5634), but this PR wasn't ready to merge as it contained also unwanted changes.
