### ISSUE TITLE
Dashboard 2.0: Consider using a union type for order history events

### ISSUE THREAD

**Issue by patrys** [saleor/saleor#2874]
Currently we report a list of objects with all of their fields optional. This means the client is responsible for ensuring that the correct fields were returned by the server.

I think what is worth exploring is creating a unique GraphQL type for each event type and having the order event list return a union od those. Like so:

```graphql
type OrderFulfillmentCreatedEvent {
  id: String;
  date: String;
  fulfillment: Fulfillment;
  user: User;
}

type OrderCancelledEvent {
  id: String;
  date: String;
  user: User;
}

type OrderCommentEvent {
  id: String;
  date: String;
  message: String;
  user: User;
}

union OrderEvent = OrderFulfillmentCreatedEvent | OrderCancelledEvent | OrderCommentEvent | ...
```

**Comment by Pacu2** [comment]
I like the idea, let's introduce it after merging #2901 as it introduces another OrderEvent
