### ISSUE TITLE
Draft Order Mutations should check if chosen shipping method is still valid

### ISSUE THREAD

**Issue by Pacu2** [saleor/saleor#3065]
On every significant change in Draft Order via mutations (eg. add the product, delete the product, change the quantity, change shipping address...)  we should check if assigned shipping method is still valid for the updated order.

**Comment by Pacu2** [comment]
@the-bionic Given we have mutations for draft orders in https://github.com/mirumee/saleor/blob/master/saleor/graphql/order/mutations/draft_orders.py

Some of them can change the order content, or it's shipping address.

Shipping methods are price-based, or weight-based, they are also limited to certain countries.
So if one changes his shipping address, we should check if Shipping method is still valid for the new shipping address.

If one changes the content of the order (eg. added 10 more items) we should check if the shipping method is still applicable for order with such weight and price. 

We have a `applicable_shipping_methods` method, on ShippingMethod queryset, that filters all valid methods for given cart/order/checkout.

You might want to take some inspiration from what I've done in `clean_shipping_method` in https://github.com/mirumee/saleor/pull/2567/files#diff-688e75c5115df0efb4fd9175903de965R22

What do you think now? Is there anything else that needs some clarification?

**Comment by the-bionic** [comment]
Thank you, that's clear enough. I'll pick it up.

**Comment by Pacu2** [comment]
@the-bionic Great, go for it!

**Comment by the-bionic** [comment]
@Pacu2 should this check be done after the order has been updated or before?

**Comment by Pacu2** [comment]
@the-bionic I think we should clear the shipping method if it's not valid, as updating the order's content is more important.

**Comment by aniav** [comment]
Dusting off old issues on this repository 🧹

The mutations are checking if draft order has a valid shipping method in newest versions of Saleor.
