### ISSUE TITLE
Menu links does not take language in consideration

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor#3154]
### What I'm trying to achieve
When I change language in demo, I assume that links at menu will use same language.

### Steps to reproduce the problem
1. Go to https://demo.getsaleor.com/pl/ (polish version)
2. Check urls in menu - `/en/products/category/apparel-1/` (points to eng version)

### What I expected to happen
1. Go to https://demo.getsaleor.com/pl/ (polish version)
2. Check urls in menu - `/pl/products/category/apparel-1/` (points to polish version)

**System information**
Operating system: macos
Browser: chrome

**Comment by NyanKiyoshi** [comment]
I can't find a non hacky way of reversing URLs without receiving the language code. The idea would be to drop the language code prefix (e.g. `/en/`) to force django to redirect the user to the correct URL.

The faulty line:
https://github.com/mirumee/saleor/blob/ef38d4395bcfd9c986ab750c5326bcd30d7246d4/saleor/dashboard/menu/utils.py#L29

**Comment by NyanKiyoshi** [comment]
cc. @Pacu2

**Comment by chetabahana** [comment]
Is there any updates concerning this bug? I have tried to change language code to `"id"` in [django setting](https://github.com/mirumee/saleor/blob/5b85f8291f777122124ff4a37e22a5e7adae7311/saleor/settings.py#L59) and [manifest.json](https://github.com/mirumee/saleor/blob/5b85f8291f777122124ff4a37e22a5e7adae7311/templates/manifest.json#L2) but all of the menu links are still remain with `/en/`.
