### ISSUE TITLE
Activating new PWA storefront

### ISSUE THREAD

**Issue by Korred** [saleor/saleor#3240]
### What I'm trying to achieve
Activating the new PWA storefront

### Steps to reproduce the problem
1. Deploy Saleor (according to installation guide)

### What I expected to happen
Access to new PWA storefront as seen in demo: 
[https://demo.getsaleor.com/pl/](https://demo.getsaleor.com/pl/) access via banner to -> [https://pwa.getsaleor.com/](https://pwa.getsaleor.com/)

Either the installation guide is outdated and/or I am missing some settings in order to activate the new PWA storefront. Can you please advise on how to enable the new version? To be clear, site is running fine but I am still seeing the old storefront.

**Comment by maarcingebala** [comment]
Hey, the new storefront lives in a [separate repository](https://github.com/mirumee/saleor-storefront). To access it you have to set it up next to your running instance of Saleor. Take a look at the storefront's readme for instructions.
