### ISSUE TITLE
Payment gateways with redirects after dropping django payments 

### ISSUE THREAD

**Issue by itbabu** [saleor/saleor#3323]
Hello,

A lot of gateways redirect customers to an external website during the payment process.

After Django payments was dropped from Saleor I can't find a proper way to integrate these payment methods in the current workflow without changing the new payment app.

Are you going to manage these payment gateways as django payments did (```RedirectNeeded```, etc)?

**Comment by maarcingebala** [comment]
This is already supported with gateways like Stripe and Adyen.
