### ISSUE TITLE
Product Recommendations

### ISSUE THREAD

**Issue by khalibloo** [saleor/saleor#3390]
### What I'm trying to achieve
Offer product recommendations. Recommendations are a normal part of ecommerce and something that saleor will eventually need to look into. https://github.com/mirumee/saleor/issues/1089 appears only to be concerned with if the feature was available, so I opened a new issue to discuss potential solutions.

### Describe a proposed solution
Since recommendations are closely linked with search and analytics, it makes sense to approach it from the search backend perspective. Elastic's Graph looks very promising as a recommendation engine and it's built to integrate with Elastic Search. It is also open source. 
The main flaw I see with this is that it could tie saleor more to elastic search and limit the ability to plug in other search backends in the future. Or perhaps a "recommendation backend" could be built to support plugging in different recommendation engines eventually.
While recommendation may not be in the roadmap currently, maybe some pointers should be given in the saleor docs for hacks that could be used in the meantime.

### Other solutions
I've seen several articles proposing ways to achieve this using just Elastic Search. It does look like it could be a good start before implementing a more robust recommendation system.

**Comment by jdruiter** [comment]
The easiest way to achieve this, is the way Woocommerce does it: With a textbox where you can type the SKU's of products you want to appear as recommendation under the product. 

Woocommerce has a seperate field for: 
* Upsells (combination packages)
* Recommendations

Of course the default front-end layout should support it too.

**Comment by adrienshen** [comment]
I also like the idea of manual recommendations. It's more flexible for merchants to make this choice when the number of `sku`s is small. Advance solutions like graph search and collaborative filtering would better work as a plugin for larger stores that need it. In my experience, more stores have less than 100 `sku`s so it still possible for human staff to recommend stuff.

**Comment by maarcingebala** [comment]
Manual recommendations can be done with reference product attributes. A recommendation engine is probably out of scope for Saleor core, but sounds like a good idea for an external Saleor App.
