### ISSUE TITLE
Updating order in dashboard

### ISSUE THREAD

**Issue by eriktelepovsky** [saleor/saleor#3987]
### What I'm trying to achieve
Update order through dashboard.

### Describe a proposed solution
Let's say we agreed with customer on different price (discount or different tax for instance). I would like to update the order price/tax using dashboard. Is it possible?

### Other solutions I've tried and won't work
I was looking around in the dashboard for an "update" button but I found actions for payment and addresses only.

Thank you.

**Comment by maarcingebala** [comment]
Hey, our model assumes that once an order is placed it cannot be modified, especially the price. That's a good question whether we should allow to e.g. add a discount to an existing order. Question is how to handle payments e.g. when users already paid for an order, we'd have to refund some money if you applied a discount afterward.

**Comment by eriktelepovsky** [comment]
Thank you for your reply. My goal is to be able to modify the unpaid orders mostly. 

I see multiple cases we can gain from this: 
1. already mentioned: to add a discount for the customer (as thanks or apologize for any kind of troubles)
2. to add an additional item into order (free gift)
3. the most important for me: to modify the tax (in European Union, there are some cases where applied tax is 0 instead of standard one depending on the relationship between a customer and the supplier). As I know (correct me if I am wrong), the current version is not able to handle such cases as it is not possible to enter the VAT ID in the billing details/address so the Saleor doesn't know how to handle taxes in such cases correctly.

**Comment by eriktelepovsky** [comment]
+1

**Comment by zodiacfireworks** [comment]
+1

**Comment by wfelius** [comment]
So what If I want to swap the product .. the costumer wants a different colour (but the same price) I would like to toggel the status of the order back to "draft"

**Comment by maarcingebala** [comment]
Some of these features are already implemented - first of all, the ability to place unconfirmed orders which can be modified as long as the order is in the unconfirmed state. Secondly, the admin can modify the order line prices by applying line discounts.
