### ISSUE TITLE
Find a way to group all validation errors while performing a mutation

### ISSUE THREAD

**Issue by akjanik** [saleor/saleor#3997]
After merging #3891 in few places there may be a case when someone received a validation error, corrected data only to get another one, he did not know because code stopped execution after first `raise` that happened.
`validate_address` may be a good example
https://github.com/mirumee/saleor/blob/cb312fa32fbc69de60c6fc6c000f47b5e58f80be/saleor/graphql/account/i18n.py#L14-L30
If both  `country_code` and `address` will be wrong, a user needs to send request twice, to realize that.

**Comment by peelar** [comment]
@maarcingebala Is this up to date? Is it more of a bug or a feature request?

**Comment by maarcingebala** [comment]
It is partially solved for some mutations. I would say it's a low priority for now.

**Comment by aniav** [comment]
Dusting off old issues on this repository 🧹

Most mutations follow the pattern of collecting errors into a field called `errors` now. If you notice a mutation that's missing this behaviour please don't hesitate to report a specific mutation. Thank you!
