### ISSUE TITLE
Selective email sending

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor#4020]
### What I'm trying to achieve
ATM I can send all emails (Order Confirmation, Registration, etc). I would like to choose which ones are sent by backend and which not. 

Use case: Order confirmation email is handled by external API and I don't want to use those generated by Saleor.

### Describe a proposed solution
Multiple settings in `settings.py` where I can select which types of emails I will send.

**Comment by maarcingebala** [comment]
Or an interface in Dashboard 2.0. If we had a section like this in the dashboard, we could think of some email template management, in the simples form, just to change the copy. Sooner or later we will probably have to as this might be required for Saleor Cloud.

**Comment by timuric** [comment]
Using webhooks is the best way to achieve that.
