### ISSUE TITLE
Add Customer Segments

### ISSUE THREAD

**Issue by Pacu2** [saleor/saleor#4048]
**Customer segmentation**
As a store admin, I would like to create  ‘promotion groups’ of customers.
Rules could be based on Recency, Frequency, Order Value, and Country 

So for example, we need to be able to set:
- Customers from US
- Have ordered in the past 6 months
- Have spent at least $300

or 

- Customers from all countries
- Have more than 3 orders in past 12 months
- Have spent at least 400$

**Promotion group**
Above customers should have prices automatically discounted. I think we can extend our current Sale implementation to include customers and promotion group. Open for the discussion.

**Comment by timuric** [comment]
Hey @here ! We have a draft of a custom pricing mutation, please take a look https://github.com/saleor/saleor/pull/9326
It will allow you to add lines to checkout with arbitrary prices. 
Any feedback is welcome!
