### ISSUE TITLE
Allow per-order purchase limits

### ISSUE THREAD

**Issue by patrys** [saleor/saleor#4191]
### What I'm trying to achieve
This is especially useful when selling pre-orders for a product with limited stock as it prevents a single customer from buying the entire available pool of items.

### Describe a proposed solution
Introduce a field on the product (or variant, TBD) that would allow the maximum quantity for a single order to be limited. This will need a separate error message from the one presented when the stock limit is hit.

**Comment by siphon-app** [comment]
Looking for the same feature.

**Comment by maarcingebala** [comment]
Added in 3.1.
