### ISSUE TITLE
Add value descriptions to (all) GraphQL enums

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#4248]
It also needs to be "standardized" into the Saleor code and into the documention. So we only have one style and the "perfect" non-magic way.

**Comment by maarcingebala** [comment]
Btw we've recently bumped Graphene version and now Graphene supports setting deprecation messages for enums. I think we have our own wrapper for that which I think isn't required anymore. See the [changelog](https://github.com/graphql-python/graphene/releases/tag/v2.1.5) and [these changes](https://github.com/graphql-python/graphene/commit/6a4091b3e4734fe032397b0bcd350820f6037d0f).

**Comment by maarcingebala** [comment]
That's a separate issue but this version also added the implementation of `Decimal` scalar so we should be able to drop our own implementation.

**Comment by NyanKiyoshi** [comment]
> Btw we've recently bumped Graphene version and now Graphene supports setting deprecation messages for enums. I think we have our own wrapper for that which I think isn't required anymore. See the changelog and these changes.

Our wrapper is converting our custom enums that have the `CHOICES` fiels into a GraphQL enum, it's meant to avoid repetitive `[(k, v.upper()) for k, v in cls.CHOICES.items()]`.

**Comment by maarcingebala** [comment]
Adding `good first issue` label. If anyone wants to pick this up, it's best to work on this in smaller batches and provide pull requests for each module separately. Reviewing and improving is easier than a big PR with changes in many modules.

**Comment by moraj-turing** [comment]
I am available to work on this, please provide an example, I see some enums already have `@proprerty def description()` created, is this what the issue is referring to?
