### ISSUE TITLE
Add queries and mutation for handling user credit cards

### ISSUE THREAD

**Issue by mateuszkula** [saleor/saleor#4285]
### What I'm trying to achieve
I would like to have query and mutation for managing user credit cards. 

Needed data can be found on mockup from storefront design on Figma:
<img width="942" alt="Zrzut ekranu 2019-06-14 o 09 04 00" src="https://user-images.githubusercontent.com/30259869/59490117-27702900-8e84-11e9-8102-c1ed0a6ea85b.png">

Querying would include:
- List of all CCs
- Data for each card - Name on card, expiration date, last 4 digits of CC

Mutation:
- Removing CC
- Changing Name on card/expiration date

**Comment by maarcingebala** [comment]
This is not yet supported in Saleor, here is the related backend issue: #2700.

**Comment by salwator** [comment]
@mateuszkula 
We are not going to store in saleor db CC info, we rely on gateways in this regard, so mutation part is pointless, if anyone want to change card, using new one in checkout is the way to go.
Implemented in #4195 .

**Comment by maarcingebala** [comment]
Is this issue resolved then @salwator @mateuszkula ?

**Comment by maarcingebala** [comment]
Part of that is already covered - we have queries to get stored credit card info:

```
{
  me {
    storedPaymentSources {
      gateway
      creditCardInfo {
        brand
        firstDigits
        lastDigits
        expMonth
        expYear
      }
    }
  }
}
```

However, storing credit cards depends on the gateway's configuration and it's not available for all of them. At the moment we have it only for Stripe.
