### ISSUE TITLE
Voucher for non-discounted products

### ISSUE THREAD

**Issue by fowczarek** [saleor/saleor#4383]
I would like to be able to create the voucher which can be used only for non-discounted products. 

Voucher can be applied for orders with at least one product without sales. 
If a user has the checkout with products, voucher discount is applied only to products without a sale.

For example:
User has a t-shirt and shoes in checkout. The store has a 20% sale for all shoes. If the user applies the entire order voucher for non-discounted products, the voucher is applied only for the t-shirt.

**Comment by timuric** [comment]
Indeed a very common scenario during sales

**Comment by maarcingebala** [comment]
Closing, as this is not part of the roadmap currently, let's reopen or create a new ticket with RFC if we want to add these changes.
