### ISSUE TITLE
Product search query should return the list of applicable attribute filters

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#4437]
Our API needs to provide a way to determine in the frontend what faceted search filters are available i.e. attribute filters. E.g. in the case below we don't want to return all available attribute filters but only those that are suitable for the given results:

![image](https://user-images.githubusercontent.com/5421321/60980041-06d8a900-a334-11e9-9931-97708eecd17b.png)

Another thing to remember is that in PR #4259 we're introducing a flag to determine whether an attribute should be displayed in the faceted search which also should be taken into consideration in this API.

**Comment by NyanKiyoshi** [comment]
After internal talking, we came up with a few possibilities with some advantages and drawbacks.

#### 1 – Including a `attributes` connection in the root query of the `products` connection
```gql
{
  products(first: 10) {
    attributes(first: 10, filter: ..., sortBy: ...) { edges { node { ... } } }
    
    edges {
      node {
        attributes {
          attribute {
            name
          }
        }
      }
    }
  }
}
```

- Against our implicit convention of only having `edges`, `pageInfo` and `totalCount` fields.
- Have to query the products again if we need to fetch new attributes, e.g. another sorting, 10 more to load (pagination), etc.

#### 2 – Splitting the query/request into two sub-queries
##### Queries
1. Filter attributes through some product filters, "`productsMatching: "Apple"`"
1. Filter the products: `products(filter: { search: "Apple" })`

##### Advantages & Drawbacks
- Can run it in a single HTTP request using a bulk query request
- It is not very user/developer friendly, it is pretty dirty and hard to achieve for new-comers
- It makes the `attributes` connection, (the filters are) very complex and hard to understand
- It is forcing us to filter the products twice to come up with all the results

#### 3 – Introducing a new query connection for searching for products
```gql
{
  productSearch(terms: "Apple") {
    attributes(first: 10, ...) { ... }
    products(first: 10, ...) { ... }
}
```

- Returns products on demand
- Easy to paginate
- Prevents from making two separate queries

**Comment by vinit-m** [comment]
Even we are facing the same issue when products query is called using the search parameter,  the attributes (filters) is not dynamic based on the products list. Is there any way that we can have attributes (filters) always based on the products API results.

**Comment by lastmaj** [comment]
is the integration of a search engine (ex: elasticsearch) a viable option ?

**Comment by maarcingebala** [comment]
Faceted search should be most likely handled by an integration like Elasticsearch, Algolia, etc. Currently, this is not in the scope of Saleor Core. The integration could be built as Saleor App.
