### ISSUE TITLE
Simplify the default sorting of M2M models (django 3.0)

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#4565]
### What I'm trying to achieve
It would be better to have a simple default ordering through meta data than having to call a method of the querysets. The issue, is that it is not currently possible due to a bug in Django 2.0 ([ticket](https://code.djangoproject.com/ticket/30501)) but was fixed on development branch 3.0.

Whenever this is possible, it would be great to unify and simplify the default ordering logic.

**Comment by maarcingebala** [comment]
Is this still an issue?

**Comment by NyanKiyoshi** [comment]
> Is this still an issue?

I don't think so. I'm not sure what the ticket is trying to solve too, it lacks details.
