### ISSUE TITLE
Braintree: make sure we use an appropriate merchant account

### ISSUE THREAD

**Issue by patrys** [saleor/saleor#4604]
A single Braintree account can have multiple merchant accounts, each for a different settlement currency. It seems the current implementation of the Braintree gateway does not pass a merchant account ID which means that Braintree will use the default account, which may not be the one we want.

We should either let the user configure an explicit account ID for any given currency, or fetch the list of merchant accounts and see if there is one matching the checkout's currency before attempting to use the gateway, then pass the appropriate merchant account ID when authorizing or charging.

**Comment by maarcingebala** [comment]
I'll close this one since the Braintree plugin won't be developed anymore and apps are recommended way of handling payments. See https://github.com/saleor/apps.
