### ISSUE TITLE
elasticsearch returns only 10 items( not return all items)

### ISSUE THREAD

**Issue by kevin-eom** [saleor/saleor#4657]
### What I'm trying to achieve
I'm trying to integrate with ES but recognized that elasticsearch-dsl returns only 10 items by default 

### Steps to reproduce the problem
1. Set ES on settings
2. Search items with condition which has more than 10 items

### What I expected to happen
I expected it returns all results which is matched with pagenation but it returns only 10 items without pagenation

### Screenshots

**System information**
Operating system: 
Browser:

**Comment by korycins** [comment]
@kevin-eom  Thanks for reporting this issue.
ES by default returns 10 items. 
I don't see any logic to handle iteration or fetch all results in Saleor. -> `saleor/search/backends/elasticsearch_storefront.py`

**Comment by kevin-eom** [comment]
I found workaround.
If you put 'extra(from=0, size=1000)' on end of 13 line, you can get 1000 results.
But it is also a little bit tricky, if search result is exceed 1000, it won't work properly.

I think you need to consider using other method such as 'scan' or build other method for searching if you want handle es result size.

By the way, do you guys consider to implement other es's feature such as 'auto complete' for search word?

@korycins

**Comment by maarcingebala** [comment]
Closing as Elasticsearch is no longer supported.
