### ISSUE TITLE
Change AddressInput type field name

### ISSUE THREAD

**Issue by mateuszkula** [saleor/saleor#4662]
### What I'm trying to achieve
When using mutations to add/modify address Saleor uses `AddressInput` type which contains `country` field.

From description:
```
 country String
Country. 
```

Its hard to figure out what should be correct input(country name(translated?) or country code). The actual valid input is **country code**.

I suggest to change this type in following way:
-> add new field - `countryCode`
-> make `country` field depracated

**OR** add better description to this particular field so the user knows what is correct input,

**Comment by Kwaidan00** [comment]
I think better docs would be enough. Confusing comes from bad documentation.
If field name was be changed, additional logic would have to be added to mutation and validation stuff., I'm afraid.

**Comment by Kwaidan00** [comment]
Moreover, here is very similar issue: https://github.com/mirumee/saleor/issues/4466. There are also a suggestion that type should be changed to `CountryCode`.

**Comment by peelar** [comment]
I think the docs for that were improved. @maarcingebala can you please confirm? 🙏

**Comment by maarcingebala** [comment]
Yep, we have added descriptions to `AddresInput` fields.
