### ISSUE TITLE
Consider moving some of core.utils modules

### ISSUE THREAD

**Issue by Kwaidan00** [saleor/saleor#4744]
### What I'm trying to achieve
I think that `core` package should avoid importing from other packages. It could lead to circle imports in the future.

The problematic modules I've found are:
1. `core.utils.promo_code`. It imports models from two packages (`discount` and `giftcard`). It would import more stuff if #4676 was merged.
2. `core.utils.url`. It has one function, used only in one package (`graphql.account`). It would import from `account` package if #4676 was merged.
3. `core.exceptions`. If #4676 was merged, it would import from `checkout` module.

### Describe a proposed solution
It's open question where that modules should live. I think we should discuss it.

I don't have a clear answer where 1. should be. For the second module, I think it could be moved to `graphql.account.utils`. If a new use case for that function was found, it would have sense to move it somewhere.

**Comment by maarcingebala** [comment]
This is a low priority and likely won't be touched in the near future. I'm closing this for now.
