### ISSUE TITLE
BasePlugin saves config structure to DB

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#4897]
The `BasePlugin` should store its configuration as a  list of `key: value`. There is a bug that adds the whole `config_structure` to DB.

**Comment by szewczykmira** [comment]
This will be a bigger task as it will need to add more tests (and fix all current one as some of them have wrong test data ;) )
A good idea would be to add validators that check if those values are in proper type.

**Comment by szewczykmira** [comment]
@korycins 
Before I start to changing everything - which option we should keep in databse:
1. `"name": "Company name", "value": "DEFAULT"`
2. `"Company name": "DEFAULT"`

**Comment by korycins** [comment]
Each plugin has overwritten `_get_default_configuration`. There you will find an expected structure of configuration that we should store in DB. The issue is probably connected with `_update_configuration_structure` which updates a configuration when some fields have been changed. Tests could be written based on the `test_update_config_items_keeps_bool_value`, which provides whole saving process.

**Comment by aniav** [comment]
I'll close this as we're moving away from plugins and towards apps and we're only fixing crtical bugs.
