### ISSUE TITLE
Payment gateway availability based on customer

### ISSUE THREAD

**Issue by salwator** [saleor/saleor#4909]
### What I'm trying to achieve

I want to show customer personalized list of payment gateways that takes into account type of user and/or other metadata.

### Describe a proposed solution

Gateways could (optionaly) implement additional method that validates user capability. We should filter availablePaymentGateways in checkout based on their response to customer validation.
Arguably, best way would be to pass dedicated private meta to gateway to avoid passing customer model around.

**Comment by krzysztofwolski** [comment]
I'm suggesting using whole checkout when validating payment methods: in both of my previous projects I had to implement logic to block payment methods based on items in cart

Use case:
I would like to use Affirm payments only for physical products and block it when user has any digital product in cart.

**Comment by maarcingebala** [comment]
Closing as payments are now handled by apps.
