### ISSUE TITLE
Make the context processors lazy

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#4918]
It can happen we want to be able to render a template without ever needing the data returned by the context processors that are querying the database.

Just like the middlewares, we have no choice, we cannot decide if we want them to execute or not, but we do have the choice to make them lazy. Which also seems to be a common practice when looking at the third party context processors saleor is using.

An example use case is to render a template while the database might not be ready to be queried, but the context processors would trigger an internal error.

**Comment by maarcingebala** [comment]
Templates and context processors are not a thing anymore in Saleor 🎉
