### ISSUE TITLE
plugin.get_plugin_configuration should not return fields not attached in `CONFIG_STRUCTURE`

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#4963]
`get_plugin_configuration` returns all fields that exist in DB. We should return only the fields which exist in `CONFIG_STRUCTURE` variable

**Comment by korycins** [comment]
Test to modify - `test_plugin_updates_configuration_shape`

**Comment by korycins** [comment]
`saleor.extensions.base_plugin.BasePlugin#_update_configuration_structure` Should handle the case when plugin owner changed `default_configuration` to None. Now it fails.

**Comment by maarcingebala** [comment]
Closing as plugins are getting deprecated and won't be developed anymore.
