### ISSUE TITLE
3D Secure Payments Fail with Braintree

### ISSUE THREAD

**Issue by petedermott** [saleor/saleor#4975]
### What I'm trying to achieve
Process a payment with the Braintree gateway with 3D Secure enabled.

### Steps to reproduce the problem
1. Download and install the 2.9 master
2. Populate the DB
3. Setup a Braintree Payment configuration with 3D Secure enabled
4. Make a test purchase either via the GQL storefront (0.7.0) or the 1.0 Django dashboard

### What I expected to happen
The purchase to go through or at least pass the data to the bank for verification

### What actually happens
The 1.0 Storefront returns an error "Unable to process transaction. Please try again in a moment __all__"

The GQL Storefront returns  an "Unable to process transaction. Please try in a moment" error.

### Screenshots
![saleor-django-fail](https://user-images.githubusercontent.com/7780261/68941263-45c4b280-079d-11ea-89b2-0605b612571f.jpg)

![saleor-gql-fail](https://user-images.githubusercontent.com/7780261/68941268-49583980-079d-11ea-802c-1b6ef120d0ac.png)

**System information**
Operating system: Windows 10 Pro
Browser: Chrome 78.0.3904.97 and Firefox 70.0.1

**Comment by karolkielecki** [comment]
Hi @petedermott ! We'll take a look into this as soon as we can. If there are any news, I will let you know. Thanks for your patience and your support!

**Comment by giovannipiccinelli** [comment]
@karolkielecki has this problem been resolved? Is there a PR for this? I am experiencing issues from customers unable to pay. Thanks for the support!

**Comment by maarcingebala** [comment]
The problem might be relevant in the old version of Saleor, it should be working now in 3.0/3.1, although I'm not sure that [saleor-storefront](https://github.com/saleor/saleor-storefront) fully support 3DS flow with Stripe. Note that both Saleor 2.9 and saleor-storefront are no longer maintained, a successor project is https://github.com/saleor/react-storefront.
