### ISSUE TITLE
Shipping price plugin interface

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor#5001]
### What I'm trying to achieve
I would like to use ExtensionManager to create a plugin for calculating the shipping price.

To be discussed:
- simple plugin with 'checkout_shipping_price' is enough?
- should we create a similar interface as payment methods? (pluggable shipping gateways for using Saleor Build In, Shippi, Different api etc) - that's my personal preference but will need more work

Notes:
- shipping price depends on currency, warehouse location, shipping address location, the weight of checkout, size of the checkout, chosen shipping method, products in checkout lines  (the last one is my project requirement)

**Comment by aniav** [comment]
I'll close this as we're moving away from plugins and towards apps and we're only fixing crtical bugs.
