### ISSUE TITLE
Extensions: checkout outstanding balance calculation

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/saleor#5009]
### What I'm trying to achieve

I would like to have single place for calculating how much I have to pay for a checkout and how much I've already paid. Since we use gift cards, (its non payment type which lowers checkout value) we manually subtract it from cart total in few places which counts as logic duplication.

The current algorithm for this value:
outstanding_balance  = checkout total - the sum of gift card value - the sum of all created payments

### Describe a proposed solution
- new method in `checkout.base_calculations.outstanding_balance `
- new method in `checkout.calculations.outstanding_balance `
- new method in extension manager `outstanding_balance `
- same for calculating paid amount

**Comment by patrys** [comment]
I believe it's usually called `outstanding_balance`.

**Comment by krzysztofwolski** [comment]
@patrys exactly :)

**Comment by aniav** [comment]
I'll close this as we're moving away from plugins and towards apps and we're only fixing crtical bugs.
