### ISSUE TITLE
Support more input types for attribute values

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#5036]
In the `Attribute` model we have the `input_type` field which determines how a value can be entered in the dashbaord and how it's rendered in the storefront. Now we have two types:
- dropdown - to select one value from a list of predefined choices
- multiselect - as above, but to select multiple values

We need to introduce more input types:
- text field - for storing simple text values (think CharField in Django)
- text area
- datetime
- boolean - for yes/no attributes

**Comment by matthewjralston** [comment]
For a customized product I would need a collection of attributes in a form I can validate and send back to the server to get an updated preview image based on the user data entered into the attribute fields. 

Data types would be open text fields, file uploads for spreadsheets, photos, logos and other content to build data driven products.

**Comment by dankolbman** [comment]
In addition to the above input types, I'd like to motivate the need for numeric types as well.

We have products with attributes such as volume, dimensions, or age which we would like to allow users to filter by using a range search.

**Comment by maarcingebala** [comment]
@dankolbman Numeric input types are definitely on our roadmap as well.

**Comment by itsgauravjain22** [comment]
Yes I am looking for this. Consider I want to have book store. If we have text type and numerical type product attribute option, we can create ISBN13, ISBN10 and Pages as number product attributes. That would be appropriate if added in saleor as soon as possible.

**Comment by cr0nex** [comment]
Do you have any ideas as to how to approach the implementation that would build off the current attribute system?
Particularly integers/floats that would be searchable by ranges (preferably on the DB level).

**Comment by khalibloo** [comment]
This is one issueI consistently run into as well. Color and even Image input types especially. For color, we sometimes use hacks such as hex codes, but that's less than ideal. I've only had one instance where image input type was needed though. That was for textile/fabric patterns.

**Comment by LeOndaz** [comment]
same

**Comment by maarcingebala** [comment]
For anyone interested in progress on this topic - we're currently working on many improvements to the attributes system. First, we're adding page types (PR is already open) that will work similarly to product types, but for pages. Then we'll introduce more input types:
- file uploads
- references - attributes of this type will be able to reference other items in the system by ID; this will allow you to e.g. create an attribute "related products" and assign a set of products IDs that should be rendered on a product page (or a content page)
- rich-text - attributes of this type will be rendered in the dashboard as rich-text editor and will store content as JSON; this will unlock CMS-like capabilities for pages (creating new page sections as separate attributes)

And more to come in the future :)

**Comment by Ahzam-Lathiya** [comment]
hey @maarcingebala how's that input charfield coming up in the models. If you guys have already patched some changes can you please teach me how to use it in the current version. I'm using 2.10 stable release.

**Comment by artdiev** [comment]
@maarcingebala thank you for the hard work 😊
Will you be addressing storing numbers and searching by numbers (inc. ranges)?

Use case:
We have an attribute size (meters) that can range from 0 to 5000.
Instead of having 5000 standalone values in the system (really hurts performance of attribute queries), it would be nice to be able to store it just as one value in the DB, and filter by >, <, =. I was trying to come up with a flexible solution that would use numbers in the DB, but could not tie it into the current implementation (allow users to select Numbers alongside Dropdown & Multiselect).

**Comment by ace-han** [comment]
How is this feature going?

My use case:
T-shirts with below attributes
`color`: red, green, blue
`size`: small, medium, large
`message`: text field for a personalized message to print on the T-shirt, like [option](http://docs.oscarcommerce.com/en/latest/ref/apps/catalogue.html?highlight=option#oscar.apps.catalogue.abstract_models.AbstractOption) in `django-oscar` 

How to implement this `message` attribute in current Saleor 3.0 or 3.1? 
Thanks in advanced.

**Comment by maarcingebala** [comment]
Currently supported types in 3.1:
- dropdown
- multiselect
- file
- reference
- numeric
- rich-text
- swatch
- boolean
- date
- date-time
