### ISSUE TITLE
Add test cases for filtering products by attributes when providing multiple inputs

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#5060]
We are missing some for `AND` and `OR` conditions, we should have a case for, i.e.:
- Products having:
  - 1 or 2 GB or RAM
  - and 500 or 1 TB of storage

Currently, we only test:
- Products having:
  - X value in Y attribute

**Comment by jmfsilva** [comment]
@NyanKiyoshi there is actually a bug with multiple filtering on attributes.
If you filter with product attributes using more than 1 filter no product will be displayed.
The multiple filtering only works if you use one product attribute and one variant attribute, for example on the demo site if you select groceries category and you pick filtering "orange" and "500 ml" you will get the correct orange juice product, but in that case "orange" is product attribute and "500ml" is variant attribute, if you add to that juice another product attribute that is not variant attribute and you try to filter for both of those, no product will be displayed...
Adding this test would probably expose this issue.

**Comment by NyanKiyoshi** [comment]
@jmfsilva thanks for reporting, could you open an issue?

**Comment by txhai** [comment]
I've met the same issue (release 2.10.2), filtering with more than 1 input on variant attributes returns zero records although there are matched products.
I temporarily get the acceptable result by editing the filter:
https://github.com/mirumee/saleor/blob/82526238ab451f052bf91cdd7a8203959c3a5666/saleor/product/filters.py#L34-L35
to
```python
for condition in combine_and:
    qs = qs.filter(condition).distinct()
```

**Comment by maarcingebala** [comment]
Closing in favor of https://github.com/saleor/saleor/issues/14087 - we will be using a dump of a large DB to test performance, including attributes and filtering.
