### ISSUE TITLE
checkoutUpdateMeta requires permissions to append data

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#5071]
Issue discovered here: https://github.com/mirumee/saleor/issues/4779#issuecomment-539623681
We have the same situation with `Checkout` as we had with `Order`. Here is the PR for Order: https://github.com/mirumee/saleor/pull/4876

We should allow to update and use metadata without permission. To protect it, as an ID we should use `checkout_token`

**Comment by EwanValentine** [comment]
Is anyone working on that fix already? I might take a stab at it if not @korycins

**Comment by korycins** [comment]
Hey, it is free, you can take it.
You should use the flow from the PR for Order Meta #4876

**Comment by EwanValentine** [comment]
Will do, thanks!

**Comment by EwanValentine** [comment]
@korycins do you have any steps for contributing at all? How the tests are ran etc, or what set-up's needed? I took a look but couldn't find much

**Comment by EwanValentine** [comment]
@korycins hey again, I've done most of the changes, I followed the pr you linked me to. But there's no checkout permissions currently, so I've attempted to add that in, but I'm not having much luck. Could you offer any guidance as to how to add new permissions?

I'm getting an error (among a few others):
```
self = <User: staff_test@example.com>, perm = 'checkout.manage_checkouts', obj = None

    def has_perm(self, perm: BasePermissionEnum, obj=None):
        # This method is overridden to accept perm as BasePermissionEnum
>       return super().has_perm(perm.value, obj)
E       AttributeError: 'str' object has no attribute 'value'

```

Apologies, I'm not too familiar with Django unfortunately!

**Comment by EwanValentine** [comment]
@korycins hey, there were some slight differences with the other PR, I've got into a bit of a mess with the permissions, just wondered if someone could give me some guidance? Thanks!

https://github.com/mirumee/saleor/pull/5112

**Comment by korycins** [comment]
@EwanValentine Hey, I've checked your PR. It looks really good. only some small comments

**Comment by EwanValentine** [comment]
@korycins I've updated this and fixed all the issues mentioned, there's a failing test I can't figure out, if anyone could help me out, would be greatly appreciated

**Comment by EwanValentine** [comment]
@korycins I fixed that final test, and fixed any linting issues, everything's passing building apart from the codeclimate build, let me know what I can do to fix it, and I'll get it sorted asap

**Comment by maarcingebala** [comment]
Closing this as mutation `checkoutUpdateMeta` was removed. With the current metadata API, checkout public metadata doesn't require permissions, but you need to know the token. Private metadata requires MANAGE_CHECKOUT.
