### ISSUE TITLE
Fix object permissions for service accounts

### ISSUE THREAD

**Issue by salwator** [saleor/saleor#5111]
Object permissions are not properly checked for multiple object types in API when using service accounts, ex:
- Collection and Category through Sale
- Pages
- Collections
- ProductVariant
- Product through ProductType

Nature of this problem is described in detail for Products in #5108 
More general approach and object access logic refactoring should be applied to avoid code redundancy and easy to make future bugs.

I would suggest connecting context with checking for permissions so it can access locally both user and service account when needed.

**Comment by maarcingebala** [comment]
Apps have now proper permissions control on most of the objects, if anything is misconfigured around this, let's open a new issue.
