### ISSUE TITLE
CheckoutLine.objects.create causes undesired count query

### ISSUE THREAD

**Issue by purpledot** [saleor/saleor#5200]
### What I'm trying to achieve
Create checkout with a checkout line.

### Steps to reproduce the problem
1. `checkout = Checkout.objects.create(...)`
2. `checkout.lines.create(...)` or `CheckoutLine.objects.create(checkout=checkout, ...)`

OR

1. `checkout = Checkout.objects.create(...)`
2. `if checkout: pass`

### What I expected to happen
Database insertion without additional count query `
SELECT COUNT(*) AS "__count"
FROM "checkout_checkoutline"
WHERE "checkout_checkoutline"."checkout_id" =
`.

I think, the cause is [Checkout's](https://github.com/mirumee/saleor/blob/master/saleor/checkout/models.py#L113)  `__len__`  method and this behaviour described in [ python's documentation](https://docs.python.org/3.7/reference/datamodel.html#object.__bool__).

> object.__bool__(self)
> Called to implement truth value testing and the built-in operation bool(); should return False or True. **When this method is not defined, __len__() is called**, if it is defined, and the object is considered true if its result is nonzero. If a class defines neither __len__() nor __bool__(), all its instances are considered true.

So, checkout's `__len__` method is called every time there is `if checkout:`.
In case of `CheckoutLine.objects.create(checkout, ...)` it's called [here](https://github.com/django/django/blob/master/django/db/models/base.py#L684).

**Comment by maarcingebala** [comment]
Good catch. I think we could drop the `__len__` implementation and, when needed, to check if checkout lines exist in an explicit way. Actually I don't see any `if checkout` or `bool(checkout)` checks in the code, so maybe it's not even used.
