### ISSUE TITLE
Inputs on database design decisions

### ISSUE THREAD

**Issue by saiprashanth173** [saleor/saleor#5216]
Hello folks,

Thanks for developing Saleor.

We are part of the database group at Georgia Tech. We are developing a tool, called sqlcheck, for assisting database application developers in designing performant and maintainable applications. sqlcheck automatically detects sub-optimal database design choices and suggests better alternatives. For instance, storing comma-separated values in a column violates the first normal form, which impacts the performance, maintainability, and extensibility of the application.

We extracted SQL queries from Saleor and analyzed them with sqlcheck. Here are the results:

- **Too many indexes/Indexes not being used:** In certain tables (e.g., product_category), we observed that the application constructs indexes on many columns in these models. We found that many of these indexes are not being utilized by the queries obtained by running the integration tests. Our experiments with sqlcheck showed that constructing too many indexes slows down data ingestion. We understand that this design decision could stem from application requirements. Could you please share the rationale behind this design decision?
- **Multi-valued attributes:** Storing delimiter separated values in a single column. In Saleor, the tool identified the usage of pattern matching on **countries** column of **shipping_shippingzone** table for filtering rows and we believe this column contains delimiter separated values. Our experiments with sqlcheck showed that there is a significant performance impact in querying or updating such columns and the pattern matching could possibly return inaccurate results. The alternate better approach, i.e., having an intermediate table to represent this Many to Many relationship, could result in an approximately 10x performance gain and also makes sure that the application is maintainable, accurate and extensible. 

We hope that sqlcheck will assist the broader community of database application developers with designing applications. Your feedback will be greatly appreciated.

Thanks for your time.

**Comment by gsoec** [comment]
Saleor internally uses [https://github.com/SmileyChris/django-countries](https://github.com/SmileyChris/django-countries) which is based on Django's `CharField` and is unable to be separated into another table at the moment i guess?

**Comment by maarcingebala** [comment]
Thanks for your valuable feedback. We're currently testing performance in Saleor and there are a few areas where we can make improvements - using indexes is one of them.

`ShippingZone.countries` is an interesting example, because as @gsoec wrote, we use there `CountryField` from `django-countries` package, which allows for storing comma-separated country codes. If having an M2M relation with country codes would be more efficient, it's also something that we should change there. One place where we use this field for filtering is e.g. this one: https://github.com/mirumee/saleor/blob/997dbb519053c52380f191cb1b47b4473468e17c/saleor/shipping/models.py#L108. I'd love to see a benchmark comparing the current solution vs. M2M relation with an additional table for countries.

**Comment by patrys** [comment]
I would also be interested in comparing the current solution vs. an array field vs. a separate table.

**Comment by saiprashanth173** [comment]
Thanks for replying back. We are glad that you find the suggestions provided by sqlcheck useful. 

We have already performed a similar experiment with a table containing 10 million records (M2M relations). The experiment is performed in an environment where there are no concurrent requests to the database. Please check the table below. 

|                                     | SELECT | INSERT new |
|-------------------------------------|--------|------------|
| comma separate strings              | 5s     | 0.7s       |
| separate table (no-index on fields) | 0.003s | 0.003s     |
| separate table (index on fields)    | 0.002s | 0.003s     |
| Array with "GIN Index"              | 0.005s | 1.4s       |

Note: We performed all our experiments on PostgreSQL 11. For Array, we used "string_to_array" and created a GIN index on the column. 

If you are looking for a quick solution to improve your read performance, you could look into the GIN index provided by postgres. 

If you could provide us some stats on, the size of your tables, queries which are executed the most, etc, we will be happy to provide more inputs and results from relevant experiments. 

Hope you find this information useful.
