### ISSUE TITLE
Populatedb randomly crashes if some already existing users don't have a billing address

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#5226]
### Steps to reproduce the problem
1. Create some or a user having no default billing address
1. Optionally remove other users to have more chance of crashing
1. Run populatedb
1. It might crash when trying to create a fake payment

### What Happened
The following code snippet will select a user randomly which might not have an existing billing address:
https://github.com/mirumee/saleor/blob/61b3a62988599d76184955663f89e8892b92b6e4/saleor/core/utils/random_data.py#L507-L510

```
  File "/app/saleor/core/utils/random_data.py", line 387, in create_fake_payment
    billing_address=order.billing_address,
  File "/app/saleor/payment/utils.py", line 82, in create_payment
    "billing_first_name": billing_address.first_name,
AttributeError: 'NoneType' object has no attribute 'first_name'
```

**Comment by megamayoy** [comment]
is this bug still relevant now ?

**Comment by maarcingebala** [comment]
This is now fixed.
