### ISSUE TITLE
Add saleor version to OpenTracing

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#5267]
### What I'm trying to achieve
I would like to be able to know which version of Saleor is X trace associated to.

### Describe a proposed solution
Whether being build through a tag for releases or git hash for master.

This could be easily achievable through CircleCI when building the latest docker version. Suggestions would be nice to have.

**Comment by TANATNATH** [comment]
Hi 😊😊👋👋

**Comment by maarcingebala** [comment]
Done.
