### ISSUE TITLE
Exceptions coming from GraphQL API are not reported to OpenTracing

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#5284]
### What I'm trying to achieve
I would like to be able to see in traces that a query (segment) failed because X exception was not expected. Currently the executor will return HTTP 200 (expected) and give information about the internal error but not tell the tracer about it.

### Steps to reproduce the problem
1. Raise an exception in a GraphQL handler (resolver or mutation)
2. It won't be reported to the tracer

### What I expected to happen
Have a traceback in the failing segment(s) and an error flag set to `True` when something unexpected happened.

**Comment by maarcingebala** [comment]
Done.
