### ISSUE TITLE
Add sortBy parameter to queries

### ISSUE THREAD

**Issue by dominik-zeglen** [saleor/saleor#5322]
### What I'm trying to achieve
To sort `query.homepageEvents` and `query.customer.orders`.

### Describe a proposed solution
Add `sortBy` field.

### Other solutions I've tried and won't work
Using `last` without `before` should not be possible, so now it relies on a bug.

References https://github.com/mirumee/saleor-dashboard/issues/428

**Comment by eCzerniak** [comment]
Issue reported. 

https://app.clickup.com/t/2kpayuk
