### ISSUE TITLE
Email is not completely translated

### ISSUE THREAD

**Issue by Anyman552** [saleor/saleor#5374]
The main part of the email("You're receiving this e-mail...") is not translated. The parts after are properly translated. However, the text in text/plain is completely correctly translated. I've tried it with different languages (german and russian).

However, the text in text/plain is completely correctly translated:
```
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit



Hi!

Sie bekommen diese E-Mail weil Sie oder jemand anders ein Passwort für Ihren Benutzeraccount auf localhost:8000 angefordert hat.
Sie können diese Nachricht ignorieren, wenn sie es nicht selber angefordert haben.
Klicken Sie unten um Ihr Passwort zurückzusetzen.


http://localhost:8000/de/account/password/reset/MQ/5ez-e13a9786c6c548232f8b/


Dies ist eine automatisch generierte E-Mail, bitte antworten Sie nicht auf diese E-Mail-Adresse.
Mit freundlichen Grüßen, Saleor e-commerce
```

### Steps to reproduce the problem
1.  go to password reset page (e.g. /de/account/password/reset/)
2. provide email and click on send

### What I expected to happen
a fully translated email

### Screenshots
<img width="712" alt="email" src="https://user-images.githubusercontent.com/15652645/77230292-7c6b6900-6b93-11ea-94ae-c7c1be7587d2.png">

**System information**
Operating system: macOS Catalina & Windows 10

**Comment by NyanKiyoshi** [comment]
Hi! This is because it is not fully translated, contributions can be made at https://www.transifex.com/mirumee/saleor-1/

**Comment by Anyman552** [comment]
Hi, thanks for the fast reply! There is actually a translation for this phrase: https://www.transifex.com/mirumee/saleor-1/translate/#de/storefrontpo/164691015.

Also, the same text is correctly translated in text/plain. I think it's a different problem.

**Comment by NyanKiyoshi** [comment]
It is possible the translations inside saleor are outdated. I will synchronize them on Monday, and I will check the emails are fully translated.

**Comment by NyanKiyoshi** [comment]
Hi sorry been very busy lately, I will take a look whenever I can.

**Comment by Anyman552** [comment]
Can i help you with that?

**Comment by NyanKiyoshi** [comment]
Not really, would be more time consuming to! But I really can't, I don't have such spare time available, I'm already totally overwhelm. I will try to find someone to investigate.

**Comment by EduardoZepeda** [comment]
I had the same issue, apparently the mjml parser has some problems parsing special characters inside trans blocks, you'll notice that all translation blocks that include an < or an > present some problems with their translation. 

I solved the issue enclosing all the mjml translation blocks that included special characters in an autoscape on tag, rebuilding the emails and translating them.

```django
{% autoescape on %}         
  {% blocktrans trimmed context "Password reset e-mail text" %}
    You're receiving this e-mail because you or someone else has requested a password for your user account at {{ domain }}.<br/> It can be safely ignored if you did not request a password reset. Click the link below to reset your password.
  {% endblocktrans %}
{% endautoescape %}
```

**Comment by f00wl** [comment]
I achieved french translation of emails in file `saleor/locale/fr/LC_MESSAGES/django.po`.
After run `manage.py compilemessages`,  `npm run build-emails` and well exported `LANGUAGE_CODE=fr` I still received emails **in HTML format** are still partially in french and mainly in English , but the **text version is well fully translated**.
Invoice are well translated as well.

Is it the wanted behavior ? Is the HTML email handle multiple language version ? I tried to change locales of my webmail and browser but nothing change.  What did I missed ?
Tank you!

**Comment by JayBenato** [comment]
im having the same problem anyone found a solution ?

**Comment by JayBenato** [comment]
> I had the same issue, apparently the mjml parser has some problems parsing special characters inside trans blocks, you'll notice that all translation blocks that include an < or an > present some problems with their translation.
> 
> I solved the issue enclosing all the mjml translation blocks that included special characters in an autoscape on tag, rebuilding the emails and translating them.
> 
> ```
> {% autoescape on %}         
>   {% blocktrans trimmed context "Password reset e-mail text" %}
>     You're receiving this e-mail because you or someone else has requested a password for your user account at {{ domain }}.<br/> It can be safely ignored if you did not request a password reset. Click the link below to reset your password.
>   {% endblocktrans %}
> {% endautoescape %}
> ```

tried this with no luck

**Comment by JayBenato** [comment]
For anyone having the same problem it's probably due to outdated messages follow these steps to solve the issue :
1) python manage.py makemessages -l <locale you desire to translate>
2) translate messages in locale folder django.po file
3) python manage.py compilemessage --locale <locale>
4) recompile your docker image and deploy

hope this helps
J.

**Comment by f00wl** [comment]
ty @JayBenato, I tried that and now `html` emails are in french but `plain text` version are in English... this is better because mainly people use `html` email rendering but this still an issue. The **subject** of the email is in English to.
In fact everything outer of `{% block html %}` in `.email` file are not translated.

**Comment by f00wl** [comment]
I finally found that `makemessages` doesn't care about `.email` files, don't know why...
So I used the english `django.po` and retranslate everything (quickly with [this awesome vim plugin](https://github.com/voldikss/vim-translator)). Then `compilemessages` and now it works! Seems that the french `django.po` is not reflecting the saleor v2.11.

**Comment by NyanKiyoshi** [comment]
To make django process `.email` files you can do this:

```
python manage.py makemessages -l en --extension=email,html,mjml,py,txt --ignore="templates/templated_email/compiled" --ignore="node_modules"
```

Then, still the same to compile:
```
python manage.py compilemessages
```

**Comment by f00wl** [comment]
Thanks @NyanKiyoshi! I missed [this point in the doc](https://docs.djangoproject.com/en/3.1/ref/django-admin/#makemessages), my bad :grin:

**Comment by maarcingebala** [comment]
Emails should now be handled by apps using proper webhooks, including translations.
