### ISSUE TITLE
Drop support for ServiceAccount after 2020-07-31

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#5521]
We are renamed the `ServiceAccount` to `App`. Saleor still supports old queries and mutations. After 2020-07-31 we should drop them.:
DoD:
- [ ]  Confirm that Dashboard uses new queries/mutations
- [ ]  Remove `ServiceAccount` mutations and queries
- [ ]  Remove unit tests for `SA`
- [ ]  Remove all helpers logic dedicated to `ServiceAccount`
- [ ]  Drop get_type_for_model from App mutations:
We are support `ServiceAccount` and `App` mutations. To do that we have to overwrite `get_type_for_model`  for each App mutation. This will be unneeded when we will drop support for ServiceAccount
- [ ]  Drop custom logic dedicated to `SA` from webhook mutations/queries

**Comment by maarcingebala** [comment]
Service accounts are now apps.
