### ISSUE TITLE
AccountService methods don't work properly

### ISSUE THREAD

**Issue by IKarbowiak** [saleor/saleor#5527]
### What I'm trying to achieve
`has_perm` and `has_perms` should work the same as django methods in `User` model. Right now it operates on `Enum` instead of string. 
https://docs.djangoproject.com/en/3.0/ref/contrib/auth/#django.contrib.auth.models.User.has_perm

### What I expected to happen
`has_perm` and `has_perms` works the same as django methods in `User` model.

**Comment by maarcingebala** [comment]
Looks like we're using it in the same way for both users and apps, by passing permission enums as parameters.
