### ISSUE TITLE
product import (until a better solution is available)

### ISSUE THREAD

**Issue by grll** [saleor/saleor#5558]
Hi,

I needed to be able quickly insert a large number of products loaded in python into saleor so I developed a little helper class that let you do that pretty easily and decided to share it.

The class is available as a pip package for details on usage and installation check this out: https://github.com/grll/saleor-gql-loader

it uses the graphql endpoint created by your installation of saleor and is currently working only with Saleor 2.9.

**Comment by maarcingebala** [comment]
Really nice work! It's exciting to see that you're using service accounts for that, that's exactly what we built them for.

We're now finishing our work on a new version of Saleor that will go public this week and there are some changes in the service accounts API. We renamed them to "Apps" as we think this will be more user friendly and it's also related to the fact that we're building a marketplace for such apps.

**Comment by maarcingebala** [comment]
Forgot to add - we're also working on CSV import/export which will be another way and optimized way to import products to Saleor.

**Comment by grll** [comment]
Thanks for the good word! Aren't they already named app ? (I have been using the master branch actually) so this is already an app I guess.

I am looking forward to the CSV import/export feature as indeed it would be much better for testability/optimizing if it was part of the django project.

Let me know if you need some work done on that!

**Comment by maarcingebala** [comment]
Yes, that was merged a few days ago so if you're using master that they're already apps :)

**Comment by oviliz** [comment]
@maarcingebala is now possible importing/updating products from CSV or is that still something you're working on?

**Comment by maarcingebala** [comment]
We're working on exporting products in [this pull request](https://github.com/mirumee/saleor/pull/5255). The functionality is already working and can be tested with the `exportProducts` mutation on that branch, but we need to test with a large DB of products. Once the export feature is done, we'll move on to importing products.

**Comment by dsoprea** [comment]
What's the status on the CSV import? The export was merged about five months ago and I don't see any other issues or PRs that mention "csv" or "import", but it sounds like the plan was to start working on an import after the export was finished.

**Comment by blueyo** [comment]
Any update about the CSV import. Export is already there in v2.11? What about importing Customers? I am working to migrate from Magento 2 to Saleor. that migration is not straightforward. I want to be able to migrate customer account along with their passwords.

**Comment by cenekSvoboda** [comment]
What are the import possibilities right now? Graphql, XML, CSV? Is there any import possibility anywhere by anyone, that would fit the latest release? Is there some recommendation regarding this?

Č

**Comment by rofkk** [comment]
I have 200k products, and I want to use saleor. Any updates about the possibilities to upload these number of products?

**Comment by maarcingebala** [comment]
There are now bulk mutations to import data in batches, e.g. https://docs.saleor.io/docs/3.x/api-reference/products/mutations/product-bulk-create.
