### ISSUE TITLE
Listing all menuItems 

### ISSUE THREAD

**Issue by PiotrLaszczyk** [saleor/saleor#5609]
### What I'm trying to achieve
In my setup query { menuItems { totalCount - gives some number, X

I'm trying to iterate over all menu items in that way that I ask for first 100 items, read cursor from last and read next 100 items starting from cursor and read till I get all items from totalCount.. In all list I read up to now in mentioned way it works. In fact I have general mechanism for that. Works except menuItems list which is in general shorter, as I have access to Y items in this scenario. So in conclusion something is wrong with totalCount or iteration. Maybe from some reason order of items is different but its Y each time and in this case it would vary.. or there is some other limitation in code?

Case is that value get from totalCount(X) and number of items from iteration(Y) is different.. 

### Steps to reproduce the problem
1. Create lots of categories, then create menuItem for each category, try to get whole list of menu items

**Comment by patrys** [comment]
I'm going to mark this as a bug as it seems pagination returns a different result set than the counter.

Aside from the bug, care to share your use case and why you need to fetch hundreds of menu items at the same time? Maybe we could make your case easier.

**Comment by PiotrLaszczyk** [comment]
I have system which is working autonomously, put offers from external  vendors, update it, remove if necessary... no human between. In such situation there is no intelligent decision point;).

So it take all offers (~7-8k actually but its not big nubmer, really), put theh in to categories (~750), for each category create menu item on 4 level deep tree..

Why need to iterate over all, to get something like that..  
![Zrzut ekranu z 2020-05-08 20-09-57](https://user-images.githubusercontent.com/19570394/81435416-231dc000-9168-11ea-8eb5-dbd15771185e.png)

In general navigation (surfing) is a problematic i storefront but its not the point ;)
I'm working on own solution to make this easier for customers.
