### ISSUE TITLE
Create generic function - ensure_can_manage_permissions

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#5641]
The number of places where we implement the same logic for handling permissions - `ensure_can_manage_permissions` is growing. We should implement a generic method that can be used in all places.
https://github.com/mirumee/saleor/pull/5573#discussion_r424903298

**Comment by maarcingebala** [comment]
The link doesn't work anymore, also I think handling permissions in now more centralized in functions in the `saleor/permission` module.
