### ISSUE TITLE
Improve retrieving permissions from get_permissions

### ISSUE THREAD

**Issue by korycins** [saleor/saleor#5643]
`saleor/core/permissions.py::get_permissions` is basic function to retrieve a permissions. All API modules are using it. When `get_permissions`  receives permission list, it splits permissions and uses only a codename. It works because of our codenames are unique (for now). This will break up when someone will add the same codename in two different modules - Django handles it as a two different type of permissions, for Saleor it will be the same permission: 
Example:
```
"account.manage_users"
"app.manage_users"
```
Codenames are the same but content_types are different. `get_permissions` will treat is as the same permissions - `manage_users`.
Saleor generates permission enums based on codenames. 

We could introduce some mechanism which will protect from duplicated codenames.

**Comment by aniav** [comment]
This issue has 3 years. Is it still valid?

**Comment by maarcingebala** [comment]
I'm closing it, since we control these permissions, we can figure out some solution when this becomes a problem. So far we are not experiencing it (or could work around this).
