### ISSUE TITLE
Searching/Filtering does not use product description

### ISSUE THREAD

**Issue by khalibloo** [saleor/saleor#5679]
### What I'm trying to achieve
When searching or filtering products with the API, the description of the product does not seem to be used. More accurately, the descriptionJson does not seem to be used.

### Steps to reproduce the problem
1. Create a new product with some description
2. Search for product based on unique words in description

### What I expected to happen
Product should be returned in results. Looking at the postgres search backend, it appears the matching is being done against `description` rather than `descriptionJson`. https://github.com/mirumee/saleor/blob/b38ad825a19c7ebec1f85a6944b1ca4d716e9e31/saleor/search/backends/postgresql_storefront.py#L19

Additionally, the search should take into consideration attributes and category/collection names. For example, searching for "silver" should return products with "silver" in their attribute values. Searching for "bed sheets" should return products under category/collection "bed sheets" even if the product name does not include "bed sheets".

**System information**
Operating system: Windows x64

**Comment by maarcingebala** [comment]
The description is stored as JSON in the `description_json` field (output produced by rich-text editor used in the dashboard is in JSON format). I'm not sure how will the search work over this JSON-content field. Maybe we should store description as plain-text as well for search purposes?

**Comment by khalibloo** [comment]
I agree with that approach. It would also be useful as meta information for SEO.

**Comment by maarcingebala** [comment]
Another idea is to use [SearchVectorField](https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/search/#searchvectorfield) to store data needed for search, it should be faster than plain-text field

**Comment by khalibloo** [comment]
The SearchVectorField would still need to reference a model field containing the plain text description. That's the "body_text" in the example in the link. I think either SearchVectorField or Trigram Similarity would fit depending on whether we want to enable fuzzy search. But I do not know how they compare in terms of performance.

In my current use case, a fuzzy search and hence trigram similarity would be preferred because the population speaks a variety of languages. English spelling errors and also the mixed use of American and British English are common.

**Comment by rmelisson** [comment]
the doc here might be outdated then :
https://docs.saleor.io/docs/developer/products#filtering
`search: String: search by name or part of the description.`

**Comment by simon-online** [comment]
What's the latest on this?

It looks like searching over product description still isn't working. Will I just have to tell my client that sorry your new online store doesn't have as good a search as your old Woocommerce store we are replacing does?
