### ISSUE TITLE
Email template editing

### ISSUE THREAD

**Issue by khalibloo** [saleor/saleor#5722]
### What I'm trying to achieve
Email templates are one of the parts of saleor core that still needs to be manually edited from the source code whenever a new deployment is made. It would be great if we could manipulate them through the API. This would open the way for having the ability to customize them on the admin dashboard.

### Describe a proposed solution
Email templates and translations should be stored in the database. A default set of templates would be nice to have. These templates can then be assigned to events such as when a user signs up or when an order is placed. Ideally, we should have as many events as possible, and the emails should be neatly divided between staff emails and customer emails. Each event should also expose contextual variables to be used in the email templates. For example, `{{orderNumber}}` should be available in the `orderPlaced` event.

### Other solutions I've tried and won't work
Another solution is to rely on sendgrid's email templating system. This would however tie saleor to one provider unless different implementations could be made for different emailing services. I think this is worth considering also.

**Comment by maarcingebala** [comment]
Thanks for opening the issue. It's on our roadmap to move email templates from the core and delegate sending emails to dedicated services such as Mailgun, Amazon SES or Sendgrid. Ideally, we would like to have integrations with all these services, which should be achievable with plugin architecture or as external integrations (Saleor Apps). All of these services use Handlebars as a template framework, so we could convert our templates to this format and provide that as a default. Templates could be later customized and previewed outside of Saleor.

**Comment by maarcingebala** [comment]
Email templates are now stored in the database.
