### ISSUE TITLE
Migrate description_json to description field

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#5726]
Some models have `description` and `description_json` fields. The first one was used in legacy Saleor to store plain text / HTML descriptions. Later, we migrated to JSON format which is outputted from DraftJS editors used in the dashboard. We need to unify these fields. 

We can change the type of `description` fields to JSON, migrate data from `description_json` to `description`, and remove `description_json` from models and API. The only issue is that the API type of `description` field would change from `String` to `JSON` which is a breaking change, so this could be released in next major version Saleor 3.0.

**Comment by patrys** [comment]
Can we do this before 3.0 ships? `description` was deprecated so I'm thinking about moving the resolver to `description` and deprecating `descriptionJson` (returning the same value as `description`).

**Comment by maarcingebala** [comment]
Done.
