### ISSUE TITLE
Website performance improvements

### ISSUE THREAD

**Issue by PiotrLaszczyk** [saleor/saleor#5754]
### What I'm trying to achieve
I'm trying understand options I have to optimize my shop performance. Actually Im running this on saleor - heroku standard 2x dyno plan, storefront - heroku standard 1x dyno plan 

https://developers.google.com says that first load in 'laboratory env' tooks 12.0s, quite long ...
and most suggested improvements are text compression:
**/js/app.ad65d2c….js(www.***) | 1567,4 KB | 1151,7 KB
/app.c5c7a00….css(www.***) | 47,7 KB | 38,6 KB**
 
https://gtmetrix.com also suggests to enable compression:
    **Compressing https://www.***/js/app.ad65d2c0d037432d8698.js could save 1.1MiB (73% reduction).
    Compressing https://www.***/app.c5c7a004382e5f252ded.css could save 38.6KiB (80% reduction).**
    Compressing https://www.***/ could save 4.2KiB (74% reduction).
    Compressing https://www.***/images/logo.svg could save 2.0KiB (50% reduction).
    Compressing https:/www.***/images/favicons/manifest.json could save 1.0KiB (74% reduction).
    Compressing https://www.***/images/user.svg could save 919B (49% reduction).
    Compressing https://www.***/images/cart.svg could save 618B (47% reduction).
    Compressing https://www.***/images/instagram-icon.svg could save 470B (53% reduction).
    Compressing https://www.***/images/search.svg could save 310B (45% reduction).
    Compressing https://www.***/images/twitter-icon.svg could save 303B (44% reduction).
    Compressing https://www.***/images/youtube-icon.svg could save 281B (45% reduction).
    Compressing https://www.***/images/facebook-icon.svg could save 111B (31% reduction).
    Compressing https://www.***/images/carousel-arrow.svg could save 61B (24% reduction).

Additionally there is some potential in browser caching for the following cacheable resources:
    **https://abc.s3.amazonaws.com/__sized__/products/APWTZMWZFZXA-thumbnail-255x255.png (expiration not specified)**
(...)

Compression would speed up loading but its not main factor in this case - its my observation as I compared my shop with some randomly chosen competitor (similar total size of downloaded page).

![obraz](https://user-images.githubusercontent.com/19570394/83460889-c8763c00-a467-11ea-9b97-7f1ec0b4399c.png)

The biggest difference is that everything is loaded in one shot. 11%...11%, 17%, 100% (9.5s).
Problem is visible here:
![untitled](https://user-images.githubusercontent.com/19570394/83462354-4c7df300-a46b-11ea-9f4d-fef80088dce5.png)

 I have some menu, 10 pictures from categories and carousel. Why its so slow? Its not because of uncompressed app, isn't it ;)?

I looked at time line:
![untitled(3)](https://user-images.githubusercontent.com/19570394/83463467-58b77f80-a46e-11ea-827d-87ab879d5abc.png)

App is loading quite fast...<1s. Waiting for graphql query tooks 5s and then loading pictures tooks ~2s.  That's the whole picture.  

### Question
Do You have some plans to introduce performance optimization package? 
Maybe some hints what to do and how... to speed up shops based on saleor? 
What are potential improvements?

**Comment by PiotrLaszczyk** [comment]
Thank You.  

Last question. How about app compression. There is some potential in this also. Would You consider to add this in future? 

My initial goal was to make my site working as fast as possible... to have good background for populating by new products..

**Comment by patrys** [comment]
We have our CloudFront configures to automatically compress all traffic but we're open to pull requests adding compression to Webpack.

**Comment by maarcingebala** [comment]
A lot of optimization work has been done since the last activity in this issue; please reopen if any particular performance issues are observed.
