### ISSUE TITLE
"shippingPriceUpdate" mutation requires "type" input field to update shipping prices

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor#5878]
### What I'm trying to achieve
I'm trying to update order price ranges for an existing shipping method.

Mutation to update shipping method that is price-based (has constraints of min/max order value):
```graphql
mutation UpdateShippingRate($id: ID!, $input: ShippingPriceInput!) {
  shippingPriceUpdate(id: $id, input: $input) {
    shippingMethod {
      minimumOrderPrice {
        amount
      }
    }
  }
}
```

Input:
```json
{
  "id": "U2hpcHBpbmdNZXRob2Q6MzQ=",
  "input": {
    "minimumOrderPrice": 5,
    "name": "Test",
    "price": 5,
    "shippingZone": "U2hpcHBpbmdab25lOjY="
  }
}
```

Input field `minimumOrderPrice` is not taken into account unless I also pass `type`:
```json
{
  "id": "U2hpcHBpbmdNZXRob2Q6MzQ=",
  "input": {
    "minimumOrderPrice": 5,
    "name": "Test",
    "price": 5,
    "shippingZone": "U2hpcHBpbmdab25lOjY=",
    "type": "PRICE"
  }
}
```

### What I expected to happen
Since this is an existing shipping method, it shouldn't be required to pass the `type` field to update this value.

**Comment by techytoes** [comment]
hey @maarcingebala ! Can I pick this issue up?
