### ISSUE TITLE
Ignored Exceptions are Showing in Sentry 

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor#5915]
### What I'm trying to achieve
Get normal/handled exceptions to not show up in exceptions logging (stderr, sentry, etc.).

### Steps to reproduce the problem
1. Enable sentry (using only stderr should do the trick too, but double check it)
2. Use an expired JWT token, e.g. set expiration to a few seconds
3. It would send to sentry/write to stderr

**Comment by maarcingebala** [comment]
I think we're not logging these exceptions anymore?
