### ISSUE TITLE
Unnecessary null values in generated graphql types

### ISSUE THREAD

**Issue by JNaftali** [saleor/saleor#6050]
### What I'm trying to achieve
Autogenerate accurate typescript types using Apollo Client

### Steps to reproduce the problem
1. In a project that's been set up to work with Apollo Client, make a query like the following:
```
      query GetPdpProduct($id: ID) {
        product(id: $id) {
          name
          description
          slug
          variants {
            id
            name
            sku
            attributes {
              attribute {
                id
                name
              }
              values {
                id
                name
              }
            }
          }
        }
      }
```
2. run `apollo client:codegen` and observe the created types

### What I expected to happen
* a Product should always have variants, but the generated type for `GetPdpProduct_product.variants` is `ReadonlyArray<(GetPdpProduct_product_variants | null)> | null;`
* a SelectedAttribute should always have values, but the generated type for `GetPdpProduct_product_variants_attributes.values` is `ReadonlyArray<(GetPdpProduct_product_variants_attributes_values | null)>;`
* an Attribute or AttributeValue should always have a string name, but the generated type for `GetPdpProduct_product_variants_attributes_attribute.name` and `GetPdpProduct_product_variants_attributes_values.name` is `string | null`

**System information**
Operating system: MacOs
Node version: v12.13.0
@apollo/client version: 3.1.3

apollo.config.js:
```module.exports = {
  client: {
    service: {
      name: 'saleor',
      url: 'https://thelab.sandbox.saleor.rocks/graphql/'
    },
    includes: ["./pages/**/*.ts", "./pages/**/*.tsx"]
  }
}
```
Full command used to generate types: `apollo client:codegen ./graphql/generated.ts --config=./apollo.config.js --outputFlat --target=typescript --useReadOnlyTypes`

**Comment by maarcingebala** [comment]
The mentioned fields should have `required=True` attribute set.

**Comment by JPaulMora** [comment]
I can confirm this issue in the latest main branch, using the newer `@graphql-codegen/cli` package I got the same optionals as part of the Product schema

```ts
/** Represents an individual item for sale in the storefront. */
export type Product = Node & ObjectWithMetadata & {
  __typename?: 'Product';
  /**
   * Get a single attribute attached to product by attribute slug.
   *
   * Added in Saleor 3.9.
   */
  variant?: Maybe<ProductVariant>;
  /** List of variants for the product. Requires the following permissions to include the unpublished items: MANAGE_ORDERS, MANAGE_DISCOUNTS, MANAGE_PRODUCTS. */
  variants?: Maybe<Array<ProductVariant>>;
  /** Weight of the product. */
};
```
