### ISSUE TITLE
Error on checkout fully payed with a gift card without other payment method

### ISSUE THREAD

**Issue by tilman** [saleor/saleor#6246]
### What I'm trying to achieve
using a gift card to pay the full amount of an checkout

### Steps to reproduce the problem
1. use graphql to create a checkout with address and select shipping method as in saleor-storefront
2. add a gift card to a checkout using `AddCheckoutPromoCode mutation`. The gift card `currentBalance` should be greater as totalPrice
3. After adding the gift card the checkout totalPrice is 0. Therefore it should be possible to skip payment method and `CreateCheckoutPayment mutation`
4. if we now execute `CompleteCheckout mutation`, it will result in the following error: 
```json
{
   "errors":[
      {
         "message":"'NoneType' object has no attribute 'to_confirm'",
         "locations":[
            {
               "line":160,
               "column":3
            }
         ],
         "path":[
            "checkoutComplete"
         ],
         "extensions":{
            "exception":{
               "code":"AttributeError"
            }
         }
      }
   ],
   "data":{
      "checkoutComplete":null
   }
}
```

### What I expected to happen
It should be possible to call completeCheckout on an order if the used gift cards currentBalance is high enough to "pay" the full checkout. 

**System information**
Operating system: linux
Version: 2.11, Rc 7

**Comment by JannikZed** [comment]
hey @maarcingebala I want to take a look into this issue and see, if I can fix it maybe ... do you already have an idea, where the root-cause of the issue is and point me to a certain direction?

**Comment by maarcingebala** [comment]
Actually, we already have a PR that would fix this issue: https://github.com/mirumee/saleor/pull/6211.
To finish it, we would have to modify our storefront to skip the payment step in case the checkout total is zero, which is a bit more work and we had yet no time to do that. The issue is open and I hope we'll be able to address it in the next stable release - Saleor 3.0.

**Comment by JannikZed** [comment]
ah okay amazing! As we already implemented the frontend part for our store, we are going to test the merge request immediately. Thank you for pointing that out.

**Comment by maarcingebala** [comment]
Great, let me know if you find any issues with that solution.
