### ISSUE TITLE
Filters are not working on Collection Pages

### ISSUE THREAD

**Issue by yevheniidehtiar** [saleor/saleor#6266]
### What I'm trying to achieve
Direct your attention to non-working functionality.
I investigated a little bit and found that it is backend problem, might be it would be easy to fix for someone from saleor-team

### Steps to reproduce the problem

1. Try to use some attributes to filter products on collection page
2. Any combination gives you same products nodes from graphql

### What I expected to happen
I expected to have working filtering by attribute for customers (storefront users)

### Screenshots

![i am using latest 2.11 of saleor and saleor-storefront](https://user-images.githubusercontent.com/25932077/96008920-b90cf380-0e48-11eb-934b-91063051998a.gif)

<img width="1552" alt="Screenshot 2020-10-14 at 18 09 41" src="https://user-images.githubusercontent.com/25932077/96008830-9f6bac00-0e48-11eb-9e83-8d559b8fbbfc.png">
<img width="1552" alt="Screenshot 2020-10-14 at 18 09 54" src="https://user-images.githubusercontent.com/25932077/96008834-a1356f80-0e48-11eb-8452-b8990cc487e2.png">
<img width="1552" alt="Screenshot 2020-10-14 at 18 08 28" src="https://user-images.githubusercontent.com/25932077/96008849-a72b5080-0e48-11eb-907a-804489dd129b.png">
<img width="1552" alt="Screenshot 2020-10-14 at 18 09 00" src="https://user-images.githubusercontent.com/25932077/96008869-ae525e80-0e48-11eb-9264-425ea071a618.png">

**System information**
Operating system:  MacOS
Browser: Firefox, Chrome

**Comment by karolkielecki** [comment]
We've fixed the issue and merged PR into the master branch: https://github.com/mirumee/saleor/pull/6215. Once again, thanks for reporting!

**Comment by yevheniidehtiar** [comment]
Unfortunately, that fix didn't helped, i rebased the last commits from 2.11. Did you tested it or just had hope...?

**Comment by maarcingebala** [comment]
It seems it's a different issue than the one fixed in #6215. We'll check it.
