### ISSUE TITLE
PayPal via Braintree is broken and dangerous!

### ISSUE THREAD

**Issue by JannikZed** [saleor/saleor#6267]
### What I'm trying to achieve
Try to successfully checkout using the Braintree Gateway, Drop-In UI in the frontend and PayPal as payment method.

### Steps to reproduce the problem
1. Use Saleor 2.11, create a checkout with PayPal
2. Look at the Braintree dashboard - the amount gets captured successfully, but Saleor is failing critically! So it is impossible for the frontend to tell the user, that the checkout was actually successful.
3. The request is failing in Saleor, because `lower()` could not be run on type `none`:             `brand=credit_card.get("card_type", "").lower(),`

The `def authorize` function https://github.com/mirumee/saleor/blob/bb9ffe88f7275e2a52c801334f1e00bbfab2c1bf/saleor/payment/gateways/braintree/__init__.py#L124
is actually really! unsafe. When it fails out of any reason, there is no protection, like a refund of the already captured amount.
Furthermore, the backend is just prepared for credit cards. When using PayPal, there is no need to collect the brand of the credit card .. 

As we are using Braintree / Paypal heavily and are planing to integrate local payment providers like Klarna, we would like to discuss the implementation of braintree with you guys here and want to help out with merge requests. We created a temporary fix, that is at least a little more stable than the current approach, by using a feature from the braintree SDK: `braintree_sdk.PaymentInstrumentType.PayPalAccount` 

```python
   if(error):
        print('error occured')
        return GatewayResponse(
            is_success=result.is_success,
            action_required=False,
            kind=kind,
            amount=gateway_response.get("amount", payment_information.amount),
            currency=gateway_response.get("currency", payment_information.currency),
            transaction_id=gateway_response.get(
                "transaction_id", payment_information.token
            ),
            error=error,
            raw_response=gateway_response,
        )
    if(result.transaction.payment_instrument_type == braintree_sdk.PaymentInstrumentType.PayPalAccount):
        print('is paypal')
        return GatewayResponse(
            is_success=result.is_success,
            action_required=False,
            kind=kind,
            amount=gateway_response.get("amount", payment_information.amount),
            currency=gateway_response.get("currency", payment_information.currency),
            customer_id=gateway_response.get("customer_id"),
            transaction_id=gateway_response.get(
                "transaction_id", payment_information.token
            ),
            error=error,
            payment_method_info=PaymentMethodInfo(
                type="paypal",
            ),
            raw_response=gateway_response,
        )
    if(result.transaction.payment_instrument_type == braintree_sdk.PaymentInstrumentType.CreditCard):
        print('is creditcard')
        return GatewayResponse(
            is_success=result.is_success,
            action_required=False,
            kind=kind,
            amount=gateway_response.get("amount", payment_information.amount),
            currency=gateway_response.get("currency", payment_information.currency),
            customer_id=gateway_response.get("customer_id"),
            transaction_id=gateway_response.get(
                "transaction_id", payment_information.token
            ),
            error=error,
            payment_method_info=PaymentMethodInfo(
                last_4=credit_card.get("last_4"),
                exp_year=credit_card.get("expiration_year"),
                exp_month=credit_card.get("expiration_month"),
                brand=credit_card.get("card_type", "PayPal").lower(),
                name=credit_card.get("cardholder_name"),
                type="card",
            ),
            raw_response=gateway_response,
        )
    # unsafe TODO: uncapture payment
    return GatewayResponse(
        is_success=result.is_success,
        action_required=False,
        kind=kind,
        amount=gateway_response.get("amount", payment_information.amount),
        currency=gateway_response.get("currency", payment_information.currency),
        transaction_id=gateway_response.get(
            "transaction_id", payment_information.token
        ),
        error=error,
        raw_response=gateway_response,
    )
```

**Comment by patrys** [comment]
I think the PayPal case should return `PaymentMethodInfo(type="other", brand="paypal")` instead. Otherwise we'd have to introduce special payment method types for all possible PSPs in the core.

**Comment by JannikZed** [comment]
would be okay as well - still you would need to check, if it is paypal or not, right?

**Comment by patrys** [comment]
Yes, but only in the Braintree plugin code.

**Comment by JannikZed** [comment]
@patrys could you point me to the file where you want the additions to be implemented? I will create a pull request then to discuss it further with you guys. We want Braintree to support Google Pay, Apple Pay, Local Payment Methods like Klarna, Paypal, etc.. and we can test the implementation immediately.

**Comment by JannikZed** [comment]
aaaannd we would love to integrate Braintree Webhooks as well, as they are needed for local payment methods: https://developers.braintreepayments.com/guides/webhooks/overview
Do you already have recommendations for that?

**Comment by patrys** [comment]
For pointers on how to implement this and where to put code, I think @korycins is a better candidate than I am.

**Comment by korycins** [comment]
Hey @JannikZed 
I think you can start with the payments/gateways/braintree code.
You can use Adyen as a sample. It already supports additional actions (like 3d secure etc) and webhook notifications.
