### ISSUE TITLE
Exceptions raised inside perform_mutation do not propagate

### ISSUE THREAD

**Issue by LeOndaz** [saleor/saleor#6452]
I'm creating a reviews plugin, this is a mutation 
```
    @classmethod
    def perform_mutation(cls, _root, info, input):
        user = cls.get_node_or_error(
            info, input.user_id, only_type=User
        )
        
        product = cls.get_node_or_error(
            info, input.product_id, only_type=Product
        )
        
        review = Review.objects.create(
            product=product,
            user=user,
            content=input.content,
            rating=input.rating,
        )

        return ReviewCreateMutation(review=review)
```
This is perfectly fine, let's make something not working, let's use the User model instead of User ObjectType here 
```
    @classmethod
    def perform_mutation(cls, _root, info, input):
        user = cls.get_node_or_error(
            info, input.user_id, only_type=UserModel
        )
       ...
```
This should raise an exception, however, it doesn't, no console output, the server still runs as it was, The GraphQL response is 
```
{
CreateReview: {
   Review: null
   }
}
```

**Comment by LeOndaz** [comment]
I've spent a day debugging this till I decided to print `type(User)` and damn, my stupidity has an important role in discovering this

**Comment by LeOndaz** [comment]
not stale

**Comment by LeOndaz** [comment]
Not stale

**Comment by maarcingebala** [comment]
Plugins are not recommended anymore as a  way to add such features, instead, you should use an app. I'm closing the ticket as the problem doesn't currently affect us in the core.
