### ISSUE TITLE
Filter results are not sorted by relevance

### ISSUE THREAD

**Issue by khalibloo** [saleor/saleor#6494]
### What I'm trying to achieve
This affects the parts of the dashboard that use the AutoComplete component. When adding menu items or creating products for example, the category/collection filter results are not sorted by how well they match they query.

If I have a category called "Whiskeys" and it has subcategories such as "Black whiskeys" and "Blue whiskeys", typing "whiskeys" brings up the children first. And since the list doesn't scroll, if there are enough children, it becomes impossible to select "Whiskeys".

### Steps to reproduce the problem
1. Create categories like in the screenshot below, as children of a "Whiskeys" category
2. Try to add "Whiskeys" as a menu item

### What I expected to happen
The filter results should be scrollable and should be sorted by relevance to my search.

### Screenshots
![image](https://user-images.githubusercontent.com/6402969/63585381-0cbade80-c5b0-11e9-9370-106ffaba018a.png)

**System information**
Operating system: Windows 10 x64
Browser: Firefox 68

**Comment by aniav** [comment]
Dusting off old issues on this repository 🧹

I can confirm this problem doesn't exist any more. Thank you for reporting!
