### ISSUE TITLE
plugins show_on_dashboard variable

### ISSUE THREAD

**Issue by LeOndaz** [saleor/saleor#6792]
Just for UX, some plugins don't have a config

**Comment by LeOndaz** [comment]
.

**Comment by keithmacinnis** [comment]
@LeOndaz , I'd like to contribute. I have time to take on a task; could you expand on this?

**Comment by LeOndaz** [comment]
@keithmacinnis this #6802 is probably the easiet one to start with, it's simple, create and invoice and look closely to see the bug.

**Comment by maarcingebala** [comment]
Closing as plugins are getting deprecated and won't be developed anymore.
