### ISSUE TITLE
install_app rejects valid URLs

### ISSUE THREAD

**Issue by emdemir** [saleor/saleor#6808]
### What I'm trying to achieve

I have `saleor-platform` running. I have added a few containers of my own to integrate another service into Saleor via the third-party app protocol. The app lives under the hostname `otherapp`. When I type `docker exec -it saleor-platform_app_1 python manage.py install_app http://otherapp:9090/manifest.json`, I get `CommandError: Incorrect format of manifest-url: http://otherapp:9090/manifest.json`.

### Steps to reproduce the problem
1. Start `saleor-platform`
2. Run `manage.py install_app <any url without TLD>`

### What I expected to happen
The app to be installed.

### Notes
It seems like Django's `URLValidator` rejects URLs that don't have a TLD even though those URLs are completely valid. On this line: https://github.com/django/django/blob/6822aa5c6c3fbec7c5393a05e990865ba59fe167/django/core/validators.py#L84

The only allowed domain without a TLD is `localhost`. I didn't know whether to open a bug here or on Django's side, so please let me know.

**System information**
Operating system: Debian buster

**Comment by maarcingebala** [comment]
Thanks for reporting, we confirmed it's a bug. It will be addressed in Saleor 3.0.

**Comment by chronark** [comment]
@emdemir have you found a workaround?
I'm running into the same issue

**Comment by maarcingebala** [comment]
It's fixed in this PR: https://github.com/saleor/saleor/pull/6956
