### ISSUE TITLE
Signout from dashboard after few sec of sign in

### ISSUE THREAD

**Issue by ShahrearBinAmin** [saleor/saleor#6837]
### What I'm trying to achieve
We are running saleor for production for two months. Everything was good but for the last couple of days we are signed out from dashboard after few sec of sign in.

### Steps to reproduce the problem
For our system just log in the dashboard.

### What I expected to happen
Keep us log in dashboard

### Screenshots

Please check the sentry log here https://sentry.io/share/issue/c88735e9bc4d412aaa3b84bac968907f/
![image](https://user-images.githubusercontent.com/36158654/106803020-e7c80780-668d-11eb-9c11-ac9bb0cb726c.png)

**System information**
Operating system: Linux
Python version: 3.8.5

**Comment by maarcingebala** [comment]
@ShahrearBinAmin Which version of Saleor and Saleor Dashboard are you using?

**Comment by rohitchopra32** [comment]
I am facing the same issue.

`  File "/home/rohit/virtualenvs/saleorEnv/lib/python3.8/site-packages/jwt/api_jws.py", line 155, in decode
    self._verify_signature(payload, signing_input, header, signature,
  File "/home/rohit/virtualenvs/saleorEnv/lib/python3.8/site-packages/jwt/api_jws.py", line 223, in _verify_signature
    raise InvalidSignatureError('Signature verification failed')
jwt.exceptions.InvalidSignatureError: Signature verification failed
`

I am using saleor==2.11, saleor-dashboard==2.11 & saleor-storefront==2.11

**Comment by Pczek** [comment]
Same here, one month in and we experience some customers having `Signature verification failed` Errors. Definitely seems to be related to JWT not sure whats wrong with it.

**Comment by maarcingebala** [comment]
Please reopen the issue in the [dashboard repo](https://github.com/saleor/saleor-dashboard/) or check if there is any issue about this already.
