### ISSUE TITLE
management/commands errors

### ISSUE THREAD

**Issue by sophie200** [saleor/saleor#6878]
There are some queries that reference deleted fields in this module (examples below). I was wondering does it matter if this module is updated because it seems like this file hasn't been updated in a while, or are there other reasons that these queries still exist? Thanks.

https://github.com/mirumee/saleor/blob/master/saleor/core/management/commands/change_currency.py#L45
https://github.com/mirumee/saleor/blob/master/saleor/core/management/commands/change_currency.py#L51
https://github.com/mirumee/saleor/blob/master/saleor/core/management/commands/change_currency.py#L52
https://github.com/mirumee/saleor/blob/master/saleor/core/management/commands/change_currency.py#L53

**Comment by maarcingebala** [comment]
Hey, the referenced command was a temporary thing that was needed to update currencies in a production environment. This shouldn't have been added to the repo, I will remove the command. Currencies can be now managed in channels.
