### ISSUE TITLE
Plugins that include models.py must be included in not only PLUGINS but also INSTALLED_APPS

### ISSUE THREAD

**Issue by LeOndaz** [saleor/saleor#7185]
PLUGINS list is mentioned to be included in INSTALLED_APPS. however, plugins wiyh models.py can't be migrated unless we include the plugin in PLUGINS and INSTALLED_APPS together.

**Comment by LeOndaz** [comment]
I'll test if the same issue happens with setup.py instead of PLUGINS

**Comment by maarcingebala** [comment]
Closing as plugins are getting deprecated and won't be developed anymore.
