### ISSUE TITLE
web  first open the saleor   ,need load long long time

### ISSUE THREAD

**Issue by pingyuan2016** [saleor/saleor#7186]
![截图](https://user-images.githubusercontent.com/25808622/115170210-a96db080-a0f2-11eb-920b-c31a6410ab50.png)
DEBUG=False

why load many file first opent for the saleor?

**Comment by pingyuan2016** [comment]
clear the web cache


![微信截图_20210419113606](https://user-images.githubusercontent.com/25808622/115178330-a29b6980-a103-11eb-8f82-e9500db1de0a.png)

**Comment by maarcingebala** [comment]
Closing, as this is unrelated to the core. See the [Storefront](https://github.com/saleor/storefront) repo for questions around frontend, or feel free to ask on our [Discord](https://discord.gg/H52JTZAtSH).
