### ISSUE TITLE
`defaultShippingAddress` and `defaultBillingAddress` are not part of user `addresses` and they fail to fetch by id

### ISSUE THREAD

**Issue by cipriancaba** [saleor/saleor#7368]
### What I'm trying to achieve
I am trying to fetch a user's defaultShippingAddress by id. That query returns null

### Steps to reproduce the problem

1. Just save a defaultShippingAddress
2. Save other user addresses
3. Try to fetch the defaultShippingAddress by id, and it will return null. It's also not part of the addresses query response.

### What I expected to happen
I expect the defaultShippingAddress and defaultBillingAddress are part of the user addresses array and I am able to query them by id's just like regular addresses.

### Screenshots and logs
![Screenshot 2021-05-19 at 10 36 04](https://user-images.githubusercontent.com/695515/118773988-07c2b600-b88e-11eb-9e29-1d409327a64a.png)

**System information**

Saleor version:
- [ ] dev (current master)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

**Comment by tomaszszymanski129** [comment]
@cipriancaba Could you check in current master? Recently i've patched exact same issue on user creation in https://github.com/mirumee/saleor/pull/7327

**Comment by tomaszszymanski129** [comment]
If it won;t work on master please provide which mutation you used in order to set the default address.
