### ISSUE TITLE
File names containing slashes

### ISSUE THREAD

**Issue by serena-yu-rozettatech** [saleor/saleor#7385]
### What I'm trying to achieve
Checkout and access the Saleor source code on Linux (Ubuntu 20.04.2 LTS) and Windows 10 (latest retail), but all other Linux or Windows distributions should be affected alike.

### Steps to reproduce the problem
1. Clone the saleor repository and checkout master
2. Access the following files through Linux or Windows:
`saleor/graphql/core/tests/cassettes/test_get_oembed_data[http:/www.youtube.com/watch?v=dQw4w9WgXcQ-VIDEO].yaml` 
`saleor/graphql/core/tests/cassettes/test_get_oembed_data[https:/vimeo.com/148751763-VIDEO].yaml`
`saleor/graphql/core/tests/cassettes/test_get_oembed_data[https:/www.flickr.com/photos/megane_wakui/31740618232/-IMAGE].yaml`
`saleor/graphql/core/tests/cassettes/test_get_oembed_data[https:/www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=TestingChannel-VIDEO].yaml`
`saleor/graphql/core/tests/cassettes/test_get_oembed_data[https:/www.youtube.com/watch?v=dQw4w9WgXcQ-VIDEO].yaml`

### What I expected to happen
I have access to these files.

### Screenshots and logs
Linux reports file doesn't exist and takes the first part of the file name as a directory `test_get_oembed_data[http:`. Windows just breaks and cannot find the file.

**System information**
Linux (Ubuntu 20.04.2 LTS) and Windows 10 (latest retail), but all other Linux or Windows distributions should be affected alike

**Saleor version**
current master

**Operating system**
- [x ] Windows
- [x ] Linux
- [ ] MacOS
- [ ] Other

### Reasoning
File names containing slashes `/` are only supported by MacOS. Linux takes such a file as a path containing multiple layers of directories `test_get_oembed_data[http:/www.youtube.com/watch?v=dQw4w9WgXcQ-VIDEO].yaml`.

This is because `/` is hard-coded in Linux source code and is always interpreted as a path separator:
https://elixir.bootlin.com/linux/latest/source/fs/namei.c#L2188
```
static int link_path_walk(const char *name, struct nameidata *nd)
{
	int depth = 0; // depth <= nd->depth
	int err;

	nd->last_type = LAST_ROOT;
	nd->flags |= LOOKUP_PARENT;
	if (IS_ERR(name))
		return PTR_ERR(name);
	while (*name=='/')
		name++;
	if (!*name) {
		nd->dir_mode = 0; // short-circuit the 'hardening' idiocy
		return 0;
	}
//...
```

###  Possible solutions
Escape or remove slashes in the file names and use slashes only for paths.

**Comment by maarcingebala** [comment]
Fixed in #9236
