### ISSUE TITLE
iDEAL Redirect causes 404 - `no checkout with this payment`

### ISSUE THREAD

**Issue by peetzweg** [saleor/saleor#7446]
### What I'm trying to achieve

I want to complete the payment via the iDEAL payment method with the adyen payment gateway and it's plugin.

I can get through the whole payment process with the adyen drop In library on iOS (https://github.com/Adyen/adyen-ios) and managed to get redirected to the Saleor instance (had a issue described here: https://github.com/mirumee/saleor/issues/7430).
But on accessing the page I get redirect to I get a 404 and this error message:
```Cannot perform payment.There is no checkout with this payment.```

The payment id and checkout id are exactly the same I get during step 1 & 2, see below.
When checking via graphql the `Payment` Entity with the id does not have a checkout attached, however a Order is attached to it. So overall complete checkout seems to have resolved into an order. 🤷 

<img width="1782" alt="Screenshot 2021-06-07 at 15 13 56" src="https://user-images.githubusercontent.com/839848/121023600-b7ab8500-c7a3-11eb-80c5-1d7903b1b2a0.png">

What I'am doing is:
1. use `checkoutPaymentCreate` mutation to create a payment
2. use `checkoutComplete` mutation to complete the checkout 
3. handle the confirmation Data with the adyen drop in.
What am I missing?

### What I expected to happen
 The redirect page should not return 404. At best I want to be retunred to the `redirectUrl ` passed to the `checkoutComplete` mutation.

**System information**

Saleor version:
- [ ] dev (current master)
- [ ] 3.0
- [X] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [X] MacOS
- [ ] Other

**Comment by Pczek** [comment]
Okay I got one piece of the puzzle figured out. 
After the additional action is handled Saleor is redirecting me to the `returnURL` passed to the `checkoutPaymentCreate` mutation.
It seems Saleor even handles passing the results of the additional action to `payments/details` and passes these parameters as query parameters in the URL.

```
checkout: "Q2hlY2tvdXQ6Mjc3OGY0ZGUtYzVmNS00MjIwLTk0MjYtNzRlYjljOTZlYWY5"
payment: "UGF5bWVudDo3OQ=="
resultCode: "Authorised"
```

However, as the checkout is completed and delete, I'm not sure how to figure out the `Order` which was just created from this. I can't query `payments` or `order` queries with my Saleor customer JWT token. 🤔

**Comment by korycins** [comment]
@Pczek  The second call on `checkoutComplete` with checkout token will return an order embedded to this checkout.

**Comment by maarcingebala** [comment]
The [comment above ](https://github.com/saleor/saleor/issues/7446#issuecomment-861321304) should help resolving this issue, if not, please reopen.
