### ISSUE TITLE
Order confirmation email template broken on long product name

### ISSUE THREAD

**Issue by gorjan-mishevski** [saleor/saleor#7498]
### What I'm trying to achieve
ç from the console, as well as query/response help us fix the bug faster -->
1. Create an order with product item that has a long name.

### What I expected to happen
1. Enjoy a well formated email.

### Screenshots and logs

![Screenshot_20210619-122911_Gmail.jpg](https://user-images.githubusercontent.com/12861838/122639494-7481d800-d0fa-11eb-8949-3addabbdb782.jpg)

**System information**

Saleor version:
- [ ] dev (current master)
- [ x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

**Comment by eCzerniak** [comment]
@gorjan-mishevski Thanks for reporting! Added to our backlog :).
