### ISSUE TITLE
Non-credit card payment sources

### ISSUE THREAD

**Issue by onecrayon** [saleor/saleor#7524]
### What I'm trying to achieve

We are currently migrating to Saleor as a headless CMS for both B2B and B2C transactions (with separate behavior and pricing handled via channels). One of our requirements is providing our B2B customers ACH transactions as a payment source. We are using Stripe as our payment processor, which does support this type of payment source. However, Saleor does not because all of the data models assume a credit card (last four digits, expiration date, and other details that are not applicable to ACH).

### Describe a proposed solution

We would be happy to contribute generic, low-level support for ACH payment sources to be modeled by the User.storedPaymentSources GraphQL output (which could then be leveraged on a per-plugin basis, where needed), but wanted to check in prior to starting work on this to make sure that it is consistent with Mirumee's vision for 3.0 (if not, we can simply make the modifications to our fork and not submit them back upstream).

Is this something that you would be interested in pulling into Saleor 3.0, or should we pursue a forked strategy?

**Comment by korycins** [comment]
Hey @onecrayon !
The idea sounds amazing. If you want to build it, I can assist you and try to help with any issues related to Saleor
I think that you could use the new StripePlugin (it will be included in Saleor3.0 https://github.com/mirumee/saleor/pull/7452), to extend it by ACH support.

**Comment by onecrayon** [comment]
@korycins Sorry, should have been more clear; we're strictly working with the 3.0 betas, since supporting price lists through channels was a hard requirement. We were originally planning to make a private fork of the Stripe plugin that allowed for handling credit cards and ACH transactions, but if you're interested in seeing first-party support for that in the core Stripe plug-in we'd be happy to contribute our changes upstream. I'll make a note on our internal task to ensure that any changes we make in our fork to Stripe are generic and can be contributed.

**Comment by korycins** [comment]
@onecrayon  Let me know if you have any questions or need assistance.
Would be great if you could share your idea, how you're going to cover the feature.  Are you going to use Plaid or manually verify bank accounts or both? 
First idea is that you could use `paymentData` input from `checkoutComplete` mutation to pass field like `payment_method_type`  with value "ACH" (in the future we could use `payment_method_type` to add support for more payment methods). The `paymentData` from the checkoutComplete input will be directly passed to the StripePlugin, which will call logic dedicated to ACH.

Also, keep in mind that the current StripePlugin (which is on the master) will be deprecated as it doesn't allow to handle 3d secure operation, and doesn't use Stripe's webhooks.
If you're going to add ACH to Stripe, I would strongly recommend extending a new StripePlugin (it is still not merged as I need to proceed with some tests and finalize docs for this plugin, but will be included in future beta releases of 3.0).

**Comment by onecrayon** [comment]
@korycins Will do! I'm currently working on #7526 so I haven't sat down and investigated exactly what will be necessary for ACH payments; hopefully by the time I get to it you folks will have had a chance to get the new Stripe plug-in into `master`. Either way, I'll definitely check in with my plans before I start writing logic.

**Comment by timuric** [comment]
@onecrayon please check new payment API https://docs.saleor.io/docs/3.x/developer/checkout#creating-payment
