### ISSUE TITLE
Processing fee

### ISSUE THREAD

**Issue by onecrayon** [saleor/saleor#7526]
### What I'm trying to achieve

For some of our B2B customers, we charge a processing fee for credit card transactions. There doesn't appear to be any way to capture this sort of thing in Saleor (in our case, we charge a percentage of the cost of the entire order if they use a credit card).

### Describe a proposed solution

We've been considering adding a processing fee via a plugin, but it would be nice if there was some standardized way to capture it in the checkout/order models. Currently there doesn't appear to be any way to charge any sort of fee beyond shipping for an order (and discounts aren't allowed to be negative, which was the other hacky way we were thinking of approaching things).

**Comment by timuric** [comment]
This might be hacky but I have solved this case by adding negative discount when b2b customers select certain payment options.

**Comment by onecrayon** [comment]
Unfortunately, in our case it is likely we will sometimes need to apply a normal voucher to such orders, and if I'm not misreading the documentation each checkout/order can only have a single voucher. ☹️

**Comment by onecrayon** [comment]
As this is a blocking problem for our usage of Saleor, we are considering implementing generic support for an order-level fee and submitting it upstream (similar to the existing OrderDiscount that allows applying either a fixed amount or percentage discount to the entire order, except inverted).

Current plan:

* Add a `saleor.fee` application including an OrderFee model (imitating `saleor.discount` OrderDiscount); should support percentage of the order total or a flat numeric value
* Update `saleor.order` methods to ensure that fee is calculated when processing the order
* Update certain plugin hooks to accept a list of fees (similar to how they accept lists of discounts)

Do Mirumee folks have any feedback before we start work on this, or is there anything obvious I'm missing?

**Comment by patrys** [comment]
I would propose to add `Order.surcharges` like we have `Order.discounts` and a matching field for the `Checkout` object (there is no `Checkout.discounts` yet, we still have to implement that). Then you could observe checkouts using events and populate the field accordingly.

**Comment by onecrayon** [comment]
@patrys Sounds good! I'll post a PR when I have a basic implementation up and running.

**Comment by onecrayon** [comment]
@patrys (or anyone else who is interested in generic surcharge support): I'm working to design surcharge support, and of course the business folks in the company had to make things more difficult. For percentage fees their desired process is basically:

* Per line item:
    * Lookup base price for the given channel
    * Apply discount(s)
    * Apply processing fee
    * Apply taxes
* Sum line items to obtain subtotal
* Apply shipping
    * Apply processing fee to shipping

Does this flow make sense to other folks (that is, having the processing fee applied per line item such that the surcharge is subject to taxes rather than having taxes subject to the processing fee)? If not, what method of applying surcharges makes sense for other folks' needs?

**Comment by onecrayon** [comment]
After thinking about this some more and going through the code, I'm planning to add percentage surcharges to all line item calculations (so the flow will be variant price => apply discounts => apply percentage surcharges => apply taxes), add fixed surcharges after calculating line items but before calculating shipping, and then if someone needs to apply surcharges to shipping like we do they can do it in a simple custom plugin. I just don't think that sounds like a sane default for percentage surcharges.

**Comment by onecrayon** [comment]
FYI, I'm throwing this back into Mirumee's court as a straight feature request. I've spent about 3 weeks on this issue, and the complete lack of communication from Mirumee on this or related code issues that I've run across has made it a non-starter. While I'd hoped to implement generic surcharge support and submit upstream, we will instead be implementing narrow support for exactly what we need via a plugin along with minor modifications to our private fork.

Incidentally, we have been very unhappy with the level of responsiveness from Mirumee after making good faith attempts to contribute to the project. I am hoping that things will stabilize as you sort out your hosted solution and release Saleor 3, but we are highly concerned that our decision to migrate to Saleor was a mistake since it's very difficult to contribute to the open source, and there isn't the level of support that you would expect from a closed source commercial product outside of your hosted solution. I would love to hear if there is a better way to get into contact with people knowledgeable about the codebase outside of GitHub issues.

**Comment by patrys** [comment]
@onecrayon I'm sorry for dropping the ball here. The entire Saleor Commerce team (Mirumee Software is innocent, the repository will be moved to Saleor's organization soon not to mislead users) is currently sprinting towards a stable 3.0 release and general availability of Saleor Cloud. I feel your pain and I'm sorry for the long wait on this, supporting contributors in a timely manner a problem that we want to address.
