### ISSUE TITLE
Insufficient Stock Error for Digital Product Type

### ISSUE THREAD

**Issue by huy-au-rozettatech** [saleor/saleor#7531]
### What I'm trying to achieve
I want to be able to create Digital Products that do not require assignment to a Warehouse.
This bug report is similar to a previous one that was closed https://github.com/mirumee/saleor/issues/6001.

### Steps to reproduce the problem
1. Create a Simple Product type that is not shippable (Digital Product Type)
2. Create a Product by filling the mandatory fields on the Dashboard.
3. Do not assign the Product to any Warehouse.
4. Checkout the product variant.

### What I expected to happen
Product variants that are digital and are not inventory tracked should be purchasable without assigning to a Warehouse.
Fulfilling an Order should be possible without a Warehouse for Digital Products.

The following issue appears to correct the problem in 2020:
https://github.com/mirumee/saleor/issues/6001
https://github.com/mirumee/saleor/pull/6021
https://github.com/neerajgupta2407/saleor/blob/26068cb46ed3f18c0bc824495be8bb7281ea08b6/saleor/graphql/checkout/mutations.py#L126

However, the current implementation in 2021 https://github.com/mirumee/saleor/blob/master/saleor/graphql/checkout/mutations.py#L158 checks Warehouse stock instead of bypassing the inventory check.

The following input/mutation may be too strict when fulfilling an order as the warehouse is used to group orderlines for stock management which shouldn't be required for digital products.
https://github.com/mirumee/saleor/blob/master/saleor/graphql/order/mutations/fulfillments.py#L30-L38

### Screenshots and logs

![image](https://user-images.githubusercontent.com/63189731/123211571-f90f9480-d506-11eb-8efd-fd84ee456619.png)
![image](https://user-images.githubusercontent.com/63189731/123211778-3ffd8a00-d507-11eb-874c-33ca99411171.png)

**System information**
Saleor version: 3.0
Saleor storefront: 3.0
Saleor dashboard: 3.0

Operating system:
MacOS

**Comment by krzysztofwolski** [comment]
At the moment warehouse is required for all the products, even digital:
https://docs.saleor.io/docs/3.0/dashboard/catalog/products/#stock-management

We'll be revisiting this requirement in the future for digital products

**Comment by maarcingebala** [comment]
Clickup task: https://app.clickup.com/t/2549495/SALEOR-3997

**Comment by iprlic** [comment]
We are facing the same issue, any update on this?

**Comment by manojLondhe** [comment]
+1 We are facing the same issue, any update on this?

**Comment by nnthuan** [comment]
+2 We are facing the same issue, any update on this?

**Comment by simon-online** [comment]
+3 It's nearly been a year since this issue was raised.

This issue makes it seem like Saleor doesn't really have proper support for digital products.

**Comment by timuric** [comment]
our apologies for not solving this sooner, as we had other priorities. We will add high priority to this issue

**Comment by nnthuanegany** [comment]
It's still not working for me. I'm using the cloud version of Saleor with the Developer package
