### ISSUE TITLE
Attribute translate permission not working

### ISSUE THREAD

**Issue by mowafy** [saleor/saleor#7540]
### What I'm trying to achieve
Translate an attribute using `attributeTranslate` mutation using app token (app with full permissions). The mutation returns don't have permission error.

### Steps to reproduce the problem

1. Create an app with full permissions and activate it.
2. Create an attribute using dashboard (or whatever).
3. Try to translate the created attribute using app token in graghql playground using `attributeTranslate` mutation.
4. The mutation returns error: you don't have permission

### What I expected to happen
The translation to be added

### Screenshots and logs

**System information**

Saleor version:
- [ ] dev (current master)
- [ ] 3.0
- [✓] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [✓] Linux
- [ ] MacOS
- [ ] Other

**Comment by eCzerniak** [comment]
Hi @Mowafy, you give me more information, because I cannot reproduce it. 
When I use app which has full rights then everything works fine.

![image](https://user-images.githubusercontent.com/29308910/128340824-d6e2d9f8-d85b-496d-93a0-da9ed282f7c1.png)

**Comment by eCzerniak** [comment]
Hello @Mowafy this issue has been corrected in version 3.0 and we advise to use this version. If you need more information please let me know.
