### ISSUE TITLE
Voucher with apply_once_per_customer doesn't work with 3DSecure

### ISSUE THREAD

**Issue by Kwaidan00** [saleor/saleor#7588]
### What I'm trying to achieve
I'm trying to use voucher with `apply_once_per_customer` set to `True` in the checkout and pay with payment method that requires additional confirmation (3DSecure). However, it fails, because voucher is marked as used during the first call of `checkoutComplete` - and the second call returns an validation error.

### Steps to reproduce the problem

1. Create voucher with `apply_once_per_customer` set to `True`
2. Add this voucher to the checkout
2. Send `checkoutComplete` that returns `confirmationNeeded`
3. Confirm payment on frontend
4. Send the second `checkoutComplete` mutation

As the result, `checkoutComplete` returns `VOUCHER_NOT_APPLICABLE` error.

### What I expected to happen
The second call of `checkoutComplete` processes payment successfully. 

The hot fix (maybe it's an actual fix) is to add an `else` to the last conditional statement in `checkout_complete` (https://github.com/mirumee/saleor/blob/486a38ff58bab220fef884dd8852112ef5f7b026/saleor/checkout/complete_checkout.py#L612-L627)
```
if not action_required:
        ...
else:
    release_voucher_usage(order_data)
```

### Screenshots and logs

**System information**

Saleor version:
- [x] dev (current master)
- [ ] 3.0
- [x] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

**Comment by eCzerniak** [comment]
Hello @Kwaidan00  thanks for reporting this issue! I've just added it to our backlog but I also want to point out that the fix will be added in version 3.0 also we advise to switch to this version.
