### ISSUE TITLE
Editing the quantity of a line item in a draft order does not trigger the `order_updated` plugin method

### ISSUE THREAD

**Issue by rrustvold** [saleor/saleor#7620]
### What I'm trying to achieve
There doesn't appear to be any methods in the BasePlugin class that can be triggered by editing a draft order's line item's quantity. As far as I can tell this is the only element of an order that can be changed without triggering at least one of the built in plug in methods. I'm not sure if this is by design or just an oversight. I would expect to see a plugin method called in the save method of the OrderLineUpdate mutation class. Either the generic `order_updated` method, or a specific method for line item quantity would seem appropriate. 

Saleor version:
- [ ] dev (current master)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

**Comment by maarcingebala** [comment]
Yes, there seems to be an oversight - draft order doesn't trigger any webhooks when it is created or edited, except for setting the shipping method, which triggers `order_updated`. Thanks for reporting, I'll put the but to the backlog so that the core team can fix it.
