### ISSUE TITLE
win10系统，docker desktop,所有主机都正常运行，但是打不开storefront页面，请帮忙解决一下，谢谢

### ISSUE THREAD

**Issue by dinghongbi** [saleor/saleor#7624]
storefront_1  | Starting type checking service...
storefront_1  | Using 1 worker with 2048MB memory limit
storefront_1  | ℹ ｢wds｣: Project is running at http://localhost:3000/
storefront_1  | ℹ ｢wds｣: webpack output is served from /
storefront_1  | ℹ ｢wds｣: Content not from webpack is served from /app
storefront_1  | ℹ ｢wds｣: 404s will fallback to /index.html
storefront_1  | Browserslist: caniuse-lite is outdated. Please run next command `npm update`

**Comment by sunel** [comment]
Same here, unable to open 3000

**Comment by twocucao** [comment]
@dinghongbi @sunel try? this https://stackoverflow.com/questions/44649438/localhost-refuses-connection-with-docker

**Comment by timuric** [comment]
I believe this is not related to the core and should be moved to discussions
