### ISSUE TITLE
Webhook Doesn't send any data 

### ISSUE THREAD

**Issue by D161764** [saleor/saleor#7625]
### What I'm trying to achieve
…
I have deployed saleor core 2.11.1 stable version to AWS EC2 Running Docker Container, The moment i create any object like customer or product. Though Webhook Should get triggered but its not sending any data .
### Steps to reproduce the problem

1.
2.

### What I expected to happen
…

### Screenshots and logs

**System information**

Saleor version:
- [ ] dev (current master)
- [ ] 3.0
- [X ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ X] Linux
- [ ] MacOS
- [ ] Other

**Comment by krzysztofwolski** [comment]
Webhook sending is done by worker instance. Have you deployed one?

**Comment by D161764** [comment]
Well below is my dockerrunaws.json for elasticbeanstalk , how i can add worker node there any idea, i dont see in documentation

{
    "AWSEBDockerrunVersion": "1",
    "Image": {
      "Name": "codersudip/saleorcorestable:latest",
      "Update": "true"
    },
    "Ports": [
      {
        "ContainerPort": "8000"
      }
    ]
  }

**Comment by maarcingebala** [comment]
This doesn't look like a relevant issue anymore, please reopen if there are any issues with webhook delivery in the newest version of Saleor.
