### ISSUE TITLE
ProgrammingError at /graphql/

### ISSUE THREAD

**Issue by vaibhavG321** [saleor/saleor#7656]
### What I'm trying to achieve
I am trying to up my Saleor server using PuTTy. The server is hosted on AWS.
But I am getting 400 error from graphql API when I try to login on dashboard.
Then I tried to open the playground where I got the error.

### What I expected to happen
I expected to see the playground where I can test my queries. And also able to login on dashboard

### Screenshots and logs

![Screenshot (1367)_LI](https://user-images.githubusercontent.com/51531542/126276220-e389f46a-b706-47bd-98f7-547f2da66b30.jpg)
Above is the error screenshot.

In the below screenshot, I have run the migrate command. Which clarifies that no migration is remaining.
Then I have also shown that there is no error shown while running the server locally.
![Screenshot (1370)_LI](https://user-images.githubusercontent.com/51531542/126277059-30404364-3044-4bd4-af1f-a5a4247cafde.jpg)

At last you can also see that in database there exist this field which is the cause of error.
![Screenshot (1372)](https://user-images.githubusercontent.com/51531542/126277647-799861b3-de80-44b8-9f27-6dd5bc7943b3.png)

**System information**

Saleor version:
- 3.0

Operating system:
- Windows

**Comment by maarcingebala** [comment]
Looks like a problem with DB setup, but I would check if this still happens with the newest version. If yes, please reopen the ticket.
