### ISSUE TITLE
CORS not handled outside the GraphQL

### ISSUE THREAD

**Issue by karer** [saleor/saleor#7722]
### What I'm trying to achieve
I added some endpoints to my app, using custom plugin with WebHook. Although I have added origins to "ALLOWED_CLIENT_HOSTS", my custom endpoints return error about CORS. After investigations, I found out, that CORS settings only apply to GraphQL endpoint, but not other ones. After adding django-cors package and configuring it, it works well. Anyway, I think that this should be handled by default.

### Steps to reproduce the problem
1. Create plugin with webhook endpoint (simple HTTP endpoint)
2. Add custom origin to cors (ALLOWED_CLIENT_HOSTS)
3. Enter custom origin page
4. Request endpoint url from that page. It will throw cors error.

### What I expected to happen
Endpoints should grab their CORS whitelist from ALLOWED_CLIENT_HOSTS

### Screenshots and logs
-

**System information**
Saleor version:
- [ ] dev (current master)
- [ ] 3.0
- [ x] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [x ] MacOS
- [ ] Other

**Comment by burenhuu** [comment]
when I configure the django cors package the graphql is not working. How did you get around that?

**Comment by piotrantosz** [comment]
@maarcingebala Can we add csrf_exempt to all plugins / apps URLs?

**Comment by maarcingebala** [comment]
CSRF middleware was enabled in 2.11 which we don't support. In Saleor 3.x we don't use this middleware anymore.
