### ISSUE TITLE
Getting hidden collections does not work

### ISSUE THREAD

**Issue by DVSoftware** [saleor/saleor#7981]
### What I'm trying to achieve
I'm trying to get hidden collections using graphql with app token, however CollectionPublished filter doesn't seem to work at all. It doesn't return any collections, while on the dashboard it does.

### Steps to reproduce the problem
Unpublish a collection, then try running a query. Make sure to use app token.

```
{
    collections(first: 100, filter:{published: HIDDEN }) {
        edges {
            node {
                id
            }
        }
        pageInfo {
            hasNextPage
            endCursor
        }
    }
}
```

### What I expected to happen
I expect hidden collections to be returned.

### Screenshots and logs

**System information**

Saleor version:
- [ ] dev (current master)
- [ ] 3.0
- [x] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by eCzerniak** [comment]
Hi @DVSoftware this issue has been corrected in version 3.0 and we advise to use this version. If you need more information please let me know.

**Comment by DVSoftware** [comment]
@eCzerniak Is the version 3.0 production ready?

**Comment by eCzerniak** [comment]
Hi @DVSoftware  stable version should be available within 2 months, but beta is faster and more stable than 2.11, so production services are already running on it.

**Comment by szczecha** [comment]
Works in 3.18 
<img width="1372" alt="image" src="https://github.com/saleor/saleor/assets/30683248/a479d862-59a0-4070-830a-815cc67ace4e">
