### ISSUE TITLE
Regarding Stripe Capture(Saleor 2.11)

### ISSUE THREAD

**Issue by KrEnjuTSU** [saleor/saleor#8010]
### Discussed in https://github.com/mirumee/saleor/discussions/8009

<div type='discussions-op-text'>

<sup>Originally posted by **KrEnjuTSU** September  2, 2021</sup>
Hello,

I am trying to do a partial capture based on partial fulfillment. Initially, I  disable Automatic payment capture in Stripe plugin settings. Then I am using orderCapture mutation to capture the amount based on the fulfillment. But the orderCapture is not working properly, the full amount is captured always irrespective of the amount I am passing in orderCapture mutation. 
eg: I authorize the card for 50 euros, I try to capture 40 euros but it does not work like that, by default the entire pre-authorized amount is getting captured when I am passing 40  euros using orderCapture mutation. Can anyone help me with this?</div>

**Comment by aniav** [comment]
I'll close this one as we are no longer supporting Saleor 2.11 and we have since deprecated Stripe plugin in favour of a Stripe app. Sorry this didn't have a response before 🙌
