### ISSUE TITLE
Countries in warehouse create and permission groups not showing

### ISSUE THREAD

**Issue by DTrafford** [saleor/saleor#8063]
When running the latest:

  "name": "saleor-dashboard",
  "version": "3.0.0-b.11",

  "name": "saleor",
  "version": "3.1.0-a.0",

I cannot see permission groups or countries in the warehouse create page without doing a page reload.

**Comment by maarcingebala** [comment]
It looks like the issue is related to the dashboard, but it's also about quite an old version. I would check if it works as expected in the newest version. Also, please use the [saleor-dashboard](https://github.com/saleor/saleor-dashboard/) repo for any issues related to the dashboard.
