### ISSUE TITLE
Git Clone and checkout having issue

### ISSUE THREAD

**Issue by nskit84** [saleor/saleor#8069]
### What I'm trying to achieve
Git clone the project

### Steps to reproduce the problem

1. git clone https://github.com/mirumee/saleor.git

### What I expected to happen
Clone the project in local computer

### Screenshots and logs

 git clone https://github.com/mirumee/saleor.git

Cloning into 'saleor'...
remote: Enumerating objects: 196222, done.
remote: Counting objects: 100% (414/414), done.
remote: Compressing objects: 100% (301/301), done.
remote: Total 196222 (delta 245), reused 171 (delta 113), pack-reused 195808 eceiving objects: 100% (196222/196222), 106Receiving objects: 100% (196222/196222), 109.81 MiB | 11.89 MiB/s, done.

Resolving deltas: 100% (144186/144186), done.
error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[http:/www.youtube.com/watch?v=dQw4w9WgXcQ-VIDEO].yaml'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

===================================================================================

git checkout 3.1
error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[http:/www.youtube.com/watch?v=dQw4w9WgXcQ-VIDEO].yaml'
error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[https:/vimeo.com/148751763-VIDEO].yaml'
error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[https:/www.flickr.com/photos/megane_wakui/31740618232/-IMAGE].yaml'
error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[https:/www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=TestingChannel-VIDEO].yaml'
error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[https:/www.youtube.com/watch?v=dQw4w9WgXcQ-VIDEO].yaml'

===================================================================================git checkout 3.0
error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[http:/www.youtube.com/watch?v=dQw4w9WgXcQ-VIDEO].yaml'
error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[https:/vimeo.com/148751763-VIDEO].yaml'
error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[https:/www.flickr.com/photos/megane_wakui/31740618232/-IMAGE].yaml'
error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[https:/www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=TestingChannel-VIDEO].yaml'
error: invalid path 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[https:/www.youtube.com/watch?v=dQw4w9WgXcQ-VIDEO].yaml'

===================================================================================

**System information**

Saleor version:
- [*] dev (current master)
- [*] 3.0

Operating system:
- [*] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

**Comment by sfehlandt** [comment]
A coworker of mine, who also uses windows has the same problem. I think it is because there are a couple of test files whose names contain characters forbidden on Windows directories (such as `[` and `]` ).

Here are some examples:
https://github.com/mirumee/saleor/tree/3.0/saleor/graphql/core/tests/cassettes

**Comment by Milena92** [comment]
Same problem on Windows, with the folder names in the 'saleor/graphql/core/tests/cassettes' folder... Neither git clone command or cloning using pycharm works.

**Comment by maarcingebala** [comment]
Fixed in #9236
