### ISSUE TITLE
Maintain user account balance

### ISSUE THREAD

**Issue by dawidjk** [saleor/saleor#8097]
### What I'm trying to achieve
We would like to grant users $xxx worth of credit that they can use on any purchase(s) they'd like, and have it carry over such that a user doesn't need to input a gift card balance every time they want to redeem the credit for an item.

Potential other use cases: 
 - refunding a user and granting them store credit instead of returning to balance to their original payment method.
 - Apply a charge to a user balance that they'll need to fulfill at time of next purchase (we don't necessarily need this feature)

### Describe a proposed solution
Store a balance field on the user object and during the checkout flow deduct account balance as the first form of payment.
Alternate solution is to be able to link a gift card to a particular user and have that as the default payment method until it's all used/expired

### Other solutions I've tried and won't work
Gift cards get us 90% of the way there, but it requires that the user input the code at every purchase

**Comment by timuric** [comment]
@dawidjk please take a look at the giftcard feature in saleor 3.1
You can sign up for a free dev box account here https://cloud.saleor.io/
