### ISSUE TITLE
Connecting the channel to a type of customer

### ISSUE THREAD

**Issue by taha2002** [saleor/saleor#8114]
I want to have. Types of customers and each type at special product prices. The customer is created with the default type. Then the owner of the store determines its type if he wants. And the customer cannot change his channel .

It will be more effective for merchants who sell to the final consumer and to wholesalers 

and thank u ❤️.

**Comment by T3P3** [comment]
is there any progress to this request? having customers in groups with different discount %s would be a very useful addition.

**Comment by timuric** [comment]
We have a draft of a custom pricing mutation, please take a look https://github.com/saleor/saleor/pull/9326
It will allow you to add lines to checkout with arbitrary prices. 
Any feedback is welcome!
