### ISSUE TITLE
checkoutCreate mutation issue -   { "code": "REQUIRED",  "field": "country",  "message": "This field cannot be blank." }

### ISSUE THREAD

**Issue by epoq** [saleor/saleor#8127]
### What I'm trying to achieve
try to add checkout step with createCheckout mutation.

### Steps to reproduce the problem

1. use docker-platform, deploy with docker compose, delete saleor folder and replace it by saleor folder with 3.1 branch clone
2. use playgraphl to test mutation request (checkoutCreate)

### What I expected to happen
i make test on saleor demo site : https://demo.saleor.io/graphql/

```bash
mutation CheckoutCreate {
  checkoutCreate(
    input: { channel: "default-channel", email: "john@example.com", lines: [] }
  ) 
  {  errors {
        code
        field
        message
      }
    checkout {
      id
      token
      created
       
    }
  }
}

```
result on : https://demo.saleor.io/graphql/
```bash
{
  "data": {
    "checkoutCreate": {
      "errors": [],
      "checkout": {
        "id": "Q2hlY2tvdXQ6MDQ2MmQwMzQtZGJmYi00MTg1LWExZTMtMWUwYTU2YWMxYjJi",
        "token": "0462d034-dbfb-4185-a1e3-1e0a56ac1b2b",
        "created": "2021-09-17T13:17:33.994853+00:00"
      }
    }
  }
}


```

# this is fine for me but ....
When i try the samething on my local machine (deploy with docker compose)
i get this:

```bash

{
  "data": {
    "checkoutCreate": {
      "errors": [
        {
          "code": "REQUIRED",
          "field": "country",
          "message": "This field cannot be blank."
        }
      ],
      "checkout": null
    }
  }
}

```
i want to get checkoutID and token and the system ask me to add some country field.....

**System information**

Saleor version:
- [ ] dev (current master)
- [ X] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ X] Linux
- [ ] MacOS
- [ ] Other

**Comment by epoq** [comment]
Any help ??

**Comment by timuric** [comment]
Please use this as a reference https://github.com/saleor/react-storefront

**Comment by benhavo** [comment]
@epoq I'm sure you found the solution by now, but I came here with the same problem. For anyone looking for the solution in the future, the channels created by the data population script do not have a `default_country` assigned. Once I populated that field, the mutation worked as expected.

**Comment by benhavo** [comment]
> > @epoq I'm sure you found the solution by now, but I came here with the same problem. For anyone looking for the solution in the future, the channels created by the data population script do not have a `default_country` assigned. Once I populated that field, the mutation worked as expected.
> 
> How did you populate that field?

I did it manually in the database. The default_country field is in the channel_channel table.

**Comment by roperi** [comment]
Thanks, @benhavo !
