### ISSUE TITLE
UI Bug 

### ISSUE THREAD

**Issue by kapil-sh** [saleor/saleor#8164]
There is an issue in responsiveness, the store-frontsite UI is not working properly in mobile phone  (check the filter section )
![UI_bug](https://user-images.githubusercontent.com/85110569/134334398-1ebbebd9-3f4a-4bd4-a72a-f36d177b7b87.png)

**Comment by Arpppit** [comment]
Hey Hi I can fix this. What else should I take note of before starting on project ?

**Comment by kapil-sh** [comment]
Not only the filter section but look into the NAV and product section to, they are also not looking good because of the remaining space

**Comment by timuric** [comment]
Please take a look at the new storefront which is under heavy development https://github.com/saleor/react-storefront
