### ISSUE TITLE
GrahpQL note in checkout support

### ISSUE THREAD

**Issue by ace-han** [saleor/saleor#8199]
### What I'm trying to achieve
There is no way to apply any note message to the checkout model.

This feature is so needed in `saleor-storefront` and `saleor` so that order detail view in `saleor-bashboard` won't always display an empty `customerNote`

### Describe a proposed solution
1. add a `note` field in `CheckoutCreateInput`
2. add a new mutation like `checkoutUpdateCustomerNote `

### Other solutions I've tried and won't work
…

### Screenshots or mockups

![image](https://user-images.githubusercontent.com/1177332/134845565-5c077a41-de23-455d-b28a-b2378676594c.png)

![image](https://user-images.githubusercontent.com/1177332/134845380-28a9167e-c746-4a7f-acf2-613ded7e5422.png)

**Comment by Juleszz** [comment]
Same for metdata on checkoutComplete. This would open up a lot of further possibilities 👍

**Comment by timuric** [comment]
@Juleszz we would be adding metadata to `checkoutComplete` soon
