### ISSUE TITLE
How to serve Static files on a Linode Volume. In Prod on Docker

### ISSUE THREAD

**Issue by dialformonkey** [saleor/saleor#8256]
Hey guys. I've setup saleor core for prod on docker hosted on Linode. However i am unable to get the configuration right for serving static files through the linode volume 

Static files are served by Django only in DEBUG mode, for production use it is recommended to serve them from the external resource, eg. Amazon S3 buckets. We have integration guide for it somewhere in the docs

_Originally posted by @Pacu2 in https://github.com/mirumee/saleor/issues/2675#issuecomment-415959797_

**Comment by timuric** [comment]
@dialformonkey I would advise to move this question to Discussions
