### ISSUE TITLE
Insufficient stock at checkoutShippingAddressUpdate Mutation

### ISSUE THREAD

**Issue by Juleszz** [saleor/saleor#8257]
### What I'm trying to achieve
When running `checkoutShippingAddressUpdate` Mutation after `checkoutCreate` Mutation, an Error of insufficient stock is thrown even if stock is sufficient. It looks like Saleor is trying to validate the quantities against stock twice (first on `checkoutCreate` and then on `checkoutShippingAddressUpdate`). This error won't happen if stock quantity is >= twice whats in the cart.

### Steps to reproduce the problem

1. Create a Product with variant quantity of e.g. 4
2. Run `checkoutCreate` Mutation with this product variant and quantity of 4 (**no insufficient stock error**)
3. Run `checkoutShippingAddressUpdate` Mutation (**insufficient stock error**)

**System information**

Saleor version:
- [ ] dev (current master)
- [ X ] 3.1 (3.1.0-a.8)
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ X ] HEROKU

**Comment by maarcingebala** [comment]
I'm not 100% sure, but I believe this will be fixed in PR #7589 by passing `replace=True` to `check_lines_quantity` ([see these changes](https://github.com/mirumee/saleor/pull/7589/files#diff-c70a2160c49088fa171fda2b4904744130f9cfa1476711c26813f0cf744f20feR857-R859)). We are planning to merge this PR soon - currently we're waiting for related frontend changes in the dashboard.

**Comment by 0842752682** [comment]
> ### What I'm trying to achieve
> When running `checkoutShippingAddressUpdate` Mutation after `checkoutCreate` Mutation, an Error of insufficient stock is thrown even if stock is sufficient. It looks like Saleor is trying to validate the quantities against stock twice (first on `checkoutCreate` and then on `checkoutShippingAddressUpdate`). This error won't happen if stock quantity is >= twice whats in the cart.
> 
> ### Steps to reproduce the problem
> 1. Create a Product with variant quantity of e.g. 4
> 2. Run `checkoutCreate` Mutation with this product variant and quantity of 4 (**no insufficient stock error**)
> 3. Run `checkoutShippingAddressUpdate` Mutation (**insufficient stock error**)
> 
> **System information**
> 
> Saleor version:
> 
> * [ ]  dev (current master)
> * [ X ] 3.1 (3.1.0-a.8)
> * [ ]  2.11
> * [ ]  2.10
> 
> Operating system:
> 
> * [ ]  Windows
> * [ ]  Linux
> * [ ]  MacOS
> * [ X ] 

>  #7588
