### ISSUE TITLE
Manual Payment - Pay later and upload proof of payment

### ISSUE THREAD

**Issue by chinkung** [saleor/saleor#8380]
### What I'm trying to achieve
Support pay later option and after paid for order within specific time, go to order details and upload proof of payment to confirm the order

### Describe a proposed solution
1. On payment page, allow customer to choose pay later with description how to pay (Bank transfer, etc)
2. Customer go back to order history and upload  proof of payment (pay slip screenshot, etc.) to confirm the order
3. If customer don't go to upload proof of payment to confirm order in specific timeframe, cancel the order

### Other solutions I've tried and won't work
…

**Comment by timuric** [comment]
You can automate this flow by using private order metadata

**Comment by timuric** [comment]
Partial payments are coming soon, subscribe to newsletter to stay up to date with the new features https://saleor.typeform.com/to/JTJK0Nou
