### ISSUE TITLE
Fetch channel in migration when there are multiple channels with same currency code

### ISSUE THREAD

**Issue by perastated** [saleor/saleor#8416]
### What I'm trying to achieve
I am studying the new Channel feature. Thanks for providing it! It can be useful. 
I have one question. 
From the [documentation](https://docs.saleor.io/docs/3.0/dashboard/channels), we can create a currency for each channel. We can also create multiple channels with the same currency. (E.g., one web-channel, one mobile-channel.)

When I look at the code, I notice this migration snippet, which gets the channel by the `currency_code`. Seems to me it would cause a problem if there are multiple channels with the same currency code. 

Note that it happens in multiple migration files as well, including vouchor/order/shippingmethod/collection_channel_listing.py, 
```python
File saleor/product/migrations/0134_product_channel_listing.py
def migrate_products_publishable_data(apps, schema_editor):
...
    channels_dict = {}

    for product in Product.objects.iterator():
        currency = product.currency
        channel = channels_dict.get(currency)
        if not channel:
            name = f"Channel {currency}"
            channel, _ = Channel.objects.get_or_create(
                currency_code=currency,
                defaults={"name": name, "slug": slugify(name)},
            )
            channels_dict[currency] = channel
```

Do you have thoughts on this? Thanks.

### Steps to reproduce the problem
Not yet. 

### What I expected to happen
Maybe add logics to deal with multiple Channels with the same currency_code when migration. 

**System information**
- [ ] dev (current main)

Operating system:
- [ ] Linux

**Comment by korycins** [comment]
I don't think that there is anything to worry about here. Assuming that, you're migrating from 2.10 or 2.11 to 3.0. Previous versions didn't support multiple currencies, and Saleor was using a currency defined in settings.py. At the end of migrations, you will finish with a single channel with a single currency (used in Saleor previously).
