### ISSUE TITLE
Invalid Cache Configuration with Saleor SDK useAuthState()

### ISSUE THREAD

**Issue by TurkaljGoran** [saleor/saleor#8425]
### What I'm trying to achieve

After a customer comes to Login page and does not have an account, he clicks 'register', and is taken to Registration Page.
After the customer is successfully registered, if he clicks Back button for example and is taken to Login Page, the Login Page checks with useAuthState() from Saleor SDK to see if user exists and is authenticated in which case it should redirect to Home or Account Page. 

However, upon clicking the back button this error happens:

![image](https://user-images.githubusercontent.com/75638667/138412746-1f50d1e3-94d1-4808-9c4e-56b8af517ffe.png)

I'm using Saleor SDK 0.4.0.7. 

### What I expected to happen

I expected no errors when user tries to go back to Login page, useAuthState should know that now there is a user who is authenticated and redirection should proceed accordingly based on that. 

This error also constantly happens

![image](https://user-images.githubusercontent.com/75638667/138413181-a145b943-ff40-4c55-a452-b398f5d193ea.png)

Is SaleorSDK recommended by Saleor team for production ready authentication at this point?

**Comment by timuric** [comment]
@TurkaljGoran please address this issue in the storefront https://github.com/saleor/react-storefront
keep in mind that it is currently under heavy development
