### ISSUE TITLE
checkoutCreate doesn't update SaleorState or SaleorCheckoutAPI's checkout

### ISSUE THREAD

**Issue by alxvallejo** [saleor/saleor#8449]
### What I'm trying to achieve

Basically I am forking off the checkout page to create my own checkout workflow. I notice that in the existing saleor-storefront, once a shipping address is selected and the user hits Continue to payments, the checkoutCreate mutation is run. I'm really not sure where that mutation is being called, but I am basically trying to consolidate the shipping address and shipping method in one screen and running the mutation manually.

My input looks like this

```
    const checkoutInput = {
      email: user?.email,
      lines: items.map((item) => {
        return { quantity: item.quantity, variantId: item.variant.id };
      }),
      shippingAddress: {
        firstName,
        lastName,
        companyName,
        streetAddress1,
        streetAddress2,
        city,
        postalCode,
        country: country.code,
        countryArea,
        phone,
      },
    };
```

This seems to successfully create the checkout, I get an id and the fields are set where appropriate.

However, I'm trying to push the new checkout into SaleorState so i can use the checkout hooks. 

```
const { loaded, checkout, availableShippingMethods, setShippingAddress, setShippingMethod } = useCheckout();
  console.log('checkout: ', checkout);
```

Checkout is always null here and doesn't even get logged when I successfully run my mutation.

So the useCheckout hooks are basically useless unless I can somehow load my checkout into state.

Also of note - if I refresh my page - the checkout object is populated! So how can I accomplish this without refreshing the page?

**System information**
2.11

Operating system:
MacOS

**Comment by timuric** [comment]
@alxvallejo please address this issue in the storefront https://github.com/saleor/react-storefront
keep in mind that it is currently under heavy development
