### ISSUE TITLE
Creating an order programmatically - TAX reset

### ISSUE THREAD

**Issue by osher-retailin** [saleor/saleor#8461]
### Discussed in https://github.com/saleor/saleor/discussions/8460

<div type='discussions-op-text'>

<sup>Originally posted by **osher-retailin** October 26, 2021</sup>
**What I'm trying to achieve**
Creating an order through the "draftOrderCreate" and "draftOrderComplete".

**What's the problem**
"Taxes" field of the order created via "draftOrderCreate" is being reset when draft order is complete and order is created.
Another problem, the is not being recalculated when quantity or price of an order item is changed.

I'm working on Saleor version **3.0.0-a.16**.

Best regards for the helpers.</div>

**Comment by timuric** [comment]
This issue is resolved in Saleor 3.1.
You can signup for a free devbox account to try latest Saleor in the cloud https://cloud.saleor.io/
