### ISSUE TITLE
Somer orders not connected to Customer profile

### ISSUE THREAD

**Issue by benoj** [saleor/saleor#8464]
### What I'm trying to achieve
List user orders in account page - 

### Steps to reproduce the problem
(hard to repeat as it seems to be intermittent)
1. User creates order (or several)
2. Query for user orders / navigate to customer in admin UI and see no orders

### What I expected to happen
Orders return to user 

### Screenshots and logs
here we see the customer has no orders in their customer profile (from admin UI)
<img width="571" alt="Screenshot 2021-10-26 at 17 35 19" src="https://user-images.githubusercontent.com/2669116/138922685-92230cb2-19b3-416f-987f-59ff6aa16d97.png">

Clicking the view orders button - I can see the orders connected to the email.
<img width="789" alt="Screenshot 2021-10-26 at 17 35 35" src="https://user-images.githubusercontent.com/2669116/138922678-d46b84c1-3626-44a1-af53-5d77951ee6bb.png">

**System information**
3.0.0-b.19

Saleor version:
- [ ] dev (current main)
- [X] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

**Comment by timuric** [comment]
@benoj doesn't seem to be an issue in 3.1
You can signup for a free devbox account to play with latest Saleor in the cloud https://cloud.saleor.io/

**Comment by timuric** [comment]
Our current implementation requires email confirmation for linking the new user with existing orders. That's why orders weren't linked.
