### ISSUE TITLE
CORS error right out of the box

### ISSUE THREAD

**Issue by manuelaguirre** [saleor/saleor#8469]
### What I'm trying to achieve
Login to the saleor dashboard

### Steps to reproduce the problem

1.Install saleor platform
2. Run containers and go to `localhost:9000/dashboard`
3. Sign in with superuser

### What I expected to happen
Login successful

### Screenshots and logs
I get a CORS issue out of the box, how can I sort this out? Where should I change environment variables (I have seen some allowed hosts variable default to localhost, so I don't know)
```
Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://localhost:8000/graphql/. Raison : échec de la requête CORS.
```

**System information**

Saleor version:
- [ ] dev (current main)
- [ ] 3.0
- [ x] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ x] Linux
- [ ] MacOS
- [ ] Other

**Comment by omars-code** [comment]
apparently the options request returns correctly, but the POST does not have a the Allow origin header
