### ISSUE TITLE
ALLOWED_CLIENT_HOSTS variable wrongly handled

### ISSUE THREAD

**Issue by jbod** [saleor/saleor#8556]
The `validate_storefront_url()` function in `saleor/core/utils/url.py` attempts to validate the URL domain against the `ALLOWED_CLIENT_HOSTS` setting using the `validate_host()` function from Django. However, this latter expects the `allowed_hosts` parameter to be a list of hostnames, not URLs, making the validation to fail.

According to the documentation at https://docs.saleor.io/docs/3.0/developer/running-saleor/configuration#allowed_client_hosts, the URLs described in the `ALLOWED_CLIENT_HOSTS` setting should observe the RFC1808 format, which is `<scheme>://<host>:<port>`. But according to the way it is validated, it simply cannot be.

We use the `django-cors-headers` package and we wanted to use the `ALLOWED_CLIENT_HOSTS` to populate the `CORS_ALLOWED_ORIGINS` setting (in theory, this would be OK to do so according to documentation). This makes, as an example, the dummy payment plugin to fail while validating the `redirect_url`.

Suggestions (choose one of them):
- Change the documentation to not refer to the RFC1808 for the `ALLOWED_CLIENT_HOSTS` setting, so that only `<host>:<port>` values are populated.
- Change line 23 of file `saleor/core/utils/url.py` from `if not validate_host(domain, settings.ALLOWED_CLIENT_HOSTS):` to `if not validate_host(domain, [urlparse(url).netloc for url in settings.ALLOWED_CLIENT_HOSTS]):`

**Comment by karolkielecki** [comment]
@jbod Hi, thanks for your suggestions. Our team will investigate it.
