### ISSUE TITLE
Ugly dashboard design

### ISSUE THREAD

**Issue by snax4a** [saleor/saleor#8557]
### What I'm trying to achieve
Better looking dashboard UI.
The current UI looks really poor and not professional.

### Describe a proposed solution
Hire a designer who will re-design your UI.

**Comment by karolkielecki** [comment]
@snax4a Hello Szymon,

Our top priority is to deliver Saleor 3.0 and then 3.1. We're constantly improving our UI when we have time to do it.

I understand that you may not be a fan of our current UI, but could you please be more specific with your feedback? What would you like to change? What do you dislike about our UI?

**Comment by snax4a** [comment]
@karolkielecki 
First of all, i would have changed i

**Comment by karolkielecki** [comment]
@snax4a We've improved the components you mentioned in our new design. The components will be consistent. We'll implement the new UI as soon as we can, but there is no ETA.
