### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'PATTERNS_IGNORED_IN_QUERY_CAPTURES'

### ISSUE THREAD

**Issue by btodorce** [saleor/saleor#8581]
Using the latest saleor 3.0 beta

Trying to run pyton tests with docker-compose run --rm api python3 manage.py test.
It fails with error AttributeError: 'Settings' object has no attribute 'PATTERNS_IGNORED_IN_QUERY_CAPTURES'

**Comment by thanghoian123** [comment]
i dont know???????????
