### ISSUE TITLE
Make variants after initial creation

### ISSUE THREAD

**Issue by DTrafford** [saleor/saleor#8589]
### What I'm trying to achieve
…. Create variants with channel listings after 1st variant made

### Steps to reproduce the problem

1.  Make a variant
2. Make a new variant after first one is saved

### What I expected to happen
…. Be able to add prices per channel

**System information**
Saleor version:
- [ ] 3.0

** Suggested solution:

Saleor > GraphQL > product > mutations > products.py > ProductVariantCreate

    @classmethod
    def create_variant_channel_listings(cls, variant, channels):
        variant_channel_listings = []
        for channel in channels:
            try:
                listing = models.ProductVariantChannelListing.objects.get(
                    channel_id=channel.get("id"), variant_id=variant.id)
            except:
                listing = None
            if not listing:
                variant_channel_listings.append(
                    models.ProductVariantChannelListing(
                        channel_id=channel.get("id"),
                        variant_id=variant.id,
                        currency=channel.get("currency"),
                    )
                )
        models.ProductVariantChannelListing.objects.bulk_create(
            variant_channel_listings
        )

    @classmethod
    @traced_atomic_transaction()
    def save(cls, info, instance, cleaned_input):
        new_variant = instance.pk is None
        instance.save()
        if not instance.product.default_variant:
            instance.product.default_variant = instance
            instance.product.save(update_fields=["default_variant", "updated_at"])
        # Recalculate the "discounted price" for the parent product
        update_product_discounted_price_task.delay(instance.product_id)
        stocks = cleaned_input.get("stocks")
        if stocks:
            cls.create_variant_stocks(instance, stocks)

        attributes = cleaned_input.get("attributes")
        if attributes:
            AttributeAssignmentMixin.save(instance, attributes)
            generate_and_set_variant_name(instance, cleaned_input.get("sku"))

        channel_listings = models.ProductChannelListing.objects.filter(
            product_id=instance.product.id)
        channels = []
        for channel in channel_listings:
            channels.append({"id": channel.channel_id, "price": 0,
                             "cost_price": 0, "currency": channel.currency})
        cls.create_variant_channel_listings(instance, channels)

        event_to_call = (
            info.context.plugins.product_variant_created
            if new_variant
            else info.context.plugins.product_variant_updated
        )
        transaction.on_commit(lambda: event_to_call(instance))

**Comment by timuric** [comment]
@DTrafford you should enable products in channels before setting prices per channel.
Please use dashboard UI as a reference (this tool might come handy https://chrome.google.com/webstore/detail/graphql-network-inspector/ndlbedplllcgconngcnfmkadhokfaaln?hl=en-GB )
