### ISSUE TITLE
Azure blob storage integration

### ISSUE THREAD

**Issue by d3vsh4** [saleor/saleor#8618]
### What I'm trying to achieve
Additional azure storage for serving static media files just like AWS s3 and gcp, it would be really helpful If this feature was there.

Also I could have proposed solution myself but I am afraid of breaking things, may be if there was some docs on how to add remote storage for serving media or atleast how to customise backend explaing how everything is working would be really helpfull for contributing more

**Comment by timuric** [comment]
@d3vsh4 unfortunately we are not planning to add support for azure any time soon, but we are open to PR

**Comment by peastuti** [comment]
Any chance it is going to be planned? 
It's quite a mess for those that have to use azure.

**Comment by manojLondhe** [comment]
+1 


> Any chance it is going to be planned? It's quite a mess for those that have to use azure.

**Comment by manojLondhe** [comment]
Looks like it is added in https://github.com/saleor/saleor/pull/9866
