### ISSUE TITLE
Pricing Table + Additional Options

### ISSUE THREAD

**Issue by guyathomas** [saleor/saleor#8619]
### What I'm trying to achieve
I would like to be able to select a product, and then have the price of my order adjust based on the dimensions of that product (i.e. when ordering curtains ).
…

### Describe a proposed solution
...

### Other solutions I've tried and won't work
Offering every combination of variants for the dimensions is not feasible since they can be down to the mm in 2 dimensions.
…

**Comment by karolkielecki** [comment]
@guyathomas Hi! Thanks for your suggestion. I've passed it to the team. Currently, it's not on our radar. In your use case, you can only create many variants. 

If you have more questions, we encourage you to open a GitHub discussion: https://github.com/saleor/saleor/discussions

Cheers,
