### ISSUE TITLE
Category name with all Chinese result in routing failed

### ISSUE THREAD

**Issue by fxp** [saleor/saleor#8653]
### What I'm trying to achieve
I'm trying to add a new category with full Chinese name, for example "加工包装", and then I can query that category in graphql. But storefront, it become empty because of non-ascii characters, and the route become invalid, like /category//5

### Steps to reproduce the problem

1. create a category naming  "加工包装"
2. add a new menu point to that category in dashboard-navigation
3. refresh storefront page and goto that menu

### What I expected to happen
Maybe setting and using slug by default if category name is full non-ascii characters is a good way.

**System information**

Saleor version:
2.11

Operating system:
Linux

**Comment by chrislais** [comment]
手动把Categories的Search Engine Preview的slug写成拼音不行吗？

**Comment by timuric** [comment]
@fxp Please address this in the dashboard repository. Thanks!
