### ISSUE TITLE
AWS Cognito Integration

### ISSUE THREAD

**Issue by dvdthecoder** [saleor/saleor#8662]
Hi ,

We are a start-up in seed stage using Saleor open source. We are using AWS Cognito as our third party integration for customer auth. 

How can this pair up with Saleor ? Any references. 

Also can I be provided direction on extending functionality using plugins. Can we use Nodejs?

**Comment by timuric** [comment]
@dvdthecoder you can use Saleor cloud which provides SSO features and many other advantages when it comes running Saleor. You can get free dev sandbox here https://cloud.saleor.io/
Let me know if you have questions (dm on twitter)
