### ISSUE TITLE
Order Fullfilled webhook payload does not contain product id inside "OrderLines"

### ISSUE THREAD

**Issue by ChintanDiwakar** [saleor/saleor#8753]
### What I'm trying to achieve
I am trying to sync my external system according to saleor. I am using webhooks for it. I am trying to get an POST API hit when an order is fulfilled.  
### Steps to reproduce the problem

1. Added all the necessary details on the webhook page

### What I expected to happen
I expect to get the entire order details of the order placed. The ISSUE is that the Order lines do not contain the id of the Product. 
Basically, the payload which they have mentioned in the docs are not been reflected in the response correctly. 

`"lines": [
            {
                "type": "OrderLine",
                "id": "T3JkZXJMaW5lOjI3Ng==",
                "total_price_net_amount": "1.000",
                "total_price_gross_amount": "1.000",
                "allocations": [
                    {
                        "quantity_allocated": 0,
                        "warehouse_id": "V2FyZWhvdXNlOjdkMDdmYmEzLTQ1MzctNDQ3Zi05YWZlLTdlZjgzMmZjOGFmOQ=="
                    }
                ],
                "product_name": "Lime & Cilantro Jasmine Rice",
                "variant_name": "23456",
                "translated_product_name": "",
                "translated_variant_name": "",
                "product_sku": "23456",
                "quantity": 1,
                "currency": "USD",
                "unit_discount_amount": "0.000",
                "unit_discount_type": "fixed",
                "unit_discount_reason": null,
                "unit_price_net_amount": "1.000",
                "unit_price_gross_amount": "1.000",
                "undiscounted_unit_price_gross_amount": "1.000",
                "undiscounted_unit_price_net_amount": "1.000",
                "undiscounted_total_price_gross_amount": "1.000",
                "undiscounted_total_price_net_amount": "1.000",
                "tax_rate": "0.0000"
            },
            {
                "type": "OrderLine",
                "id": "T3JkZXJMaW5lOjI3Nw==",
                "total_price_net_amount": "1.000",
                "total_price_gross_amount": "1.000",
                "allocations": [
                    {
                        "quantity_allocated": 0,
                        "warehouse_id": "V2FyZWhvdXNlOjdkMDdmYmEzLTQ1MzctNDQ3Zi05YWZlLTdlZjgzMmZjOGFmOQ=="
                    }
                ],
                "product_name": "Japanese Teriyaki with Udon Noodles",
                "variant_name": "54212",
                "translated_product_name": "",
                "translated_variant_name": "",
                "product_sku": "54212",
                "quantity": 1,
                "currency": "USD",
                "unit_discount_amount": "0.000",
                "unit_discount_type": "fixed",
                "unit_discount_reason": null,
                "unit_price_net_amount": "1.000",
                "unit_price_gross_amount": "1.000",
                "undiscounted_unit_price_gross_amount": "1.000",
                "undiscounted_unit_price_net_amount": "1.000",
                "undiscounted_total_price_gross_amount": "1.000",
                "undiscounted_total_price_net_amount": "1.000",
                "tax_rate": "0.0000"
            }
        ],`

I am unable to get the product Id in this.

### Screenshots and logs
![image](https://user-images.githubusercontent.com/48587709/145053312-8e059dde-f3e1-4c6c-998a-2e12209b4af6.png)

**System information**

Saleor version:
- [ ] dev (current main)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

**Comment by timuric** [comment]
As a workaround, please fetch the order to obtain product IDs. In Saleor you would be able to use to select payload schema for each webhook
