### ISSUE TITLE
Missing pycurl module while trying to use SQS as Celery broker

### ISSUE THREAD

**Issue by geovanisouza92** [saleor/saleor#8804]
### What I'm trying to achieve

Trying to use SQS as Celery Broker.

### Steps to reproduce the problem

1. Using `roribio16/alpine-sqs` instead of `redis` container
2. Set `CELERY_BROKER_URL=sqs://AAA:SSS@alpine-sqs:9324/`
3. Start `worker` service

### What I expected to happen

Worker (celery) process to connect on SQS and start processing.

### Screenshots and logs

<details>
<summary>Worker container logs</summary>
worker_1      | /usr/local/lib/python3.9/site-packages/celery/platforms.py:834: SecurityWarning: You're running the worker with superuser privileges: this is
worker_1      | absolutely not recommended!
worker_1      | 
worker_1      | Please specify a different user using the --uid option.
worker_1      | 
worker_1      | User information: uid=0 euid=0 gid=0 egid=0
worker_1      | 
worker_1      |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
worker_1      |  
worker_1      |  -------------- celery@84ef76d0f2b7 v5.1.2 (sun-harmonics)
worker_1      | --- ***** ----- 
worker_1      | -- ******* ---- Linux-5.10.47-linuxkit-aarch64-with-glibc2.31 2021-12-15 14:44:15
worker_1      | - *** --- * --- 
worker_1      | - ** ---------- [config]
worker_1      | - ** ---------- .> app:         saleor:0xffffa934cd90
worker_1      | - ** ---------- .> transport:   sqs://AAA:**@alpine-sqs:9324//
worker_1      | - ** ---------- .> results:     disabled://
worker_1      | - *** --- * --- .> concurrency: 4 (prefork)
worker_1      | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
worker_1      | --- ***** ----- 
worker_1      |  -------------- [queues]
worker_1      |                 .> default          exchange=default(direct) key=default
worker_1      |                 
worker_1      | 
worker_1      | [tasks]
worker_1      |   . saleor.account.thumbnails.create_user_avatar_thumbnails
worker_1      |   . saleor.app.tasks.install_app_task
worker_1      |   . saleor.core.analytics.ga_report
worker_1      |   . saleor.core.search_tasks.set_order_search_document_values
worker_1      |   . saleor.core.search_tasks.set_user_search_document_values
worker_1      |   . saleor.core.tasks.delete_from_storage_task
worker_1      |   . saleor.csv.tasks.export_products_task
worker_1      |   . saleor.order.tasks.recalculate_orders_task
worker_1      |   . saleor.plugins.admin_email.tasks.send_email_with_link_to_download_file_task
worker_1      |   . saleor.plugins.admin_email.tasks.send_export_failed_email_task
worker_1      |   . saleor.plugins.admin_email.tasks.send_set_staff_password_email_task
worker_1      |   . saleor.plugins.admin_email.tasks.send_staff_order_confirmation_email_task
worker_1      |   . saleor.plugins.admin_email.tasks.send_staff_password_reset_email_task
worker_1      |   . saleor.plugins.avatax.tasks.api_post_request_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_account_confirmation_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_account_delete_confirmation_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_email_with_dynamic_template_id
worker_1      |   . saleor.plugins.sendgrid.tasks.send_fulfillment_confirmation_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_fulfillment_update_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_gift_card_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_invoice_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_order_canceled_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_order_confirmation_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_order_confirmed_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_order_refund_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_password_reset_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_payment_confirmation_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_request_email_change_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_set_user_password_email_task
worker_1      |   . saleor.plugins.sendgrid.tasks.send_user_change_email_notification_task
worker_1      |   . saleor.plugins.user_email.tasks.send_account_confirmation_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_account_delete_confirmation_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_fulfillment_confirmation_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_fulfillment_update_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_gift_card_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_invoice_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_order_canceled_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_order_confirmation_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_order_confirmed_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_order_refund_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_password_reset_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_payment_confirmation_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_request_email_change_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_set_user_password_email_task
worker_1      |   . saleor.plugins.user_email.tasks.send_user_change_email_notification_task
worker_1      |   . saleor.plugins.webhook.tasks._get_webhooks_for_event
worker_1      |   . saleor.plugins.webhook.tasks.send_webhook_request
worker_1      |   . saleor.plugins.webhook.tasks.trigger_webhooks_for_event
worker_1      |   . saleor.product.tasks.deactivate_preorder_for_variants_task
worker_1      |   . saleor.product.tasks.update_product_discounted_price_task
worker_1      |   . saleor.product.tasks.update_products_discounted_prices_of_catalogues_task
worker_1      |   . saleor.product.tasks.update_products_discounted_prices_of_discount_task
worker_1      |   . saleor.product.tasks.update_products_discounted_prices_task
worker_1      |   . saleor.product.tasks.update_variants_names
worker_1      |   . saleor.product.thumbnails.create_category_background_image_thumbnails
worker_1      |   . saleor.product.thumbnails.create_collection_background_image_thumbnails
worker_1      |   . saleor.product.thumbnails.create_product_thumbnails
worker_1      |   . saleor.shipping.tasks.drop_invalid_shipping_methods_relations_for_given_channels
worker_1      |   . saleor.warehouse.tasks.delete_empty_allocations_task
worker_1      |   . saleor.warehouse.tasks.delete_expired_reservations_task
worker_1      | 
worker_1      | INFO celery.worker.consumer.connection Connected to sqs://AAA:**@alpine-sqs:9324// [PID:1:MainThread]
worker_1      | WARNING py.warnings /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
worker_1      |             leak, never use this setting in production environments!
worker_1      |   warnings.warn('''Using settings.DEBUG leads to a memory
worker_1      |  [PID:1:MainThread]
worker_1      | INFO celery.apps.worker celery@84ef76d0f2b7 ready. [PID:1:MainThread]
worker_1      | CRITICAL celery.worker Unrecoverable error: ImportError('The curl client requires the pycurl library.') [PID:1:MainThread]
worker_1      | Traceback (most recent call last):
worker_1      |   File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/http/__init__.py", line 18, in get_client
worker_1      |     return hub._current_http_client
worker_1      | AttributeError: 'Hub' object has no attribute '_current_http_client'
worker_1      | 
worker_1      | During handling of the above exception, another exception occurred:
worker_1      | 
worker_1      | Traceback (most recent call last):
worker_1      |   File "/usr/local/lib/python3.9/site-packages/celery/worker/worker.py", line 203, in start
worker_1      |     self.blueprint.start(self)
worker_1      |   File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
worker_1      |     step.start(parent)
worker_1      |   File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 365, in start
worker_1      |     return self.obj.start()
worker_1      |   File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 326, in start
worker_1      |     blueprint.start(self)
worker_1      |   File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
worker_1      |     step.start(parent)
worker_1      |   File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 618, in start
worker_1      |     c.loop(*c.loop_args())
worker_1      |   File "/usr/local/lib/python3.9/site-packages/celery/worker/loops.py", line 81, in asynloop
worker_1      |     next(loop)
worker_1      |   File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/hub.py", line 299, in create_loop
worker_1      |     item()
worker_1      |   File "/usr/local/lib/python3.9/site-packages/vine/promises.py", line 160, in __call__
worker_1      |     return self.throw()
worker_1      |   File "/usr/local/lib/python3.9/site-packages/vine/promises.py", line 157, in __call__
worker_1      |     retval = fun(*final_args, **final_kwargs)
worker_1      |   File "/usr/local/lib/python3.9/site-packages/kombu/transport/SQS.py", line 513, in _schedule_queue
worker_1      |     self._get_bulk_async(
worker_1      |   File "/usr/local/lib/python3.9/site-packages/kombu/transport/SQS.py", line 530, in _get_bulk_async
worker_1      |     return self._get_async(queue, maxcount, callback=callback)
worker_1      |   File "/usr/local/lib/python3.9/site-packages/kombu/transport/SQS.py", line 540, in _get_async
worker_1      |     qname, count=count, connection=self.asynsqs(queue=qname),
worker_1      |   File "/usr/local/lib/python3.9/site-packages/kombu/transport/SQS.py", line 743, in asynsqs
worker_1      |     c = self._asynsqs = AsyncSQSConnection(
worker_1      |   File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/aws/sqs/connection.py", line 20, in __init__
worker_1      |     super().__init__(
worker_1      |   File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/aws/connection.py", line 180, in __init__
worker_1      |     super().__init__(sqs_connection, http_client,
worker_1      |   File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/aws/connection.py", line 134, in __init__
worker_1      |     self._httpclient = http_client or get_client()
worker_1      |   File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/http/__init__.py", line 20, in get_client
worker_1      |     client = hub._current_http_client = Client(hub, **kwargs)
worker_1      |   File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/http/__init__.py", line 11, in Client
worker_1      |     return CurlClient(hub, **kwargs)
worker_1      |   File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/http/curl.py", line 41, in __init__
worker_1      |     raise ImportError('The curl client requires the pycurl library.')
worker_1      | ImportError: The curl client requires the pycurl library.
worker_1      | INFO celery.beat beat: Shutting down... [PID:1:MainThread]
saleor_worker_1 exited with code 0
</details>

**System information**

Saleor version:
- [x] dev (current main)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [x] MacOS (M1)
- [ ] Other

**Comment by daltonsena** [comment]
I don't think that this is a bug @geovanisouza92. When you have a little time, it's worth browsing through the amazing [docs](https://docs.saleor.io/docs/3.0/) and discussions page: https://github.com/saleor/saleor/discussions/

Recently this subject popped there: https://github.com/saleor/saleor/discussions/8707

Also, I don't know the current status but had Saleor have a spectrum space: https://spectrum.chat/saleor

**Comment by geovanisouza92** [comment]
Thank you @daltonsena ! I'll test it soon and confirm if it works for me.
