### ISSUE TITLE
Changing stripe locale to receive error messages in different language!

### ISSUE THREAD

**Issue by KrEnjuTSU** [saleor/saleor#8844]
can you guys help me with changing the stripe locale? can you point me to where exactly the change has to be done?

**Comment by timuric** [comment]
I am afraid you would have to check the documentation as we are not actively developing Stripe plugin due to the new payment gateway app which would have Stripe in the future. https://github.com/saleor/saleor-checkout/tree/main/apps/checkout-app/pages/api
