### ISSUE TITLE
Anyone can update the metadata of any Order

### ISSUE THREAD

**Issue by sfehlandt** [saleor/saleor#8884]
### What I'm trying to achieve (problem)

I think Order's metadata should be protected.
Currently anyone can perform the `updateMetadata` mutation on an Order
…

### Steps to reproduce the problem

1. Get the ID of an order (create a new one with the dashboard if necessary). Eg: "T3JkZXI6MQ=="

2. perform the updateMetadata mutation without an Authorization token:

```
mutation {
  updateMetadata(
    id: "T3JkZXI6MQ=="
    input: {
      key: "some-key"
      value: "some-value"
    }
  ) {
    errors {
      field
      message
    }
  }
}

```

You will see that this mutation works correctly, even if no `Authorization` header is provided

### What I expected to happen

I expect this to fail with an error message like this:

```json
{
  "errors": [
    {
      "message": "You do not have permission to perform this action",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateMetadata"
      ],
      "extensions": {
        ...
      }
    }
  ],
  "data": {
    "updateMetadata": null
  }
}
```

### How to solve it

If we change the `PUBLIC_META_PERMISSION_MAP` in this line: <https://github.com/saleor/saleor/blob/70b72de39d431357b137f6ee279803e430fe0fa3/saleor/graphql/meta/permissions.py#L116>

from this:

```
PUBLIC_META_PERMISSION_MAP = {
    ...
    "Order": no_permissions,
    ...
}
```

to this:

```
PUBLIC_META_PERMISSION_MAP = {
    ...
    "Order": order_permissions,
    ...
}
```

We will have the `updateMetadata` mutation forbidden for non-admin users.

### Discussion

I tried this and it works but the mutation is forbidden to all non-admin users.
I understand this may be undesirable for some applications, but I think it is
much worse that anyone can modify any order.

I can make a Pull Request with this change if you like (it is a very small change)
What branch should I request this to be merged? (I need it in version 3.0)

Kind regards

**System information**

Saleor version:

- [ ] dev (current main)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:

- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by maarcingebala** [comment]
Answered in this comment: https://github.com/saleor/saleor/pull/8898#issuecomment-1008665883
