### ISSUE TITLE
Add to cart / Checkout with react&saleor

### ISSUE THREAD

**Issue by gabylim** [saleor/saleor#8941]
### Add to cart / Checkout with react&saleor

Hello everyone,

I am a beginner in saleor and reactjs and I am struggling to add my product created in the saleor dashboard to the cart,

I use graphql but I don't know if there is a way to make it simple with the sdk saleor, otherwise someone can help me do it please?

**System information**

Saleor version:
- [ ] dev (current main)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [x] Linux with docker

Programming language:
- [X] reactjs 5

Thanks in advance

**Comment by timuric** [comment]
Hi @gabylim please use react-storefront as a reference
