### ISSUE TITLE
Group Products together

### ISSUE THREAD

**Issue by smalltoe** [saleor/saleor#8997]
### What I'm trying to achieve
My product consists of many parts of the same kind and I would like to sell a product as a set of those parts. Like if you would sell a renovation kit of 5 Hyperspace Turquoise Paint plus 7 brushes and 5 rolls to paint a room of x square meters.

### Describe a proposed solution
I have set up those parts in saleor as own products and I tried to create a collection that consists of the mentioned parts. Unfortuantely it seems that I can only add one part to a collection. So only 1 Hyperspace Turquoise Paint, 1 brush and 1 roll. It would be great if collections could consist also of many items of the same kind.

### Other solutions I've tried and won't work
For the time being I would describe the product in more detail in the meta data section of the collection - however it does not tie in nicely with inventory etc.

### Screenshots or mockups
None

**Comment by karolkielecki** [comment]
Hi @smalltoe, 
Thanks for your suggestion. We have a product bundle feature on our roadmap. However, there is no ETA. You can check our roadmap here: https://github.com/saleor/saleor/projects/12

**Comment by smalltoe** [comment]
Great to know you are planning for that. I will keep an eye on it for the time being. Many Thanks for your great work!

**Comment by karolkielecki** [comment]
Thanks! If you also have other questions or you would like to discuss something Saleor related, we encourage you to open a GitHub discussion: https://github.com/saleor/saleor/discussions
