### ISSUE TITLE
I can't clone on windows 11

### ISSUE THREAD

**Issue by hanimounla** [saleor/saleor#9012]
### What I'm trying to achieve
To clone the repo

### Steps to reproduce the problem
gh repo clone saleor/saleor

### What I expected to happen
The repo to be cloned normally 

### Screenshots and logs
Cloning into 'saleor'...
remote: Enumerating objects: 208929, done.
remote: Counting objects: 100% (520/520), done.
remote: Compressing objects: 100% (436/436), done.
remote: Total 208929 (delta 236), reused 153 (delta 84), pack-reused 208409Receiving objects: 100% (208929/208929), 122.02 MiB | 324.00 KiB/s
Receiving objects: 100% (208929/208929), 122.35 MiB | 342.00 KiB/s, done.
Resolving deltas: 100% (154445/154445), done.
fatal: cannot create directory at 'saleor/graphql/core/tests/cassettes/test_get_oembed_data[http:': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**System information**
Currently the main branch
Saleor version:
- [* ] dev (current main)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ * ] Windows 11
- [ ] Linux
- [ ] MacOS
- [ ] Other

**Comment by rahulteja526** [comment]
I too faced the same issue and used the below:

`git clone https://github.com/saleor/saleor-platform.git --recursive --jobs 3`

it cloned all the three repositories without any issue.
Cloning the saleor alone is not working.

**Comment by Roffild** [comment]
Bug in https://github.com/saleor/saleor/pull/7031
```
The following reserved characters:

< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file
