### ISSUE TITLE
Image upload to a product

### ISSUE THREAD

**Issue by cenekSvoboda** [saleor/saleor#9026]
### What I'm trying to achieve
I'm trying to upload image to the product

### Steps to reproduce the problem
1. Get Token, upload
request("http://"+address+":80/graphql/", authQuery).then(async (datx) => {
    let tok = datx.tokenCreate.token;
    let o = {
        "query": "mutation productImageCreate( $product: ID! $image: Upload! ) { productImageCreate( input: { product: $product image: $image}) { errors { field message } } }",
        variables: { product: "UHJvZHVjdDo3Mg==", image: null },
    };
    let map = {
        "0": ["variables.image"],
    };
    let fd = new FormData();
    fd.append("operations", JSON.stringify(o));
    fd.append("map", JSON.stringify(map));
    fd.append(0, fs.createReadStream(`./xxx.jpg`), "xxx.jpg");
    let res = await axios.post("http://" + address + ":80/graphql/", fd, {
        headers: {
            authorization: "Bearer " + tok,
            ...fd.getHeaders(),
        },
    }).catch((error) => console.log(error));
    console.log(res?.data?.data?.productImageCreate);
});

### What I expected to happen
image gets uploaded

### Screenshots and logs
I get this, image is not uploaded:
PS C:\prace\saleor-platform\xmls> node .\xmls.js
{
  errors: [
    {
      field: 'product',
      message: "Couldn't resolve to a node: UHJvZHVjdDo3Mg=="
    }
  ]
}

**System information**
I use main branch
Saleor version:
- [ ] dev (current main)

Operating system:
- [ ] Linux

**Comment by cenekSvoboda** [comment]
When I create (mandatory) variants, upload is successful

**Comment by timuric** [comment]
@cenekSvoboda please use the dashboard as a reference for how to use image upload API. This tool might come in handy https://chrome.google.com/webstore/detail/graphql-network-inspector/ndlbedplllcgconngcnfmkadhokfaaln?hl=en-GB
