### ISSUE TITLE
'api' Failed to Build

### ISSUE THREAD

**Issue by darrylmorley** [saleor/saleor#9029]
### What I'm trying to achieve
Setup Saleor, first time.
…

### Steps to reproduce the problem

git clone https://github.com/saleor/saleor-platform.git --recursive --jobs 3
cd saleor-platform
docker-compose build

### Screenshots and logs
 => ERROR [stage-1 3/9] RUN apt-get update   && apt-get install -y   libxml2   libssl1.1   libcairo2   libpango-1.0-0  1.8s
------                                                                                                                      
 > [stage-1 3/9] RUN apt-get update   && apt-get install -y   libxml2   libssl1.1   libcairo2   libpango-1.0-0   libpangocairo-1.0-0   libgdk-pixbuf2.0-0   shared-mime-info   mime-support   && apt-get clean   && rm -rf /var/lib/apt/lists/*:        
#8 0.801 Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]                             
#8 0.818 Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]                                                     
#8 0.978 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]                                            
#8 1.085 Err:1 http://security.debian.org/debian-security bullseye-security InRelease
#8 1.085   At least one invalid signature was encountered.
#8 1.254 Err:2 http://deb.debian.org/debian bullseye InRelease
#8 1.254   At least one invalid signature was encountered.
#8 1.442 Err:3 http://deb.debian.org/debian bullseye-updates InRelease
#8 1.442   At least one invalid signature was encountered.
#8 1.455 Reading package lists...
#8 1.472 W: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
#8 1.472 E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
#8 1.472 W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
#8 1.472 E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
#8 1.472 W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
#8 1.472 E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
------
executor failed running [/bin/sh -c apt-get update   && apt-get install -y   libxml2   libssl1.1   libcairo2   libpango-1.0-0   libpangocairo-1.0-0   libgdk-pixbuf2.0-0   shared-mime-info   mime-support   && apt-get clean   && rm -rf /var/lib/apt/lists/*]: exit code: 100
ERROR: Service 'api' failed to build : Build failed

**System information**

Saleor version:
- [ x ] dev (current main)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [ x ] MacOS
- [ ] Other

**Comment by agarjoshua** [comment]
Has anyone found any solution for this?

**Comment by agarjoshua** [comment]
> Has anyone found any solution for this?

https://github.com/saleor/saleor/issues/7856#issuecomment-960910160 This solutions worked for me

**Comment by timuric** [comment]
@darrylmorley can you reproduce this issue with 3.1?

**Comment by lathinharoon** [comment]
I am also having the same issue.

[ x ] current main

Operating system:
[ x ] MacOS

**Comment by maarcingebala** [comment]
Please check if it still happens with the newest version of Saleor, if yes, let's reopen then with more info.
