### ISSUE TITLE
Variant creator not working for multiple channels and multiple variant attributes

### ISSUE THREAD

**Issue by JustCreate3D** [saleor/saleor#9054]
### What I'm trying to achieve

(Edit1: Solved, this isn't a really a bug, actually a wanted behavior, but there is a lack of indicative error message on the dashboard and a lack of restrictions to prevent this to happen, see comment below))
(Edit2: "multiple attributes" = "dropdown" (catalog input type for store owner))

I'm trying to create multiple variants via the **variant-creator** using **multiple attributes** for **multiple channels.**
Note: I was aware of this bug when creating product variants for 3 channels simultaneously (so I stick to 2 because of this), now after updating the dashboard to version: dashboard v3.0.0-b.29 core vdev and the core to the current version, the variant creator doesn't work anymore even with 2 active channels. I've created this way thousands of SKUs (for 2 channels) without any problem until now.
### Steps to reproduce the problem

1. Create at least 2 channels with different currencies and set them to active
2. Create one warehouse
2. Create a product type with at least 1 multi-select and one numeric attribute, set them to required and fill some random data there
3. Assign this attribute as a variant attribute
4. Create a product and assign it the product type you just created
5. Click create variants and select the "Create multiple variant via variant creator" option
6. In the "Choose Values" step select at least 2 values to the variant attribute
7. In the "Price and SKUs" step select the "Apply unique prices by attribute to each SKU" and there, select the attribute
8. Enter random prices and below in the "Stock and Warehousing" select "Apply single stock to all SKUs" and enter a random number
9. In the "Summary" step, enter random SKUs and then click create
10. There, the variants should be created, but I got an API response with an error instead. 

### What I expected to happen

Variants to be created using the variant creator following the pattern described above
### Screenshots and logs
Step by step screenshots:
[Step 1](https://ibb.co/KLV9Ghp)
[Step 2](https://ibb.co/qDsLgt5)
[Step 3 with the network browser view showing the API error channel related](https://ibb.co/0K5Wf8n) 

API response below:
```
{
   "data":{
      "productVariantBulkCreate":{
         "errors":[
            {
               "field":"attributes",
               "code":"REQUIRED",
               "index":null,
               "channels":null,
               "__typename":"BulkProductError"
            }
         ],
         "__typename":"ProductVariantBulkCreate"
      }
   },
   "extensions":{
      "cost":{
         "requestedQueryCost":0,
         "maximumAvailable":250
      }
   }
}
```

### What I already tried:

- Ctrl shift r
- Other browsers (tried on Opera and Chrome)
- Activating and deactivating channels
- Tried to create variants in a different way than the above described and that works! But I really need this variant creator feature as I'm creating sometimes 100products at once. 

So from the API response, it looks like the channels are not passed properly to the to the  `ProductVariantBulkCreate` mutation using this sequence of steps.  

**System information**

Saleor version:
- [x] dashboard v3.0.0-b.29 core vdev
- [x] dev (current main)

Operating system:
- [x] Windows

**Comment by JustCreate3D** [comment]
Okaay I figured this out. 
Sorry for bothering but this may happen to someone else:
I have some dropdown (multiple values) attributes (required), and also one numeric attribute (required too) on my product types (variant)
As the numeric attribute was set to "value required", the API wouldn't let the dashboard create a variant via the creator without this attribute filled in - which in fact, cannot be filled in the variant creator. Before the update, the variant creator would create the variants without the need of this "required" numeric attribute (and the once created by the variant creator, the dashboard wouldn't let you save it without updating that required numeric value in the variant edit page)

### Proposed solutions:
The simplest: Do not allow numeric attributes value to have a required value as variant attributes, as the variant creator won't let the API `createBulkVariants` without if filled.
The ideal: Add an option to fill not dropdown values in the variant creator. 

Kind of a niche error, but when someone will encounter it, I believe this post will help him :)

**Comment by timuric** [comment]
_The ideal: Add an option to fill not dropdown values in the variant creator._
@JustCreate3D in attributes setting you can set attribute to optional or required
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/4006792/156526779-59a234cd-23fd-46c8-aaee-5913988244ce.png">
