### ISSUE TITLE
Can't change Product Type for a product 

### ISSUE THREAD

**Issue by IgorKhomenko** [saleor/saleor#9073]
### What I'm trying to achieve
Once a product is created, I want to be able to change a Product Type for a product 

### Steps to reproduce the problem

1. Create product and assign a product type
2. Then open a product details and try to change a product type

### What I expected to happen
Have product type field as editable

### Screenshots and logs

![Screenshot 2022-02-03 at 12 56 16](https://user-images.githubusercontent.com/70977170/152329706-d8e03487-ad77-4334-ab7d-399572fa386e.png)

**System information**

Saleor version:
- [ ] dev (current main)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [x] MacOS
- [ ] Other

**Comment by IgorKhomenko** [comment]
@patrys 

Since filling the shop data is a pretty time consuming task, I see 2 possible scenarios where it can be needed: 

1 - set a wrong product type by mistake 
2 - on a later stage, e.g. decided that some product should be moved to a diff product type

I would say this is something that is expected to be done in an easy way (simply updating the DB table field value, right? )

**Comment by timuric** [comment]
@IgorKhomenko 
> (simply updating the DB table field value, right? )

It might seem simple with similar product types, but there are cases when it is not straightforward. Product types can be virtual, physical, variant based, single product, and have a different set of attributes.
