### ISSUE TITLE
Payment apps have unpredictable identifiers when listing the available payment methods

### ISSUE THREAD

**Issue by artursmet** [saleor/saleor#9091]
### What I'm trying to achieve
I'm working on a third-party app that would connect Saleor to an external payment provider. My app is providing two payment methods, for example `credit card` and `check`.
The app itself, exposes the `id` in Manifest (according to docs: https://docs.saleor.io/docs/3.0/developer/extending/apps/manifest), my app is called for example `saleor-awesome-payments`.  Since the app is a third party app, it automatically subscribes itself to webhooks.

After installing this app in the store, the outcome of `availablePaymentGateways` query is 

```json
{
	"name": "Awesome card ",
	"id": "app:11:credit-card",
	"config": [
	],
	"currencies": [
		"USD"
	]
},
{
	"name": "Awesome check ",
	"id": "app:11:check",
	"config": [
	],
	"currencies": [
		"USD"
	]
}
```

Everything works fine, however during the Storefront implementation, the client-app is parsing results of above query and it should map the query result to the front-end behavior. 
Fact that Saleor API is using internal db-identifier to create the `id` values 
https://github.com/saleor/saleor/blob/250d18cd6225d0a8c3cc72005a24bcfad8ac14d6/saleor/plugins/webhook/utils.py#L42

makes the mapping harder to achieve. The `id` value would be different in every installation of the app, so the front-end would need to use some more advanced logic for the mapping.

What do you think about using the app identifier (so `saleor-awesome-payments` in my example) as part of the identifier, instead of the database id? It would make sense when app is a Third Party app. For the apps created from the level of the dashboard I believe it's fine to keep the db-based identifiers.

So in my example, the payment methods would be called:
* `app:saleor-awesome-payments:check`
* `app:saleor-awesome-payments:credit-card`

**System information**

Saleor version:
- [x] dev (current main)
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

**Comment by maarcingebala** [comment]
It sounds like a good idea, I think we could add a unique `slug` field to the App model and rely on that as an app identifier.

**Comment by maarcingebala** [comment]
Clickup: https://app.clickup.com/t/2549495/SALEOR-5891

**Comment by korycins** [comment]
Sounds great. Looks like easy thing to fix but we need to make sure that we don't break any existing integrations that uses this approach.

**Comment by korycins** [comment]
The PR that introducing the proposed changes: https://github.com/saleor/saleor/pull/10772. We use `app.identifier` to build predictable `id`. If `app.identifier` is missing, we use `app.id`.
