### ISSUE TITLE
Dots on the tracking input field

### ISSUE THREAD

**Issue by MikkelScheike** [saleor/saleor#9146]
### What I'm trying to achieve
Easier workflow when adding tracking to orders through the dashboard

### Describe a proposed solution
Currently, when opening up for tracking code you have to manually remove the three dots (...) and it is becoming quite old very fast. Can we implement a clearing mechanism when a user starts to type?

### Other solutions I've tried and won't work
Manual deletion is the only option. Removing input recreates the dots for user to remove once more.

### Screenshots or mockups

![image](https://user-images.githubusercontent.com/10270075/153780017-a80120a9-896e-4553-985b-b639d91643f1.png)

**Comment by jbergstroem** [comment]
Does this belong in the saleor dashboard repo? Also; thinking out loud but using a `<input placeholder="…">` could work?

**Comment by timuric** [comment]
which version of the dashboard are you using?

**Comment by MikkelScheike** [comment]
I am using 3.1
