### ISSUE TITLE
Saving a product variant puts SKU in name too

### ISSUE THREAD

**Issue by narayandreamer** [saleor/saleor#9178]
### What I'm trying to achieve
Editing a product variant

### Steps to reproduce the problem
1. Saving a product variant puts SKU in name too

### What I expected to happen
If variant is say 1l, 500 ml it should save like that

### Screenshots and logs
![screenshot-192 168 0 101_9000-2022 02 16-23_08_10](https://user-images.githubusercontent.com/61919250/154323564-ae737624-2c8c-4a58-83eb-afee5cd45fb6.png)

**System information**

Saleor version:
- [ ] 3.1.0-a.25 (f838419945cd0d18284bcfe2689648745bbe04c5 commit)

Operating system:
- [ ] Linux

**Comment by narayandreamer** [comment]
3.1.0-a.18

**Comment by eCzerniak** [comment]
Hi @narayandreamer I have reproduced your issue in your version, but also checked that this issue no longer exists in the latest version that has been [released](https://github.com/saleor/saleor/releases/tag/3.1.1), so I would recommend to use the latest version of saleor :). If you need more help please ask, if not, please close this ticket. 

Regards.

**Comment by narayandreamer** [comment]
I build using saleor-platform. Version bump done there too?

**Comment by timuric** [comment]
@narayandreamer you could also signup for a free devbox to run the latest version of saleor https://cloud.saleor.io/
Feel free to dm on Twitter if you have questions
