### ISSUE TITLE
Referral/Loyalty System for giving discounts to the referrer

### ISSUE THREAD

**Issue by CuriousLearner** [saleor/saleor#9251]
### What I'm trying to achieve

A referral system where both the referrer and referee are provided rewards/discounts for the loyalty

### Describe a proposed solution

Having a referral system in place such that each customer has a unique referral link to share with friends/family/world. If anyone uses this link to make a purchase (they can get certain discount on their order/product) and the referrer gets a reward (points/discount on their next order, etc.)

**Comment by timuric** [comment]
@CuriousLearner referral systems are quite broad in scope and have can be quite specific to each business. We are not planning anytime soon to build this feature into the core.

Here are a few options you could consider:
• Use existing systems and integrate them with Saleor using webhooks. 
• Use marketing automation software like zappier, automate.io to integrate with referral systems
• Build your own system on top of Saleor using vouchers, metadata, webhooks, etc.

We are working on a marketplace to bring such apps to the community, but this would be available later this year and would take time for referral apps to appear.
