### ISSUE TITLE
How can plugins add new models, migrations and mutations

### ISSUE THREAD

**Issue by coolbung** [saleor/saleor#9278]
### What I'm trying to achieve
Allow buyers to pick a "delivery slot" for when to deliver their orders

### Describe a proposed solution
Wish to introduce a new table for storing the available delivery slots, with the following schema
slot_id | slot_date | slot_start | slot_end | max_deliveries | remaining_deliveries
1 | 2022-03-02 | 09:00:00 | 13:00:00 | 100 | 17
2 | 2022-03-03 | 09:00:00 | 13:00:00 | 100 | 85
3 | 2022-03-03 | 14:00:00 | 18:00:00 | 150 | 45

1. The customer will be able to pick a slot for their delivery
2. When the order is saved, the slot_id will be added to the checkout metadata
3. The plugin will use the `order_updated` method to deduct the remaining_deliveries
4. Need to be able to create the schema using migrations, and create a mutation to insert a new slot

### Other solutions I've tried and won't work
Do this outside of Saleor using a separate set of APIs, and create an APP to use the webhooks to update the external API. Don't want to go this route, since it'll mean running and maintaining another service. 

### Screenshots or mockups
None

**Comment by timuric** [comment]
@coolbung Have you considered using serverless functions like AWS lambda, Vercel, Cloudflare workers? 
This is our recommended way to extend Saleor and we are planning to phase out plugins eventually (long-term goal).

**Comment by coolbung** [comment]
Have certainly considered that option as mentioned in my post. If that is the recommended way, thats fine.

So plugins cannot add mutations / schemas / models ?

**Comment by timuric** [comment]
_So plugins cannot add mutations / schemas / models ?_
Correct, plugins should not be able to do so
