### ISSUE TITLE
Color Attribute

### ISSUE THREAD

**Issue by uroybd** [saleor/saleor#9279]
### What I'm trying to achieve
Color is a very important attribute for various products. It is possible to use a text field for hex color but that is not ideal. A color picker with the color type defined for attributes is what. I believe, is the best for UX. 

### Describe a proposed solution
Previously, I've implemented color attributes for 2 projects of mine. It is doable and I believe it will not be hacky in the new major version.

I'm willing to contribute code if you want to implement this feature.

**Comment by timuric** [comment]
@uroybd please use the swatch attribute for colors which is available in 3.1.
You can get a free dev account to explore the latest features in Saleor https://cloud.saleor.io/
