### ISSUE TITLE
Is this available on PH?

### ISSUE THREAD

**Issue by jajamoks** [saleor/saleor#9321]
I tried to add country but it seems I cannot add country on the dashboard and I can't even create price per variant, I'm not sure why it it was unable only I can see is a placeholder text with 'There is no channel to define prices for' not sure how to this. I already added a channel for my product but still cannot add price for variants.

**Comment by timuric** [comment]
@jajamoks Please configure a channel first (configuration-> channels), then create a product type with variants.
