### ISSUE TITLE
add filter to get customers by id's.

### ISSUE THREAD

**Issue by g-londhe** [saleor/saleor#9523]
### What I'm trying to achieve
Get customer by id.

### Describe a proposed solution
User/Programmer should be able to get customers based on customer/user id.

### Other solutions I've tried and won't work
We are able to get users by id, but In my case, I want to filter customers by a list of id's provided.

**Comment by uthorat** [comment]
+ 1 we need this too.

**Comment by Rohan-Chavan-4196** [comment]
We want this too.
