### ISSUE TITLE
UserEmails plugin ignores `EMAIL_URL`

### ISSUE THREAD

**Issue by heyarne** [saleor/saleor#9528]
### What I'm trying to achieve

I'm following the docs to set up Saleor. Fiddling around with the GraphQL API I noticed that e-mails weren't sent (when creating an account for example), so I tried to set it up using the [documented environment variable](https://docs.saleor.io/docs/3.x/developer/running-saleor/configuration#email_url). I'm trying to set up mails via sendgrid, so I took the provided example and set my actual API key as password.

### Steps to reproduce the problem

1. Open `$dashboard/plugins/mirumee.notifications.user_email/`
2. Find all fields unfilled, along with references to new environment variables such as `EMAIL_HOST`, `EMAIL_HOST_USER` and more.
3. `DEFAULT_FROM_MAIL` also seems to be ignored

I then tried to set the other environment variables as follows, and setting the password in the plugin's settings:

```
EMAIL_URL=smtp://apikey:...@smtp.sendgrid.com:465/?ssl=True
EMAIL_HOST=smtp.sendgrid.com
EMAIL_PORT=465
EMAIL_USE_SSL=true
DEFAULT_FROM_EMAIL=noreply@some.url
EMAIL_HOST_USER=apikey
```

Trying to activate the plugin still failed with a timeout. The error message is shown below.

### What I expected to happen

I expected the mail server config to be present once I set the environment variable as documented. I also expected SMTP config to be reused in the same way across plugins that come with Saleor out of the box.

### Screenshots and logs

<details>
<summary>Server Response</summary>

``` json
{
  "data": {
    "pluginUpdate": {
      "errors": [
        {
          "code": "PLUGIN_MISCONFIGURED",
          "field": "host",
          "message": "Unable to connect to email backend. Make sure that you provided correct values. Connection unexpectedly closed: timed out",
          "__typename": "PluginError"
        },
        {
          "code": "PLUGIN_MISCONFIGURED",
          "field": "port",
          "message": "Unable to connect to email backend. Make sure that you provided correct values. Connection unexpectedly closed: timed out",
          "__typename": "PluginError"
        },
        {
          "code": "PLUGIN_MISCONFIGURED",
          "field": "username",
          "message": "Unable to connect to email backend. Make sure that you provided correct values. Connection unexpectedly closed: timed out",
          "__typename": "PluginError"
        },
        {
          "code": "PLUGIN_MISCONFIGURED",
          "field": "password",
          "message": "Unable to connect to email backend. Make sure that you provided correct values. Connection unexpectedly closed: timed out",
          "__typename": "PluginError"
        },
        {
          "code": "PLUGIN_MISCONFIGURED",
          "field": "senderName",
          "message": "Unable to connect to email backend. Make sure that you provided correct values. Connection unexpectedly closed: timed out",
          "__typename": "PluginError"
        },
        {
          "code": "PLUGIN_MISCONFIGURED",
          "field": "senderAddress",
          "message": "Unable to connect to email backend. Make sure that you provided correct values. Connection unexpectedly closed: timed out",
          "__typename": "PluginError"
        },
        {
          "code": "PLUGIN_MISCONFIGURED",
          "field": "useTls",
          "message": "Unable to connect to email backend. Make sure that you provided correct values. Connection unexpectedly closed: timed out",
          "__typename": "PluginError"
        },
        {
          "code": "PLUGIN_MISCONFIGURED",
          "field": "useSsl",
          "message": "Unable to connect to email backend. Make sure that you provided correct values. Connection unexpectedly closed: timed out",
          "__typename": "PluginError"
        }
      ],
      "plugin": null,
      "__typename": "PluginUpdate"
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 0,
      "maximumAvailable": 50000
    }
  }
}
```
</details>

**System information**

Saleor version:
- [ ] dev (current main)
- [x] 3.1.19
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Comment by timuric** [comment]
@heyarne currently we are migrating the email plugin to an app, and we will deprecate email plugin soon. I would advise you to use webhooks to trigger emails in sendgrid or wait for the release of email app that you would be able to host on Vercel.

**Comment by heyarne** [comment]
@timuric How soon is soon? I'm aware of the intricacies of estimating software arrival dates, but we are currently setting up our shop using Saleor and I need to evaluate whether writing a custom e-mail delivery mechanism via webhooks makes sense or if the migration you mentioned is around the corner anyways.

**Comment by jbergstroem** [comment]
We ran into this as well. @timuric would you accept a PR that takes permisisons from the environment variable if present (but overridable via plugin)?
