### ISSUE TITLE
Add Variant Attributes in payload for emails

### ISSUE THREAD

**Issue by jaydotcom** [saleor/saleor#9531]
### What I'm trying to achieve
I'd like to add some attribute descriptions of my variant in my confirmation Email.

### Describe a proposed solution
I need to have attributes at variant level (only at product level at the moment) in payload sent to sendgrid.
Need to enrich get_product_variant_payload in notifications.py

**Comment by timuric** [comment]
Looks like you can achieve this by using the new subscription API https://docs.saleor.io/docs/3.x/developer/extending/apps/subscription-webhook-payloads

We are working on a new playground to make it easier to create custom payloads for your webhooks.
