### ISSUE TITLE
Filter products by array of id.

### ISSUE THREAD

**Issue by ibtsam0018** [saleor/saleor#9575]
Is there a way of get products corresponding to multiple ids?

**Comment by timuric** [comment]
We are planning to do major enhancements of our filters API Q3 this year

**Comment by korycins** [comment]
Hey @ibtsam0018 
It is already possible. You can use filter input for this:
```graphql
query search_products {
  products(
    first: 50,
    channel:"default-channel",
    filter: {ids: ["UHJvZHVjdDoxNTI=", "UHJvZHVjdDoxMzQ="]}
  ) {
    totalCount
    edges {
      node {
        id
      }
    }
  }
}
```
Let us know if this solve your problem and we will close the issue.
