### ISSUE TITLE
Mutation for adding a note to the checkout

### ISSUE THREAD

**Issue by DidoMarchet** [saleor/saleor#9591]
### What I'm trying to achieve
Have a mutation for adding a note.
Nowadays there is no way to add a note to the checkout despite the GQL Schema have it.

### Describe a proposed solution
Create a mutation named `checkoutAddNote`

### Ref.
[https://github.com/saleor/saleor/discussions/9580#discussioncomment-2614909](https://github.com/saleor/saleor/discussions/9580#discussioncomment-2614909)

Thanks and regards, 

Davide

**Comment by maarcingebala** [comment]
Fixed in https://github.com/saleor/saleor/pull/16315.
