### ISSUE TITLE
Preorder product variant emails issues

### ISSUE THREAD

**Issue by Anubiella** [saleor/saleor#9632]
### What I'm trying to achieve
After successfully set a product variant to a preorder, with an end date,
I've proceeded to a purchase in frontend, no errors logged; purchase completed successfully but, 
unexpectedly, no email was sent to the customer (me in this case).

### Steps to reproduce the problem

1. Set a product variant as a preorder.
2. Set a preorder end date.
3. Save the product.
4. Proceed to a purchase in frontend.
5. See that there are no errors in console while purchasing.
6. Complete the purchase.
7. Wait for the email to come.

### What I expected to happen
All the emails regardins the order as usual.

### Screenshots and logs

![Order -498 - Ale Bike Wear 26-4-2022 16-20-31](https://user-images.githubusercontent.com/31857092/165321444-4ade0d97-c875-4d6b-b24b-f865c0a657fe.png)

**System information**

Saleor version:
- [ x ] dashboard v3.1.0-dev core vdev

Operating system:
- [ x ] Windows

**Comment by szczecha** [comment]
Unable to reproduce v3.18 
![image](https://github.com/saleor/saleor/assets/30683248/2e026b31-a3e7-4aa7-a654-01321486ad92)
![image](https://github.com/saleor/saleor/assets/30683248/5ddca6e3-ae8e-4282-8bbf-b01cbcbea4fc)
