### ISSUE TITLE
Avalara plugin - Discount and taxes issue

### ISSUE THREAD

**Issue by Anubiella** [saleor/saleor#9677]
### What I'm trying to achieve
Taxes been applied on discounted price and not on the gross price by Avalara plugin.

### Steps to reproduce the problem

1. Purchase a discounted product.
2. Check on the dashboard in the Orders section whether taxes has been applied on gross price or just on the discount price.

### What I expected to happen
We expect to see that the taxes will be applied just on the discounted price, not on the total gross price, incurring in higher taxes.

### Screenshots and logs

**System information**

Saleor version:
- [ ] dashboard v3.1.0-dev core vdev
- [ ] [saleor-sdk](https://github.com/saleor/saleor-sdk) v^0.3.0-11 for the checkout

Operating system:
- [ ] Windows

**Comment by aniav** [comment]
The issues related to Avalara Lubin should be fixed in the newest version of Saleor. Feel free to tropem of this is not the case 🙌
