### ISSUE TITLE
Conflicting voucher code length definitions

### ISSUE THREAD

**Issue by tmechsner** [saleor/saleor#9779]
### What I'm trying to achieve
We created a voucher with a code that is longer than 12 chars. Creating is not a problem - but the Checkout model has a maximum length of 12 for the voucher code, while the Voucher model itself has a maximum length of 255.

### Steps to reproduce the problem
1. Create a voucher with a code that has more than 12 chars
2. Try to add it to a checkout (mutation CheckoutAddPromoCode)

### What I expected to happen
Long voucher codes should work like any other voucher.

### Screenshots and logs
```
DataError
value too long for type character varying(12)
...

cls | <CheckoutAddPromoCode meta=<MutationOptions name='CheckoutAddPromoCode'>>
data | {'checkout_id': 'Q2hlY2tvdXQ6ODc2YzdkYzEtMDI1NS00YTIzLWJhMTQtOGE2Y2ExODg0MTEx',  'promo_code': 'ThisIsAVeryLongVoucherCode'}
info | <graphql.execution.base.ResolveInfo object at 0x7fa6b5b39ec0>
root | None
```

**System information**

Saleor version:
- [x] dev (current main)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [x] Linux
- [x] MacOS
- [ ] Other

**Comment by maarcingebala** [comment]
Fixed in https://github.com/saleor/saleor/pull/9791
