### ISSUE TITLE
Invoices are filled with the customer's info in place of the company's info.

### ISSUE THREAD

**Issue by zyp** [saleor/saleor#9804]
### What I'm trying to achieve
[This](https://saleor.io/blog/saleor-invoicing-api-storefront-sdk-app-installation-support-139/) blog post shows invoices looking like this:

![](https://getsaleor-cms.s3.eu-west-1.amazonaws.com/2f8620fc680b44408306c6f326f354a5.png)

However, the default template fills the top left section with the customer's billing address instead of the company's info:

```html
    <div class="section-header section-left">
        <div class="content-padded">
            <span class="normal-text">{{ order.billing_address.company_name }}</span>
            <br />
            <span class="normal-text">{{ order.billing_address.street_address_1 }}</span>
            <br />
            {% if order.billing_address.street_address_2 %}
                <span class="normal-text">{{ order.billing_address.street_address_2 }}</span>
                <br />
            {% endif %}
            <span class="normal-text">{{ order.billing_address.city }}</span>
            <br />
            <span class="normal-text">{{ order.billing_address.postal_code }}</span>
            <br />
            {% if order.billing_address.phone %}
                <span class="normal-text">{{ order.billing_address.phone }}</span>
                <br />
            {% endif %}
            <span class="normal-text">{{ order.get_customer_email }}</span>
            <br />
        </div>
    </div>
```

**System information**

Saleor version:
- [x] dev (current main)
- [x] 3.0
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

**Comment by peelar** [comment]
Hello @zyp 👋 

Thank you for your report. We added it to our backlog and will let you know as soon as it's done.

Have a nice day 🌷

**Comment by aniav** [comment]
The invoices plugin has been deprecated and removed. We do not intend to provide an invoices solution as we found most of the companies integrating with Saleor have separate solutions for that area.
