### ISSUE TITLE
Stripe plugin should allow setting "automatic_payment_methods" when creating PaymentIntent

### ISSUE THREAD

**Issue by n-borges** [saleor/saleor#9858]
### What I'm trying to achieve
When calling the mutation checkoutComplete, in the optional input paymentData, we should add a key to set "automatic_payment_methods" to true. The setting allows to automatically enable all the payment methods that the Stripe user has enabled in his dashboard, which seems more reasonable than listing all of them each time the mutation is called.

### Describe a proposed solution
We should add the required lines in saleor/payments/stripe/plugin.py, specifically I was thinking about something like this:
```python
@require_active_plugin
    def process_payment(
        self, payment_information: "PaymentData", previous_value
    ) -> "GatewayResponse":
# snip
        
++++automatic_payment_methods = data.get("automatic_payment_methods") if data else None++++

        intent, error = create_payment_intent(
                api_key=api_key,
                amount=payment_information.amount,
                currency=payment_information.currency,
                auto_capture=auto_capture,
                customer=customer,
                payment_method_id=payment_method_id,
                metadata={
                    **payment_information.payment_metadata,
                    "channel": self.channel.slug,  # type: ignore
                    "payment_id": payment_information.graphql_payment_id,
                },
                setup_future_usage=setup_future_usage,
                off_session=off_session,
                payment_method_types=payment_method_types,
       ++++automatic_payment_methods=automatic_payment_methods,++++
                customer_email=payment_information.customer_email,
            )
...
```

**Comment by timuric** [comment]
We will be deprecating payment plugins in favor of the new Payment APIs. For reference, you can check the new payments app that implements Stripe and Adyen using webhooks and new `TransactionRequestAction` mutations https://github.com/saleor/saleor-checkout/tree/main/apps/checkout-app/pages/api

We will be adding Stripe to the payment app in a few months.
