### ISSUE TITLE
Apply conditional discount on product - only if another product is in checkout

### ISSUE THREAD

**Issue by TurkaljGoran** [saleor/saleor#9865]
### What I'm trying to achieve

Hello Saleor team, 

We've received a client request as follows: 

User must add product A to checkout, and ONLY then should be able to apply a voucher with discount on product B.
So product A acts like a condition if a discount can be applied to another product.

In the Dashboard, under Vouchers > Minimum Requirements, another option could be added where we could enter information:
- conditional  product/s that are a basic requirement for the particular voucher to even be usable just like minimum order value or quantity of items.

Is a feature like this considered, maybe the upcoming Discount API will make something like this possible natively, or perhap easier to implement on our end?

Any information is welcome!

Cheers!

**Comment by timuric** [comment]
@TurkaljGoran with the upcoming Discount API it would be possible to create a custom webhook for that. Alternatively you could use this API to set custom prices https://docs.saleor.io/docs/3.x/developer/checkout#setting-custom-prices-for-checkout-items
