### ISSUE TITLE
Unable to update Company info from Dashboard

### ISSUE THREAD

**Issue by blackyzero** [saleor/saleor#9894]
### What I'm trying to achieve
Update Company info

### Steps to reproduce the problem
New install, then update company info from dashboard

```
[28/May/2022 02:22:14] "OPTIONS /graphql/ HTTP/1.1" 200 0
INFO saleor.graphql.errors.handled A query had an error [PID:26314:Thread-151]
graphql.error.base.GraphQLError: Variable "$isCloudInstance" is never used in operation "ShopSettingsUpdate".
WARNING django.request Bad Request: /graphql/ [PID:26314:Thread-151]
[28/May/2022 02:22:14] "POST /graphql/ HTTP/1.1" 400 417
[28/May/2022 02:22:24] "OPTIONS /graphql/ HTTP/1.1" 200 0
```

### What I expected to happen
company info should be updated

### Screenshots and logs

**System information**

Saleor version:
- [ ] dev (current main)
- [ x] 3.0 & 3.4.1
- [ ] 2.11
- [ ] 2.10

Operating system:
- [ ] Windows
- [ x] Linux
- [ ] MacOS
- [ ] Other

this is also mentioned in Saleor Dashboard,
https://github.com/saleor/saleor-dashboard/issues/2070

**Comment by vetemi** [comment]
This is still a problem in dashboard v3.5.2 core v3.5.10

Dear team, can you please give us an update to this?

**Comment by timuric** [comment]
@vetemi thanks for reporting. Fix is awaiting merge https://github.com/saleor/saleor-dashboard/pull/2228

Closing this issue as it is not related to the saleor core.
