### ISSUE TITLE
Apollo Gateway 2 cannot compose with Saleor as a subgraph

### ISSUE THREAD

**Issue by fetimo** [saleor/saleor#9939]
### What I'm trying to achieve

I'm trying to compose a supergraph with @apollo/gateway@2.0.4.

### Steps to reproduce the problem

1. Create a gateway using @apollo/gateway (see [gist](https://gist.github.com/fetimo/7d33b6fab8f4b016f442ea8438e942a5))
2. Add Saleor (3.1.16) GraphQL endpoint to the subgraphs array.
3. Try running it

### What I expected to happen

The schema to compose without errors.

### Screenshots and logs

```
error - Error: A valid schema couldn't be composed. The following composition errors were found:
        [saleor] Invalid default value (got: "none") provided for input field PaymentInput.storePaymentMethod of type StorePaymentMethodEnum.
```

**System information**

Saleor version: 
dashboard v3.1.5, v3.4.0
core v3.1.16, v3.4.2

Operating system:
- [ ] Windows
- [ ] Linux
- [x] MacOS
- [ ] Other

**Comment by peelar** [comment]
Can you confirm this one was solved @korycins?

**Comment by korycins** [comment]
@peelar  We fixed the incorrect value that was added in grapqhl scheme. I think it should work now.

**Comment by peelar** [comment]
@fetimo As you can see, the error should no longer occur. Please confirm if this is the case and I will close the issue.
