### ISSUE TITLE
Can't completing the checkout without additional payment action for digital product

### ISSUE THREAD

**Issue by nnthuan** [saleor/saleor#9947]
### What I'm trying to achieve
Create and complete the checkout without additional payment action for a digital product.

### Steps to reproduce the problem

Use: $DOMAIN/graphql/

1. Creating a checkout session
```
mutation {
    checkoutCreate(
      input: {
        channel: "vn",
        email: "my-email@gmail.com"
        lines: [{ quantity: 1, variantId: "UHJvZHVjdFZhcmlhbnQ6Ng==" }]
        billingAddress: {
          firstName: "My first name"
          lastName: "My last name"
          streetAddress1: "12 Quang Trung, Gò vấp"
          city: "Hồ Chí Minh"
          country: VN
        }
      }
    ) {
      checkout {
        id
        token
        totalPrice {
          gross {
            amount
            currency
          }
        }
        isShippingRequired
        shippingMethods {
          id
          name
          active
          message
        }
        availableCollectionPoints {
          id
          name
          clickAndCollectOption
        }
        availablePaymentGateways {
          id
          name
          config {
            field
            value
          }
        }
      }
      errors {
        field
        code
      }
    }
  }
```
2. Completing the checkout without additional payment action
```
  mutation {
    checkoutComplete(
      token: "5a10a4eb-573d-4db3-93dc-e222c1a7e95a"
    ) {
      order {
        id
        status
      }
      errors {
        field
        message
      }
    }
  }
```
3. Response
```
{
  "data": {
    "checkoutComplete": {
      "order": null,
      "errors": [
        {
          "field": null,
          "message": "Provided payment methods can not cover the checkout's total amount"
        }
      ]
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 0,
      "maximumAvailable": 50000
    }
  }
}
```

### What I expected to happen
completing checkout and creating a new order from this checkout.

**System information**
Saleor version:
- [ ] dev (current main)
- [x] 3.5.0-a
- [ ] 3.0
- [ ] 2.11
- [ ] 2.10

Saleor configuration:
- [x] replica

Operating system:
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Other

**Product information**
- [x] Digital

Pricing:
|Channel Name|Selling Price|Cost price|
|--------------------|-----------------|-------------|
|VN|140000|0|

Inventory:
|SKU|Variant currently in preorder|Track Inventory|
|--------------------|-----------------|-------------|
|pro|false|false|

|Warehouse Name|Allocated |Quantity|
|--------------------|-----------------|-------------|
|Global|0|0|

**Comment by nnthuan** [comment]
I am currently using https://docs.saleor.io/docs/3.x/developer/checkout#creating-order-from-checkout to instead

**Comment by timuric** [comment]
@nnthuan we recommend using these two mutations for payments
 https://docs.saleor.io/docs/3.x/developer/checkout#creating-order-from-checkout 
https://docs.saleor.io/docs/3.x/developer/api-reference/objects/transaction-create

We are going to release payments guide soon, meantime you can use this payment app for reference https://github.com/saleor/saleor-checkout/tree/2ac594d88092951051212911b6c5ce3f2376674d/apps/checkout-app/pages/api/webhooks

**Comment by nnthuan** [comment]
@timuric Thanks for your support.
