### ISSUE TITLE
Substring text Search

### ISSUE THREAD

**Issue by TurkaljGoran** [saleor/saleor#9972]
### What I'm trying to achieve
…
Hello Saleor team,

I'm going through your Full-text search for products #9344 pull request, since we've updated our new Saleor project to dashboard v3.3.2, core v3.3.8 and noticed that we need to type in an entire word for search to return any results. 

This is very important for clients that use the dashboard and customers on the storefront - since, let's face it, most people are lazy. Typing in 3 characters and getting something back is much easier than typing out an entire word, especially when its more than 7-8 characters, or if you don't know the exact word. 

We have 2 webshops already running in production on Saleor - but they are on older versions which still have substring text search. 
The 'weighted' ranking was achieved on front end which filters out Saleor's search results and displays only products which have the search term in the title - no matter if it is a substring or full string, and if no such products are found, it displays all of the results. 

This proved to be very simple to implement and our clients were pleased since it gave the impression of a more sophisticated search. 

Now, we would like to continue to upgrade Saleor but this poses an issue if we lose substring search with the next upgrade. 

Are there any plans on keeping the new weighted ranking but also bring back substring text search in the near future / at all? In that case we could hold off on unnecessary search implementation efforts via TypeSense or Algolia (this one is costly). 

Any info on this is greatly appreciated!

Cheers, 

Goran

**Comment by peelar** [comment]
Hello @TurkaljGoran 👋, I hope you are well. 

Thank you for your request, and please accept my apologies for making you wait so long for the answer 🙏.

We replaced the substring search with a full-text search that gives our users much greater possibilities. Unfortunately, they are not compatible with each other, so you may need to invest a little bit of time in the migration.

The solution that resembles your current experience the most would probably leverage sorting the results by relevance.

Please let us know if you have any further questions.

Have a nice day 🌻
